### ISSUE TITLE
Inaccurate chapter title.

### ISSUE THREAD

**Issue by SebastienAime** [MicrosoftDocs/windowsserverdocs#1025]
To me the chapter's name "Hybrid Modern Authentication - seamless SSO with Alternate-ID" is not accurate.
Currently, this article put almost completely aside the Federation Auth scenario. This is not a good thing as it's a hugely deployed scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02d8b61-29e8-c0a7-b3b2-79be7212a91c
* Version Independent ID: b4346d87-0727-c7fe-7896-7fd79098825c
* Content: [Configuring Alternate Login ID](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configuring-alternate-login-id#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Fair point. "seamless" is probably a stretch there and reads more like a sales pitch than technical documentation.

**Comment by illfated** [comment]
Sorry, I replied before checking the document content. There have been multiple commits and massive overhauls in this document since Q3 2018 and up until December 2020.

Please open a new issue ticket if you still find that this document still needs improvement in the areas you described above.

"seamless SSO with Alternate-ID" is long gone. AD FS paragraphs have been added.

#please-close
