### ISSUE TITLE
Support for CAA records

### ISSUE THREAD

**Issue by jeroenlandheer** [MicrosoftDocs/windowsserverdocs#1034]
The CAA record type doesn't seem to be supported yet, any news on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b8a4bf-b99a-b80f-2402-af8ffd4f4eba
* Version Independent ID: b8aabc28-d1e1-f12d-7562-9d31e6407391
* Content: [nslookup set type](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup-set-type)
* Content Source: [WindowsServerDocs/administration/windows-commands/nslookup-set-type.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/nslookup-set-type.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Not very likely. There are other tools out there to help you look up CAA records, for example the Unix/Linux command `dig`.

Example output from the nslookup command, interactive mode, with the option `set type=ANY` enabled:

```
C:\Users\illfated>nslookup
Default Server:  dns.google
Address:  8.8.8.8

> set type=ANY
> microsoft.com
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
microsoft.com   internet address = 104.215.148.63
microsoft.com   internet address = 40.76.4.15
microsoft.com   internet address = 40.112.72.205
microsoft.com   internet address = 40.113.200.201
microsoft.com   internet address = 13.77.161.179
microsoft.com   nameserver = ns1-205.azure-dns.com
microsoft.com   nameserver = ns2-205.azure-dns.net
microsoft.com   nameserver = ns3-205.azure-dns.org
microsoft.com   nameserver = ns4-205.azure-dns.info
microsoft.com
        primary name server = ns1-205.azure-dns.com
        responsible mail addr = azuredns-hostmaster.microsoft.com
        serial  = 1
        refresh = 3600 (1 hour)
        retry   = 300 (5 mins)
        expire  = 2419200 (28 days)
        default TTL = 300 (5 mins)
microsoft.com   MX preference = 10, mail exchanger = microsoft-com.mail.protection.outlook.com
microsoft.com   text =

        "docusign=d5a3737c-c23c-4bd0-9095-d2ff621f2840"
microsoft.com   text =

        "v=spf1 include:_spf-a.microsoft.com include:_spf-b.microsoft.com include:_spf-c.microsoft.com include:_spf-ssg-a.microsoft.com include:spf-a.hotmail.com include:_spf1-meo.microsoft.com -all"
microsoft.com   text =

        "google-site-verification=Zv1IvEEZg4N9wbEXpBSSyAiIjDyyB3S-fzfFClb7D1E"
microsoft.com   text =

        "google-site-verification=6P08Ow5E-8Q0m6vQ7FMAqAYIDprkVV8fUf_7hZ4Qvc8"
microsoft.com   text =

        "facebook-domain-verification=gx5s19fp3o8aczby6a22clfhzm03as"
microsoft.com   text =

        "atlassian-domain-verification=jbey7I2+3Wyl+PZ0QUCC6fCz2Gu5KO7GQPcy/0c4za7ebQxar/qqujJH4kZLVQHZ"
microsoft.com   text =

        "adobe-sign-verification=c1fea9b4cdd4df0d5778517f29e0934"
microsoft.com   text =

        "docusign=52998482-393d-46f7-95d4-15ac6509bfdd"
microsoft.com   text =

        "google-site-verification=8-zFCaUXhhPcvN29EVw2RvtASDCaDPQ02L1HJ8Om8I0"
microsoft.com   text =

        "adobe-idp-site-verification=8aa35c528af5d72beb19b1bd3ed9b86d87ea7f24b2ba3c99ffcd00c27e9d809c"
microsoft.com   text =

        "d365mktkey=4fr9fops9mbcxcsuvt0lhx46d"
microsoft.com   text =

        "d365mktkey=4d8bnycx40fy3581petta4gsf"
microsoft.com   text =

        "8RPDXjBzBS9tu7Pbysu7qCACrwXPoDV8ZtLfthTnC4y9VJFLd84it5sQlEITgSLJ4KOIA8pBZxmyvPujuUvhOg=="
microsoft.com   text =

        "google-site-verification=1TeK8q0OziFl4T1tF-QR65JkzHZ1rcdgNccDFp78iTk"
> _
```

You may want to look elsewhere for answers, unless you have suggestions for improving document with recommended changes.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by IngridAtMicrosoft** [comment]
#please-close
