### ISSUE TITLE
Missing Locally and remotely using Windows PowerShell reference

### ISSUE THREAD

**Issue by jgallucci32** [MicrosoftDocs/windowsserverdocs#1083]
The overview lists "Locally and remotely using Windows PowerShell" as one of the way to manage Server Core, yet these instructions are missing from this section (or at least a link to the instructions). It would be helpful to provide an example of how to connect remotely to Server Core using PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebe4d150-8841-b5b8-4762-2383cb3a7163
* Version Independent ID: f57bcc2a-ca9b-eea2-f778-091d7678c6ed
* Content: [Manage Server Core](https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-manage)
* Content Source: [WindowsServerDocs/administration/server-core/server-core-manage.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-core/server-core-manage.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap

**Comment by ausesims** [comment]
It may be because there are enough commands for powershell to fill at least two hard copy best sellers. However, if you need to know the basics I would start here...

 https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-administer

Alternatively I found it's in my best interest to use the MMC snap in when I want to configure the SQL server in combination with Windows Admin Center since I use my powershell commands from there.
