### ISSUE TITLE
Specials char in passwords

### ISSUE THREAD

**Issue by GillesRonsin** [MicrosoftDocs/windowsserverdocs#1089]
Enclosing password with double quote /PASS:"p@$$w0rd", allows using specials characters but not double quote itself ! No way found to escape it.  
would you envisage to pass password parameter as hexadecimal string or give escape char ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caebc8e0-4c03-4714-b7a8-3d55ef0f6ab1
* Version Independent ID: 5a7b7ad8-8f55-fb3e-54ee-b8aff333b7c7
* Content: [cmdkey](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmdkey)
* Content Source: [WindowsServerDocs/administration/windows-commands/cmdkey.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/cmdkey.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by mkupper** [comment]
@GillesRonsin - I suspect you are asking that the cmdkey application get updated to support double quotes in passwords.  The github thing is only for proposing documentation updates.  While there's a product feedback button it seems the our requests will only be seen by people who have no ability to punt the feedback into Microsoft's software development group.  I tried the live chat feature as the queue length was zero.  I was connected to Mirachel S.

Me: how do I report bugs with cmdkey.exe ?
Me: cmdkey.exe is an application that has shipped with all versions of windows since Windows Vista and is still available in Windows 10

Mirachel S: Thank you for the information, let me help you with this concern. To report a bug, you can use the Windows 10 Feedback Hub: https://aka.ms/AA160kq
Me: Thank you.  I'll need to boot up a Windows 10 machine as that page only works if someone is running win10.

**Comment by illfated** [comment]
@GillesRonsin and @mkupper : Thank you both for the discussion. You are quite right, this repository is only intended for MS Docs documentation improvement.

However, if you do find that there are errors, discrepancies, incorrect information or known missing information that the document page needs, feel free to open a new ticket with the necessary information to work on and possibly create a Pull Request to have the document page updated. Useful feedback aimed at improving the docs is always welcome.

Please also note the following (even if it may be too late for your original issue):

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
