### ISSUE TITLE
Robocopy can corrupt deduplicated server volumes

### ISSUE THREAD

**Issue by DMahalko** [MicrosoftDocs/windowsserverdocs#1104]
The Robocopy utility included with Windows Server 2016 can instantly and irrecoverably corrupt deduplicated server volumes. To prevent this corruption, the volume root directory "\System Volume Information" needs to be manually excluded from all Robocopy operations, because deduplication data is stored in "\System Volume Information\Dedup\".

This problem along with a log of the corruption is discussed here in more detail: https://serverfault.com/questions/920018/apparently-robocopy-does-not-understand-windows-server-2016-deduplication-is-th

I believe this is a bug and Robocopy for Server 2016 should be modified by Microsoft to automatically exclude "\System Volume Information". As far as I am aware the data contained in that directory should never normally be accessed by anything other than the operating system for any reason.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ad82255-4174-62fa-835c-1648e9643d2f
* Version Independent ID: 0b4da799-8195-7f61-5074-8eecea6a527c
* Content: [Data Deduplication Overview](https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/overview)
* Content Source: [WindowsServerDocs/storage/data-deduplication/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/data-deduplication/overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @wmgries
* Microsoft Alias: **wgries**

**Comment by wmgries** [comment]
Hi DMahalko,

As you correctly point out, Robocopy has a design bug that causes it to delete SVI on the source-side of a copy operation. This has been the case for many years (at least in 2012, 2012 R2, and 2016, though likely earlier). This has been fixed in Windows Server, version 1803, and will be available in Windows Server 2019 as well.

@dawnwood please make a call whether this issue can be closed or should remain open until Windows Server 2019 ships.

Thanks,

Will Gries
Program Manager, Data Deduplication
