### ISSUE TITLE
If ReFS returns an error can data still be accessed?

### ISSUE THREAD

**Issue by mjohnsonn** [MicrosoftDocs/windowsserverdocs#1120]
Nice how you outline what ReFS does if there is a data corruption, but I think one thing is missing from the description:  If integrity streams settings are enabled and an error is returned instead of requested data because ReFS is unable to correct a corruption, can the data still be accessed by disabling integrity streams?  If not, is there some other way to access the data?  If I have a 10GB video file and just a couple of bits are rotted in an unfixable way,  I’d like to be alerted to the corruption, but I certainly don’t want the entire file to be discarded!  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca609fd-a4a8-c238-1f90-9e7223ca338d
* Version Independent ID: ed26c24f-a7bd-5041-c372-146527d6a600
* Content: [ReFS integrity streams](https://docs.microsoft.com/en-us/windows-server/storage/refs/integrity-streams)
* Content Source: [WindowsServerDocs/storage/refs/integrity-streams.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/refs/integrity-streams.md)
* Product: **windows-server-threshold**
* GitHub Login: @gawatu
* Microsoft Alias: **jgerend**

**Comment by JasonGerend** [comment]
I'm asking around - stay tuned!

**Comment by mjohnsonn** [comment]
Any update on this?  Can't really use this product without knowing what will happen to my data!
Thanks

**Comment by gawatu** [comment]
Hi Aniket – I started another thread with you and Andrew, but didn’t seem like that got resolved. Can you please answer here? I’m not sure what happens in this scenario – but this customer is requesting a response.

**Comment by mjohnsonn** [comment]
I can come up with multiple fully reasonable scenarios where if ReFS returns an error, the file in question would still be valuable and its data should be accessible.  We need to determine if ReFS is going to completely lose all data from a given file in those cases.

ReFS is now included in the Win 10 Workstation SKU not just Server.  Microsoft is encouraging it's use by scientists, engineers, and videographers.

How can any customers use the product when the only available docs indicate that their data could be tossed if a single bit out of whack when the rest of a data file or video is just fine?

**Comment by mjohnsonn** [comment]
Per the ReFS Overview doc:  If a volume becomes corrupted and an alternate copy of the corrupted data doesn't exist, ReFS removes the corrupt data from the namespace.

For the scenario I outlined that's unacceptable.  I did some testing with some file corruption and the event log now shows a Warning Event ID 513 "The file system detected a corruption on a file. The file has been removed from the file system namespace."

The file is GONE!

Certainly for a Workstation user, ReFS should be able to detect corruption and then allow the user to determine what action to take.  For ReFS to just delete the file is ridiculous.  The lack of any answer from the file system folks is also a bad indication.

**Comment by AniketNaravanekar** [comment]
Hello mjohnsonn,

ReFS deletes files in two scenarios:
1. ReFS detects Metadata corruption AND there is no way to fix it. Meaning ReFS is not on a mirrored volume where it can fix the corrupted copy. 
2. ReFS detects data corruption AND Integrity Stream is enabled AND there is no way to fix it. Meaning if Integrity Stream is not enabled, the file will be accessible whether data is corrupted or not. If ReFS is running on a mirrored volume using Storage Spaces, the corrupted copy will be automatically fixed.

So to answer your question, the file will not be deleted because a few bits are corrupted. The value of ReFS lies in providing guarantee that the data you're reading is exactly what was written to the disk. It does this by correcting errors through copies stored on mirrors. 

I would recommend using mirrored volumes to compliment ReFS for:
1. data integrity guarantee
2. automatic error correction

Thanks,
Aniket.

**Comment by mjohnsonn** [comment]
Aniket,

All that you said is moot.  I decided to continue testing on my W10 Pro Workstations machine so as not to disturb our servers.  ReFS barely detects corruption at all and when it does it rarely corrects anything. Folks can check my tests here [https://social.technet.microsoft.com/Forums/windowsserver/en-US/cd28095d-e421-4538-9a9f-a15260e79a75/refs-test-with-corrupt-data-does-it-work?forum=winserverfiles](url)

ReFS corruption detection does not work properly.  This problem gets no attention because:
 
(A) Nobody is looking for it--everyone assumes the product would have to be performing this most basic function.
 
(B) An error is caught and reported every now and then which makes ReFS look like it works.
 
(C) It’s difficult for end users to verify proper corruption detection through testing so nobody tests.

**Comment by mjohnsonn** [comment]
Thanks for the response.  ReFS may be fine on Server but it turns out that the ball has been dropped for the Windows 10 Pro for Workstations SKU.  I am 100% sure I have file corruption because ReFS indicates checksum errors for dozens of files when integrity is enforced.  Problem is that only one error is shown in the event log whether or not enforced, no repairs are accomplished, and the data integrity scan does not work at all when integrity is enabled whether or not enforced.
On another forum, some of the folks at this alias suggested the corruption I created was perhaps on unallocated space.  That is incorrect.
Again, the W10 Pro for Workstations version has obviously not been developed and tested the way Server has.  Please address.
Thanks,Mark



    On ‎Tuesday‎, ‎August‎ ‎14‎, ‎2018‎ ‎03‎:‎52‎:‎42‎ ‎PM‎ ‎PDT, Aniket Naravanekar <notifications@github.com> wrote:  
 
 
Hello mjohnsonn,

ReFS deletes files in two scenarios:
   
   - ReFS detects Metadata corruption AND there is no way to fix it. Meaning ReFS is not on a mirrored volume where it can fix the corrupted copy.
   - ReFS detects data corruption AND Integrity Stream is enabled AND there is no way to fix it. Meaning if Integrity Stream is not enabled, the file will be accessible whether data is corrupted or not. If ReFS is running on a mirrored volume using Storage Spaces, the corrupted copy will be automatically fixed.

So to answer your question, the file will not be deleted because a few bits are corrupted. The value of ReFS lies in providing guarantee that the data you're reading is exactly what was written to the disk. It does this by correcting errors through copies stored on mirrors.

I would recommend using mirrored volumes to compliment ReFS for:
   
   - data integrity guarantee
   - automatic error correction

Thanks,
Aniket.

**Comment by JackTrapper** [comment]
ReFS has a feature known as **Integrity Streams**. When you enable this optional feature for files, the filesystem maintains a CRC of the file. With this checksum, it can validate that a file has not been damaged.

The down-side of the **Integrity Streams** feature is:

- if it detects even a single-bit error
- in an otherwise fine 340 GB file (e.g. `ProductionServer.vhdx`)
- it will **delete** the *entire* file

No warning. No question. No appeal. One uncorrectable bit and you lose all your data.

This is what **Enforced** means. It means that you are forced to suffer complete data loss. And if you didn't like it: you shouldn't have enabled *file integrity*.

This behavior is quietly [documented:][1]

> Key Benefits
> ---------
> 
> Resiliency
> 
> Salvaging data - If a volume becomes corrupted and an alternate copy of the corrupted data doesn't exist, **ReFS removes the corrupt data from the namespace.** ReFS keeps the volume online while it handles most non-correctable corruptions, but there are rare cases that require ReFS to take the volume offline.

*(emphasis mine)*

It's also partially documented in [**Set-FileIntegrity** cmdlet:][2]

> **-Enforce**: Indicates whether to enable blocking access to a file if integrity streams indicate data corruption.

That sounds like the thing that we'd want to **not** exist. That sounds like the feature that no sane person on the planet would ever want to even **exist**, let alone have Enabled. And yet it defaults to on.

**Note**: It says *"block"*, and the first page says *"remove"*. Whatever the terminology: there is no way to access the file ever again. I.e. there is no way to "un-block" it, nor is there any way to *"un-remove"* it. In all ways that matter your data is gone.


  [1]: https://docs.microsoft.com/en-us/windows-server/storage/refs/refs-overview
  [2]: https://docs.microsoft.com/en-us/powershell/module/storage/set-fileintegrity

**Comment by NilEinne** [comment]
> It's also partially documented in [**Set-FileIntegrity** cmdlet:](https://docs.microsoft.com/en-us/powershell/module/storage/set-fileintegrity)
> 
> > **-Enforce**: Indicates whether to enable blocking access to a file if integrity streams indicate data corruption.
> 
> **Note**: It says _"block"_, and the first page says _"remove"_. Whatever the terminology: there is no way to access the file ever again. I.e. there is no way to "un-block" it, nor is there any way to _"un-remove"_ it. In all ways that matter your data is gone.
> 
> People at Microsoft tried to talk to people on the Storage team, and the answer is: [you lose everything if 1 bit is bad. ](https://social.technet.microsoft.com/Forums/windowsserver/en-US/17c879b2-8b4b-4692-8c8d-201a062d1ec8/recovery-after-refs-events-133-513-apparent-data-loss-on-dual-parity)

If "blocking access" means the file is removed when it's unrecoverable, IMO this should be clarified in all documentation where it says "blocking access". To my mind, blocking access and indeed the description used on Set-FileIntegrity simply suggests that access to the file is denied if it corrupt. This doesn't mean it is removed nor does it mean it can't be unblocked. 

To my mind, if access is simply blocked then at a minimum logically, an admin should be able to use Set-FileIntegrity to change the Enforce flag to False which would enable them to access it. They should even be able to simply remove FileIntegrity stream even though the file is corrupt. Perhaps when they do so a warning should be raised unless they use a force parameter, but I would assume this is possible if it's simply blocking access.

**Comment by mjohnsonn** [comment]
Again for the casual reader not reading the whole thread:

You could have a multi GB video file where one bit has flipped due to rot and you used ReFS because you thought it was resilient.  Because of ReFS, the entire file is gone.  Still being there but inaccessable by any means is still gone.

Has this been addressed?  NilEinne's response seems like a reasonable fix.

BTW I have a billion dollars in my pocket right now.  It's just not accessable by any means.

**Comment by mechanical-snail** [comment]
Hi, it looks like this issue was mistakenly closed due to some pull request having the same number as this issue. It was not actually addressed. Can it be reopened?

The `windows-server/storage/refs/integrity-streams` doc doesn't currently mention the enforce setting, and this setting and its behavior should really be documented there.
