### ISSUE TITLE
The option to "Change Drive Letter and Paths" is greyed out.  

### ISSUE THREAD

**Issue by rossed1** [MicrosoftDocs/windowsserverdocs#1146]
The option to "Change Drive Letter and Paths" is greyed out.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc0bd645-908f-3997-f21e-df23e54614da
* Version Independent ID: 5edc90ff-7167-e42e-aef7-7b72318d230e
* Content: [Change a drive letter](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-a-drive-letter#feedback)
* Content Source: [WindowsServerDocs/storage/disk-management/change-a-drive-letter.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/change-a-drive-letter.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by findalina** [comment]
When I right click on the System Reserved Partition it does not offer anything but help.  I would like to name the drive.  How can I fix this?

**Comment by devoncoldwell** [comment]
I have this problem as well. This particular partition was not showing on my computer before, but after an update it seems to have appeared. Particularly annoying when it always gives me a 'This drive is full!' notification.

**Comment by Dreammaster13** [comment]
![initialize](https://user-images.githubusercontent.com/33403853/46064849-26e90400-c136-11e8-83f1-8fe27e473880.PNG)
I can't do anything with this drive. 
When I try to initialize it using MBR style it says - Device is not ready.
When I try to initialize it using GPT style it says - The specified disk is not convertible because the size is less than the minimum size required for GPT disks.
