### ISSUE TITLE
Missing Section?  CA configuration for non-domain joined computers?

### ISSUE THREAD

**Issue by drewPrince** [MicrosoftDocs/windowsserverdocs#1163]
I left another comment on a closed thread, so just in case this new thread may be more appropriate.

I am setting up a non-domain joined VPN server as recommended, however, waaay at the top in section "Configure certificate autoenrollment in Group Policy" step 4 the next button in grayed out.  I believe it is because my VPN server does not know to contact the domain to find the CA.  Can some documentation be added to show how to properly and safely complete this step?

I found this separate, not related, 8 year old article, but I dont want to have to configure additional services and security issues if I dont have to.  Or maybe it is a DNS related issue such as a SPN so the internal NIC of the VPN server can find the CA?  I dont know enough about either obviously.

https://blogs.technet.microsoft.com/askds/2010/05/25/enabling-cep-and-ces-for-enrolling-non-domain-joined-computers-for-certificates/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e886cf2-b2cc-1942-2e93-b83ba3f5c81a
* Version Independent ID: 14185f76-c920-66a5-9d3b-51ddc4845ee8
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@drewPrince, Thank you for your feedback.  I reached out to engineering and support to incorporate the steps for nondomain-joined configurations.

**Comment by plekkenpol** [comment]
It's not so much a non-domain joined configuration that is in question.  Obviously the DC, CA and NPS server are domain joined (hence the DC).  The VPN server sits on a perimeter network (Internal perimeter and External perimeter in this case).  Typically Microsoft will suggest that these types of servers are non-domain joined since they are accessed by clients from the Internet.  This article suggests you can just fire up certlm.msc on the non-domain joined VPN server and ask the domain for a certificate.  What we need are instructions on whether the VPN server should be domain joined, and if not, instructions on how to submit an offline request for the certificate from the VPN server.  The article seems to infer the VPN server should be domain joined since it calls for creation of the VPN Servers group...

**Comment by drewPrince** [comment]
In response to your comment:  "This article suggests you can just fire up certlm.msc on the non-domain joined VPN server and ask the domain for a certificate"

These instructions here do not show how to "fire up" certlm.msc on a non-domain joined server and pull a cert from the domain.  The instructions show how to pull a certificate from a domain joined VPN server which yes, is easy.  But when the VPN server is not on the domain it cannot easily pull a cert, THAT is asking what is the proper, safe & secure method?

I did manage to pull a cert myself, but my configuration is not yet working and I'm not sure if it is related to something else, or perhaps the certificate wasn't installed properly.

**Comment by shortpatti** [comment]
@drewPrince, Thank you :)  That's quite useful.  I did find the written instructions so I'll keep this in mind when I start to incorporate the information.

**Comment by shortpatti** [comment]
The content has been added and will be published later this morning.
