### ISSUE TITLE
Can't Sign into https://<fqdn>/RDWeb/webclient/index.html 

### ISSUE THREAD

**Issue by zoddd** [MicrosoftDocs/windowsserverdocs#1191]
When browsing to https://&lt;fqdn&gt;/RDWeb/webclient/index.html I am getting a credential prompt that does not let me in with an account that is a member of a security group provided in the RD-CAP. So I just get the login prompt over and over with no error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Heidilohr** [comment]
I’m sorry to hear you’re having problems with the web client. If you’re not able to fix it using the information here, please reach out using the email address found on the About page of the client.

**Comment by zoddd** [comment]
I can't get to the about page, the focus of the credential prompt does not allow you to click anywhere else.  See attached screenshot.

![2018-07-20_11-12-46](https://user-images.githubusercontent.com/16342574/43013466-9b5c0268-8c0e-11e8-956d-ff0c5ab3395d.png)

**Comment by fragwhistle** [comment]
We had a similar issue where one of the people testing the system couldn't log in even though they're a member of the right groups and were typing their password in correctly.
Found that there were some special characters in the password that were causing the issue even though it works fine for a normal windows password.

**Comment by zoddd** [comment]
Thanks for the info, do you recall what characters were not being accepted?

**Comment by fragwhistle** [comment]
Sorry, should have put that in the original comment. The user had the "<" and ">" characters in his password. After he changed his password and removed those special characters it started working.

In my experience putting a space, a "$" or similar can cause issues even though it's technically allowed for a Windows password. I might do some testing today to see if I can build a list of special characters that cause problems with sign-in.

**Comment by fragwhistle** [comment]
So I just went through and tested the following passwords and they all worked. There may be a combination of characters that cause problems. The user I was working with had a number of special characters.
I don't have the resources to test combinations of characters so if someone else has the resources it'd be interesting to know. I've seen it on other web based applications where the windows password works but doesn't in the web app. Presumably because a character hasn't been escaped properly (or because it's causing an escape). 

Password! | ok
Password@ | ok
Password# | ok
Password$ | ok
Password% | ok
Password^ | ok
Password& | ok
Password* | ok
Password( | ok
Password) | ok
Password{ | ok
Password} | ok
Password[ | ok
Password] | ok
Password\| | ok
Password\ | ok
Password; | ok
Password: | ok
Password" | ok
Password' | ok
Password< | ok
Password> | ok
Password, | ok
Password. | ok
Password? | ok
Password/ | ok
Password_ | ok
Password- | ok
Password+ | ok
Password= | ok

**Comment by timbourne** [comment]
We're running Server 2019 and experiencing the issue with $'s in our passwords.  There are probably other special characters it's barfing on, we just don't have the time right now to diagnose further.  We saw this on our Server 2012 installs too.
