### ISSUE TITLE
More steps for ADFS WIA setup?

### ISSUE THREAD

**Issue by billvolt** [MicrosoftDocs/windowsserverdocs#1234]
Should this document link to other documents providing further steps need to configure ADFS for WIA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 375a5fd8-c881-b6f7-c93f-b8898020c43f
* Version Independent ID: 0c58c9d1-cb1f-03b2-9456-3e5550e8d8ab
* Content: [Configure browsers to use Windows Integrated Authentication (WIA) with AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-browser-wia)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by jeremycook** [comment]
I'd add it would be valuable to link to the following page since it covers configuring "Chrome" support and this one does not, or perhaps combine the two pages into one.

https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-intranet-forms-based-authentication-for-devices-that-do-not-support-wia#configuring-wia-for-chrome

**Comment by IngridAtMicrosoft** [comment]
#please-close
