### ISSUE TITLE
Maximum size/length of BannedIpList

### ISSUE THREAD

**Issue by CJA-Emory** [MicrosoftDocs/windowsserverdocs#1257]
What's the maximum size/length of the BannedIpList?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e37706-af12-9dc3-4004-bdab6f8039e9
* Version Independent ID: c9f498a9-457b-b22f-2071-5f5dab609981
* Content: [Configure AD FS Banned IP Addesses](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-banned-ip)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Banned-IP.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Banned-IP.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Nick42-** [comment]
300 entries, at least per the command itself (I had a list MUCH longer....).    This REALLY needs to be longer.  Like 5 digits longer.

**Comment by leohoknows** [comment]
Nick42 were you using a script to read from a file containing your 300+ banned IP list?

**Comment by Nick42-** [comment]
No.  I made a ridiculously long powershell script that added each one with a separate command (in an attempt to see if it was a batch thing, or ...)

**Comment by leohoknows** [comment]
Thanks for responding Nick. I managed to get this figured out. We have a list of banned IPs in a CSV coming from our PaloAlto and I created a basic script to read the contents and add to the banned IPs list.

Looks like it’s working great!!!

If this email is in regards to an IT request, please redirect it to ITSupport@bonavistaenergy.com<mailto:ITSupport@bonavistaenergy.com> or by calling 403-514-7329 so it may be dealt with in a timely manner.


LEO HO | Systems Administrator
D 403.514.7329
E Leo.Ho@bonavistaenergy.com<mailto:Leo.Ho@bonavistaenergy.com>
1500, 525 8th Avenue SW | Calgary, AB T2P 1G1
bonavistaenergy.com<http://bonavistaenergy.com/>

[cid:image001.png@01D0EED9.64735BA0]

**Comment by Nick42-** [comment]
More than 300?!?!?!

**Comment by leohoknows** [comment]
No, our IP list gets updated daily and maybe has a few hundred

If this email is in regards to an IT request, please redirect it to ITSupport@bonavistaenergy.com<mailto:ITSupport@bonavistaenergy.com> or by calling 403-514-7329 so it may be dealt with in a timely manner.


LEO HO | Systems Administrator
D 403.514.7329
E Leo.Ho@bonavistaenergy.com<mailto:Leo.Ho@bonavistaenergy.com>
1500, 525 8th Avenue SW | Calgary, AB T2P 1G1
bonavistaenergy.com<http://bonavistaenergy.com/>

[cid:image001.png@01D0EED9.64735BA0]

**Comment by leohoknows** [comment]
FYI, this is how I went through automating adding banned IPs to ADFS.

We have a list of banned IP addresses that gets updated from our PaloAlto to a CSV file.

I created the following powershell script to pull the IPs from the CSV and then add those IPs to the ADFS bannedip list:
$BNPBannedIPs = Get-Content C:\Scripts\ADFS\Test.csv
Set-AdfsProperties -AddBannedIps $BNPBannedIPs

Since the CSV file that contains the banned IPs gets updated daily from our PaloAlto,
I created a scheduled task to have the powershell script run daily.

Hope this helps

**Comment by Nick42-** [comment]
So I'm curious what happens once you hit 301 entries...

**Comment by leohoknows** [comment]
I will let you know if and once I get there :)

**Comment by hodgesb** [comment]
I hit the 300 limit fairly quickly. I created a powershell script to automatically ban IPs found in brute force password spray attacks in ADFS and I reached the 300 limit. It simply will not increment higher than 300.

**Comment by leohoknows** [comment]
Since I'm still fairly new with this, when I run get-adfsproperties I see 4 banned ips followed with an ellipses. Does anyone know how to view all of the banned ips that have been set?

**Comment by hodgesb** [comment]
get-adfsproperties | select bann* -expandproperty bann*
I didn't confirm this, but I think it's correct.

**Comment by leohoknows** [comment]
Hey Bob, do you happen to know how to remove an ip from a user's list of familiarips?

**Comment by Mike-Crowley** [comment]
Please vote on this topic here:

[https://windowsserver.uservoice.com/forums/295047-general-feedback/suggestions/36651025-significantly-increase-the-number-of-banned-ips-th](https://windowsserver.uservoice.com/forums/295047-general-feedback/suggestions/36651025-significantly-increase-the-number-of-banned-ips-th)

I can't imagine any organization that is small enough to think 300 is adequate while also being large enough to deploy ADFS in the first place.

**Comment by KurtBoswood** [comment]
Arrgh... just came across the same issue.
I was in the process of implementing a rotating block list (of known recent brute force attacks), and reached the 300 limit *sigh*

To assume there are only 300 “bad” IP’s out there in the big wide world is delusional.
I totally agree, and hope the limit is increased!  :)

Cheers, Kurt.

**Comment by hodgesb** [comment]
Leeharrison,

You can view the entire list this way:

get-adfsproperties | select bann* -expandproperty bann*

**Comment by reevesjeremy** [comment]
The field accepts ranges and CIDR notation. So try getting more spread by blocking large blocks of IPS that are your largest offenders.

You can use tools below to identify appropriate CIDR notation and what IP spaces are owned by who to help identify appropriately what you want to block.

https://www.ipaddressguide.com/cidr  and 
https://wq.apnic.net/static/search.html

**Comment by Nick42-** [comment]
Still need more entries than the system allows for, since the address spaces are not congruent.

-----Original Message-----

**Comment by reevesjeremy** [comment]
> Still need more entries than the system allows for, since the address spaces are not congruent.

@Nick42- I use Splunk to create a report with all Class B subnets generating excessive EventCode=516, filtered by foreign IPs using Geo location. Sorting by highest count, I check the Class b subnet to ensure the entire net is "owned/operated" by the same foreign entity. Assuming I know that our org does not have affiliates regularly in that geographical location (or require them to VPN if they are), I'll block that entire Subnet range using CIDR. We have 164 ranges covering about 1200 Class Bs. I havn't done a count, but I venture to say that we're blocking millions of IP hosts this way. This reduced our EventsCode=516 from a daily range of 37,000 to 70,000, down to an average of 4,000. Coincidently, most of them are internal now, due to password changes!

If your people are geographically located in places you know, it could be beneficial to block all the other offending geo locations.

Hopefully that helps. If not, sorry! Maybe it could improve but not completely eliminate...  I review the splunk alert periodically and tweak a little here and there.

**Comment by IngridAtMicrosoft** [comment]
#please-close
