### ISSUE TITLE
Reference to SMS-challenge in RD Gateway MFA combined with the NPS Extension - Not possible?

### ISSUE THREAD

**Issue by jotheman03** [MicrosoftDocs/windowsserverdocs#1325]
In this article there is a reference to using an SMS-challenge with an RD Gateway with MFA, based on usage of the NPS Extension. Is this possible? I know this is possible with an Azure MFA Server, but I do not think this is possible using the NPS Extension for MFA, as the RDP-client does not accept any input. Am I correct there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb07b788-3b99-3340-0653-7eda1e3c794c
* Version Independent ID: 70b806b1-23bc-ee70-9fa7-2eb91767c839
* Content: [Remote Desktop Services - Multi-Factor Authentication](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-plan-mfa)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-plan-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-plan-mfa.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by pstasik** [comment]
This has been my experience from day 1.  Phone call and notification through the mobile app work because they are one-way approvals.  RDS (at this time) has no way of prompting for codes, etc.  2-way SMS will work with MFA Server (on-prem) but I think that feature is also being deprecated.  RDS will also ONLY use whatever is setup as the user's default method.

**Comment by shaikhosama** [comment]
Hi Pstasik,
You mentioned if we use azure MFA on prem we could 2 factor SMS with while RDP'ing to server ? since RDP client doesnt take anyinputs except credenatils how can we achieve that or if its not possible with SMS Text  then let me know

**Comment by pstasik** [comment]
> Hi Pstasik,
> You mentioned if we use azure MFA on prem we could 2 factor SMS with while RDP'ing to server ? since RDP client doesnt take anyinputs except credenatils how can we achieve that or if its not possible with SMS Text then let me know

@shaikhosama 
2-way SMS does not require any input on the RDS logon screen, only a reply to the original SMS sent to the phone. The end-user experience is similar to using the Microsoft Authenticator mobile app.  I would recommend using the mobile app instead of a SMS anyway as it is easier to use, in my experience.  

For MFA with RDS, we stopped using MFA on-prem and started using the NPS Extension.

**Comment by IngridAtMicrosoft** [comment]
#please-close
