### ISSUE TITLE
Change drive letter greyed out

### ISSUE THREAD

**Issue by rinn009** [MicrosoftDocs/windowsserverdocs#1462]
I can't change the drive letter at this point as the function is greyed out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc0bd645-908f-3997-f21e-df23e54614da
* Version Independent ID: 5edc90ff-7167-e42e-aef7-7b72318d230e
* Content: [Change a drive letter](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-a-drive-letter)
* Content Source: [WindowsServerDocs/storage/disk-management/change-a-drive-letter.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/change-a-drive-letter.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dpbrick** [comment]
Same issue here.  So the article is of very limited value.  Please advise as to next steps when context menu options are grayed out.

**Comment by JasonGerend** [comment]
I've updated the topic to try to address the most common cases where the menu options aren't available, so hopefully that helps some. However, our technical support has told me that because of the huge variety of storage devices that work with Windows, there will be other cases that we can't address here, in which case we suggest that you contact either the device manufacturer or Microsoft support. Thanks, and again I hope this helps...
