### ISSUE TITLE
HA Install Fails on Windows Server 2016 v1709 (Core)

### ISSUE THREAD

**Issue by andyhud** [MicrosoftDocs/windowsserverdocs#1543]
Trying to install WAC on 2 x Windows Server 2016 v1709 Core Servers

Failover Cluster all built with CSV for storage (15GB) and Witness etc. Usual stuff.

When I run the installer this is what I'm executing

 .\Install-WindowsAdminCenterHA.ps1 -clusterStorage C:\ClusterStorage\Volume1 -c
lientAccessPoint wac -msiPath .\WindowsAdminCenter1809.msi -certPath .\wac.pfx -certPassword $certpasswor
d -staticAddress 192.168.0.150

I get this, on either node I run it on:

Processing data for a remote command failed with the following error message: The I/O operation has been aborted
because of either a thread exit or an application request. For more information, see the about_Remote_Troubleshooting
Help topic.
At C:\InstallFiles\Windows Admin Centre\Install-WindowsAdminCenterHA.ps1:115 char:9
+         Invoke-Command -ComputerName $computer -ScriptBlock $command  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (WAC01:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : WAC01

I've set executiion policy on both nodes for Local Machine and Process to Unrestricted, no change.
Both servers have 16GB Ram etc.
Winrm quickconfig done

Any ideas?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32deb7a0-4ea0-caf1-0777-580539173e44
* Version Independent ID: a6ee1f9d-b316-c69d-fa9d-2a1556454868
* Content: [Deploy Windows Admin Center with High Availability](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/high-availability)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/high-availability.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/high-availability.md)
* Product: **windows-server-threshold**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by hinz888** [comment]
I am having the same problem with Windows Server 2016 1607.  I had Windows Admin Center 1804.25 installed without any problems.  I tried to upgrade that installation to 1809 and it failed.  I then discovered I was able to install the 1808 preview version of Windows Admin Center without any problem, but again if I try and upgrade the 1808 version to 1809 it fails.  When I try a brand new install of 1809 on my Windows 2016 1607 HA it fails with the same error you are seeing on Windows Server 2016 1709.  I am using the GUI version and not the Core install of Windows Server 2016.

**Comment by andyhud** [comment]
Thanks, if I do the install on a Single Windows 2016 v1709 Core server as a standalone install it works fine, only if I try to run the HA cluster scripts does it fail. I'm going to try the cluster on the long term channel Windows 2016 (as a Core install) and see if the same problem occurs.

**Comment by lizap** [comment]
Hi, @andyhud and @hinz888 - just wanted to let you know that we're aware of this problem and are working on a fix. Sorry you're having problems. :(

**Comment by hinz888** [comment]
Thanks for the update.  I am looking forward to the fix.

**Comment by andyhud** [comment]
Thanks @lizap - Is this issue specific to v1709 Server OS?

**Comment by brian0975** [comment]
I don't know why this issue was closed. I've been watching it because I've had the same issue.
Today, I downloaded the HA scripts again and they're exactly the same as I had last month - all with a date of 4/10/18
After attending Ignite I was really excited to deploy WAC since it was talked up so much. This I/O operation error is a total show-stopper for us.

**Comment by hinz888** [comment]
I agree.  I am not aware the problem has been fixed yet.

**Comment by andyhud** [comment]
Yep, I saw the Closed too and though "Oh wow, they fixed it".. oh wait, they just closed it with no reason.. Wicked.

**Comment by coreyp-at-msft** [comment]
Hi @brian0975, @hinz888 and @andyhud,

This Issue was closed because it has been answered. We provide Github Issues for reporting inaccuracies in the Windows Server documentation set. This Issue pertains to software functionality and has been reported to Engineering, as Liza answered. When an issue is closed, it is not necessarily because it has been fixed or resolved, but because we have taken note and provided all the information we have at the time. We do not use Github Issues to track resolution of software requests or bugs, but we do report them to the Engineering group and let you know when we've done so. We apologize if this has caused confusion and we will soon provide a better explanation of how we use Github Issues for addressing documentation inaccuracies in the repo readme and Issues template. 

Please note that this issue, although closed, is not locked and you are still able to comment in it, and all participants are still notified when you do. Before I closed the issue, I added Jeff Woolslayer, the Engineering Program Manager, so he can track any further conversation.

Thanks,
Corey

**Comment by andyhud** [comment]
Hi @coreyp-at-msft 

Thanks for the clarity, that does now make more sense and knowing the reason why you closed this here for me at least, is clearer.

Where is the best place to ensure we are kept aware of progress of this issue?

Thanks
Andy

**Comment by andyhud** [comment]
Any update on this?

**Comment by brian0975** [comment]
After studying the HA scripts for 1804, and much trial and error, I have been able to successfully install 1809 in HA mode. I have written this powershell script.

Please open the file in your editor of choice, read the comments, understand it, and run each section manually, as appropriate. DO NOT simply run the script.

[Install_WAC_1809.zip](https://github.com/MicrosoftDocs/windowsserverdocs/files/2606064/Install_WAC_1809.zip)

**Comment by hinz888** [comment]
I was also able to manually install using the scripts provided by @brian0975 . Thank you.
