### ISSUE TITLE
Windows 10 support?

### ISSUE THREAD

**Issue by maximojoexpress** [MicrosoftDocs/windowsserverdocs#1631]
Hi,

Is this available on Windows 10 Pro (Consumer and or Business)?

m

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06fc7832-1655-f552-de28-b99bf2ab092f
* Version Independent ID: 2a99f3c3-3472-1a5a-0a22-b99615108980
* Content: [Deploy graphics devices using Discrete Device Assignment](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/deploying-graphics-devices-using-dda)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/Deploying-graphics-devices-using-dda.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/deploy/Deploying-graphics-devices-using-dda.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @chrishuybregts
* Microsoft Alias: **chrihu**

**Comment by mcheve01** [comment]
Hello,  When I run these commands in Powershell, it says "Dismount-VMHostAssignableDevice" is not recognized,  Is this command supported by server 2012 r2?

**Comment by larsiwer** [comment]
@mcheve01 
Please take a look at the "Applies To" section of the documentation -- this feature is available for Hyper-V on Windows Server 2016 and Windows Serve 2019.

@maximojoexpress 
This feature is currently not available on client operating systems. Can you share more about the scenario that you're trying to light up?

**Comment by larsiwer** [comment]
@cwilhit might be interested in learning more about the applications that you're trying to isolate.

**Comment by cwilhit** [comment]
Hey @glowtape, can you point me to where you're drawing this info from? Thanks!

"...current transition tech listed is DDA, even for the client version of Windows"

**Comment by glowtape** [comment]
Various places on the web. Since you're with Microsoft, I figure you'd be aware of that? The code is the same for common functionality between client and server. Anything that applies to the server version also applies to the client, say like RDSH.

The quickest direct reference I could dig up on the quick right now is this Twitter statement of a coworker of yours: https://twitter.com/rds4u/status/997418881034719232

**Comment by glowtape** [comment]
Well, anyway, RemoteFX 3D is deprecated. The Hyper-V manager on client disallows adding the virtual hardware to VMs. PowerShell still does it, but that's beside the point, and a guess for how long it'll still do. 

DDA also works in client. Theoretically, anyway, because NVidia does their usual and prevents their users from using the passed-through hardware, when their driver detects being run in a VM (same spiel as with Linux KVM, which at least allows hiding the hypervisor).

**Comment by cwilhit** [comment]
Thanks for that. DDA has never been a recommendation to our client users; it doesn't work, plain and simple. 

Can you tell me more about these graphics intensive apps? Are these games, or other? I periodically see this request come by from users and it's good to get an idea for use cases.

**Comment by glowtape** [comment]
Things like Solidworks or Photoshop. Both are the sort of apps I'd love to run isolated, due to how much things they tend to install that keep running in background. It's gone, if contained within a VM, after you shut it down.

Solidworks litters the system with old DLLs and Office 2003 components and some background services, Photoshop (or Adobe software in general) installs tons of background and antipiracy services that love to go haywire once a while. I'm sure there's more applications that'd qualify.

They both profit from a GPU. Solidworks for rendering the graphics and Photoshop for both rendering and using GPU compute. The scenario I'd like realized is to boot a VM with a graphics card on a HDMI dongle and then RDP into it. That already sorta worked on Linux with KVM and VFIO, but I'd rather not use Linux.

As far as DDA goes, seems like the relevant people claiming to have it running seemed to implicitly use the server version (without saying so, probably because it wasn't legit). A supposed co-worker of yours posted on Reddit (_hypervguy) that the one of main reasons DDA is disabled on client is that it'd break some consumer scenarios like hibernation and sleep. Considering how much of a niche use case it is, anyone using DDA would probably be fine with that.

**Comment by Bugra-chem** [comment]
If DDA gets popular with all Win10 versions(and also one click to switch gpu in gui), Linux OS gonna be not more than program for devs and Linux allows gpu passthrough for windows.
So Windows are you gonna be nested program in Linux or reverse in the future... =)
