### ISSUE TITLE
Storage migration feature missing in server 2019 GA

### ISSUE THREAD

**Issue by Bartsmet** [MicrosoftDocs/windowsserverdocs#1636]
This feature is not present in the GA release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3b0886-820a-0b3c-8382-8d65fc8c3b27
* Version Independent ID: 3e310218-abc0-5249-bb16-7c21402e32c0
* Content: [Storage Migration Service overview](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/overview#feedback)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by nedpyle** [comment]
Hi. This happens when you are using the 1809 WAC versus an old insider build of Windows Server. The 1809 SMS WAC extension is version bound to the Windows Server 1809 (or later) build. 

If you were to download an older preview SMS WAC extension or wait for Windows Server 2019 to GA, the issue will stop. 

I will update our FAQ and requirements to reflect this until the server GAs. Thanks for the comment.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
