### ISSUE TITLE
Can't Connect WAC to Azure Update Management

### ISSUE THREAD

**Issue by marktheiii** [MicrosoftDocs/windowsserverdocs#1727]
So, every time I try to run through the wizard to connect to AUM, it fails out while creating the Automation account, with the error: Error while setting up Update Management - Object reference not set to an instance of an object.

I tried to work around this by just setting up an Automation account in Azure ahead of time, but the wizard does not see the created account and continues to fail out.

Any help?

Thanks,
Mark

**Comment by jwwool** [comment]
Adding the owner of this area, @Haley-Rowland

**Comment by sushmad** [comment]
@marktheiii Can you answer some questions for me?
1. Is your gateway running in service mode or desktop mode?
2. Which region are you creating your automation account in?
3. Are you also creating a log analytics workspace? If yes, does that step succeed? or are you using an existing one?
4. Can you get me a detailed error for when automation account creation fails? You can go to Event Viewer-> Applications and Services Logs -> Microsoft-ServerManagementExperience and export the logs for me.

Finally - when you create a new automation account by yourself, are you also linking it to your workspace? Because WAC can only enumerate those accounts that are already linked to your workspace. may be you didn't and that's why the wizard doesn't enlist your automation account.
