### ISSUE TITLE
Be more specific on registry subkeys and perhaps add in info about how to figure who is using a given protocol

### ISSUE THREAD

**Issue by jricha34** [MicrosoftDocs/windowsserverdocs#1738]
Every single place where you have 

Registry path: HKLM SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols

To enable the XXX protocol, create an Enabled entry in the appropriate subkey. 

You should be fully documenting what the appropropriate subkey is as right now on first glance it looks like with the exception of TLS 1.0 you are just assuming someone knows and if they already know they wouldn't be here looking at the documentation.

Something else you should probably consider adding is how people can ascertain whether or not certain protocols are being used and the source of that use such that when you release something saying "TURN THIS OFF" they have a fighting chance at figuring out what might break when they do turn it off.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38fcd9dd-91c8-e79b-5f4d-28a435a8ada8
* Version Independent ID: 0d79a0c8-0b73-c783-4d5c-b107d24acf55
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server-threshold**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@jricha34 Thanks for the feedback Joe! I revised the TLS 1.0 section to make the registry path and subkey more clear: https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#tls-10 

Is that better? If so I'll do the same for the other sections.

I ran your other suggestion about how to tell what protocols are in use and what will break when we say to turn them off by the dev. He agreed this would be useful for customers so he's added it to their backlog. It is fundamentally difficult because we can’t guarantee that the app gets used when they’re watching for it, and there's a perf hit if we monitor for it all the time.

**Comment by jricha34** [comment]
Much better, thanks Justin.

Cool on the sorting out protocols in use. It is indeed painful. But for good security it needs to be known and for good operational stability you can't just turn it off and see what breaks.

   joe

________________________________
