### ISSUE TITLE
Can this topic be removed?

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windowsserverdocs#1746]
WEDSUtil is not included in server 2016 by default or in Server 2019 and I assume WIndows Server SAC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7430147-3003-7132-4a4c-ff3a50ab7b9f
* Version Independent ID: 15186af0-cda0-00c1-cd84-04df5cf34615
* Content: [wdsutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wdsutil#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/wdsutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/wdsutil.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Sorry about not discovering this ticket earlier and hence not getting around to answer your report before now.
Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.
The MS Docs team members may not have time to answer your question or report, both due to the small size of the team and the big workload.

Please note: The `wdsutil` tool (WDS Utility) is not installed by default, that is correct. But it is part of the installation software on the Windows Server OS DVD or ISO image.

WDS, or Windows Deployment Services is a Role, just like WSUS (Windows Server Update Services) and RDS (Remote Desktop Services), so you need to install the Role "Windows Deployment Services" before you get access to the utility/software tool `wdsutil`. Otherwise, your CMD line will just say:
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Windows\system32>wdsutil /?
'wdsutil' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>_
```

For example, my workplace production server, Windows Server 2016 Standard, does not currently have the tool 'wdsutil' available, even if Active Directory (AD DS) is set up, DHCP & DNS is installed, File and Storage Services, IIS, Print Services, and Remote Access is running (see the Server Manager image below as an example):

![image](https://user-images.githubusercontent.com/38162891/98305119-8aa2b400-1fc1-11eb-8151-8f12991150d4.png)

***

To reiterate, you absolutely have to install the Role "Windows Deployment Services" before 'wdsutil' becomes available.

See the following image from the Role selection wizard in Server Manager:

![image](https://user-images.githubusercontent.com/38162891/98305784-cee28400-1fc2-11eb-8ed8-44d60fb1a3aa.png)

**Comment by illfated** [comment]
#please-close

**Comment by doctordns** [comment]
Good catch!

Rather than closing, can we update the page to mention that this utility is part of WDS?

**Comment by illfated** [comment]
Sure, we can do that. Would you like to look up some already existing text (phrasing) to add, or just suggest something yourself, to make it clear for everybody why WDS is not installed by default?
