### ISSUE TITLE
The Desktop Experience is back?

### ISSUE THREAD

**Issue by shebaldenkov** [MicrosoftDocs/windowsserverdocs#1791]
1709 1803 1809 never include Desktop Experience
2016 include Core and Desktop Experience

So why is it "back" in 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 844864ef-2c94-77ff-b85e-301331d283a6
* Version Independent ID: 960ddbd0-a265-7730-859d-a0a308d7a3b1
* Content: [What's new in Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/get-started-19/whats-new-19)
* Content Source: [WindowsServerDocs/get-started-19/whats-new-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/whats-new-19.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by coreyp-at-msft** [comment]
Hi @shebaldenkov , Since the Windows Server releases between 2016 and 2019 did not include the Desktop Experience, it's back again in Windows Server 2019.

Windows Server 2016 (Long-Term Servicing Channel) with Desktop Experience
Windows Server, version 1709 (Semi-Annual Channel) without Desktop Experience
Windows Server, version 1803 (Semi-Annual Channel) without Desktop Experience
Windows Server, version 1809 (Semi-Annual Channel) without Desktop Experience
Windows Server 2019 (Long-Term Servicing Channel) with Desktop Experience

**Comment by tanwarsatya** [comment]
Not able to download the 2019 Long-Term Servicing Channel from MSDN subscriber downloads, Anyone knows the location to download the same.
