### ISSUE TITLE
OpenID requires SQL in farms

### ISSUE THREAD

**Issue by hellfire27** [MicrosoftDocs/windowsserverdocs#180]
It should really be mentioned in the prerequisites that OpenID will not work with using WID in an ADFS farm with multiple servers. Those ADFS servers all have to point to a centralized SQL server for OpenID to function. I discovered this the hard way, and I'm sure it would be helpful for others to know. Thanks

**Comment by thibaultchatiron** [comment]
OpenID actually works with WID as database in an ADFS farm

**Comment by hellfire27** [comment]
At least with my installation that has three load balanced servers in it, OpenID/Oath would not function correctly against the two secondary servers. It worked fine against the primary but that meant it failed 2/3rds of the time. We believe it had something to do with some artifacts not replicating from the primary server's WID to the others. Once we converted all three to use a centralized database all of those problems cleared up instantly.

**Comment by thibaultchatiron** [comment]
Artifact is a part of SAML protocol, so that's not the problem.
Actually, there are an issue with WID and ADFS farm where some keys were not synchronized, but this is a known issue and a KB was performed. See [KB4038801 ](https://support.microsoft.com/en-us/help/4038801)
On my side, I have a farm with 3 ADFS servers and WID, and OpenID works well ! :)

**Comment by hellfire27** [comment]
Ah makes sense. We ran into that wall in June of last year, and the patch hit in September. If I build another farm I'll give it a spin. Thanks for the info.
