### ISSUE TITLE
No FFL/DFL update?

### ISSUE THREAD

**Issue by sime3000** [MicrosoftDocs/windowsserverdocs#1818]
MicrosoftGuyJFlo
Hi John. Did we miss your promised update to this article last week re FFL/DFL ? ?
It’s what we do as IT Pros.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86e4b814-7c4a-0895-2eea-667e3870053f
* Version Independent ID: 740cea70-5958-4560-617f-d9f55e7dc78d
* Content: [Windows Server 2016 Functional Levels](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/active-directory-functional-levels)
* Content Source: [WindowsServerDocs/identity/ad-ds/active-directory-functional-levels.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/active-directory-functional-levels.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Nope you didn’t. Corey just gets a little Issue closing happy sometimes. I’ll follow up when I publish the update.

**Comment by coreyp-at-msft** [comment]
Hi @sime3000, The Issue was closed because it has been answered. We provide Github Issues for reporting inaccuracies in the Windows Server documentation set. When an issue is closed, it is not necessarily because it has been fixed or resolved, but because we have taken note and provided all the information we have at the time. We do not use Github Issues to track resolution of requests or bugs.

Please note that your issue, although closed, is not locked and you are still able to comment in it, and all participants are still notified when you do.

Thanks,
Corey

**Comment by MicrosoftGuyJFlo** [comment]
@sime3000 I pushed the button just now to get the following added to the article today. 

Windows Server, version 1809
There are no new forest or domain functional levels added in this release.

#please-close

**Comment by MicrosoftGuyJFlo** [comment]
@coreyp-at-msft you can close now.
