### ISSUE TITLE
Incorrect WSL Prerequisite

### ISSUE THREAD

**Issue by dreblen** [MicrosoftDocs/windowsserverdocs#1880]
The "Note" section at the top of the page indicates that you need WSL enabled before you can run this utility, but the "Applies to" section lists several operating systems where WSL isn't applicable. I've also confirmed that I can run the utility without WSL enabled.

If there is a connection between this utility and WSL, it should probably be clarified. Otherwise, that part of the note is misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c21d61-d08c-250a-097b-6e5794525107
* Version Independent ID: 121ab330-a917-d5f2-d9f3-e317d95bc584
* Content: [Fsutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/fsutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/fsutil.md)
* Product: **windows-server-threshold**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

**Comment by beltaurus** [comment]
I just stumbled into this because I need to know if my customers will be able to run fsutil on their machines.
I believe that WSL is only required for certain commands (e.g
```
fsutil file setCaseSensitiveInfo <path> enable
```
)

But for other commands, it is not (e.g.
```
fsutil fsinfo drives
fsutil file queryfileid <directory>
```
)

The command documentation should be a lot clearer on this.

I also find myself not even needing administration privileges, to run query-type commands... (which is what I want to do in the scripts for my customers)... Doing more research on this...

**Comment by IngridAtMicrosoft** [comment]
#please-close
