### ISSUE TITLE
Change Win 10 Admin Center port after Admin Center has been installed without having to uninstall & reinstall

### ISSUE THREAD

**Issue by itguy007z** [MicrosoftDocs/windowsserverdocs#1882]
I installed the Windows Admin Center on Windows 10 using the default port number of 6516.

Is there any way of changing this port number from 6516 to another port without having to uninstall and then reinstall the Windows Admin Center?

If so how can this be done?

**Comment by jwwool** [comment]
When installed on desktop, uninstall and reinstall is the easiest. It is **possible** to change without reinstall, but not supported.
If this is something that you like to see added to Windows Admin Center, please [create a suggestion](http://aka.ms/wacfeedback) for it to be tracked!

To do it without reinstall, follow these steps:
* Stop smedesktop.exe
* Edit ```HKLM\SOFTWARE\Microsoft\ServerManagementGateway\SmePort``` in the registry to reflect the new value
* Follow the steps [here](https://charbelnemnom.com/2017/10/how-to-change-the-thumbprint-of-a-certificate-in-microsoft-project-honolulu-servermgmt-servermgmt/), *except replacing the port instead of the thumbprint*. The url acl for network service is also not necessary, but it might be necessary to add a url acl for your user account.
