### ISSUE TITLE
Use Case Scenarios

### ISSUE THREAD

**Issue by jwashbur79** [MicrosoftDocs/windowsserverdocs#1961]
Hi Team, thank you so much for sharing this documentation! Is Storage Spaces Direct & Storage QoS only for use with a File Server Cluster, or are there other scenarios where this concept would work. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fd16ce-9e03-4eb7-8ada-8d227d48d973
* Version Independent ID: a79cb8ca-fd11-b067-d503-e19d5cbeee61
* Content: [Storage Quality of Service](https://docs.microsoft.com/en-us/windows-server/storage/storage-qos/storage-qos-overview)
* Content Source: [WindowsServerDocs/storage/storage-qos/storage-qos-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-qos/storage-qos-overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @KumudD
* Microsoft Alias: **JGerend**

**Comment by zburtondbrs** [comment]
You can use Storage QoS for the storage for your Hyper-V machines. You cannot use it for generalized file server use--since both use-cases listed above rely on Cluster Shared Volumes, you would hit a metadata bottleneck and performance would be quite poor.

The situation is very similar with Storage Spaces Direct. On the S2D side, though, an SQL workload is another option. Since SQL writes to metadata very infrequently, it is a good fit for Cluster Shared Volumes.

It seems that the biggest Storage Spaces Direct use-case is as part of the high-availability strategy in a large Hyper-V cluster.

**Comment by IngridAtMicrosoft** [comment]
#please-close
