### ISSUE TITLE
Linux Client

### ISSUE THREAD

**Issue by AdiFahmi** [MicrosoftDocs/windowsserverdocs#2015]
No set up instructions for Linux platform, on Ubuntu (the most popular Linux variant) it comes with pre-installed remote desktop client (Remmina). Please add it to the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588d12d1-fdd1-892a-eb5e-9e2d86302368
* Version Independent ID: 5eceac91-1d90-a663-2856-19e13da59351
* Content: [Remote Desktop clients](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by fitzenterprises** [comment]
I absolutely agree with AdiFahmi - I also use Linux as my primary and ONLY workstation OS (Red Hat variants - RHEL/Fedora) which also uses Remmina. I use Remmina for ALL of my remote desktop connections (RDP, VNC, SSH, SPICE, SFTP). If you're going to include every other O/S then you also need to include Linux (Android is a lightweight/embedded variant of Linux anyways). Plus with the recent partnership of Red Hat and Microsoft last year it would only seem appropriate to also include RHEL-based OSes at a bare minimum.

**Comment by Heidilohr** [comment]
I'm asking the dev team if they have instructions specifically for Linux and Ubuntu. I will keep you posted.

**Comment by Chaz6** [comment]
Adding my support to this.

**Comment by adiastra** [comment]
I am also adding my support to this. I would like to be able to use an official RDP client on my Linux desktop.

**Comment by nealmcb** [comment]
I get this error with remmina:

> you requested an H264 GFX mode for server but libfreerdp does not support H264. please check color depth settings

**Comment by nealmcb** [comment]
There should also be documentation to clarify which certificates should be expected and trusted, and what workgroup to use (`Azure\` seems to have worked, but is completely unintuitive to me.)

**Comment by antenore** [comment]
> I get this error with remmina:
> 
> > you requested an H264 GFX mode for server but libfreerdp does not support H264. please check color depth settings

This is because either the freerdp package you have it's old or either because your distro misses H264 support.

If you use Ubuntu you can use our official PPA.

Have a look in [our wiki](https://gitlab.com/Remmina/Remmina/wikis/home), on Gitlab for instruction about how to upgrade/install Remmina

**Comment by antenore** [comment]
> There should also be documentation to clarify which certificates should be expected and trusted, and what workgroup to use (`Azure\` seems to have worked, but is completely unintuitive to me.)

@nealmcb Can you clarify a bit more what is untuitive in the Remmina interface to specify the domain/workgroup? We have a field for that, than, yes, if you want to make it untuitive you can use the `workgroup\user` syntax, but yet, it's something that it's in use since the beginning of the time. :-) 

I'd appreciate a lot if you could submit enhancement requests and/or bug reports in our repository (GitLab), we work very hard to improve Remmina at each release and some feedback from Microsoft would be awesome!!! 

cc @giox069

**Comment by antenore** [comment]
Please don't forget https://github.com/FreeRDP/FreeRDP , that is used by Remmina for the RDP client.
The FreeRDP library (and the relative android and Linux clients) is the only open source project that have implemented most of the RDP specifdications.  

cc: @bmiklautz

**Comment by nealmcb** [comment]
Thanks for the tips, @antenore!

Where is the official PPA?

Re:
> Have a look in [our wiki](https://gitlab.com/Remmina/Remmina/wikis/home), on Gitlab for instruction about how to upgrade/install Remmina

Note that the links at the top of the new wiki:
> From the 1st of July 2018 the following links have to be used instead of GitHub.
>  issues URL
>  wiki URL

are confusing and wrong (404) with an extra `DAGUniverse/`

I've never used Windows regularly, so my notion of "intuitive" will differ ;) , but it seems relevant since Microsoft is trying to welcom Linux open source developers.  The whole notion of a "workgroup" is unfamiliar to me, but I guess the main point is that the specific magic string "`Azure\`" is not mentioned anywhere obvious that I was paying attention to.

Re the certificates, if I recall correctly (I'm not actually sure), I was simply asked to trust some random official-sounding strings. My security orientation makes that a nonsensical thing to do, since I think X.509 lets you put pretty much anything you like in your names.  So I'd want to know a rigorous procedure to be able to get from a known root-of-trust (my distro and the certificates it provides, or DNSSEC or some other good root) to the particular certificate authorities and certificates that I'm being asked to trust. Otherwise, MITM attacks are trivial.

**Comment by Chaoticwhizz** [comment]
I have never had any luck getting RemoteApp to work in Remina on Ubuntu. ALso,  I was hoping Microsoft would port their other RDP app from say MacOS or Android to Linux. Is there any chance of this happening? Microsoft loves Linux now. Why not have an official Linux RDP client?

**Comment by sergiuprt** [comment]
it seems that Microsoft loves Linux for it's own good, not for ours

**Comment by gr0und0** [comment]
Bump!

**Comment by Harrioson** [comment]
Microsoft window is an operating system, 
which is needed to be loaded in a computer after purchasing it.
https://www.techsovibe.com/microsoft-windows/

**Comment by bigpod98** [comment]
Official linux client would be great to gave

**Comment by bigpod98** [comment]
have*

**Comment by adiastra** [comment]
Just recompile the OSX client and release it. Or better yet release it open source and we will handle the rest.

**Comment by bigpod98** [comment]
I second that notion
