### ISSUE TITLE
Getting WSMAN Error in AdminCenter

### ISSUE THREAD

**Issue by EricR82** [MicrosoftDocs/windowsserverdocs#2036]
I get the following error when trying to connect to the server

"The WinRM client sent a request to an HTTP server and got a response saying the requested HTTP URL was not available. This is usually returned by a HTTP server that does not support the WS-Management protocol."

I automatically enable powershell remoting using GPO and this may have something to do with it. I just don't know what settings Admin Center needs in regards to WS-Management, so that I can add them to the GPO.

**Comment by egallagh** [comment]
Can I ask what OS you are running on the system that has Admin Center? What OS is the system that the admin center is trying to connect to? Which implementation topology are you using?

**Comment by egallagh** [comment]
This describes the topologies: https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/plan/installation-options
The answers you already gave had enough info regarding topology.
Are the Win 10 client and the server members of the same domain? Are you using domain accounts? Have you tried specifying the credentials of the default local admin on the server for the connection? (yes, the default admin, using computer name instead of domain name) Let me know if that works

**Comment by EricR82** [comment]
Both the client computer and the server are a member of the same domain. I am using a domain account.

I tried with the local administrator account (<server_name>\Administrator), but that yielded the same result.

**Comment by EricR82** [comment]
I stopped the GPO from applying to the server then re-installed the Windows Admin Center. It works now.
