### ISSUE TITLE
Self-signed certificate for web client

### ISSUE THREAD

**Issue by aries-strato** [MicrosoftDocs/windowsserverdocs#2058]
Is there anyway this can work with a self-signed certificate? I have one right now and keep getting white space instead of a Desktop when I connect to my web client URL.

**Comment by doctordns** [comment]
What 'this' does not work? 

A self signed certificate can certainly 'work'. You can create a new certificate using `New-SelfsignedCertificate`. That cmdlet can put the certificate anywhere you want (typically you save it to the user or computer store).  

If your host has IIS, you can store it in the local computer's 'my' store and then use it just fine to setup TLS with IIS. However, because that cert is not explicitly trusted you get trust issues when using the web site. To avoid that, just copy the certificate from the 'MY' store to the Trusted Root store and it all works for the local user.

**Comment by aries-strato** [comment]
Referring to the web client. I was following this guide on a single VM with a public IP and I had assumed it wasn't working because I was using a self signed certificate (https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin).

This guide indicates multiple times to use a valid public certificate.

**Comment by aries-strato** [comment]
Sorry, disregard this - my problems were related to a misconfiguration with my RD broker.
