### ISSUE TITLE
The settings do not work for high accuracy time.

### ISSUE THREAD

**Issue by adragoset** [MicrosoftDocs/windowsserverdocs#2065]
Not only do these settings not change anything about the way the WindowsTime service operates. The few registry keys mentioned here are not even half of the total number available of actual registry settings on windows 10 or on server 2016 for that matter. I ended up installing a 3rd party tool http://www.timesynctool.com/ because windows absolutely cannot deal with time in an acceptable fashion anytime you need better than a +-500ms time synchronization between two machines 2 feet away from each other. This has caused me a week of troubleshooting the windows time service only to throw Microsoft solution in the garbage and go to a 3rd party tool because its 2018 and Microsoft still cannot deal with time correctly in an operating system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e54ff244-1d40-1f7d-16d9-53c0b31481fe
* Version Independent ID: 8d078d58-34fc-0048-8e77-8b9bbd7d7ca1
* Content: [Configuring Systems for High Accuracy](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/configuring-systems-for-high-accuracy?tabs=MinPollInterval)
* Content Source: [WindowsServerDocs/networking/windows-time-service/configuring-systems-for-high-accuracy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/configuring-systems-for-high-accuracy.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **dacuo**

**Comment by dcuomo** [comment]
Hi - The registry keys listed in the article are those required to reach "high accuracy time."  If configured properly we fully support up to 1ms of accuracy.  If you didn't see anything change, then that's something needing troubleshooting and we can help with that.

If you are interested in troubleshooting this please update this thread with the output of:
- The OS of one of your clients and Time source.  If this is a virtual machine the OS of the hypervisor is also interesting

- w32tm /query /configuration /verbose
- w32tm /query /peers /verbose
- w32tm /stripchart /computer:time.windows.com /rdtsc /period:1 /samples:300

Considering the holidays, please realize response times will be delayed.

**Comment by f0ff886f** [comment]
I followed these instructions and still got drift up to a second off after about 9 hours of testing.

```
w32tm /query /configuration /verbose
[Configuration]

EventLogFlags: 2 (Local)
AnnounceFlags: 10 (Local)
TimeJumpAuditOffset: 28800 (Local)
MinPollInterval: 6 (Local)
MaxPollInterval: 6 (Local)
MaxNegPhaseCorrection: 4294967295 (Local)
MaxPosPhaseCorrection: 4294967295 (Local)
MaxAllowedPhaseOffset: 300 (Local)

FrequencyCorrectRate: 2 (Local)
PollAdjustFactor: 5 (Local)
LargePhaseOffset: 50000000 (Local)
SpikeWatchPeriod: 900 (Local)
LocalClockDispersion: 10 (Local)
HoldPeriod: 5 (Local)
PhaseCorrectRate: 1 (Local)
UpdateInterval: 100 (Local)

FileLogName:  (Undefined or NotUsed)
FileLogEntries:  (Undefined or NotUsed)
FileLogSize: 0 (Undefined or NotUsed)
FileLogFlags: 0 (Undefined or NotUsed)

[TimeProviders]

NtpClient (Local)
DllName: C:\WINDOWS\system32\w32time.dll (Local)
Enabled: 1 (Local)
InputProvider: 1 (Local)
CrossSiteSyncFlags: 0 (Undefined or NotUsed)
AllowNonstandardModeCombinations: 1 (Local)
ResolvePeerBackoffMinutes: 15 (Local)
ResolvePeerBackoffMaxTimes: 7 (Local)
CompatibilityFlags: 2147483648 (Local)
EventLogFlags: 1 (Local)
LargeSampleSkew: 3 (Local)
SpecialPollInterval: 64 (Local)
Type: NTP (Local)
NtpServer: ntp0.as34288.net,0x9 (Local)

NtpServer (Local)
DllName: C:\WINDOWS\system32\w32time.dll (Local)
Enabled: 0 (Local)
InputProvider: 0 (Local)
```

```
w32tm /query /peers /verbose
#Peers: 1

Peer: ntp0.as34288.net,0x9
State: Active
Time Remaining: 40.7908749s
Mode: 3 (Client)
Stratum: 2 (secondary reference - syncd by (S)NTP)
PeerPoll Interval: 17 (out of valid range)
HostPoll Interval: 6 (64s)
Last Successful Sync Time: 20-Feb-19 09:05:59
LastSyncError: 0x00000000 (Succeeded)
LastSyncErrorMsgId: 0x00000000 (Succeeded)
AuthTypeMsgId: 0x0000005A (NoAuth )
Resolve Attempts: 0
ValidDataCounter: 2
Reachability: 6
```

I ran the sampler first to see what was up:

```
w32tm /stripchart /computer:ntp0.as34288.net /rdtsc /period:1 /samples:300
Tracking ntp0.as34288.net [81.94.123.16:123].
Collecting 300 samples.
The current time is 20-Feb-19 08:59:18.
RdtscStart, RdtscEnd, FileTime, RoundtripDelay, NtpOffset
840363924892297, 840363960316100, 131951231589718090, +00.0145543, +00.9680824
840366359068027, 840366391629223, 131951231599883972, +00.0129088, +00.9678636
840368794367407, 840368829054480, 131951231610054545, +00.0140680, +00.9687240
840371227599907, 840371263458336, 131951231620216487, +00.0143560, +00.9680972
840373665673033, 840373714882219, 131951231630398645, +00.0201053, +00.9710358
840376118747701, 840376156511148, 131951231640643454, +00.0152620, +00.9689962
840378557603430, 840378709072026, 131951231650828879, +00.0629024, +00.9447477
840381109158733, 840381375175680, 131951231661484975, +00.1105496, +00.9208017
840383776492972, 840383808482936, 131951231672624598, +00.0130455, +00.9671213
840386207059624, 840386238364185, 131951231682775407, +00.0125722, +00.9677633
840388638327163, 840388690916448, 131951231692929142, +00.0213014, +00.9714517
840391091437488, 840391134155532, 131951231703174100, +00.0173128, +00.9688789
840393537543127, 840393571797192, 131951231713389805, +00.0137713, +00.9675554
840395973635941, 840396009221659, 131951231723563692, +00.0144259, +00.9677696
840398416708880, 840400812695292, 131951231733766730, error: 0x800705B4
840403214512513, 840403247171227, 131951231753803862, +00.0131663, +00.9680211
840405648116052, 840405686955163, 131951231763967354, +00.0157617, +00.9683446
840408088510375, 840408138982044, 131951231774159205, +00.0206650, +00.9710650
840410541392958, 840410619898608, 131951231784403211, +00.0325152, +00.9645386
840413019775390, 840413052948892, 131951231794753716, +00.0135815, +00.9668899
840415450862035, 840415561298844, 131951231804906694, +00.0457015, +00.9576712
840417965503465, 840418022851399, 131951231815408631, +00.0233455, +00.9710888
840420424986048, 840420464634924, 131951231825680195, +00.0160765, +00.9696133
840422865942805, 840423063092520, 131951231835874396, +00.0818293, +00.9345491
840425464185455, 840425647612319, 131951231846725472, +00.0762139, +00.9363435
840428048160835, 840428171313523, 131951231857516963, +00.0509196, +00.9517050
840430572509716, 840430610754740, 131951231868059534, +00.0157227, +00.9685598
840433008574665, 840433048931807, 131951231878233206, +00.0166019, +00.9696325
840435446644429, 840435488208607, 131951231888415350, +00.0167849, +00.9689570
840437891254237, 840437925441252, 131951231898624807, +00.0138254, +00.9675961
840440324852155, 840440359524696, 131951231908788274, +00.0141331, +00.9677513
840442761248965, 840442817661872, 131951231918963431, +00.0233115, +00.9634101
```

I stopped it to run the other commands, and after I did it seems the time synced in the small window:

```
w32tm /stripchart /computer:ntp0.as34288.net /rdtsc /period:1 /samples:300
Tracking ntp0.as34288.net [81.94.123.16:123].
Collecting 300 samples.
The current time is 20-Feb-19 09:08:17.
RdtscStart, RdtscEnd, FileTime, RoundtripDelay, NtpOffset
841651218510604, 841651276865480, 131951236975542534, +00.0240255, -00.0111940
841653674152056, 841653717903565, 131951236985789510, +00.0178033, -00.0129070
841656116918491, 841656348236376, 131951236995983289, +00.0957027, -00.0495535
841658751406211, 841658784227176, 131951237006977682, +00.0132998, -00.0113654
841661184272653, 841661217722227, 131951237017131129, +00.0135838, -00.0109161
841663615899724, 841663657036712, 131951237027279826, +00.0168915, -00.0112626
841666055986021, 841666126802863, 131951237037464231, +00.0289690, -00.0180111
841668527366928, 841668567571441, 131951237047779635, +00.0161019, -00.0112638
841670974911120, 841671031370323, 131951237057995902, +00.0230598, -00.0102810
841673430918664, 841673478969345, 131951237068247828, +00.0195688, -00.0075669
841675878950875, 841675928637067, 131951237078466778, +00.0203350, -00.0106560
841678325985624, 841678375364284, 131951237088681846, +00.0201183, -00.0038432
841680774439669, 841683170269664, 131951237098903116, error: 0x800705B4
841685581562335, 841685618054431, 131951237118971565, +00.0145917, -00.0055881
841688020419319, 841688058830667, 131951237129153475, +00.0157622, -00.0041708
841690456582891, 841690506242628, 131951237139324350, +00.0202194, -00.0036756
841692907447215, 841692939114512, 131951237149556793, +00.0129717, -00.0051447
841695338102089, 841695385615951, 131951237159705046, +00.0188068, -00.0055794
841697785665240, 841697823165345, 131951237169924061, +00.0152438, -00.0047920
841700222365627, 841700312934696, 131951237180097884, +00.0371839, -00.0135769
841702715548128, 841702790702293, 131951237190507688, +00.0307080, -00.0113813
841705191681325, 841705239079236, 131951237200846449, +00.0192771, -00.0054126
841707643212805, 841707682286095, 131951237211082625, +00.0155629, -00.0034271
841710083675611, 841712478847356, 131951237221272705, error: 0x800705B4
841714879004815, 841714915882596, 131951237241295792, +00.0148239, -00.0041683
841717319983027, 841717357601325, 131951237251488345, +00.0152409, -00.0035669
841719761110771, 841719807860551, 131951237261681616, +00.0190071, -00.0027670
841722210958801, 841722250809613, 131951237271911390, +00.0160577, -00.0040942
841724650900579, 841724692838736, 131951237282099881, +00.0170152, -00.0016022
841727094236737, 841727133631056, 131951237292302625, +00.0158463, -00.0031501
841729535286192, 841729578832711, 131951237302495892, +00.0175657, -00.0016211
841731981495055, 841732027548871, 131951237312710773, +00.0185971, +00.0004247
841734429794179, 841734486468151, 131951237322934446, +00.0230498, -00.0038949
841736887470216, 841736927916348, 131951237333197337, +00.0163094, -00.0028027
841739328797020, 841739373451828, 131951237343392010, +00.0183752, -00.0008282
841741771794373, 841741809680916, 131951237353593714, +00.0152265, -00.0012439
841744212134227, 841744264234764, 131951237363784368, +00.0209948, +00.0017612
841746665466283, 841749060838920, 131951237374029324, error: 0x800705B4
841751462670391, 841751499896616, 131951237394062257, +00.0148462, -00.0008268
```

What is worrisome is why it drifted up to a second overnight. I will test again tonight.

**Comment by f0ff886f** [comment]
An hour and a half later, it drifts:

```
w32tm /stripchart /computer:ntp0.as34288.net /rdtsc /period:1 /samples:300
Tracking ntp0.as34288.net [81.94.123.16:123].
Collecting 300 samples.
The current time is 20-Feb-19 10:39:32.
RdtscStart, RdtscEnd, FileTime, RoundtripDelay, NtpOffset
854761480225078, 854761514801788, 131951291725919686, +00.0140848, +00.0641892
854763913660287, 854763951055879, 131951291736081820, +00.0151353, +00.0652117
854766352788711, 854766387035708, 131951291746267727, +00.0140120, +00.0653491
854768786758511, 854768831210335, 131951291756432096, +00.0180989, +00.0669025
854771232099972, 854771273396700, 131951291766643951, +00.0166290, +00.0637399
854773673580323, 854773710613271, 131951291776839676, +00.0150167, +00.0651324
854776109606304, 854776143700296, 131951291787012630, +00.0136671, +00.0646691
854778545697253, 854778835385563, 131951291797185852, +00.1206497, +00.0117994
854781237447180, 854781313889976, 131951291808426719, +00.0312986, +00.0563942
854783716110859, 854783749512924, 131951291818777728, +00.0133548, +00.0645347
854786149803385, 854786183691082, 131951291828940935, +00.0138050, +00.0650342
854788582810429, 854788618283736, 131951291839101280, +00.0142108, +00.0653106
854791020983863, 854791057284751, 131951291849283200, +00.0145265, +00.0651931
854793461587291, 854793515905776, 131951291859475268, +00.0219779, +00.0660359
```

**Comment by janhanekom** [comment]
A few things:
* The #1 requirement listed in this set of documentation is a stable and reliable time source.  Your time source times out on a regular basis in the stripcharts you've supplied and this is also indicated in the "reachability" value of "6" in your "/query /peers /verbose" output - "reachability" should stabilise on 255 after a while if you have a reliable time source.
* The guidance in this set of documentation explicitly state that you should use symmetric active mode, yet you forced your time sync type to 0x9, which combines special poll interval (0x1) with *client* mode (0x8) - which is also reflected in your output of "w32tm /query /peers".  Leaving NTP to figure the correct mode out for itself (0x1) or explicitly configuring symmetric active mode (0x5) should help.
* Configuring multiple time sources will help NTP distill a more stable time from them.  Having a single reliable NTP source is good - having multiple reliable NTP sources is better.
* You were asked for information about your platform, but provided none.  If you are synchronising a VM on a Hyper-V host to an external source, and the Hyper-V host is synchronising its clock to the VM, you will very likely see drift simply because the VMIC time provided by default serves as an input into the clock of the VM.  This can be disabled, and is documented elsewhere.

I agree with you that the NTP documentation for Windows is contradictory at worst and unclear at best, but these pages have been the most authoritative and sensible source on NTP configuration in Windows I've seen in a long time.  They've worked well for me.

**Comment by f0ff886f** [comment]
Thanks for the info, and apologies, I am not the OP so didn't properly parse all the questions in your the first Msft response. My omission of host details was not malice, it was an oversight. The host is Win 10 Pro 1809.

The information you provided will give me a lot of pointers on how to narrow in on the desired behaviour. Knowing what reachability should stabilise on gives one point of guidance. The #1 requirement on this documentation (you're referring to https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/accurate-time, not the page that this issue was opened against) doesn't actually say anything about what reachability should stabilise on. How should we know that 6 is bad and 255 is good?

I didn't explicitly set time sync type to `0x9`, but knowing it shouldn't be `0x9` is again, useful information. However, I didn't force it. Where does that leave me?

I thought this is something I failed at, so I wanted to go back and really figure out where I missed the information you stated so clearly.

I went searching in the documentation for symmetric, symmetrical: no results. OK, so I went to the page that is called `Accurate Time for Windows Server 2016`, I actually omitted that page since I'm not on Windows Server 2016. Turns out that isn't just for Windows 2016, its for `Applies to: Windows Server 2016, Windows Server 2012 R2, Windows Server 2012, Windows 10 or later`. That would have been nice to know.

Now I found something about symmetrical:

> Symmetrical NTP communication - It is critical that the connection for NTP communication is symmetrical. NTP uses calculations to adjust the time that assume the network patch is symmetrical. If the path the NTP packet takes going to the server takes a different amount of time to return, the accuracy is affected. For example, the path could change due to changes in network topology, or packets being routed through devices that have different interface speeds.

That's not what you were talking about I presume, since that's more related to actual network topology than a regkey setting? Or is it? How can I know, it doesn't describe the setting you referred to anywhere.

I found it! https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings

And there it is! To be clear  though, the page states 0x4, not 0x5, for SymmetricActive. Unless we need 0x1 & 0x4 ? Who knows. There's a link there about what SymmetricActive is, takes me to: http://www.bytefusion.com/products/ntm/pts/3_3modesofoperation.htm

OK, so I'm still looking for the page that says I need SymmetricActive for high resolution time synchronization. I don't see it, but at the top of the page that describes the SymmetricActive info

>Prior to Windows Server 2016, the W32Time service was not designed to meet time-sensitive application needs. However, updates to Windows Server 2016 now allow you to implement a solution for 1ms accuracy in your domain. See Windows 2016 Accurate Time and Support boundary to configure the Windows Time service for high-accuracy environments for more information. 

On https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings, which is telling me about Server 2016 again.

Maybe I should read the entire page titled "How the Windows Time Service Works", https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/how-the-windows-time-service-works... nope, no symmetric there. But it does point me back to the page that was reported in this issue (and its the page that most people would imagine tells them how to configure the time service):

>This topic explains only how the Windows Time service (W32Time) works. For information about how to configure Windows Time service, see Configuring Systems for High Accuracy.

https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/configuring-systems-for-high-accuracy?tabs=MinPollInterval

And we're back :)

So, from the two pieces of information you provided, how can we users find that information? I really tried, and from your response that information is already giving two smoking guns.

That's why this issue was opened in the beginning I presume. Based on the article it seems hard to configure the time service to behave as desired. Based on your further response, it seems like I can't find that information on any article. This is an issue of documentation, and since documentation isn't immutable for all of eternity, there is a hope that it can be improved.

**Comment by janhanekom** [comment]
I'm a peer.  I am not a Microsoft employee, nor am I professionally associated with Microsoft in any way.

The documentation you have referenced (and where you left your comment) relates to Windows Server.  Although some of the pages make mention of Windows 10, I'm not sure how authoritative the pages are for client operating systems.  YMMV.

Understanding NTP behaviour comes as much from understanding the protocol (which Microsoft understandably does not re-document in its own documentation) as it does form understanding Microsoft's implementation (which until now has been sparsely documented at best.) I do have the benefit of having struggled with implementations on other platforms, which has helped understanding/troubleshooting Windows NTP. "Reachability" is a "left-shifted bitmap" for lack of a better term where connection attempts are appended to the right of the bitmap in sequence.  See here: https://www.linuxjournal.com/article/6812

Your time sync was explicitly configured by someone (or something) for 0x9, per the output of w32tm /query /configuration /verbose:
     NtpServer: ntp0.as34288.net,0x9 (Local)

The 0x1, 0x2, 0x4, 0x8 values for NTP server type are flags, not values.  Hence 0x1 means "use special poll interval" and 0x5 (0x1 + 0x4) means "use special poll interval and symmetric active mode."  The implied guidance in the documentation appears to be to use 0x1 unless you have a specific reason not not.  It is implied (not stated though) that 0x0 or 0x4 means that special poll interval will not be used, resulting in a standalone client Windows polling once a day or possibly once a week (depending on version) to make sure it's still on track, attempting to keep the clock "honest" by using skew statistics between connections.

Perhaps as a starting point, when selecting NTP servers, choose one or two good local sources and add some from pool.ntp.org: https://www.ntppool.org/en/use.html

**Comment by dcuomo** [comment]
I agree with @janhanekom who stated that a key requirement is a stable and accurate time source.  I would add that this excludes internet time sources because A) internet latency is high B) internet latency is not symmetric C) you have no idea what quality clock is behind the time source particularly for pooled servers.

Further, you should not believe when a client (linux, windows, etc.) tells you its own accuracy.  It is estimating based on the same characteristics that makes its time incorrect.  You need a tertiary system with symmetric network latency to validate its accuracy.  Yes, some might be more accurate than others, but if the goal is truly accuracy and not who has the best tools, then you'll need to perform a proper test.

Lastly, the high accuracy settings mentioned in the thread are what we recommend for "high accuracy support" e.g. 1ms of accuracy given the supportability requirements.  While tweaking other settings may incur an accuracy benefit, this is not what's required nor recommended to hit the high accuracy targets we've established in our supportability documentation.

**Comment by f0ff886f** [comment]
Thank you for the further explanation. My test was to setup two machines and a queue of 1024 timestamps in the future in a custom app with an associated full frame colour to present at each time stamp, then record both with a high framerate camera and compare the delta between the flip on each display. I'm aware of the extra factors that come in (eg. missing vsync for example would cost me 16ms, but was easy to spot and measure). I realize this is probably not the same domain of accuracy as you would measure with the proper tooling.

For my accuracy requirements I was able to achieve satisfactory accuracy with third party tooling, unfortunately I wasn't able to arrive at a consistent clock state using the guide. But in any case I was able to measure synchronized flips between two independent machines over 12 hours, which was more than enough for me and lead to quite nice results for my experiment.

**Comment by ValZapod** [comment]
WTF guys! I have 0x9 as well! And +00.8578214 drift! It is you problem!!! Realese an update witch will force new ntp codebase!!!

> The default value on stand-alone clients and servers is time.windows.com,0x1.

This is bullshit! It is 0x9! 

So, you need HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Parameters\NtpServer time.google.com,0x5 time.cloudflare.com,0x1 at least 2 more (in your country and in your local IX or University) https://gist.github.com/mutin-sa/eea1c396b1e610a2da1e5550d94b0453 

Now do this from all tabs
https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/configuring-systems-for-high-accuracy?tabs=MaxPollInterval#registry-settings
```
C:\WINDOWS\system32>w32tm /stripchart /computer:0.ru.pool.ntp.org /rdtsc /period:1 /samples:300
Отслеживание 0.ru.pool.ntp.org [79.120.30.43:123].
Сбор образцов 300.
Текущее время - 22.10.2019 5:45:16.
Начало RDTSC, окончание RDTSC, время файлов, задержка обмена пакетами (в обе стороны), смещение NTP
70507675541556, 70507790821942, 132161859165050044, +00.0337243, -00.0042825
70511195833806, 70511325267157, 132161859175403839, +00.0378282, -00.0021433
70514732171424, 70514851657426, 132161859185804827, +00.0348759, -00.0039778
70518258709528, 70518377897901, 132161859196176994, +00.0348319, -00.0043512
70521785999574, 70521910078672, 132161859206551371, +00.0362681, -00.0030645
70525317837785, 70525459484757, 132161859216939125, +00.0414450, -00.0005094
70528866299990, 70528982810812, 132161859227375773, +00.0340687, -00.0039357
70532390046777, 70532516142212, 132161859237739730, +00.0368061, -00.0032846
70535922139384, 70536044336147, 132161859248128245, +00.0357325, -00.0033697
70539451314558, 70539578565611, 132161859258508166, +00.0371840, -00.0041989
70542984818015, 70543104677286, 132161859268900819, +00.0350235, -00.0044193
70546508451444, 70546625261807, 132161859279264440, +00.0341198, -00.0041862
70550029328249, 70550178993464, 132161859289619955, +00.0437705, -00.0006417
70553583494645, 70553705602507, 132161859300073381, +00.0356813, -00.0032249
70557112074234, 70557242335846, 132161859310451551, +00.0380993, -00.0026843
70560646152974, 70560773994825, 132161859320845895, +00.0372607, -00.0037040
70564177426337, 70564306062265, 132161859331231988, +00.0376073, -00.0024935
70567711342880, 70567849311408, 132161859341625855, +00.0403712, -00.0012727
70571256724157, 70571388526531, 132161859352053442, +00.0385272, -00.0047236
70574794036837, 70574933216452, 132161859362457298, +00.0407205, -00.0021255
70578336603329, 70578460182935, 132161859372876606, +00.0360598, -00.0037168
70581865854202, 70581986350374, 132161859383256751, +00.0351195, -00.0044359
70585393526386, 70585526674746, 132161859393632252, +00.0389292, -00.0018506
70588930329825, 70589102595258, 132161859404033269, +00.0502806, +00.0040798
70592507277187, 70592680643190, 132161859414551292, +00.0507569, +00.0045074
70596088769632, 70596282261725, 132161859425082838, +00.0566818, -00.0149726

```

Any comments?

**Comment by dcuomo** [comment]
@valzapod - the language is not necessary nor appreciated, particularly since it is directed at a community member (not a MSFT employee).

Furthermore, @janhanekom already provided feedback that you must have a stable and reliable time source.  *.pool.ntp.org (or any internet time source) does not qualify. If there is a problem with the documentation, please suggest or submit a PR.

Finally, the stripchart you showed indicates that your worst sample was 14ms from the time source rather than the 857ms you reported (-00.0149726). It's unclear what you're asking.

@adragoset - If your question was sufficiently answered, please close this issue.  Otherwise, please let us know what else we can do to assist.  Keep in mind, GitHub is not an ideal place for support on technical issues, but rather the content of the documentation your referencing.

**Comment by adragoset** [comment]
I just used the program I linked too which worked with a few seconds of
configuration and is accurate to < 1ms jitter between my two servers that
are 1 stratum away from the time source. Overall it was a bad experience
getting Microsofts built in ntp to work and I never convincingly got it to
work. Was no longer worth the amount of time I burned on debugging the
feature.

**Comment by ValZapod** [comment]
@dcuomo It was +00.8578214 BEFORE. And I think that in this case my "language" is necessary. It is just unacceptable.

**Comment by ValZapod** [comment]
> you must have a stable and reliable time source. 

This is total bullshit! NTP was created for time sync in non stable and non reliable environment. I edited wikipedia here (added links in external links) https://en.wikipedia.org/wiki/Network_Time_Protocol and hope those people will tell you everything they think about you. I hope that will made you to release update which will change that 0x9 flag, which now obviouly can be on millions devices all over the world.

**Comment by ValZapod** [comment]
Yeah, now it looks like this, perfect. You can write good software after.
```
PS C:\Users\ZAQU> w32tm /stripchart /computer:1.ru.pool.ntp.org /rdtsc /period:1 /samples:300
Отслеживание 1.ru.pool.ntp.org [192.36.143.130:123].
Сбор образцов 300.
Текущее время - 22.10.2019 6:41:49.
Начало RDTSC, окончание RDTSC, время файлов, задержка обмена пакетами (в обе стороны), смещение NTP
82044462853744, 82044551326147, 132161893096349961, +00.0258433, +00.0000813
82047957450943, 82048053957436, 132161893106628113, +00.0281573, -00.0004334
82051458394368, 82051551553203, 132161893116924931, +00.0271804, +00.0003784
82054955877595, 82055051040544, 132161893127211572, +00.0277211, +00.0009962
82058458887921, 82058556612720, 132161893137514466, +00.0285541, +00.0003277
82061961858680, 82062049657682, 132161893147817246, +00.0256072, -00.0000487
82065456420558, 82065569322816, 132161893158095294, +00.0329486, +00.0005059
82068974388186, 82069068111532, 132161893168442182, +00.0273113, -00.0003733
82072472048814, 82072565308335, 132161893178729345, +00.0271250, -00.0006148
82075969777252, 82076060866652, 132161893189016705, +00.0265795, +00.0005978
82079463794675, 82079556552838, 132161893199293152, +00.0270780, -00.0006247
82082961930629, 82083051769616, 132161893209581712, +00.0261530, +00.0004018
82090059371942, 82090200261726, 132161893230456386, +00.0412193, +00.0064947
82093604038864, 82093698335212, 132161893240881801, +00.0275259, +00.0007558
82097101531554, 82097196218385, 132161893251168469, +00.0276272, -00.0007351
82100599094724, 82100697623426, 132161893261455344, +00.0284412, +00.0002290
82104115281099, 82104209504767, 132161893271796993, +00.0275058, +00.0007097
82107612758437, 82107708348450, 132161893282083616, +00.0278767, -00.0011142
82111113719669, 82111219893360, 132161893292380485, +00.0309633, +00.0025978
82114624810539, 82114717296864, 132161893302707148, +00.0269500, -00.0007491
```

**Comment by ValZapod** [comment]
Do you understand you can go to https://time.is and see the time drift in ±0,021? Accurate, BTW. Really when in Android one can sync time with GPS sattelites, you still only have mobile NITZ(( That is just wow. Just yesterday I argued with one guy that in modern Intel proccesors they already have clocks with picosecond precision. And you still have +0.8 second mistake with NTP!

About docs. I suppose we should add in bold red that on many PCs there is still 0x9 flag((

**Comment by ValZapod** [comment]
So what? Was there a fix for it?

**Comment by ValZapod** [comment]
So what? Was there a fix for it?
@dcuomo If you did not understand it is a console output after!
A conspiracy theory: you do not activate 0x1 flag, because in that case ntp servers will get crazy amount of trafic, your server time.microsoft.com inluding! Just saying! Disgusting!

**Comment by ValZapod** [comment]
I just found another bug. Apparently in some feature updates of windows "W32Time" service can switch from Automatic to Manual, that can lead to 0x1 flag also breaking. Very bad.

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

For questions or requests to the Microsoft developers, please consider using [**Feedback Hub**](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) to reach a more suitable audience.

**Comment by illfated** [comment]
For conclusion purposes:
- Is there anyone following this issue ticket who still see a need to change the documentation, and in case of yes, have you got a suggestion for what the changed content should look like?
- Is this issue discussed enough to reach a satisfactory conclusion?

Unless suggestions for actual change and content improvement appears, we should aim to close this issue ticket.

**Comment by illfated** [comment]
#please-close

**Comment by ValZapod** [comment]
Horrible, started happening again, **has to once again change to automatic W32Time and wait a minute or two even**! https://time.is/ agrees there is 0.5 seconds issue. 

```
PS C:\Users\ZAQU> w32tm /stripchart /computer:ntp.msk-ix.ru /rdtsc /period:1 /samples:300
Отслеживание ntp.msk-ix.ru [[2001:6d0:ffd4::1]:123].
Сбор образцов 300.
Текущее время - 23.09.2022 1:41:34.
Начало RDTSC, окончание RDTSC, время файлов, задержка обмена пакетами (в обе стороны), смещение NTP
412591938945901, 412591963223479, 133083600943012045, +00.0070035, -00.4455806
412595399000260, 412595422634723, 133083600953188682, +00.0067589, -00.4459181
412598855140377, 412598880960367, 133083600963353807, +00.0073626, -00.4455052
412602316951104, 412602344829001, 133083600973535610, +00.0080159, -00.4457121
412605774514266, 412605799655059, 133083600983704920, +00.0070886, -00.4451988
412609206388707, 412609235599942, 133083600993798675, +00.0083563, -00.4447179
412612679694434, 412612708748758, 133083601004014287, +00.0083592, -00.4454857
412616150352572, 412616177097863, 133083601014222112, +00.0076891, -00.4454650
412619600255936, 412619631689474, 133083601024368894, +00.0090468, -00.4448360
412623037704528, 412623067071513, 133083601034479043, +00.0084055, -00.4450741
```


Please change the default. Meanwhile you are still using NTP, which cannot be Stratum 0, while Android uses GNSS or LTE network which is stratum 0. Samsung updates it not that often unofortunately.
