### ISSUE TITLE
Tweek/fix to probe WAP + ADFS backend from Traffic Manager

### ISSUE THREAD

**Issue by skrubbeltrang** [MicrosoftDocs/windowsserverdocs#2091]
Hi Team

Was struggling a bit with this topic (on Windows Server 2012 R2): Your suggested solution on high availability for ADFS using Traffic Manager only probes the WAP server so Traffic Manager won't detect if backend ADFS service is down - end result is not very highly available since users are still redirected to a working WAP with a broken ADFS backend.
I solved this by configuring the probe in Traffic Manager to use HTTPS on port 81 and then configuring a rule for each WAP/Backend ADFS string on the WAP servers:
https://wap-probe1.mydomain.com:81/adfs/probe/ is proxied to http://adfs1.mydomain.com/adfs/probe/
https://wap-probe2.mydomain.com:81/adfs/probe/ is proxied to http://adfs2.mydomain.com/adfs/probe/
etc... for each string of WAP/ADFS servers.

By using port 81 on the WAP server you avoid conflicting with ADFS (443) and ADFS probe (80), and thereby Traffic Manager will detect whenever the WAP is not proxying OR the ADFS backend service is not responding.

You need of course relevant DNS records and hosts file entries to support this.

Please update the documentation, I think a lot of people would find it useful.

Kind regards,
Morten Skrubbeltrang

Edit: I've explained the tweak a bit futher here: https://www.easy365manager.com/high-availability-adfs-using-azure-traffic-manager-for-real-aws-route-53/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1af7d15-2153-5e39-0e03-17c44066472b
* Version Independent ID: a52da4ab-a8e9-60c3-e67b-bc0b36666c97
* Content: [High availability cross-geographic AD FS deployment in Azure with Azure Traffic Manager](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/active-directory-adfs-in-azure-with-azure-traffic-manager)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/active-directory-adfs-in-azure-with-azure-traffic-manager.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/active-directory-adfs-in-azure-with-azure-traffic-manager.md)
* Service: **active-directory**
* GitHub Login: @anandyadavMSFT
* Microsoft Alias: **anandy;billmath**

**Comment by cletuschukwu** [comment]
Hey @skrubbeltrang, what certificate did you use to publish the probe external url? Did you have to add the fqdn of your wap servers as SAN on the ADFS SSL certificate?

**Comment by skrubbeltrang** [comment]
Hey there

I simply used a * certificate on both WAP and internal publishing.

Med venlig hilsen/Kind regards,
============================
Morten Skrubbeltrang
Application and server insourcing
DSV IT Standardization Programme ITSP

phone: (+45) 5010 4200
mail: morten@skrubbeltrang.com

**Comment by tasdevil67** [comment]
I really tried to get this back end ADFS monitoring to work.  I apparently need help.  If someone could expand a little bit, that would be appreciated.  I am probably going to deep into some of this stuff and probably don't need to do some of the stuff that I did...but I have tried so many things to this point but I have not had any success as of yet.

I have a client internal ADFS configuration with WAP1 --> ADFS1 --> AD Server1 and I have one setup in Azure with WAP2 --> ADFS2 --> AD Server2 with VPN back to AD Server1.

I am running Windows 2012 R2 at all locations...so I can only publish https urls.

Above you said you configured "the probe in Traffic Manager to use HTTPS on port 81".  
On the WAP1 server did you add another HTTPS binding for port 81 to the existing HTTPS 443 binding and bind your wild card cert to it?

Next you created these rules:

https://wap-probe1.mydomain.com:81/adfs/probe/ is proxied to http://adfs1.mydomain.com/adfs/probe/
https://wap-probe2.mydomain.com:81/adfs/probe/ is proxied to http://adfs2.mydomain.com/adfs/probe/

When you stated that you created these rules....I assume you mean that you published rules in Remote Access Management console.

You have https://wap-probe1.mydomain.com:81/adfs/probe/ going to http://adfs1.mydomain.com/adfs/probe.

Did you have to install URL rewrite and create rules for that or does the WAP just do the request? I tried with out but it didn't work.

When I do the above, I get an error in W2K12R2. Specifically....

The internal and external URLs don't match.  This might cause access problems.  Show More.  I click Show more  and it sends me here:  https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn383995(v=ws.11)

Generally, the external and backend server URLs are different and URL translation is disabled.    So I ran the following command:
Set-WebApplicationProxyApplication –ID <application_ID> -DisableTranslateUrlInRequestHeaders:$false

This still didn't work.

You have specifically used https://wap-probe1.mydomain.com:81/adfs/probe/ as the External URL.  Did you have to add the wap-probe1.mydomain.com to the configuration of the traffic manager in the Customer Header Settings to get this to work?  If you did, since I have WAP1 and WAP2, not sure how to add two to work on both.  

The backend you stated was http://adfs1.mydomain.com/adfs/probe/ so I went onto my WAP server and modified the hosts file and added adfs1.mydomain.com to point to the ADFS backend server IP Address.  

Lastly,  my traffic manager configuration......

Protocol: HTTPS
Port 81
Path /adfs/probe/
Customer Header Settings: I left it blank.
Expected Status Code ranges...left default (200)

Unfortunatlely....none of this worked.  

Any advice?

**Comment by skrubbeltrang** [comment]
Hey, sorry to hear it's causing you trouble. The setup is quite simple and no secret tricks, scripts or URL rewrites are needed. 

Did you look at the link referenced?

https://www.easy365manager.com/high-availability-adfs-using-azure-traffic-manager-for-real-aws-route-53/

In this article I give screenshots of the (only) WAP configuration you need to succeed. I'm assuming that your ADFS proxying is functional, including a healthy hosts file/name resolution on WAP. Also, verify that port 81 is active on WAP (do a netstat -nao) and check that port 81 is accepted on WAP from outside (Test-NetConnection). Make sure you're truly testing from outside as internal communication may be routed unexpectedly.

Check the article and let me know if it helps. Fingers crossed 😊👍

Kind regards Morten

**Comment by tasdevil67** [comment]
Morten, 

Thanks for getting back to me so quickly.  For the most part, I think I figured it out.  I still show both webproxy servers in each location to be in a degraded state when looking at Traffic Manager in Azure.  

The company I'm working for didn't have proxy servers nor a redundant site so I had to add all of that.  I have not cutover to this new configuration as of yet.  Currently the url address I'm using is pointing to the company's local ADFS backend server.  I will eventually move this to a CNAME record pointing to traffic manager name.  I hope this is why the state is showing degraded but I won't know until I migrate.

I created the publishing rule on one of the Web Proxy servers to be as follows:

https://sts.companya.com:81/adfs/probe --> http://adfsprobe.companya.com/

On each webproxy server, I edited the hosts file and added an entry for adfsprobe.companya.com and pointed to the local sites ADFS server internal IP address.

I didn't create two rules though.  Should I have?  

When I created the one rule...it showed up on the other side and through hosts file manipulation using a generic PC on the Internet , I can connect to each site's Webproxy server using https://sts.company.com:81/adfs/probe and a blank screen is displayed, which I assume is returning a code of 200.

I assume that once I migrate this company over and change the sts.companya.com name to point to the traffic manager address, that the status of each side will change to online from degraded. 

The only perplexing thing is why you show 2 entries in your publishing rules: 1 for each location and I only show 1 rule.

Thanks for getting back to me and pointing me to your article.

Todd.

**Comment by skrubbeltrang** [comment]
Hi Todd 

No problem 😊 I think you're almost there. 

Each wap must have unique external host name. 
Traffic manager rule one maps external adfs name to wap1 external host name. Rule two maps to wap2 external host name. 
On wap you have two rules: Wap1 external host name to internal adfs name (mapped to adfs1 via hosts file on wap1). And Wap2 external host name to internal adfs name (mapped to adfs2 via hosts file on wap2). In both wap rules ensure that both wap and adfs have adfs/probe in their name (revisit screenshot in my article).
Traffic Manager should show both probes as healthy with proper proxy rules set up on wap. Both wap rules are set up on primary wap (but replicated to secondary via adfs communication and ad replication). 

Give it a go! 😊👍

**Comment by tasdevil67** [comment]
If this is the case, how would the traffic manager monitoring piece know how to call each waps unique name to check on its status?  

This is why I asked if a custom header settings is set on  each endpoint.

 

Would you have to go into each endpoint and specify the target IP address, priority and custom header settings?

**Comment by skrubbeltrang** [comment]
Hi Todd, each endpoint is defined by IP or FQDN so Traffic Manager will know which one is down and only return name of healthy instance as reply to the DNS lookup from the client. If this is what you're asking?

Kind regards, Morten

**Comment by tasdevil67** [comment]
Hi Morten,

I got it!  Thanks for the help.  My problem was that I defined each endpoint as an IP address not FQDN.  It would not work until I put the FQDN in the host headers field.  To verify, when I had it in, the status showed online and when I took it out it showed degraded.  

So overall.....based on all of the assistance that you gave me (much appreciated)....

We have an onsite proxy and onsite ADFS server and an azure proxy and an azure ADFS server.

1. On both proxy servers, I created a new binding in IIS to use port 81 using the HTTPS protocol and as you said, I used the wildcard certificate.

2. On the onsite proxy server, I modified the local hosts file in c:/windows/systems32/drivers/etc and added an entry to point to the onsite adfs backend server using the name backendprobe1.companya.com

3. On the azure proxy server, I modified the local hosts file and added an entry 
 for backendprobe2.company.com.

4. I added two public DNS entries for each proxy server public address:
     adfsprobe1.companya.com points to public address of the onsite proxy server.
     adfsprobe2.companya.com points to public address of the azure proxy server.

5. In traffic manager, I defined two endpoints using the public IP addresses and NOT the FQDN.  If I had used the FQDN instead of the IP address, I probably would have not required an entry in the  host header field of each endpoint.  However, since I used the IP address, I added host:adfsprobe1.companya.com to the host header field of the onsite end point and host:adfsprobe2.companya.com to the host header field of the azure end point. 

6. I then changed the configuration of traffic manager to use /adfs/probe/ as the path using HTTPS protocol on port 81. 

7.  Finally as you had stated, after opening all of the ports in the firewalls, I published two rules for each end point:

external URL: https://adfsprobe1.companya.com:81/adfs/probe/
Internal URL : http://backedprobe1.companya.com/adfs/probe/

and

external URL: https://adfsprobe2.companya.com:81/adfs/probe/
Internal URL : http://backedprobe2.companya.com/adfs/probe/

That worked!

Again Morten, thanks for all your guidance.

**Comment by skrubbeltrang** [comment]
Todd - that's awesome, glad to hear you got it working! Thx for posting the clarifying details, it will probably be useful to others. 

Kind regards, 
Morten Skrubbeltrang

**Comment by fallmake** [comment]
To add...the solution by @skrubbeltrang is good and works for the most part, but also isn't "entirely perfect" as the /adfs/probe endpoint on the WAP is handled by the adfssrv service, but published proxy applications and forwarding is handled by appproxysvc. This means that it is possible that the AD FS and WAP are in working condition in regards to AD FS/authentication if adfssrv is up and OK on the WAP and the AD FS backend server, but the probe on port 81 in the above example is not forwarded to the backend by the WAP if appproxysvc is down, resulting in an actually working AD FS being "degraded" in traffic manager.

The only "real" monitoring would be 2 separate health probes, one to the WAP and one to AD FS on port 80, each reaching reflecting the state of adfssrv on WAP and ADFS backend, perhaps proxying it through another proxy solution than WAP for this purpose (as to not having to expose the ADFS server's TCP port 80 on the internet). For practical purposes though, the solution proposed in this item is good and achievable.

**Comment by Eric-ITaaS** [comment]
What is the lasts on this, I'm running all 2019 and this issue is still there. I tried the work around external url on port 81 proxy back to the internal URL but it doesn't work. For whatever reason WAP won't proxy this request.

**Comment by IngridAtMicrosoft** [comment]
#please-close
