### ISSUE TITLE
Impossible to install the French language on windows server 2019

### ISSUE THREAD

**Issue by MaDjiDoU0911** [MicrosoftDocs/windowsserverdocs#2166]
???
![capture](https://user-images.githubusercontent.com/45048419/50552318-fbc00480-0c90-11e9-8c7f-5bdaf7ef4d7d.PNG)

**Comment by illfated** [comment]
Please use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
Closing this ticket as this issue can not be handled here in this repository.

#please-close
