### ISSUE TITLE
Server with Desktop Note

### ISSUE THREAD

**Issue by sundarchi1** [MicrosoftDocs/windowsserverdocs#222]
Add a note explaining why "Server with Desktop" is not included in semi-annual.
It's unclear and makes no sense why it's excluded - please add a note to this documentation page explaining the technical reasons behind the decision:

https://github.com/microsoftdocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/semi-annual-channel-overview.md

**Comment by lizap** [comment]
Thank you for the comment.  Customer feedback plays a big role in how we design releases of Windows Server, so we always appreciate the input.  The Semi-Annual Channel releases are designed for customers who want to onboard new server innovation faster than what is provided by the Long Term Servicing Channel releases (such as Windows Server 2016).  Feedback from these customers told us that for the most part they manage their datacenters using command line scripting with PowerShell and don’t have a strong need for the GUI available in Server with Desktop Experience.  This feedback has allowed us to focus more resources on the new technologies rather than in shipping an updated GUI every six months (which does have an engineering cost).  We do, however, always remain open to feedback when we think about future releases, so please keep the comments coming! You can add comments here or through the Feedback Hub (https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app).

We will add this same information to the article that you link above, to ensure that anyone else who has similar questions knows where we're coming from. Thanks!

**Comment by sundarchi1** [comment]
Thanks for your transparency! I'm surprised there's an engineering cost considering all the work was done already for Windows 10.

Is the next LTSC release version 1903? Isn't quite clear from [the chart](https://raw.githubusercontent.com/MicrosoftDocs/windowsserverdocs/master/WindowsServerDocs/get-started/media/SAC-release-timing.png), but it looks like that may be it? Or will it be sooner? Version 1809 will be 2 years since the last LTSC.

**Comment by sundarchi1** [comment]
@lizap You all should really consider releasing GUI. Lots of complaints and confused comments here: https://blogs.technet.microsoft.com/windowsserver/2017/10/17/windows-server-version-1709-available-for-download/
