### ISSUE TITLE
Is this a joke?

### ISSUE THREAD

**Issue by vitaprimo** [MicrosoftDocs/windowsserverdocs#2278]
How can a piece of software priced in the thousands of USD come with no documentation, dragging a GUI from the '90s lacking so much common sense and practicality that half of the documentation actually regresses to TUIs, namely PowerShell. As customers we seek Windows Server for the GUI, however "limiting" it may be. Without it, Windows is just a data collecting, crash-prone, high-maintenance, low-performing, untrustworthy lump of binaries with a sky-high price tag. Add undocumented, to the insult. 

And, support besides from being also expensive, is useless. To this day I've had zero issues on contact with over a dozen different persons per incident number no matter how simple--I'm including my two current contracts over on Microsoft Azure on that.

Take a clue from Red Hat, documentation is extensive, very well explained with no ambiguity and on highly efficient and adaptable ePub, you only have PDF for downloads, even that in that department performance is an afterthought; then, you have RADIUS under Networking, RADIUS again and the buzzword you learned over the weekend "SDN" under Management, VPN under Remote but its components like NPS or RADIUS are somewhere else, more than two diferent places each and none where VPN actually is. AAA is all over the place and the extremely ambiguous terms "load balancing" "failover + clustering", "clustering/cluster" and "replica" under somewhere else. Nothing makes sense or have the slightest hint of organization. Search plugs in your search engine that scopes all of your domains in an even worse position.

This is inexcusable, Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9b3ce11-d5f1-e91e-12a6-1f4472883fcf
* Version Independent ID: b8cbc1e7-ad7d-912b-19f4-50eddbebc1ff
* Content: [Dynamic Host Configuration Protocol (DHCP)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/dhcp/dhcp-top)
* Content Source: [WindowsServerDocs/networking/technologies/dhcp/dhcp-top.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/dhcp/dhcp-top.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by RobertKet** [comment]
What are you looking for so far as documentation? TechNet has a massive selection of resources on almost every topic, and can get as deep as the sysinternals for some topics. The current pages you're looking at are resources that are specific to 2016 "whats new". This is product evaluation guidance, not operational or administrative documentation. You won't find much technical depth in these docs, and since you may be viewing directly at the GITHUB website, that may be causing a bit of the confusion.

Now about the GUI management aspects. Microsoft provides the GUI as an ease of management tool for small operations. Most of your day to day engineering should be done with PowerShell. Infrastructure isn't focused on GUI management and hasn't been for awhile. If you're looking for improved GUI management I'd check out some of the Azure PAAS/SAAS options that are available to you.

Microsoft also has blogs for almost every team that give info about news and guidance on how to use their tools. Take DHCP for example: https://blogs.technet.microsoft.com/teamdhcp/ .

Their WIKI is a great place to start for newer admins coming off of flat-file based platform configurations that you typically see in Linux: https://social.technet.microsoft.com/wiki/

There are tons of free demonstrations and labs available here: https://www.microsoft.com/handsonlabs/SelfPacedLabs

Community MVP and Microsoft supplied guidance, tools, scripts here: 
https://gallery.technet.microsoft.com/

The overall library architecture that works very similar to the page you're on: 
https://technet.microsoft.com/library/default.aspx

And ultimately if you want to ask questions they have a very helpful community forum:
https://social.technet.microsoft.com/forums/en-us/home

**Comment by daveba** [comment]
@vitaprimo Closing this issue.  Please reopen if you have a more specific question. Thanks!
