### ISSUE TITLE
Cluster Object script error

### ISSUE THREAD

**Issue by tsotoodeh** [MicrosoftDocs/windowsserverdocs#2347]
Hi,
I have tested the powershell script for creating cluster objects in Windows server 2019 and it returns an error while identifying the vcopath variable.
Script is unable to read the distinguished name path although the path is correct.
Due to this error the acl process is not possible.
Any idea how to fix this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9765219c-3a04-c0d9-178b-618020a8679b
* Version Independent ID: b19c6bf5-4f68-a913-7ff3-61f8f303c0f3
* Content: [Install HGS in an existing bastion forest](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-install-hgs-in-a-bastion-forest)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-install-hgs-in-a-bastion-forest.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-install-hgs-in-a-bastion-forest.md)
* Product: **windows-server-threshold**
* GitHub Login: @rpsqrd

**Comment by rpsqrd** [comment]
Hi @tsotoodeh,

So `$vco.DistinguishedName` is a valid path for you, but the `$vcoPath` variable doesn't resolve to anything? Let's check if the AD provider is working correctly first, since that is often the root cause.

Can you run the following?
```powershell
Import-Module ActiveDirectory
Get-PSProvider
```

There should be an entry in there that looks like this:
```
Name                 Capabilities                                      Drives
----                 ------------                                      ------
ActiveDirectory      Include, Exclude, Filter, ShouldProcess, Crede... {AD}
```

If you don't see "AD" in Drives, then there's an issue with the virtual AD drive.

If you do see AD, can you try changing your directory to the AD root and navigate through the directory until you find your VCO?

```powershell
cd AD:\
ls
```
