### ISSUE TITLE
Web application Proxy site has errors

### ISSUE THREAD

**Issue by mitiih** [MicrosoftDocs/windowsserverdocs#244]
https://docs.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/publishing-applications-with-sharepoint%2c-exchange-and-rdg

I think there are few errors on that site above.
It states that Exchange Activesync works only with pass-through but this site claims that it can be configured with ADFS & HTTP Basic. Referring to : https://docs.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/publishing-applications-using-ad-fs-preauthentication & [https://docs.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/web-application-proxy-windows-server](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/web-application-proxy-windows-server)

Also EAC should work like the OWA. Referring to link: https://technet.microsoft.com/en-us/library/dn635116(v=exchg.150).aspx

At RDG section there is a statement: "If the External and Internal FQDN's are different you should disable request header translation on the RDWeb publishing rule. "
---> Shouldn't this be the opposite? If the URLS are different, then it needs translation enabled which is by default.

**Comment by lizap** [comment]
Hey, @mitiih - It's been ages since you opened this, but I did want to circle back with a bit of information. RD doesn't actually support this scenario with Web App Proxy. RD DOES support using Azure app proxy, though, which is described accurately here: https://docs.microsoft.com/en-us/azure/active-directory/active-directory-application-proxy-get-started
