### ISSUE TITLE
The PowerShell command says "SMBTransport" but that generates an error

### ISSUE THREAD

**Issue by VernAnderson** [MicrosoftDocs/windowsserverdocs#2623]
I believe it should read "SMB" instead of "SMBTransport" in the article on the line that has the full command. . .

"PS C:\&gt; Set-VMHost -VirtualMachineMigrationPerformanceOption SMBTransport"

-VERN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d949a743-a719-645d-a5bf-d20e79f3ece8
* Version Independent ID: a17147e0-083b-5ff5-dfcf-d2358318416e
* Content: [Set up hosts for live migration without Failover Clustering](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/Set-up-hosts-for-live-migration-without-Failover-Clustering#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/Set-up-hosts-for-live-migration-without-Failover-Clustering.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/deploy/Set-up-hosts-for-live-migration-without-Failover-Clustering.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by Tajmaha** [comment]
I too experience this.
This is the error that is generated:
`"Microsoft.HyperV.PowerShell.VMMigrationPerformance". Error: "Unable to match the identifier name SMBTransport to a valid enumerator name. Specify one of the following enumerator names and try again: TCPIP, Compression, SMB"` 
Using "SMB" instead of "SMBTransport" does not generate any error, and correctly sets the Performance option to use SMB.
