### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by harperse** [MicrosoftDocs/windowsserverdocs#2863]
The anchor links near the top of the page "Configure the first federation server in a new federation server farm" and "Add a federation server to an existing federation server farm" point to an assetid:// location and not http/https location.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c43b70d0-b180-bc0e-6056-febede9cdfe4
* Version Independent ID: 3899f0dc-e7f9-fbd8-ee05-0b5705336137
* Content: [Windows Server 2012 R2 AD FS Deployment Guide](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/configure-a-federation-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Configure-a-Federation-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Configure-a-Federation-Server.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by fate0521** [comment]
Still broken 7 months later

**Comment by illfated** [comment]
Oh. I think I see what is wrong here. Those links are supposed to point to the matching sections further down on the page. Maybe the "assetid:///" link is a remnant from a much older internal linking system, but no longer in use, or maybe even only used locally in a prototype environment from back when the page was newly created. Oh well, I don't know the actual facts. I do understand what needs to be done, though. (This issue is mostly cosmetic, meaning that those 2 links could just as easily have been removed, using the links in the right hand side margin instead.)

**Comment by fate0521** [comment]
Thanks!

**Comment by illfated** [comment]
You are most welcome. I am mostly glad I managed to notice that the link text refers to 2 sections within the same page, the first link pointing to the section just 2-3 lines below (rather redundant, if you ask me).

**Comment by illfated** [comment]
OK, so I was asked to close my PR due to an internal update, but that update has not seen light of day as far as the end users are concerned, be it the GitHub page or the docs.microsoft.com page.

I intend to open a new pull request based on the closed one (I deleted the PR branch along with its contents) to ask for the resurrection of the links to happen.
