### ISSUE TITLE
How to reinstall

### ISSUE THREAD

**Issue by brucedkyle** [MicrosoftDocs/windowsserverdocs#2928]
I uninstalled OpenSSH Client. And now it is gone from the Manage optional features panel and is missing from the Add a feature panel. 
I tried adding the feature using the PowerShell script, but it is added in the history, but using SSH does not work.

Is there a work around to reinstall OpenSSH client

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07417484-bd6d-e6f4-110e-e42c2428a369
* Version Independent ID: 844743a6-f67b-421f-9591-13da36b23b14
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by brucedkyle** [comment]
Unfortunately, Add-WindowsCapability failed. Error code = 0x800f0954

**Comment by vchirikov** [comment]
Same issue, can't remove \ install.

**Comment by gukovsem** [comment]
Hi,
I had the same isuue Error code = 0x800f0954, this issue related to bug in local network WSUS server
Fixed by next steps:
1. Run regedit as Administrator
2. Go to HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
3. Change UseWUServer to 0
4. Run CMD as Administrator and execute two commands
net stop wuauserv
net start wuauserv

After that try Install the OpenSSH Server
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

After that change UseWUServer to 1

Done, hope it will help you.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
