### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by davwilson** [MicrosoftDocs/windowsserverdocs#3389]
The link to the firewall information is broken (https://go.microsoft.com/fwlink/?LinkId=37928).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54ff3abb-0884-900e-8d2e-ec2e537582ce
* Version Independent ID: 69377df3-80fd-3d7e-4a69-bc88e2c40737
* Content: [Finding Additional Resources for Windows Server 2008 Active Directory Site Topology Design](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/finding-additional-resources-for-windows-server-2008-active-directory-site-topology-design)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Finding-Additional-Resources-for-Windows-Server-2008-Active-Directory-Site-Topology-Design.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Finding-Additional-Resources-for-Windows-Server-2008-Active-Directory-Site-Topology-Design.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Yes. The download has been removed, because it uses Windows 2000 Server as the working scenario throughout the document. The document was published in 2002 and updated in 2004.

I have done a couple of superficial web searches, but there does not appear to be any new replacement documents for that topic. I am guessing that the practical move here will be to remove the paragraph (bullet list point & sentence) entirely to let any MS internals add a new one when there is replacement documentation available.

**Comment by illfated** [comment]
Even the WayBack Machine (web.archive.org) does not have any copy of the original content from that link:
- https://web.archive.org/web/*/https://microsoft.com/download/details.aspx?familyid=c2ef3846-43f0-4caf-9767-a9166368434e

Oh well. I am done with this. Opening a PR now to request the sentence (along with its link) removed.

**Comment by illfated** [comment]
There you go, PR #4985 is now ready for review. Feel free to view, comment and suggest further improvements to that page.
