### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by bubbletroubles** [MicrosoftDocs/windowsserverdocs#3447]
There is a grammar error on the page

"This group **would provides** incomplete protection anyway..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d6ee8ba-1584-3a15-b560-d0f880bbd8f1
* Version Independent ID: 4c549846-bb86-bc11-8768-269bf3a3fe60
* Content: [Protected Users Security Group](https://docs.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/protected-users-security-group)
* Content Source: [WindowsServerDocs/security/credentials-protection-and-management/protected-users-security-group.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/credentials-protection-and-management/protected-users-security-group.md)
* Product: **windows-server**
* Technology: **security-credential-protection**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Thank you for pointing out that typo or grammatical error. I wonder if this means that the sentence should be "This group provides incomplete protection anyway, because the password or certificate is always available on the host." (removed the "would" part) or if we should simply remove the third person singular S from **provides**.

Personally, I think it reads more proper to remove the word "would" improve the sentence with better coherency, but I am open to arguments for other solutions. Creating a PR to change this sentence should in theory generate feedback from the author and managers.
