### ISSUE TITLE
Table does not display all columns at 100% zoom

### ISSUE THREAD

**Issue by Roblarson** [MicrosoftDocs/windowsserverdocs#3450]
the table above only displays some of the columns, need to fix so it auto resizes instead of making the user scroll all the way to the bottom to realize that they can scroll right to see the remaining columns

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96467ddc-a592-f70e-2b1d-c9258984558b
* Version Independent ID: 5ace59d8-2a58-e013-0bd6-8cce315783e2
* Content: [Supported Remote Desktop RDP file settings](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/rdp-files)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/rdp-files.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/rdp-files.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @btaintor
* Microsoft Alias: **helohr**

**Comment by illfated** [comment]
An existing alternative is to view the Github page, because it does not include the menu index on the sides and shows the table in full width:
- https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/rdp-files.md

What creates the limitation in the first place is the top menu, dividing the page in 3: Left index, Center article, Right index (which is an empty placeholder in this case). I worry how long the table would become if it had been designed to fit 100% within the article width, but growing downwards as the columns got narrower.

**Comment by illfated** [comment]
The tables (yes, plural tables) were updated in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/4a33a6287001e55b69e9a3b67166299007092a0d (April 9, 2020), PR #4312 to be narrower and are now visible in 100% scale, at least on a screen resolution of 1920x1080 (full HD).

**Comment by illfated** [comment]
#please-close
