### ISSUE TITLE
Broken link to KB2549369 (and recipe to this particular broken link pattern)

### ISSUE THREAD

**Issue by HelderMagalhaes** [MicrosoftDocs/windowsserverdocs#3490]
Link to KB2549369 is currently:
https://support.microsoft.com/default.aspx?scid=kb;en-US;2549369
This is "ignored" and redirects to the welcome page.

It's suggested to use the following instead:
https://support.microsoft.com/help/2549369

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daa2f587-3079-f561-de2e-6663a6dcbab1
* Version Independent ID: f9946d5c-e1fe-316a-f12c-78a061f5a029
* Content: [Troubleshoot Cache and Memory Manager Performance Issues](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot#feedback)
* Content Source: [WindowsServerDocs/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot.md)
* Product: **windows-server**
* Technology: **performance-tuning-guide**
* GitHub Login: @phstee
* Microsoft Alias: **Pavel; ATales**

**Comment by HelderMagalhaes** [comment]
If possible, it was a lot more useful to rework this issue to a global scope and fix all occurrences at once:

1. Run a regular expression over the whole repository with:
`https://support.microsoft.com/default.aspx?scid=kb;en-US;(\d+)`

1. Replace with:
`https://support.microsoft.com/help/\1`

**Comment by nucleare** [comment]
This issue was closed but presently still exists as noted when attempting to click the link found under [System file cache contains memory mapped files](https://learn.microsoft.com/en-us/windows-server/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot#system-file-cache-contains-memory-mapped-files) in the 2nd paragraph stating "This issue is described in detail in KB article [2549369](https://support.microsoft.com/default.aspx?scid=kb;en-US;2549369)." 

Below is the updated Document Details when accessed 07/18/2023:

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe81add-b285-ff8e-f383-2df80332e722
* Version Independent ID: 4e96ec10-8088-0d77-bc8b-d2197aebf9d9
* Content: [Troubleshoot Cache and Memory Manager Performance Issues](https://learn.microsoft.com/en-us/windows-server/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot#feedback)
* Content Source: [WindowsServerDocs/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @phstee
* Microsoft Alias: **pavel**

**Comment by nucleare** [comment]
> This issue was closed but presently still exists as noted when attempting to click the link found under [System file cache contains memory mapped files](https://learn.microsoft.com/en-us/windows-server/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot#system-file-cache-contains-memory-mapped-files) in the 2nd paragraph stating "This issue is described in detail in KB article [2549369](https://support.microsoft.com/default.aspx?scid=kb;en-US;2549369)."
> 
> Below is the updated Document Details when accessed 07/18/2023:
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 6fe81add-b285-ff8e-f383-2df80332e722
> * Version Independent ID: 4e96ec10-8088-0d77-bc8b-d2197aebf9d9
> * Content: [Troubleshoot Cache and Memory Manager Performance Issues](https://learn.microsoft.com/en-us/windows-server/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot#feedback)
> * Content Source: [WindowsServerDocs/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot.md)
> * Product: **windows-server**
> * Technology: **administration**
> * GitHub Login: @phstee
> * Microsoft Alias: **pavel**

I've opened a merge request to fix the specific page originally mentioned in this reported issue as Update troubleshoot.md #7393
