### ISSUE TITLE
RDP session is Qwerty

### ISSUE THREAD

**Issue by ozdotnet** [MicrosoftDocs/windowsserverdocs#3527]
I'm doing an RDP session from my Android 9 smartphone to my Windows 10 PC.

My PC is AZERTY (be-nl).

My Android smartphone is also AZERTY. Keyboard is AZERTY but the system language is English, but I don't think this would influence it.

When in a RDP session, input turns into QWERTY. Is there a place where I can change this to AZERTY?

**Comment by illfated** [comment]
Please note that this repository primarily exists for improving the documentation pages in the https://docs.microsoft.com/windows-server/ directory.

Compared to the Windows IT Pro docs pages, the server docs pages seem to get less attention, unless any important documentation issues are reported, possibly with a suggestion for how to correct them.

You might be lucky enough to get a helpful answer from a fellow user who may have been in your situation, but there is no guarantee that your question will be answered here.

I recommend that you post your question in one of the Microsoft Answers, Social or Technet pages instead, because those pages are made for troubleshooting and support.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
