### ISSUE TITLE
Yes/No Table

### ISSUE THREAD

**Issue by CrCoTx** [MicrosoftDocs/windowsserverdocs#3580]
The Yes/No tables took me way too long to interpret what "Yes Yes", "Yes No", etc meant. Maybe reformat the table using vertical lines between the columns or simply add a slash "/" between the columns so that the headers read "Success / Failure" and then the column contents read out like "Yes / Yes", "Yes / No", etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6aec18-46fe-37f4-995f-a98a65678e1f
* Version Independent ID: 519ae984-bcff-ec57-f855-c926b09ccdf2
* Content: [Audit Policy Recommendations](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/audit-policy-recommendations)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Audit-Policy-Recommendations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Audit-Policy-Recommendations.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Fair point, I see what you mean. The docs.microsoft.com pages use a form of "open table" with only horizontal lines, in contrast to the Github source page (https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Audit-Policy-Recommendations.md).

I admit that I sometimes find it slightly difficult to see straight away which value belongs to which setting, unless my head is centered in front of my screen or I highlight the entire line with the mouse pointer. From my point of view, it would be quite practical to read the MarkDown table format instead, especially because those tables use full grid lines as well as a gray shade for every second line of the table, making it very easy for my eyes to follow the horizontal lines from left to right.

I can only assume that the HTML version of the tables is either a remnant of an older format / code style, based on the idea that technical documentation should be sleek, simplified, and not as rich in graphics as some of the modern web pages.

Anyway, the TL;DR of my comment is that this topic is more suited for a discussion of the HTML design of the Microsoft Docs pages. I don't know if this Github page is the correct place to have that discussion, but it could attract attention from someone who knows where to go to ask for such a design modification. Myself, I am unable to suggest any changes to the page content, because the source page only allows us to create Pull Requests to change images & text content within the page, not any CSS, scripts or HTML design.
