### ISSUE TITLE
Why would you suggest no help links?

### ISSUE THREAD

**Issue by jdw2465** [MicrosoftDocs/windowsserverdocs#3597]
If I'm building a simple smart phone app, in which the level of complexity is almost non-existent, there would be almost no need for help. That said, I've searched online for How To articles for a number of apps; but typically, that's when I'm trying things with the app that are probably edge-case. 

But when you're designing software that solves complex problems and there is much to know conceptually, as well as the need to be reminded or taught how to do something, why in the world would giving users a simple, unobtrusive path to more information be so terrible. I disagree with you premise. And I've lived this before where a UX team insisted that adding tiny (aka, unobtrusive) links for the user that truly needs more info clutters the screen. At some point, you must realize that putting form ahead of function because it's "cleaner" is doing a disservice to your users. I think it's bad advice. Better advice would be that you design as intuitively as possible but recognize that what's intuitive to one user is not intuitive to another user. So what's the harm in giving that second user a chance at success via an unobtrusive path to learn more. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5568c70c-6538-df9f-ad48-7b8d0a9024e4
* Version Independent ID: 0d9fb31d-7f06-7054-f9b1-cafcc5641347
* Content: [Windows Admin Center UI text and design style guide](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/guides/ui-text-style-guide#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/guides/ui-text-style-guide.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/guides/ui-text-style-guide.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Even though I am not as deep into programming or making design choices as you, I try my best at helping out on these Microsoft Docs pages, both for the Windows IT Pro Docs repository and the Windows Server Docs repository. Your wording seems to be more on the general side, so I don't know where to start, other than suggesting that your material might be more suitable for the Feedback Hub than in the Windows Server Docs repository.

That being said, if you do have any specific recommendations to what needs to be changed, and possibly what sort of documentation/text/links to add to this page, I would be happy to help adding a suggestion for such a change by creating a Pull Request to have the page amended.

I also hope someone from the Microsoft Docs team with experience and background closer to yours will offer suggestions as well.

**Comment by illfated** [comment]
@jdw2465 : Sorry for the late follow-up. I am here on my own spare time. I would recommend that you share your views with Microsoft's developers via the **Feedback Hub app**.

General information:

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
