### ISSUE TITLE
Looks like the  https://packages.microsoft.com/config/ubuntu/16.04/prod msodbcsql17 is faulty after a change yesterday

### ISSUE THREAD

**Issue by djburnham** [MicrosoftDocs/windowsserverdocs#3631]
Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages.gz  Hash Sum mismatch

Any chance you can have a look at this and revert the change or fix the hash ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e7ed059-d77f-6ce0-8501-fc3afd1c8048
* Version Independent ID: f2d249ee-50e4-52b4-4187-954a84a48ec1
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute**
* GitHub Login: @szarkos
* Microsoft Alias: **szark**

**Comment by gonzalofrancoceballos** [comment]
Same problem here. Production processes depending on this are now failing

**Comment by Hellkyte** [comment]
Yeah, the CI/CD pipelines that depend on this are down right now.

**Comment by TobiasXy** [comment]
Similar problem for me, but with Debian 10. Same problem or am I doing it wrong?

**Comment by zingbretsen** [comment]
Same problem with Debian 9.

W: Conflicting distribution: https://packages.microsoft.com/debian/9/prod stretch InRelease (expected stretch but got stable)
E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.bz2  Hash Sum mismatch

It looks like maybe the wrong InRelease file was uploaded to these repos? The InRelease file is the same across both the debian 9 and xenial repos, and it references `vscode stable` instead of `microsoft-debian-stretch-prod stretch` and `microsoft-ubuntu-xenial-prod xenial`

**Comment by Hellkyte** [comment]
https://github.com/microsoft/vscode/issues/86858 is tracking the same root cause

**Comment by djburnham** [comment]
Well my jobs ran this morning and downloaded the python odbc driver correctly and I can see the date on the https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages.gz
file has moved to yesterday afternoon so I'm going to close this issue. Many thanks for replacing the file!
Kind regards,
                                  David
