### ISSUE TITLE
Change background black for image ?

### ISSUE THREAD

**Issue by fbocosta** [MicrosoftDocs/windowsserverdocs#3679]
I use RDS with Windows 2016 server and would like to change the background of the HTML 5 page to an image how should I proceed?

Because the background is static black I would like to insert an image in place of the black background

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d3b53c9-06c8-883c-6197-3fa09fa2e737
* Version Independent ID: e679b983-6e34-75a8-8e4d-f56a5067bf85
* Content: [Get started with the web client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by illfated** [comment]
(Ref. #3678 )

**Comment by illfated** [comment]
@fbocosta : Please note that this repository is only used to report issues with the referenced documentation. It is not a support instance, but might be interpreted as one, based on some of the tickets where incorrect documentation actually causes errors or issues when actively using the documentation.

Also, let me add a few notes based on my experience the last couple of years while using this repository:

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
