### ISSUE TITLE
User Tunnel DNS is non-functional when Device Tunnel is down

### ISSUE THREAD

**Issue by OKArc** [MicrosoftDocs/windowsserverdocs#3686]
**Status:** Device Tunnel Servers Offline, User Tunnel Connected
**Condition:** Applications do not resolve internal DNS
**Exception #1:** If the Device Tunnel is actively attempting a connection DNS resolves.
**Exception #2:** If I delete the Device Tunnel profile, DNS resolves.
**Exception #3:** Manually selecting the server in nslookup resolves DNS

**Comment by RAJU2529** [comment]
@OKArc. For which Content you talking about

**Comment by OKArc** [comment]
Always On VPN. I might be in the wrong place but I did see other comments, I thought in this same area.

**Comment by RAJU2529** [comment]
@OKArc . please tell me the content or website address , so that  theExpert windows users will give solutions to  you correctly. I am not an expert.

**Comment by OKArc** [comment]
Like this? https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/always-on-vpn-technology-overview

**Comment by dknappettmsft** [comment]
Hi @OKArc, GitHub issues in this repo is for reporting an issue with a particular article where our content has errors, needs extra clarity, etc. I'm struggling to find which article you're referring to as the article you added as a comment above this post is an overview of the technology, rather than specific DNS configuration.

Please can you provide a link to the article you're having an issue with and the specific part and I can look into it further.

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
#please-close
