### ISSUE TITLE
How to retrieve signed in account name from Windows Admin Center's custom extension

### ISSUE THREAD

**Issue by venocp** [MicrosoftDocs/windowsserverdocs#3696]
Windows Admin Center Settings shows Signed in account name. Can we retrieve that account name via AppContextService? or is there anyway to get the login username within the Windows Admin Center's custom extension?

**Comment by dknappettmsft** [comment]
Hi @venocp, GitHub issues in this repo is for reporting issues with specific articles that are published where there are mistakes, more clarity is required, etc. If there is an article you need us to investigate, please could you provide the link?  Otherwise, your request would be better off being made at https://aka.ms/wacfeedback, as that is managed by the product group. Thank you.

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
#please-close
