### ISSUE TITLE
Default <File> value

### ISSUE THREAD

**Issue by tdillon** [MicrosoftDocs/windowsserverdocs#3707]
When attempting to run `robocopy` with the `<File>` parameter explicitly set to the default value documented above (i.e., `*.\*`), I get the following error.

`ERROR : Invalid Parameter #3 : "*.\*"`

For example, if I run `robocopy . C:\bob *.\*` I get the error.  In my real world use case I will be using a variable for the `<File>` parameter, and in some cases I will want to use the default behaviour.  So ideally, it should be possible to literally set the `<File>` parameter to the default value without the command errorring.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af94ad3b-6603-2b26-1010-073fb2c07c2a
* Version Independent ID: 09fd75d0-8624-5cfd-5122-b40ba50055f9
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
I think there is a formatting error in the text, that the backslash **\** should not be used here and that it is a formatting error causing the backslash to show instead of being an escape character for the following asterisk.

I am fairly certain that the intended syntax there should be **\*.\*** and that there are a couple of backslashes too much in the code:

```
If the **File** parameter is not specified, **\*.\\**\* is used as the default value.
```
The correct formatting to show only *.* is a couple of backslashes less:
```
If the **File** parameter is not specified, **\*.\*** is used as the default value.
```
The complete table should look like this:

## Parameters

|   Parameter    |                                                                                            Description                                                                                             |
|----------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|   \<Source>    |                                                                            Specifies the path to the source directory.                                                                             |
| \<Destination> |                                                                          Specifies the path to the destination directory.                                                                          |
|    \<File>     | Specifies the file or files to be copied. You can use wildcard characters (**&#42;** or **?**), if you want. If the **File** parameter is not specified, **\*.\*** is used as the default value. |
|   \<Options>   |                                                                    Specifies options to be used with the **robocopy** command.                                                                     |

***

Could you check & verify this and report back here with your results?

**Comment by tdillon** [comment]
`*.*` appears to behave the same as not specifying the `<File>` argument as you suggest.  Thanks.

**Comment by illfated** [comment]
Thank you for confirming my suspicion about this issue. I will proceed by opening a Pull Request to have that text corrected.
