### ISSUE TITLE
Link to Emergency Management Services Technical Reference for wrong Windows version

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#3715]
The link to the Emergency Management Services Technical Reference above to goes to the wrong version of the Emergency Management Services Technical Reference. Specifically, the link goes to the Emergency Management Services Technical Reference for Windows Server 2003, Windows Server 2003 R2, Windows Server 2003 with SP1, Windows Server 2003 with SP2 . Since this page is part of the documentation for Windows Server 2016, it should go to the Emergency Management Services Technical Reference for Windows Server 2016 instead. Please fix this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c027a7f-550e-8f36-226b-725bc78157b5
* Version Independent ID: b774d4aa-33d7-6af2-97de-c66ce7a7fda1
* Content: [Troubleshooting Nano Server](https://docs.microsoft.com/en-us/windows-server/get-started/troubleshooting-nano-server)
* Content Source: [WindowsServerDocs/get-started/Troubleshooting-Nano-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Troubleshooting-Nano-Server.md)
* Service: **na**
* Product: **windows-server**
* Technology: **server-nano**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
I don't work on this content anymore. @JasonGerend @eross-msft is this your area now?

**Comment by eross-msft** [comment]
@rossmpersonal  Thank you for your feedback. This content is no longer being actively maintained due to resource constraints. However, you can update this article yourself, by using the **Edit** link on the page itself and creating a pull request for us to approve and publish. You can find the instructions here: https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/Contributor-guide/github-browser-updates.md#quick-edits-to-existing-articles-using-github-and-a-web-browser.

**Comment by eross-msft** [comment]
#please-close
