### ISSUE TITLE
What is the option to set the Task Category?

### ISSUE THREAD

**Issue by agvardha** [MicrosoftDocs/windowsserverdocs#3727]
In many of the system generated ETL entries I see the field called Task Category filled in. However I don't see any option to set it. Please enlighten. 
thanks
ananda

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93ffdbd5-d56b-a453-4ea6-3e9dcf53eb69
* Version Independent ID: 21ca1f42-86df-8cdf-e9ee-a2831a0c14c8
* Content: [eventcreate](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/eventcreate#BKMK_examples)
* Content Source: [WindowsServerDocs/administration/windows-commands/eventcreate.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/eventcreate.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by agvardha** [comment]
@coreyp-at-msft I was hoping some kind of answer :(. So can I assume it is broken and you are in the process of getting it fixed to make a release and hence have not replied me? Either way please let me know. I am still stuck 👎

**Comment by dknappettmsft** [comment]
Hi @agvardha, thanks for the feedback. The eventcreate tool doesn't have an option to set a value for Task Category. GitHub issues in this repo is to raise issues with a specific article where there is something that needs correcting, clarifying, etc., rather than the application itself.  As the article accurately documents what is available in the application, I will close this issue.

#please-close
