### ISSUE TITLE
Missing Storage Maintenance Mode 

### ISSUE THREAD

**Issue by jlgandy2** [MicrosoftDocs/windowsserverdocs#3745]
Would it be possible to add Storage Maintenance Mode after Pause and Drain as shown in the Troubleshoot Storage Spaces Direct, Shutdown process flow, step 3 (https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/troubleshooting-storage-spaces#shutdown-process-flow) to insure both the workload and the storage are paused before a reboot?

**Comment by dknappettmsft** [comment]
Hi @jlgandy2, thanks for the feedback. I'm trying to work out of this is still needed, or if the article already covers this. Step 3 is currently to put the disks on a node in Storage Maintenance Mode, which is after the Pause/Drain in step 2, so that's what you're after?  The command in step 3 for reference is:

Get-StorageFaultDomain -type StorageScaleUnit | Where-Object {$_.FriendlyName -eq "<NodeName>"} | Enable-StorageMaintenanceMode

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by DellProSupportGse** [comment]
Someone added SMM a long time back. Thanks for following up. :)

**Comment by dknappettmsft** [comment]
Great! I thought that was the case, but wanted to check it was covered. Sorry it took so long for the reply.

#please-close
