### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by awakecoding** [MicrosoftDocs/windowsserverdocs#3751]
I just learned about this RDP URI format today because of the iOS app support. Is Windows support planned? It is just a protocol handler, it can't be that hard to implement. I'm tempted to write a third party tool that would install a protocol handler, grab the parameters, create a .RDP file and launch mstsc.exe with it. However, this is really something that should come with Windows :/ there would be a lot of really nice use cases for this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9effefa0-ac98-1fdd-6174-f06d524622f5
* Version Independent ID: 5d405e1c-d2eb-9c72-3cf6-817930cad4f6
* Content: [Remote Desktop clients URI scheme](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-uri#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-uri.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-uri.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Sorry for taking so long to respond, but then again, I only use GitHub in my spare time.

Please note that this repository is for documentation improvement purposes only. Questions and suggestions to the Microsoft developers should be sent via the Feedback Hub app.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/
