### ISSUE TITLE
How to enable CredSSP for the cluster?

### ISSUE THREAD

**Issue by 4fd81048-Brian** [MicrosoftDocs/windowsserverdocs#3769]
I'm experiencing the CredSSP workflow failure as described here, when selecting Updates or Diagnostics.
https://social.technet.microsoft.com/Forums/en-US/cb14a059-ea1f-4d10-a0d1-11a558c26040/windows-admin-center-the-workflow-to-enable-credssp-has-been-completed-but-there-was-an-error?forum=winservergen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7be9997d-7c5d-1f44-c243-b232fdbdf8df
* Version Independent ID: 88564bdf-d24a-c298-2d0c-371b0d33288c
* Content: [Manage Hyper-Converged Infrastructure with Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/manage-hyper-converged#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/manage-hyper-converged.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/manage-hyper-converged.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @daniellee-msft
* Microsoft Alias: **jol**

**Comment by dknappettmsft** [comment]
Hi, there is some information on CredSSP in cluster creation in our docs here: https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/support/known-issues#credssp-in-cluster-creation.  Otherwise, I think you'll be best off contacting Microsoft Support (https://support.microsoft.com/contactus) as GitHub issues in this repo is to raise issues with a specific article where there is something that needs correcting, clarifying, etc. rather than particular environments where this is not working.  If there's something reproduceable and a solution to it which requires this article to be updates, I can do so. Thank you.

#please-close
