### ISSUE TITLE
X-Frame-Options setting "allow-from" is deprecated by browsers.

### ISSUE THREAD

**Issue by bieberium** [MicrosoftDocs/windowsserverdocs#3783]
It would be good to note that the "allow-from" directive for "X-Frame-Options" header has been deprecated by most browser (except Spartan Edge and Internet Explorer).
See also: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#Browser_compatibility

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34bb90bc-fc83-1c43-9ba5-22e233a5be2b
* Version Independent ID: 2160474e-a441-3349-c64a-72e9364fd5ed
* Content: [Customize HTTP security response headers with AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/customize-http-security-headers-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/customize-http-security-headers-ad-fs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/customize-http-security-headers-ad-fs.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
