### ISSUE TITLE
Step 4 Mislabeling

### ISSUE THREAD

**Issue by Drehmini** [MicrosoftDocs/windowsserverdocs#3800]
Step 4 specifies "Tools &gt; **Terminal Services**"  
This should be "Tools &gt; **Remote Desktop Services**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433e6d71-c9b3-8326-3b8d-a1e27e9ea3bc
* Version Independent ID: 2b5e85cd-9e39-f882-ee55-cb33770f45ca
* Content: [Deploy your Remote Desktop environment](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-deploy-infrastructure#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-deploy-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-deploy-infrastructure.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Looks reasonable. I tried looking this up on the production server (Windows Server 2016) at my workplace, but can not risk applying any of the previous steps in the Deployment list. Based only on what is available in the Tools menu, there is no "Terminal Services" available in the default setup, whereas the closest thing to "Remote Desktop Services" I could see was Remote Desktop Management. I assume this may be due to the steps 1 through 3 not being applied on that server yet. None of these options were available on the direct hardware server, Remote Desktop Management is only available on the VM where the SQL, File & Print server is running. Reading through steps 1, 2, and 3, I assume there is nothing there to suggest that "Terminal Services" should become available unless it was already present in the default server config.

I would like to offer a Pull Request to have the text corrected, but will wait for additional confirmation (maybe with references?) that the suggestion above is correct.

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I have corrected this step to the current terminology, the change should be visible in a few hours.

#please-close
