### ISSUE TITLE
What's new on 10.1.1148.0?

### ISSUE THREAD

**Issue by myokeeh** [MicrosoftDocs/windowsserverdocs#3813]
Why not keep this information as part of the Store listing under "What's new in this version"? There's nothing like having to type in the URL because it's not clickable in the Store app then find out this page is out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67b7b5a4-647e-fee3-6533-6ed88ae45bfa
* Version Independent ID: d9102859-0147-346f-8268-6e2a75c8b0b7
* Content: [What's new in the Windows Store client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows-whatsnew#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by myokeeh** [comment]
10.1.1149.0 is out! Yay! What's new? 🤷🏽‍♂️

**Comment by myokeeh** [comment]
10.1.1150.0 is out! The plot thickens!

**Comment by Attoy** [comment]
Yeah, this page is not updated very frequently...

**Comment by tboggs13** [comment]
Seriously, there are some major bugs with this app on my SurfaceProX, it would be great to see some feedback on if this is being addresses in recent releases. This app is my favorite RD client because of proper screen scaling and usability improvements over the old mstsc client. However it is less reliable on all my devices. But on the SurfaceProX, it is more likely to freeze, cause the screen to flicker and flat our crash.

**Comment by myokeeh** [comment]
@eross-msft @davidbel @v-thepet We'd like to know what's new. Anyway to see change log right in the Microsoft Store entry?

**Comment by myokeeh** [comment]
Thanks for updating the page. I still wish you'd make use of the "What's new in this version" field in the Store.

**Comment by davidbel** [comment]
Hi @myokeeh, thanks for the feedback. We generally update the What's new text in the Store with the content of the latest release. Since the Store allows only a certain amount of text in the What's new, we also keep a public page with information about the content of the previous releases for reference.

**Comment by myokeeh** [comment]
@davidbel I believe you have 1000 characters for that field, if I'm not mistaken. Surely, change log for the last three should fit there:

Store entry:
![image](https://user-images.githubusercontent.com/3663297/80263660-2aac7780-8646-11ea-8d22-4211ef9badf6.png)


Text from page:
![image](https://user-images.githubusercontent.com/3663297/80263632-149eb700-8646-11ea-8ef1-641ad014cb16.png)

**Comment by dknappettmsft** [comment]
Thanks for the feedback. Seeing as this issue is raised for the Docs article which is up to date, I will close this.

#please-close
