### ISSUE TITLE
Microsoft SQL Server 2019 and other MS apps

### ISSUE THREAD

**Issue by reinaldokibel** [MicrosoftDocs/windowsserverdocs#3846]
a) is this saying Microsoft SQL Server 2019 is not supported?
b) is there a link to new features on Windows Server that are leveraged by these apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 511301d9-f9cb-bad2-993f-d45c3b17b1b0
* Version Independent ID: 3f1d3506-849e-5dde-de07-edfc99b333f8
* Content: [Windows Server 2019 and Microsoft Server application compatibility](https://docs.microsoft.com/en-us/windows-server/get-started-19/app-compat-19#feedback)
* Content Source: [WindowsServerDocs/get-started-19/app-compat-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/app-compat-19.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @coreyp
* Microsoft Alias: **coreyp-at-msft**

**Comment by dknappettmsft** [comment]
Microsoft SQL Server 2019 is supported on Windows Server 2019, the table has been updated since this issue was raised. For information on whether these server applications support particular features in Windows Server, you'll need to see the product documentation for the particular server application for this information.

#please-close
