### ISSUE TITLE
Hybrid Cloud Print - 403 Forbidden: Access Denied when printing

### ISSUE THREAD

**Issue by pthoor** [MicrosoftDocs/windowsserverdocs#3885]
I've installed Hybrid Cloud Print following the guide on: https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-deploy

I can successfully deploy printers and search for printers, both with PowerShell and with Printers GUI. And can successfully install the printer on the AAD joined computer. 

But when I'm trying to do a test print page from EcpPrintTest printer, I got a strange error, just "Error - Sent to printer". When I'm printing from another app I get "403 Forbidden: Access Denied".

In AAD logs on the AAD joined computer:

> Error: 0x80070057 The parameter is incorrect.
> 
> The parameter is incorrect.
> 
> Exception of type 'class WinRTException' at oauthtokenrequestbase.cpp, line: 767, method: OAuthTokenRequestBase::QueryTokenBindingKeyId::<lambda_96afc217c121125f18a3495072ac63ea>::operator ().
> 
> Log: 0x8aa5007f Unable to create a Token Binding Key.
> Logged at oauthtokenrequestbase.cpp, line: 767, method: OAuthTokenRequestBase::QueryTokenBindingKeyId::<lambda_96afc217c121125f18a3495072ac63ea>::operator ().
> 
> Request: authority: https://login.microsoftonline.com/<TenantID>, client: 73eafb9b-610a-483f-a44d-be0be3eb085d, redirect URI: ms-appx-web://Microsoft.AAD.BrokerPlugin/73eafb9b-610a-483f-a44d-be0be3eb085d, resource: http://MopriaDiscoveryService/CloudPrint, correlation ID (request): e270a781-3a65-4bb8-a47d-128a6cb44552

In the IIS log on the Print Server, from where I install the printer, to where I tried to do a test print page:

> #Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken
> 2020-02-13 09:21:38 172.19.1.22 GET /mcs/services - 80 user@domain.com 172.21.1.4 MCP+DAF+Provider - 200 0 0 46
> 2020-02-13 09:21:38 172.19.1.22 GET /mcs/devices location_tree_type=org 80 user@domain.com 172.21.1.4 MCP+DAF+Provider - 200 0 0 125
> 2020-02-13 09:21:57 172.19.1.22 GET /mcs/services - 80 user@domain.com 172.21.1.4 MCP+DAF+Provider - 200 0 0 31
> 2020-02-13 09:21:57 172.19.1.22 GET /mcs/devices location_tree_type=org 80 user@domain.com 172.21.1.4 MCP+DAF+Provider - 200 0 0 62
> 2020-02-13 09:22:04 172.19.1.22 GET /mcs/services - 80 user@domain.com 172.21.1.4 MCP+DAF+Provider - 200 0 0 31
> 2020-02-13 09:22:04 172.19.1.22 GET /mcs/locations scope=sub&location_tree_type=org&limit=2147483647 80 user@domain.com 172.21.1.4 MCP+DAF+Provider - 200 0 0 78
> 2020-02-13 09:22:06 172.19.1.22 GET /mcs/services - 80 user@domain.com 172.21.1.4 MCP+DAF+Provider - 200 0 0 31
> 2020-02-13 09:22:06 172.19.1.22 GET /mcs/devices location_tree_type=org&country=usa&sort=orglocation%2bname&limit=20 80 user@domain.com 172.21.1.4 MCP+DAF+Provider - 200 0 0 203
> 2020-02-13 09:22:10 172.19.1.22 GET /mcs/services - 80 user@domain.com 172.21.1.4 MCP+DAF+Provider - 200 0 0 35
> 2020-02-13 09:22:10 172.19.1.22 GET /mcs/devices uuid=7c98280a-750f-54be-b653-e95eded4fa61 80 user@domain.com 172.21.1.4 MCP+DAF+Provider - 200 0 0 93
> 2020-02-13 09:22:13 172.19.1.22 POST /ecp/printer/localspl/ecpprinttest - 80 - 172.21.1.4 Windows+Internet+Print+Protocol+Provider - 401 2 5 31
> 2020-02-13 09:22:13 172.19.1.22 POST /ecp/printer/localspl/ecpprinttest - 80 - 172.21.1.4 Windows+Internet+Print+Protocol+Provider - 401 1 2148074252 31
> 2020-02-13 09:22:13 172.19.1.22 POST /ecp/printer/localspl/ecpprinttest - 80 - 172.21.1.4 Windows+Internet+Print+Protocol+Provider - 401 2 5 31
> 2020-02-13 09:22:13 172.19.1.22 POST /ecp/printer/localspl/ecpprinttest - 80 - 172.21.1.4 Windows+Internet+Print+Protocol+Provider - 401 1 2148074252 31
> 2020-02-13 09:24:21 172.19.1.22 POST /ecp/printer/localspl/ecpprinttest - 80 - 172.21.1.4 Windows+Internet+Print+Protocol+Provider - 401 2 5 31
> 2020-02-13 09:24:36 172.19.1.22 POST /ecp/printer/localspl/ecpprinttest - 80 - 172.21.1.4 Windows+Internet+Print+Protocol+Provider - 401 2 5 31
> 2020-02-13 09:24:36 172.19.1.22 POST /ecp/printer/localspl/ecpprinttest - 80 - 172.21.1.4 Windows+Internet+Print+Protocol+Provider - 401 1 2148074252 31

So the print job says error 401...
The IP: 172.19.1.22 = Print server
The IP: 172.21.1.4 = Azure AD Application Proxy server
Ports 443 and 80 are open between the servers.

When I try to access the /ecp/ page I do get an 403 error. But I don't know if thats by design. The /mcs/ page works. 
I've tried with both pre authentication Passthrough and Azure AD in the Enterprise Application part. I've set up Kerberos Constrained Delegation on the Azure AD Application Proxy server. 
I've tried to remove NTLM on the /ecp/ site.

Not sure where to continue...

**Comment by illfated** [comment]
My sympathies with your issues there. I just don't think I will be able to help, since I am mostly focused on page formatting and grammar for the MS Docs pages.

Seeing that this repository primarily handles MS Docs page issues, improvement suggestions or pointing out possible documentation errors, it is less likely that your question will be answered within any reasonable time frame here (unless you are lucky enough that someone knowing a solution to your issue chooses to post a reply here).

I could have chosen to post a canned reply here, as is often used when the ticket content is less than relevant to the document page in question, but I felt the need to point out personally that this type of issue may receive faster replies and maybe even solution suggestions way sooner than in this GitHub repository for MS Docs page issues. I particularly recommend the social or techcommunity forum pages within Microsoft's web domain (microsoft.com). You may even prefer to contact a Microsoft support instance relevant to your business size or included support level scenario.

However, should you find that the solution to your issue is something not described in the relevant MS Docs pages, or that the solution even goes against current documentation, we welcome feedback regarding this here on these pages. In such cases, we are happy to follow up suggestions to have the documentation page(s) in question changed accordingly, by posting Pull Requests to have the necessary changes reviewed by the authors & project managers.

**Comment by dknappettmsft** [comment]
As was commented above, GitHub issues in this repo aren't for product support. Please contact Microsoft Support if needed, and any updates needed to the article from that will be fed through.

#please-close
