### ISSUE TITLE
Multiscreen support

### ISSUE THREAD

**Issue by wilsonnkwan** [MicrosoftDocs/windowsserverdocs#3903]
I notice that the Windows version of the RD app (the one you get from Store, not the native version) don't have Multiscreen support. Even the Mac version has, am I missing something or there is a way to enable it? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc42a8f-2623-4352-7cc4-70f0f61e9d89
* Version Independent ID: 97d8b54b-5e7d-098b-4fb7-e8f6e0b30389
* Content: [Get started with the Windows Store client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by dteske25** [comment]
+1
I really like the new interface, and the app works great except I can't use more than one monitor, and that's the deal-breaker for me.

**Comment by TSKimball** [comment]
As an IT Worker monitoring vast amounts of data, I need a minimum of two monitors to function - either locally or remotely.  These days, I'm actually up to three, and I know many at work who use four.

Only one screen for the new RDP is an instant 'NOPE' for that use case.  The only reason I even looked at the app is because the old RDP has been freezing up constantly.

[Win10 to Win10 connection, both in the 19xx series, so its not cross-version.]

**Comment by jeremyzc** [comment]
Me too - having a few issues with the older RDP over vpn. This one works ok however one screen is a nuisance.

**Comment by SSDismay** [comment]
Me three - multiscreen is a must for me, it's the only reason i haven't switched to the new app completely.

**Comment by jwashbur** [comment]
When will Microsoft add multi-screen support for this application? Currently is it very frustrating to use as an IT admin. We are giving the desktop app a try rather than using the Microsoft Store app. Trying to manage multiple servers gets really frustrating when you are stuck inside 1 app (1 window). 

Currently this app fixes that issue:
https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop

**Comment by IngridAtMicrosoft** [comment]
GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
