### ISSUE TITLE
You could write a example command as every command line or t-sql command

### ISSUE THREAD

**Issue by momchilok** [MicrosoftDocs/windowsserverdocs#3911]
You could write a example command as every command line or t-sql command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Hi, I'm not sure I follow the request - please could you elaborate?

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @momchilok, 

Syntax between T-SQL and windows commands are so different that there wouldn't be a way to provide examples. We do not know if you intended to ask this question for the robocopy documentation or otherwise. We will be closing this thread. 

If you have more feedback with this documentation, please open another issue against it. Thank you and have a most pleasant day. 

#please-close
