### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/windowsserverdocs#3918]
@exsit commented 3 hours ago — with docs.microsoft.com
The dynamic disk appears as "invalid", it seems to me that this is not described on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d347f950-4249-15da-2b61-6cc51f5fbb28
* Version Independent ID: cce0393d-b49e-0530-c4c1-679763ab61bf
* Content: [Troubleshooting Disk Management](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/troubleshooting-disk-management#feedback)
* Content Source: [WindowsServerDocs/storage/disk-management/troubleshooting-disk-management.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/troubleshooting-disk-management.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by ticianaciminari** [comment]
Hi Team, could you please check the issue from user?

Kind regards, 
Microsoft DOCS International Team

**Comment by illfated** [comment]
Even though I do not have the exact same experience as @exsit with disks appearing as "invalid" in the disk management view (nor do I have a reasonably similar test scenario), I would like to know what kind of disk is being connected, as well as if that disk is verified to be a usable disk for this particular scenario. That kind of information would be most useful to those of the MS Docs team members who would want to create an update for the related MS Docs page, to know if the issue is, in fact, based on using supported hardware for this task.

**Comment by illfated** [comment]
Please note that questions like the one presented above belongs to Microsoft Support, although reports of incorrect documentation is welcome, if found to be in error after troubleshooting with Microsoft Support agents or local Microsoft tenant departments.

Please report back whenever the issue solution provides corrections to the referenced documentation. Corrections and improvements are always welcome.

**Comment by illfated** [comment]
#please-close
