### ISSUE TITLE
PLease add the link to add additional nodes

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/windowsserverdocs#3927]
&lt;&lt;add additional HGS nodes to your cluster?? LINK is missing on Bastion forest setups (TPM/KEY/AD mode)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae25db7-fa78-b9bd-463c-a6debe7387f9
* Version Independent ID: 9384ad42-9e6a-ecd6-b07f-7baf55cbe4eb
* Content: [Initialize the HGS cluster using TPM mode in a bastion forest](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-bastion)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-bastion.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-bastion.md)
* Product: **windows-server**
* Technology: **security-guarded-fabric**
* GitHub Login: @rpsqrd

**Comment by ryanabach** [comment]
I am following all of these steps verbatim, and I cannot get the HGS Service initialized. It appears that I am not included the correct parameters / flags. I want to initialize the service with HTTP and HTTPS (HGS server module states this is required, but HGS documentation says otherwise).

What am I doing wrong here? Please advise.

Error Message:

Write-StreamAndLog : Exception calling "Invoke" with "2" argument(s): "Value does not fall within the expected range."
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HgsServer\HgsServer.psm1:2407 char:17

Initialize Command + Parameters:

Initialize-Hgsserver -UseExistingDomain
-ServiceAccount 'USAHGSgMSA' -JeaReviewersGroup 'USHgsJeaReviewers'
-JeaAdministratorsGroup 'USHgsJeaAdmins' -HgsServiceName 'USAHgsService'
-ClusterName 'USAHgsCluster' -SigningCertificateThumbprint $Thumbprint
-EncryptionCertificateThumbprint $Thumbprint -HttpsCertificateThumbprint $Thumbprint
-Http -Https
-TrustTpm -LogDirectory 'C:\hgsdata\'
-Verbose

**Comment by dknappettmsft** [comment]
Hi @carlosmayol - I'm not sure I agree that it's best to go here. Can you provide some more information on what your thought is for where it would go, please?

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by carlosmayol** [comment]
Sure, happy to help, as well in other scenarios like initializing in a dedicated forest https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-default you will notice at the end of the section there is a link to "ADD additional nodes"  We want the same sentence to appear in the deployment using a Bastion Forest , so basically you just need to copy/past the part: That's it! In a production environment, you should continue to [add additional HGS nodes to your cluster](https://docs.microsoft.com/en-us/windows-server/virtualization/guarded-fabric-shielded-vm/guarded-fabric-configure-additional-hgs-nodes).

**Comment by dknappettmsft** [comment]
Thanks for the clarification. I've added this and the change should be visible later today.

#please-close
