### ISSUE TITLE
Key Signature for scx-1.6.4-7.universal.x64.rpm & omi-1.6.4-0.ssl_100.ulinux.x64.rpm is incorrect on https://packages.microsoft.com/rhel/7/prod/

### ISSUE THREAD

**Issue by rajsshah86** [MicrosoftDocs/windowsserverdocs#3929]
Automatic update of packages via YUM and ansible fails because 2 of the packages are not having correct signature . 

**
_
> The keys listed for the "Microsoft RHEL7 Repositories" repository are already installed but they are not correct for this package.
> Check that the correct key URLs are configured for this repository.
> 
>  Failing package is: scx-1.6.4-7.x86_64
>  GPG Keys are configured as: https://packages.microsoft.com/keys/microsoft.asc
**

If I manually download the package and check the keys 
_

> rpm -K omi-1.6.4-0.ssl_100.ulinux.x64.rpm
> omi-1.6.4-0.ssl_100.ulinux.x64.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#513b22cc)

_

Please update the package with correct keys.
scx-1.6.4-7.universal.x64.rpm
omi-1.6.4-0.ssl_100.ulinux.x64.rpm

**Comment by dknappettmsft** [comment]
Hi, GitHub issues in this repo are for raising issues with documentation, rather than issues with files such as this. In addition I searched through the entire repo for the URL https://packages.microsoft.com/rhel/7/prod/ and couldn't find it referenced. Please contact Microsoft Support if this is still an issue.

#please-close
