### ISSUE TITLE
Link sending you to nowhere

### ISSUE THREAD

**Issue by garretthutchison** [MicrosoftDocs/windowsserverdocs#3964]
This link in the document does not link you to the worksheet (https://go.microsoft.com/fwlink/?LinkID=102558). Sends you to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6de125e9-a2cd-dcc9-b52b-cc543fdd04c3
* Version Independent ID: 89599684-1c4a-5e9b-f50e-97a0c8efc422
* Content: [Planning Operations Master Role Placement](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/planning-operations-master-role-placement#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Planning-Operations-Master-Role-Placement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Planning-Operations-Master-Role-Placement.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Confirmed. The link https://go.microsoft.com/fwlink/?LinkID=102558 turns into https://www.microsoft.com/downloads/details.aspx?FamilyID=edabb894-4290-406c-87d1-607a58fc81f0&DisplayLang=en which in turn returns a 404 error page:
***
## Server Error

### 404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
***
This is the related document section:

## Planning the PDC emulator placement

The PDC emulator processes client password changes. Only one domain controller acts as the PDC emulator in each domain in the forest.  
  
Even if all the domain controllers are upgraded to Windows 2000, Windows Server 2003, and  Windows Server 2008 , and the domain is operating at the Windows 2000 native functional level, the PDC emulator receives preferential replication of password changes performed by other domain controllers in the domain. If a password was recently changed, that change takes time to replicate to every domain controller in the domain. If logon authentication fails at another domain controller due to a bad password, that domain controller forwards the authentication request to the PDC emulator before deciding whether to accept or reject the logon attempt.  
  
Place the PDC emulator in a location that contains a large number of users from that domain for password forwarding operations if needed. In addition, ensure that the location is well connected to other locations to minimize replication latency.  
  
For a worksheet to assist you in documenting the information about where you plan to place PDC emulators and the number of users for each domain that is represented in each location, see Job Aids for Windows Server 2003 Deployment Kit ([https://go.microsoft.com/fwlink/?LinkID=102558](https://go.microsoft.com/fwlink/?LinkID=102558)), download Job_Aids_Designing_and_Deploying_Directory_and_Security_Services.zip, and open Domain Controller Placement (DSSTOPO_4.doc).  
  
You need to refer to the information about locations in which you need to place PDC emulators when you deploy regional domains. For more information about deploying regional domains, see [Deploying Windows Server 2008 Regional Domains](https://technet.microsoft.com/library/cc755118.aspx).
***
A similar outdated link appears in a paragraph in the last section:

For a worksheet to assist you in planning operations master role placement, see [Job Aids for Windows Server 2003 Deployment Kit](https://go.microsoft.com/fwlink/?LinkID=102558), download Job_Aids_Designing_and_Deploying_Directory_and_Security_Services.zip, and open Domain Controller Placement (DSSTOPO_4.doc).  
***
Please note that this content refers to outdated operating systems like Windows 2000, Windows Server 2003, and  Windows Server 2008. The document collection "Job Aids for Windows Server 2003 Deployment Kit" is likely removed due to heavily outdated content using Windows 2000 and Windows Server 2003 scenarios.

**Comment by illfated** [comment]
Someone else found the correct document in issue ticket #4147.
I will start working on a PR to fix the link here too.
