### ISSUE TITLE
Edit recommended 

### ISSUE THREAD

**Issue by PishPoshery** [MicrosoftDocs/windowsserverdocs#3992]
In the claim rule set table, section “Delegation Authorization Rule Set”, the last sentence is: 
Unless you specify an issuance authorization rule, no users can act as delegates by default.
I believe this should read:
Unless you specify a delegation authorization rule, no users can act as delegates by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aad31160-1daa-169e-d87c-b5ad9fe87694
* Version Independent ID: bb49ffa6-7372-1539-d8b4-a8110d0429d9
* Content: [The Role of Claim Rules](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/the-role-of-claim-rules)
* Content Source: [WindowsServerDocs/identity/ad-fs/technical-reference/The-Role-of-Claim-Rules.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/technical-reference/The-Role-of-Claim-Rules.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Fair point. This looks like a copy-paste mistake, since the previous row (Issuance Authorization Rule Set) contains the same start of the sentence "Unless you specify an issuance authorization rule, " as the one you have pointed out. Your suggestion makes a lot of sense in making this sentence in the next row refer to the name of the rule set: "Delegation Authorization Rule Set"

I will open a PR to suggest this change (unless someone has done so already).

**Comment by illfated** [comment]
There you go. Feel free to comment or add anything else in need of fixing you happen to find in that same page.
