### ISSUE TITLE
Security and NLA

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windowsserverdocs#4003]
Im planning to use rdp with remote public ip. Is there a way to copy the server public cert to my remote client to verify if it is the server im connecting to? (Just so the popup asking unidentified trust computer disappear) Also why should i turn off NLA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4c63a8-69a4-da31-a805-54f5a4eba11d
* Version Independent ID: c1af9748-e90c-9521-7ea8-017ad238faa0
* Content: [Remote Desktop - Allow access to your PC](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-access#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-access.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by jokezone** [comment]
You should never expose RDP directly to the public internet. Use a gateway or VPN solution to access it securely. Look up the BlueKeep vulnerability if you want to learn why.

**Comment by hoksource** [comment]
thanks for the info.

https://www.microsoft.com/security/blog/2019/08/08/protect-against-bluekeep/
- says you should enable NLA and move the RDP listener behind some type of second factor authentication, such as VPN, SSL Tunnel, or RDP gateway.



Please do add further readings on this page:
https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access

Please do also provide warning note about vulnerability on public ip and provide reference on how to setup second factor authentications.

**Comment by dksimpson** [comment]
Hello @ghost,

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
