### ISSUE TITLE
Outdated instructions?

### ISSUE THREAD

**Issue by RussKeldorph** [MicrosoftDocs/windowsserverdocs#4023]
The first example containing "Install-Module -Force OpenSSHUtils -Scope AllUsers" doesn't work. 
 Apparently it is no longer necessary?  I found this.  https://github.com/PowerShell/Win32-OpenSSH/issues/1560.  Is it because I'm on an insider build of windows? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by vscodr** [comment]
Absolutely bombs for me everytime
PS C:\Windows\system32> Start-Service ssh-agent
Start-Service : Service 'OpenSSH Authentication Agent (ssh-agent)' cannot be started due to the following error:
Cannot start service ssh-agent on computer '.'.
At line:1 char:1
+ Start-Service ssh-agent
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

PS C:\Windows\system32> Install-Module -Force OpenSSHUtils -Scope AllUsers
PackageManagement\Install-Package : The module 'OpenSSHUtils' cannot be installed or updated because the authenticode
signature of the file 'OpenSSHUtils.psd1' is not valid.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.P
   ackageManagement.Cmdlets.InstallPackage

**Comment by Alex-Mann** [comment]
It would probably be good to update these instructions. Currently disabling the administrators file described [here](https://superuser.com/a/1522659/1168750) allowed me to connect without a password. For some reason adding my public key to the administrators file did not work.

**Comment by jeffwilcox** [comment]
+1 these instructions are very old unfortunately... hitting roadblocks :(

**Comment by gynnantonix** [comment]
If you want to start ssh-agent, here are instructions that worked for me (no messing around with permissions is necessary):
https://stackoverflow.com/questions/52113738/starting-ssh-agent-on-windows-10-fails-unable-to-start-ssh-agent-service-erro

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
Also: Take a quick look at ticket #3970 **OpenSSH installation** where I posted my install procedure, running on Windows 10 Home x64.
(Your problem might very well be caused by software details not available in Win10Home -- "your mileage may vary")

**Comment by konstruktoid** [comment]
I believe this is a support question, and a stale issue, and can be closed.

**Comment by illfated** [comment]
#please-close
