### ISSUE TITLE
TLS 1.3

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/windowsserverdocs#4030]
What is the Reg key for TLS 1.3? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security-tls-ssl**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by lennybacon** [comment]
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client]
"DisabledByDefault"=dword:00000000
"Enabled"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server]
"DisabledByDefault"=dword:00000000
"Enabled"=dword:00000001
```


https://stackoverflow.com/questions/56072561/how-to-enable-tls-1-3-in-windows-10

**Comment by illfated** [comment]
@lennybacon : Thank you for providing a good answer.

@Garthmj : I hope your question was answered, so I will ask for this ticket to be closed.

Please also note the following, as it is unpredictable when outside users will find their time to answer questions in this repository.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
