### ISSUE TITLE
-1 for TLS 1.2

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/windowsserverdocs#4032]
I'm seeing that -1 is listed for a high number of clients under TLS 1.2 Client Enabled setting. Am I right in assuming that thi should be NULL or 0 and is somehow gotten missed confirmed during the Windows Setup? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security-tls-ssl**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
Please note the following:

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by IngridAtMicrosoft** [comment]
@Garthmj GitHub issues for this repo are for reporting problems with documentation.  Please open a support ticket or post your question at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
