### ISSUE TITLE
Please update page title, this is not a insider preview anymore 

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/windowsserverdocs#4049]
Please update page title, this is not a insider preview anymore 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac2c66a-9734-5680-04e0-1aed2df2eb0e
* Version Independent ID: 3406e752-cef6-d640-db14-9836278f8ec3
* Content: [Insider Preview for HPN features in Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/networking/technologies/hpn/hpn-insider-preview)
* Content Source: [WindowsServerDocs/networking/technologies/hpn/hpn-insider-preview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/hpn/hpn-insider-preview.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by illfated** [comment]
Fair enough. Windows Server 2019 should be well out of its "Insider Preview" phase.
Do you have a suggestion for the page title?

I tried to synthesize a title based on the 2 sections in the page, but I am drawing the short straw here. I presume that is because I am not familiar enough with the content topics.

- [**Dynamic vRSS and VMMQ**](https://docs.microsoft.com/en-us/windows-server/networking/technologies/hpn/hpn-insider-preview#dynamic-vrss-and-vmmq)
- [**Receive Segment Coalescing (RSC) in the vSwitch**](https://docs.microsoft.com/en-us/windows-server/networking/technologies/hpn/hpn-insider-preview#receive-segment-coalescing-rsc-in-the-vswitch)

**Comment by carlosmayol** [comment]
Yes:  New HPN Features in WS2019.

Thanks

Carlos Mayol Berral  | Sr. PFE | Infrastructure, Virtualization, Azure

**Comment by carlosmayol** [comment]
New HPN Features in WS2019 should made it.

**Comment by shortpatti** [comment]
Can a Microsoft employee please remove my name from these topics?  I signed the divorce papers in Nov 2018.  If this topic is not updated or supported anymore, then MICROSOFT should show some courtesy and tell their customers.

**Comment by illfated** [comment]
@JasonGerend & @eross-msft : I am aware that your team has got more than enough work as it is, but would it be of any help if I open a PR to suggest a page title change?

Also, about the outdated presence of the name "pashort" or "shortpatti" in quite a few documents, is this something you want to handle yourself, or would you like a separate PR to have that name removed or replaced with an up-to-date name or generic term as a functional replacement?

**Comment by eross-msft** [comment]
Thank you for all of your input. @carlosmayol you can actually make this change yourself, using the edit feature in the https://github.com/MicrosoftDocs/windowsserverdocs-pr repo. 
@illfated @shortpatti  While we appreciate the fact that the author is incorrect, due to our extremely limited resources, there is no one to change the author value to. And unfortunately, an article can't be without an author. You'll find many articles throughout the library that have older authors that have either moved on or are no longer with Microsoft...it's really the nature of having newer and older content in the library and archive.

**Comment by illfated** [comment]
Fair enough, thank you for the detailed feedback. 👍

**Comment by carlosmayol** [comment]
Cool, I always refrain of making changes by myself, but let role that Growth Mindset!
Thanks!

**Comment by eross-msft** [comment]
@carlosmayol  NEVER feel like you can't make changes yourself :) We actually hope for your help! There are literally only 2 Windows Server writers and we can't keep up with new content, let alone older content updates. All of your assistance is greatly appreciated!

**Comment by illfated** [comment]
(Ref. PR #4060 )

**Comment by illfated** [comment]
Based on the successful merge of PR #4060 it should be OK to close this issue ticket. The merged content is already present in the docs.microsoft.com (https://docs.microsoft.com/en-us/windows-server/networking/technologies/hpn/hpn-insider-preview) page. What remains is to look at how the URL and its TOC index title appears, which also needs editing. Changes in those links will most likely lead to this ticket not having the correct URL for its related pages, unless the pages use any form of automated dynamic methods to keep the links updated.

**Comment by illfated** [comment]
By the way, the same goes for the page **High-performance networking (HPN)** (https://docs.microsoft.com/en-us/windows-server/networking/technologies/hpn/hpn-top) pointing to this updated page, so maybe it is better to close this ticket and open a new one from the aforementioned page "High-performance networking (HPN)".

**Comment by shortpatti** [comment]
Can a Microsoft employee PLEASE remove my name from all the documents I used to own and manage? I signed the divorce papers from Microsoft in Nov 2018 and would LOVE IT if a Microsoft writer would take ownership of the content. I don't work there, and don't get paid to correct these documents anymore. I feel sorry for the IT Professionals using these products because there's no one at Microsoft who really cares about the IT Pro :( It's obvious because these documents haven't been maintained for over 18 months.

PLEASE PLEASE PLEASE someone remove my name from these documents!!!!! I can unsubscribe until my face turns blue, but that's 100s if not 1000s of documents.

**Comment by illfated** [comment]
@shortpatti : Your request is very understandable, but I would also like to remind you of the reply from Elizabeth Ross the other day, informing us that this is difficult, given the circumstances and not enough people to take ownership of those pages. I wish you the best of luck, though, because it would seem a better idea to hide the author name from the public.

(I also presume you get "pinged" each time a new issue ticket is opened from one of the pages where you are listed as author, which makes it less than tidy to work elsewhere on GitHub.)

**Comment by illfated** [comment]
@eross-msft : I wonder if it could be remedied by disabling the inclusion of the document author in the ticket template. Is this something you could ask the web repository ticket engineers about?

**Comment by shortpatti** [comment]
I understand that, but since she's responding to these she CAN put here damn name on them since I no longer work there.  Seriously!  It's not that hard to assign an owner, even a temporary owner.  I am NOT responsible for these topics; I no longer work there!!!   I just want my damn name removed from these topics because I don't work there and haven't for 18 MONTHS!

**Comment by eross-msft** [comment]
@shortpatti  I will change the ones I can to my name. The rest there is absolutely nothing I can do about.

**Comment by illfated** [comment]
#please-close
