### ISSUE TITLE
Sentence fragment in section: Parameterized policy template vs non-parameterized policy template

### ISSUE THREAD

**Issue by PishPoshery** [MicrosoftDocs/windowsserverdocs#4054]
First line reads: 
Access control policies can be                      &lt;--- this appears to be sentence fragment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f036d934-8b6b-b5a4-113b-518c684d357e
* Version Independent ID: eddd6501-43c4-2338-ab48-1b687833caee
* Content: [Access Control Policies in AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/access-control-policies-in-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Access-Control-Policies-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Access-Control-Policies-in-AD-FS.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Very much so. The rest of the sentence or paragraph is missing. Unfortunately, the rest of the sentence or paragraph has been missing ever since this page got imported to GitHub (around June 17, 2016), so I assume the rest of the sentence needs to be filled in by someone with 5 years of experience in the topic of this document.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 4039 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
