### ISSUE TITLE
No support for DHCP Option 118

### ISSUE THREAD

**Issue by tdimli** [MicrosoftDocs/windowsserverdocs#4066]
This document contains inaccurate information re DHCP Option 118: There is currently no support for DHCP Option 118.

Please see where we have updated another document for the same wrong information:
https://github.com/MicrosoftDocs/windowsserverdocs/issues/1012

Please remove the text that incorrectly states Option 118 is supported.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4c32afd-be46-d236-c2ac-81ef2fb49fc0
* Version Independent ID: 32d18088-3ff9-7348-9f39-a11aabaa6bf9
* Content: [What's New in DHCP](https://docs.microsoft.com/en-us/windows-server/networking/technologies/dhcp/what-s-new-in-dhcp#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/dhcp/What-s-New-in-DHCP.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/dhcp/What-s-New-in-DHCP.md)
* Product: **windows-server**
* Technology: **networking-dhcp**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Can a Microsoft employee PLEASE remove my name from all the documents I used to own and manage?  I signed the divorce papers from Microsoft in Nov 2018 and would LOVE IT if a Microsoft writer would take ownership of the content.  I don't work there, and don't get paid to correct these documents anymore.  I feel sorry for the IT Professionals using these products because there's no one at Microsoft who really cares about the IT Pro :(  It's obvious because these documents haven't been maintained for over 18 months.

PLEASE PLEASE PLEASE someone remove my name from these documents!!!!!

**Comment by tdimli** [comment]
Resolved with a document update (#4382).
