### ISSUE TITLE
Supported OSs for member servers

### ISSUE THREAD

**Issue by LeonardoFelippine** [MicrosoftDocs/windowsserverdocs#4098]
Hello.

This documentation for Windows Server 2012/R2 contains a section called "Windows client and Windows Server operating systems that are supported to join Windows Server domains", which is lacking on this documentation. I believe this information to be very valuable when planning the upgrade of a domain. Could it be updated to the 2016 version and added?
If not, could you please list which versions are supported (specifically Windows Server 2003)?

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 666fb8cb-b1e5-c7b6-6326-cd172a2bf4b2
* Version Independent ID: 3d899ddb-c33f-28e6-3154-af039e28521a
* Content: [Upgrade Domain Controllers to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
I seriously doubt any Windows Server version older than 2008 will be able to join a Windows Server 2016 AD domain, mostly because Windows Server 2003 is unable to run SMBv2, but also because you run a high risk of compatibility issues with versions older than Windows 7 & Windows Server 2008 R2. Windows Server 2003 reached its End Of Life date on July 14, 2015, and that was for the 2003 editions with the longest support lifecycle ( https://support.microsoft.com/en-us/lifecycle/search/1163 ).
- https://social.technet.microsoft.com/Forums/en-US/07f89927-e445-42fe-b9ea-d0684ff33fb4/windows-2000-member-server-in-windows-2016-domain?forum=ws2016
- https://docs.microsoft.com/nb-no/archive/blogs/josebda/the-deprecation-of-smb1-you-should-be-planning-to-get-rid-of-this-old-smb-dialect

You also run the risk of many security issues and exploits, especially if you plan to configure a Windows Server 2016 to be able to talk to Windows Server 2003 and Windows Server 2003 to be able to run network traffic back. Supported operating systems must be kept up to date to be supported, which in many cases will cause them to drop support for insecure advanced network communication with unsupported end-of-life operating systems.

**Comment by IngridAtMicrosoft** [comment]
Question was answered. Closing.
