### ISSUE TITLE
Microsoft Remote Desktop (MRD) 10.3.8 - MacOS - Bulk Import

### ISSUE THREAD

**Issue by PREngineer** [MicrosoftDocs/windowsserverdocs#4100]
I manage a set of 800 VMs and I can't find a way to import an XML or RDG file with multiple VMs.

A developer mentioned (app feedback in App Store) using a script to import them but I can't find any information on how to build said script and run it for this application.

Can this information be added to the documentation?

**Comment by Xelu86** [comment]
Hey PREngineer,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you're describing a potential issue with a Windows product or service, rather than the documentation itself.

GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. We offer other channels for engaging with us, whether you have a support question, product feedback, or other feedback. 

We cannot assist with the following as it's outside our scope of work:

- Support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, please use one or more of the following:

 - On a Windows OS, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
