### ISSUE TITLE
Prior Feedback not addressed

### ISSUE THREAD

**Issue by V3ertigo83** [MicrosoftDocs/windowsserverdocs#4108]
Hi, I have prior feedback on this page, asking for specifics around the claim expression and what the string limit is, that feedback seems to be going unaddressed and has disappeared from this page. Please advise.
https://github.com/MicrosoftDocs/windowsserverdocs/issues/3567#issue-529544875

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd2b36f1-21ff-3e18-6ed3-0a9e1ac3192e
* Version Independent ID: 6ace3db6-8f8d-d080-82d1-d5c75acd79ad
* Content: [Access Control Policies in AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/access-control-policies-w2k12)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Access-Control-Policies-W2K12.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Access-Control-Policies-W2K12.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by V3ertigo83** [comment]
Any update here?

**Comment by illfated** [comment]
@eross-msft : Do you think this ticket or the 6 month old referenced issue could get some form of attention from the team? (I don't know yet if it falls within the scope of improving the docs or if it should be directed towards any specific support tenant or instance, so I rely on your expertise for a proper reply and feedback.)

**Comment by eross-msft** [comment]
@illfated  Unfortunately, the Windows Server writing team is extremely small and we don't have the bandwidth to address the numerous and ongoing GitHub issues. We're working on trying to figure out a plan for these, but in the interim we can only keep up with the open pull requests. I should say though, your help has been invaluable in getting the issues addressed that we have.
Beyond that, we try to do what we can to help, but like in these situations, there is no one active beyond a writing contact. In many cases, the product group no longer supports the content, or the program manager has moved into another role, group, or company. While the writing contact is helpful, if there's no one for them to ask, they don't typically know the info themselves.

**Comment by illfated** [comment]
(just to make this comment available in the document feedback section for this ticket, since the other ticket disappeared from the feedback section)
*
@V3ertigo83 : I can only offer my sympathy with your troubles concerning this topic. Unfortunately, I don't have any working experience from a scenario remotely like yours. I also notice that this issue ticket seems to have lost its reference appearance in the feedback section of the linked page, but I don't know why or how that happened. That being said, I would like to inform you that this repository is managed by a very small team, where the members currently don't have more capacity than to follow up direct suggestions for how the articles can be improved, provided that the community provides the content or specific written changes, either in the ticket itself or in Pull Requests containing the recommended changes. It is currently not possible to follow up support related questions or any requests to make changes, unless the requests contain the exact phrasing needed to perform the requested change. See also the feedback comment from one of the team members above.
*
That being said, I would like to recommend trying other venues of support, like the Microsoft TechNet Forums (https://social.technet.microsoft.com/Forums/), the Microsoft Developer Network Forums (https://social.msdn.microsoft.com/Forums/). or the Microsoft Tech Community Windows Server forum (https://techcommunity.microsoft.com/t5/windows-server/ct-p/Windows-Server) to ask for the same advice as you did above. You may even want to contact your local Microsoft Support tenant to ask if they will be able to answer your question.
*
We would also like to hear back from you regarding any helpful information related to this issue you are able to find, so if you can post any findings related to this issue topic here in this ticket, we appreciate the opportunity that would give us to find ways to improve the related articles, based on your findings and feedback.
*
Also, if you do have any questions regarding how to submit information you would like to see added to the current documentation, feel free to post more comments regarding this.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @V3ertigo83,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing a potential solution to an issue with the product compared to an issue with the documentation. GitHub isn't quite the right location if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, please let us know.

To get assistance or support for your product issue, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
