### ISSUE TITLE
Incorrect registry path in footnote

### ISSUE THREAD

**Issue by PHactotum** [MicrosoftDocs/windowsserverdocs#4123]
In this section https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#using-group-policy-to-configure-the-windows-time-service, the foot note 2, incorrectly list the registry path as:
`2 Subkey: HKLM\SOFTWARE\Policies\Microsoft\Windows`
This should be:
`2 Subkey: HKLM\SOFTWARE\Policies\Microsoft`

This path is correctly listed elsewhere in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d09b16e-4bbb-91fa-3d84-e7623ec4dc07
* Version Independent ID: b6eadad5-0167-34b6-ed3a-16fa7ee83c60
* Content: [Windows Time service tools and settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **lizross**

**Comment by Teresa-Motiv** [comment]
Creating a request/PR to fix this.

**Comment by RAJU2529** [comment]
@Teresa-Motiv ,. Issue is conformed checked in windows 10.

**Comment by illfated** [comment]
@Teresa-Motiv : May I ask if you have already created the PR, or would you like a PR from one of us other users?

**Comment by Teresa-Motiv** [comment]
@illfated The PR has been created and merged. It has a link to this issue--just waiting for the fix to show up on the live page.

**Comment by Teresa-Motiv** [comment]
The change is live.

**Comment by illfated** [comment]
Thank you for your useful feedback, much obliged.

Just to add some information about the missing cross-repository information: https://github.com/MicrosoftDocs/windowsserverdocs-pr/ is a private repository and only accessible to its members (mainly Microsoft employees). Since we ordinary users outside of the Microsoft organization don't have access to that repository, we do not see any linked information from there in any of the public repositories like https://github.com/MicrosoftDocs/windowsserverdocs or https://github.com/MicrosoftDocs/windows-itpro-docs/. We only notice updates within the public repositories, like when the master or public branch is updated with a new commit.

By the way, thank you for having faith in me being part of the organization, which I am not. I am merely very interested in helping out by sharing correct information, based on my experience with GitHub and some of the Microsoft OS & software environments (in addition to being very zealous about using correct grammar).

From https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#using-group-policy-to-configure-the-windows-time-service :
***
> <sup>1</sup> Category path: **Computer Configuration\Administrative Templates\System\Windows Time Service**
> <sup>2</sup> Subkey: **HKLM\SOFTWARE\Policies\Microsoft**
> <sup>3</sup> Subkey: **HKLM\SYSTEM\CurrentControlSet\Services**

***
cc: @eross-msft

**Comment by illfated** [comment]
#please-close
