### ISSUE TITLE
Question about the way web applications are created

### ISSUE THREAD

**Issue by ps-weber** [MicrosoftDocs/windowsserverdocs#4127]
Why is a "Native Application" created when "Web Application" is selected. Typically, a SPA consists of a Web Application that runs in the browser and a Web API. Shouldn't the WebAPI in the sample be created as a Web API and have its own client id? Is the way the SPA configured here compatible to an app running Azure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 564391c0-ad11-762f-41c9-cc898c7b3a46
* Version Independent ID: 04020c6c-d236-3dcb-5be2-f444d05d214e
* Content: [Build a single page web application using OAuth and ADAL.JS with AD FS 2016 or later](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/single-page-application-with-ad-fs#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md)
* Product: **windows-server**
* Technology: **active-directory-federation-services**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
