### ISSUE TITLE
Support for Windows Server 2003 as Source

### ISSUE THREAD

**Issue by rubenz91** [MicrosoftDocs/windowsserverdocs#4129]
Hello, 

I was planning a migration of a file server in 2003 with 7 TB to Azure Files, so as its not natively support for this windows version I came down to this option to improve experience vs Robocopy, but digging around before starting the journey I had found this experience. https://techcommunity.microsoft.com/t5/windows-server-for-it-pro/migrating-from-server-2003-to-server-2019-using-storage/m-p/648669# 

So I want to know if its really supported Windows Server 2003 as a source or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa81041-3a2a-961a-05d5-4a845cc74ae2
* Version Independent ID: fadf165a-5c81-0102-e096-7f527483313b
* Content: [Migrate a file server by using Storage Migration Service](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/migrate-data?source=docs#feedback)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/migrate-data.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/migrate-data.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
I hope you may get an answer sooner or later from the Windows Server team here on MicrosoftDocs. In the meanwhile, I can only offer my thoughts on this matter, based on what I read in your linked experience page discussion.

To me, it seems necessary to have all features and server roles available on the Windows Server 2003 computer, so you can easily install and configure IIS to support SMS. If your 2003 server is only configured as a basic or SMB server, you might face the same challenges as the user posting on the page you linked. I don't know if the 2003 server should be able to join a Windows Server 2019 domain or the 2019 server should be able to join the 2003 domain, but that should be documented properly in the procedures.

Unfortunately, I am unable to help you any further, as I am only a general IT technician with simple experience from migrating 2003 SMB server to 2008r2 before migrating to 2012r2 (many years ago).

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey rubenz91,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with a Windows product or service, rather than the documentation itself.

GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. We offer other channels for engaging with us, whether you have a support question, product feedback, or other feedback. 

We cannot assist with the following as it's outside our scope of work:

- Support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, please use one or more of the following:

 - On a Windows OS, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
