### ISSUE TITLE
Some mistakes in bitsadmin /*

### ISSUE THREAD

**Issue by WiVi71** [MicrosoftDocs/windowsserverdocs#4137]
## Broken table
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-setnotifyflags#remarks
```
|-----|-----| |1|Generate an event when all files in the job have been transferred.| |2|Generate an event when an error occurs.| |4|Disable notifications.|
```
And also value 3 is missing

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-getnotifyflags#remarks
```
|-----|-----| |0x001|Generate an event when all files in the job have been transferred.| |0x002|Generate an event when an error occurs.| |0x004|Disable notifications.| |0x008|Generate an event when the job is modified or transfer progress is made.|
```
## Double commands
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-setclientcertificatebyname#BKMK_examples
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-setclientcertificatebyid#BKMK_examples

```
C:\>bitsadmin Bitsadmin /SetClientCertificateByName myJob 1 MY myCertificate 
```

## Wrong examples
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-setcredentials#BKMK_examples

C:\>bitsadmin /**Remove**Credentials myDownloadJob SERVER BASIC Edward Password20

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-sethttpmethod#syntax

bitsadmin /**Get**HttpMethod <Job> <HTTPMethod>

## Unexpected space
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-setpeercachingflags#BKMK_examples
```
C:\>bitsadmin /_SetPeerCachingFlags myJob 1 
```
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-setcustomheaders#BKMK_examples
```
C:\>bitsadmin /_SetCustomHeaders myDownloadJob "Accept-encoding:deflate/gzip"
```
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-getclientcertificate#BKMK_examples
```
C:\>bitsadmin /_GetClientCertificate myDownloadJob
```

**Comment by illfated** [comment]
Please see my PR #4138 for corrections to those pages. Feel free to comment as well.

**Comment by illfated** [comment]
@WiVi71 : The Windows Server Docs team has started some planned work to make an overall cleanup on all the neighbouring pages, including the pages you have listed. My PR got closed to avoid merge conflicts due to this internal work process. Even so, I presume this ticket may stay open in the meanwhile. The internal work may take some time, so please be patient.

**Comment by illfated** [comment]
The issues seem to have been fixed in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/ad297d36711efc8984d6e6daac7b62fb71d49ab9 (direct file link https://github.com/MicrosoftDocs/windowsserverdocs/commit/ad297d36711efc8984d6e6daac7b62fb71d49ab9#diff-7e2ab1efb4bd8b1b5e4b30617757e058c954c9f5b075997de6b492665ad355b4).

**Comment by illfated** [comment]
Anyway, the page looks like it is correct now. If it is not, please open a new ticket from the link named **[ This page ]** at the bottom of the document page itself.
