### ISSUE TITLE
Client source ports?

### ISSUE THREAD

**Issue by lukpac** [MicrosoftDocs/windowsserverdocs#4145]
It is noted that Windows Time uses "UDP port 123 for all time synchronization communication". Is this meant to denote both source and destination ports? I ask for two reasons: 1) that isn't entirely correct and 2) the use of port 123 as the source port for client requests is unnecessary and causes issues with some ISPs. Specifically:

1) While running w32tm /resync results in a request being made with a source port of 123, running w32tm /stripchart results in a request being made with a random high numbered source port.

2) Some ISPs (notably AT&T) perform blocking on inbound port 123, which means that Windows cannot synchronize time when using Internet based time servers.

NTP only requires the use of 123 as the source port when operating in symmetric modes (server to server). Requests from Windows desktops are made in client mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d09b16e-4bbb-91fa-3d84-e7623ec4dc07
* Version Independent ID: b6eadad5-0167-34b6-ed3a-16fa7ee83c60
* Content: [Windows Time service tools and settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#feedback)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **lizross**

**Comment by Teresa-Motiv** [comment]
This issue should be reassigned--the article is currently being rewritten by another team, and that may resolve this issue.
PR for rewrite is MicrosoftDocs/windowsserverdocs-pr#1751

**Comment by lukpac** [comment]
@Teresa-Motiv The link you posted doesn't seem to be correct.

**Comment by Teresa-Motiv** [comment]
It works for me...maybe a permissions issue? That's the private repo. This issue now shows up as linked on that PR, so they're aware of it.

**Comment by illfated** [comment]
@lukpac : https://github.com/MicrosoftDocs/windowsserverdocs-pr/ repository is only available to the MS Docs team members, managers and owners. That part of this MS Docs repository (I don't remember if it counts as a separate repository) is not available to outsiders, regular users and contributors (like you and me) without MS Docs memberships.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey lukpac,

Thanks again for contacting Microsoft. We value your feedback. 

The W32Time doc is going through several updates, including the 4 sections surrounding the registry entries, and verbiage for more clarity. We have also included another link from the IETF for users who want a deeper understanding of the NTP - https://www.rfc-editor.org/rfc/rfc5905. We hope that this update addresses feedback from our users.

Concerning the ISPs, AT&T specifically, this is completely outside the control of Microsoft if another company decides to block the mentioned port. Seeing how this ISP entity views this port being opened as a potential security issue (DoS attacks), they have the rights to promote security for their customers as their provider. This also serves for any other ISP blocking the same port.

In AT&Ts forums, I did see this by JefferMC:

> - See https://about.att.com/sites/broadband/network regarding AT&T's traffic management policies, including traffic they drop based on ports and what direction. UDP 123 is source port blocked.  The only way around it I know of is using a client that uses an ephemeral port (instead of 123) or having the source port re-written by PAT. This is true of residential and "small-business fiber" that is using the same infrastructure as residential.
>
> - AT&T enforces a SOURCE PORT block of 123 from sources inside its network. It allows SOURCE PORT of 123 into the network from its edge. So if your NTP client appears to the AT&T Network as something other than 123, then it can communicate to an NTP server outside of AT&T's network as long as its port got PATted. Mine is apparently getting PATted by my router behind the AT&T Gateway.
>
> - https://forums.att.com/conversations/att-fiber-equipment/how-do-i-get-udp-port-123-unblocked-for-static-ip-addresses/637bffb4de539d5923202965
> - https://forums.att.com/conversations/att-internet-equipment/options-to-get-ntp-time-since-att-blocks-port-123/600aebf9127141623b1faf67?page=1
> - https://forums.att.com/conversations/att-internet-equipment/options-to-get-ntp-time-since-att-blocks-port-123/600aebf9127141623b1faf67?page=2

We cannot assist with issues outside of our scope and recommend that those customers open a case with their ISP to see what can be done in order to potentially mitigate issues, if at all possible.

Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
