### ISSUE TITLE
Storage Migration re-sync / Transfer issue

### ISSUE THREAD

**Issue by SDSnider** [MicrosoftDocs/windowsserverdocs#4159]
I am having an issue with the Transfer step of Storage Migration.  Specifically, I am trying to do a re-sync, but when I attempt to re-start the Transfer, I get a message that: "You're about to transfer everything from scratch.  This will start the transfer over, backing up folders on a destination that have the same name as folders on the source.
![Transfer - Transfer - Job detail](https://user-images.githubusercontent.com/63415201/78916729-f046b600-7a5b-11ea-93ca-ad32ad0727be.png)

I don't have the space to risk duplicating everything, so I am unwilling to test this while just hoping that it will actually do a diff and update.

How do I just update changed files?

**Comment by tdwhite93** [comment]
I seem to be having the same problem as @SDSnider. Unless there are suggestions on what I can do to resolve I plan on allowing enough time to transfer all data during the cutover window if needed so that I can still proceed with an ongoing server migration project. This is using the latest version of the Storage Migration extension in Windows Admin Center.

**Comment by illfated** [comment]
Please use real support instances like Microsoft Support or Microsoft Support forums, depending on what your license covers in terms of support assistance.

**Comment by illfated** [comment]
Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
