### ISSUE TITLE
TLS 1.2 

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/windowsserverdocs#4160]
I'm noticing on at least Windows 2019 servers, TLS 1.2\Server has Enabled set to 0xffffffff.  Any difference between 0x00000001 and 0xffffffff.  I'm examining the steps for disabled TLS 1.0 and 1.1 for Skype for Business as it might apply to SFB 2019 and in the MS released Reg files, they are setting 0x00000001, curious if there is a difference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security-tls-ssl**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by CodyMathis123** [comment]
It is my understanding that any non-zero value is going to be interpreted as turning that setting 'on'

**Comment by Garthmj** [comment]
That is not my understanding nor what is written above.  Only 1 turns on the setting, 0 turns off the  setting and anything else is unknown. It would be great to have MS officially reply to these threads.

**Comment by illfated** [comment]
Please note the following:

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by IngridAtMicrosoft** [comment]
Hello @Korbyn72 Please post your question at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
