### ISSUE TITLE
Remote mouse movement is not forwarded to local machine

### ISSUE THREAD

**Issue by Xavientois** [MicrosoftDocs/windowsserverdocs#4185]
I am working over remote desktop on a program which restricts the movement of the mouse when the focus is on the program's window. Unfortunately, the operations on the cursor that occur on my remote machine are not forwarded to my local machine, so it is difficult to develop this feature.

I am connecting over Microsoft Remote Desktop from a MacBook Air running MacOS Mojave 10.14.2 to connect to an Intel machine running Windows 10 Enterprise Version 1909, build 18363.720.

Is there a way to enable forwarding of mouse operations to the local machine?

**Comment by illfated** [comment]
Looks like you should be asking developers instead of documentation writers, because it is unclear where the restriction takes place.

Try asking in https://social.msdn.microsoft.com/Forums/ to get a quicker response. Asking here about things that are not related to documentation improvement may take weeks, maybe months to get answers.

(Please note that the issue tracker is intended for reporting errors in the documentation pages or suggesting improvements to those pages.

**Comment by Xavientois** [comment]
Thanks!

**Comment by Xavientois** [comment]
https://social.msdn.microsoft.com/Forums/en-US/c71a7f9f-e56f-4d98-acba-64317333d86c/remote-mouse-movement-is-not-forwarded-to-local-machine?forum=windowsserversolutionssdk
