### ISSUE TITLE
set /a hrs=08 - 8 will set an errorlevel (correctly) but set /a hrs=8 - 8 will *not* so you must clear %errorlevel% before

### ISSUE THREAD

**Issue by markyoung2u** [MicrosoftDocs/windowsserverdocs#4194]
If %errorlevel% is non-zero you cannot check the return status of set /a because it does not set the errorlevel in all cases.
This requires you to clear the errorlevel before testing the set /a cmd.
@echo off
:goto start
:reset_err
exit \b 0
:start
:: Force errorlevel 1
ping -n 1 10.8.1.1
set /a hrs=8 - 8
if errorlevel 1 echo FAILED1:  set /a hrs=8 - 8
ping -n 1 10.8.1.1
call :reset_err
set /a hrs=8 - 8
if errorlevel 1 echo FAILED2:  set /a hrs=8 - 8
goto :eof

Output: 
FAILED1:  set /a hrs=8 - 8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beaee6aa-060a-58d2-a474-b47b3ac89f9e
* Version Independent ID: bae22319-b13a-63f8-6da4-6411fece9f91
* Content: [set](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1)
* Content Source: [WindowsServerDocs/administration/windows-commands/set_1.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/set_1.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by v-thepet** [comment]
Hello @markyoung2u, 

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused. 

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support. 

#please-close
