### ISSUE TITLE
Windows Admin Center can't find bios serial number

### ISSUE THREAD

**Issue by oumolayna** [MicrosoftDocs/windowsserverdocs#4205]
hello , well to begin with ... this is an awesome product ... but i can't find the bios serial number in the overview nor the monitor serialnumber ... i know i can get those with powershell ... but i think this should be displayed right away ... also i suggest adding a column " Heartbeat " to show that the device is currently online or not ... and why not adding bulk management such as ... if i want to get the serialnumber of 10 servers ... i dont want to go to every server and get the serialnumber individually ... i want to be able to get it for all those 10 servers ...
thank you.

**Comment by Xelu86** [comment]
Hey oumolayna,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described a potential issue with a Windows product or service, rather than the documentation itself.

GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. We offer other channels for engaging with us, whether you have a support question, product feedback, or other feedback. 

We cannot assist with the following as it's outside our scope of work:

- Support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, please use one or more of the following:

 - On a Windows OS, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
