### ISSUE TITLE
Reboot required

### ISSUE THREAD

**Issue by sovamind** [MicrosoftDocs/windowsserverdocs#4207]
It would be nice to know if any of these settings required a reboot or restarting of a service to take effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10426ae7-c178-a8f9-7446-7a53b3774e56
* Version Independent ID: 712778c8-c86d-ee00-0302-6f3ce2942fb4
* Content: [Performance tuning for file servers](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/file-server/)
* Content Source: [WindowsServerDocs/administration/performance-tuning/role/file-server/index.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/performance-tuning/role/file-server/index.md)
* Product: **windows-server**
* Technology: **performance-tuning-guide**
* GitHub Login: @phstee
* Microsoft Alias: **nedpyle; danlo; dkruse; v-tea**

**Comment by illfated** [comment]
Seeing that all the 18 Parameters settings belong under the same main key `HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters\` and knowing that all of these affect the service named Workstation (LanmanWorkstation), they need at least to have the Workstation service restarted. In most cases, this also requires that you restart any services depending on the LanmanWorkstation service. Even so, there may be cases where restarting those services is not enough, since many of those settings affect general core network traffic and could affect how the client and server communicates.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. When it comes to editing the registry, it really depends on the changes being made. There are instances where once you modify the registry, the effects are immediate. 

In other instances, the following may be necessary for changes to take effect:
- Restarting the service running (and dependencies) if tied to those registry edits
- Opening Task Manager and restarting Windows Explorer
- Clicking on Start > Sign out > Log in again

Modifying the registry and looking for immediate changes may require trial and error whether a complete restart is necessary. We will now be closing this. Thank you and have a most pleasant day. #please-close
