### ISSUE TITLE
server 

### ISSUE THREAD

**Issue by Anuya1** [MicrosoftDocs/windowsserverdocs#4217]
i have tried it in the dos prompt. thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82772fa0-1642-4481-dff0-ebf83270db4d
* Version Independent ID: e5d451c4-2ee0-9461-c19b-19d0cb199b42
* Content: [Upgrade Windows Server 2012 R2 to Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2012r2-to-2019)
* Content Source: [WindowsServerDocs/upgrade/upgrade-2012r2-to-2019.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/upgrade-2012r2-to-2019.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by illfated** [comment]
Good to hear. Thank you for the nice comment.

**Comment by illfated** [comment]
#please-close

**Comment by Anuya1** [comment]
Who's that?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Anuya1** [comment]
who is it?

Sent from Windows Mail

**Comment by illfated** [comment]
Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

In case you need to ask for help, try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
