### ISSUE TITLE
MT option in newer versions

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/windowsserverdocs#4242]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/windowsserverdocs.de-de/issues/19

@Mac-Chiato commented 10 hours ago
Its not clear if the option /MT is available in newer versions than Windows 7 / Windows Server 2008R2
Newer versions should also be described here, as they are supported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Plusader** [comment]
I've been using robocopy since a couple of days now to copy data from my main storage to an external drive.
I have tested the /MT option first with a test-structure of empty folders and textfiles.
The task was finished immediately.
Then I have then copied a 30 GB folder with the /mt option, which took about 17 minutes(1,764 GB/minute).
The display of the percentage copied was shown in integers and progressed comparatively slowly, which caught my attention.
I have then copied a 53,2 GB folder without the /mt option, which took about 7 minutes(7,6 GB/minute).
The display of the percentage copied was shown in floating point numbers, which is updated with every first decimal place already copied.

I have run more tasks to provide for more data.
with /mt
11.195 GB in 7:53 minutes results in 1,42 GB/minute.
without/mt
50.662 GB in 4:39 minutes results in 10,89 GB/minute.


**Then I have copied the same folder using both methods(first without then with /mt):
with /mt
4.929 GB in 0:21 minutes results in 14,08 GB/minute.
without /mt
4.929 GB in 0:27 minutes results in 10,95 GB/minute.**

I have used the following commands for those operations:
robocopy "source-folder" "target-folder" /e /Move [/mt]

Since the comparison is an unexpected result I have run a further test of copying an identical folder(this time first with then without /mt).
with /mt
3.538 GB in 1:05 minutes results in 3,26 GB/minute.
without /mt
3.538 GB in 0:19 minutes results in 11,17 GB/minute.

I'm running a AMD Ryzen2700X. BIOS, Drivers, System is udpated.

**I copied the folder which was copied faster with /mt enabled again.
with /mt
4.929 GB in 0:23 minutes results in 12,85 GB/minute.
without /mt
first run
4.929 GB in 0:42 minutes results in 7,04 GB/minute.
second run
4.929 GB in 0:43 minutes results in 6,87 GB/minute.**

Each time I compared the copy times using the same folder I've been moving the already copied folder from the target back to the source using Ctrl+X and Ctrl+V (Cut&Paste), which was considerably slower.

**Comment by Plusader** [comment]
Adding some more results, since I have to copy the data anyway:
with /mt
x GB in x:xx minutes results in x GB/minute.
x GB in x:xx minutes results in x GB/minute.
x GB in x:xx minutes results in x GB/minute.

without /mt
26.676 GB in 2:35 minutes results in 10,32 GB/minute.
x GB in x:xx minutes results in x GB/minute.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @steved0x,

Thanks again for contacting Microsoft. We value your feedback.

From my understanding, the **/mt** parameter in robocopy should function in all versions of Windows starting from Windows 7 and Windows Server 2008 R2 up to Windows 11 and Windows Server 2022.

Will add a note under the "copy options" section for this distinction. Changes will be live after the next business day. Thank you and have a most pleasant day. 

#please-close

**Comment by Xelu86** [comment]
Apologies @steved0x, I meant to tag @mac-chiato.
