### ISSUE TITLE
Some of the links in the document are not working and might be outdated information.

### ISSUE THREAD

**Issue by Azhar001** [MicrosoftDocs/windowsserverdocs#4252]
Some links like Passport for work section is redirecting to WHB
and MDM enrollment link is now working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74d09c81-d205-dbd0-ea6a-aaf469eadf5c
* Version Independent ID: 458db848-1b30-1115-8814-3a639a57c70b
* Content: [Configure Device-based Conditional Access on-Premises](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-device-based-conditional-access-on-premises#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-Device-Based-Conditional-Access-on-Premises.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-Device-Based-Conditional-Access-on-Premises.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
interesting, I have not seen this link behaviour before (although I have not been through every topic in the documentation, far from it).
- https://azure.microsoft.com/documentation/articles/active-directory-azureadjoin-passport-deployment/ redirects to
- https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-identity-verification

This link, on the other hand, seems to need an update by finding the new page for this material:
- https://docs.microsoft.com/en-us/archive/blogs/enterprisemobility2015/08/14/windows-10-azure-ad-and-microsoft-intune-automatic-mdm-enrollment-powered-by-the-cloud

Any chance that the following page contains similar material, or pointers to a replacement page?
- https://docs.microsoft.com/en-us/windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal

**Comment by illfated** [comment]
@Azhar001 : Please note the following:
- https://docs.microsoft.com/en-us/windows/client-management/mdm/passportforwork-csp
> The PassportForWork configuration service provider is used to provision Windows Hello for Business (formerly Microsoft Passport for Work). It allows you to login to Windows using your Active Directory or Azure Active Directory account and replace passwords, smartcards, and virtual smart cards.

This should pretty much explain why the article related to "Microsoft Passport for Work" is now replaced by the **Windows Hello for Business** page.
The URL still needs to be updated, of course, because the redirect might become deactivated in the future. We should also find a new description sentence for the current link.

There is also the unanswered question about which page should replace the 404 error from the linked archive page "Windows 10 Azure AD and Microsoft intune automatic MDM enrollment powered by the cloud".

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86
