### ISSUE TITLE
This page has incorrect information

### ISSUE THREAD

**Issue by GordonLElliott** [MicrosoftDocs/windowsserverdocs#4274]
Please have someone who is knkown to understand use of variables in batch files look at this page. Basically it is just about completely devoid of any correct information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ef877dd-d723-6bdf-f1d8-6bd9259f0e16
* Version Independent ID: a82f3f86-9613-1f95-4a92-111e0d28fcbf
* Content: [set](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/set_1.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/set_1.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by GordonLElliott** [comment]
I was referring to the examples section of the page, I don't know about the top portion.

**Comment by illfated** [comment]
Fair enough. Could you add a comment containing the examples you have found to be incorrect, maybe even suggest what it should be instead?

For the **Examples** section (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1#examples), I notice that the [Note] blob should have copied the command directly preceding it (`set testVar=test^^1`), because when using a single caret (`^`) and not a double caret (`^^`), the actual result will be only `testVar=test1`.

Looking forward to any further details you can provide, before I start making a PR to have that detail corrected.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
