### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Loftys** [MicrosoftDocs/windowsserverdocs#4279]
The 2 hyperlinks for 'download and install WMF 5.1' redirect you to your region and language specific pages.
For English - Great Britain, clicking the hyperlink results in a 404 (https://docs.microsoft.com/en-gb/powershell/wmf/setup/install-configure). 
Change the language and region to English - US and the link works (https://docs.microsoft.com/en-us/powershell/scripting/wmf/setup/install-configure).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a65d64c7-5f3f-e516-c9c9-0f0cebe100fe
* Version Independent ID: 0bff8d8c-c692-b862-a906-483d7430415d
* Content: [Prepare your environment for Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/prepare-environment#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/prepare-environment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/prepare-environment.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by illfated** [comment]
Yes, OK. I see. The issue is not that /en-us/ needs to be part of the link (as I first assumed when seeing this ticket), but the missing directory name /scripting/ in https://docs.microsoft.com/powershell/scripting/wmf/setup/install-configure .

The language agnostic feature on docs.microsoft.com is still working for most URLs, as long as the base URL is correct.

Thank you for reporting the broken links. I will open a PR to have those URLs fixed.

**Comment by illfated** [comment]
There you go. PR #4321 is ready for review & comments.
