### ISSUE TITLE
Missing images for Autonomous and Replic mode sections

### ISSUE THREAD

**Issue by silvermarkg** [MicrosoftDocs/windowsserverdocs#4286]
Both the Autonomous mode and Replic mode sections refer to "the following image" but there are not images in this article. Either the images should be included or the article updated to remove those statements

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94dc8d96-147f-27ea-2ba8-9a346fa63d55
* Version Independent ID: ac53f9d9-629b-9a95-6fd9-790b9fa9572f
* Content: [Plan Your WSUS Deployment](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/plan/plan-your-wsus-deployment#feedback)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md)
* Product: **windows-server**
* Technology: **manage-wsus**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by v-thepet** [comment]
Hello @silvermarkg,  

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused. 

The article no longer refers to any images. Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support. 

#please-close
