### ISSUE TITLE
Table not clearly displayed

### ISSUE THREAD

**Issue by k10blogger** [MicrosoftDocs/windowsserverdocs#4316]
The table for list of commands and their description is not showing in tabular form. It is hard to read all the options in a single line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b23b3f8d-9d81-bd05-b43e-d4dae5ec394b
* Version Independent ID: 3773ccf8-6a23-8037-bd5d-6deaeee61cdf
* Content: [Services for Network File System Command Reference](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/services-for-network-file-system-command-reference#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/services-for-network-file-system-command-reference.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/services-for-network-file-system-command-reference.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Thank you for reporting that issue. Yes, I can see that same table problem as you do. Unfortunately, it is too cumbersome for my computer to view hundreds of files in each commit of the file history, in order to find where the missing (and required) spacing occurred.

I will open a PR quite soon to fix this issue.

**Comment by illfated** [comment]
(Ref. #4317 )
