### ISSUE TITLE
Complete garbage

### ISSUE THREAD

**Issue by joejustesen** [MicrosoftDocs/windowsserverdocs#4330]
Complete garbage.  I came here for information on setting up a cluster script resource, as the new resource wizard leaves a lot to be desired.  This page was absolutely NO help.  Does MS hire anybody with at least a modicum of skill?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab323676-c43c-f1cb-75f3-911fb54ac78b
* Version Independent ID: 19e5c814-4984-f1a9-1759-ac8c5bd14c87
* Content: [Failover Clustering](https://docs.microsoft.com/en-us/windows-server/failover-clustering/failover-clustering-overview#feedback)
* Content Source: [WindowsServerDocs/failover-clustering/failover-clustering-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/failover-clustering-overview.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dksimpson** [comment]
Hi @joejustesen,

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
