### ISSUE TITLE
Setting up Teaming:  Same 2 Network cards not working on a second comuter

### ISSUE THREAD

**Issue by JaminShanti** [MicrosoftDocs/windowsserverdocs#4333]
Any thoughts, I bought the same 2 network cards for a second computer and every time I reboot the team doesn't come online, if I disable/re-enable it works again.  these cards work flawlessly on the first computer.  Both running windows 10 all up to date.  suggestion on logs I should review?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 767fe038-2675-96e7-e0df-1a99bad68552
* Version Independent ID: 716198d5-83e5-a230-54ab-4d93f705324f
* Content: [Troubleshooting NIC Teaming](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nic-teaming/troubleshooting-nic-teaming#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/nic-teaming/Troubleshooting-NIC-Teaming.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nic-teaming/Troubleshooting-NIC-Teaming.md)
* Product: **windows-server**
* Technology: **networking-nict**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
Hello @JaminShanti GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
