### ISSUE TITLE
why it can’t do like this， md P{1..9}

### ISSUE THREAD

**Issue by cr51k** [MicrosoftDocs/windowsserverdocs#4335]
i don’t know English，i hope it can support
one command create many directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5923f6e9-d5d5-b824-8eed-708d0bef9627
* Version Independent ID: 649465a8-d054-a537-b869-79594e6e565d
* Content: [Md](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/md#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/md.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/md.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
`md` (or `mkdir`) is a single instruction, single task command. It does not send more than 1 read/write action per command to the computer. You need to write a script, either in Windows Batch (`*.bat`;`*.cmd`) or PowerShell (`*.ps1`) to get a command which will do this for you.

I recommend posting in the TechNet or MSDN forum pages to ask for help with this, because this repository is used for reporting issues, errors, or incorrect information in the MS Docs pages, or request/suggest new and updated information in case a page is outdated.

- https://social.technet.microsoft.com/Forums/zh-CN/home
- https://social.msdn.microsoft.com/Forums/zh-CN/home
