### ISSUE TITLE
Wrong info

### ISSUE THREAD

**Issue by sluge** [MicrosoftDocs/windowsserverdocs#4336]
DTLS 1.0 disable:
Text:Enabled:0, DisabledByDefault:1
Picture:Enabled:0, DisabledByDefault:0 
What value for DisabledByDefault  to disable it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#dtls-10)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security-tls-ssl**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
Looks like you have misread the text and image content. Maybe you are overthinking this, or reading something into the scenario which is not there.

Let me try to explain how I read the section:
1. Both registry key values should be treated as Boolean values, 0 (or "No"), 1 (or "Yes").
2. The image shows a default setup where both registry keys are disabled (0 and 0) (Read them as "No" and "No").
3. For the registry key `DisabledByDefault`, this means: 0=No (Not disabled by default), 1=Yes (disabled by default).
4. For the registry key `Enabled`, this means 0=No (Not enabled), 1=Yes (enabled).

**Comment by illfated** [comment]
(ref. #4632 and #4737 )

**Comment by illfated** [comment]
@sluge : Note that the image content may not show the correct registry setting, only where to go to edit the registry and make the necessary changes.

Please view the images as a guide to find the Registry keys, not as a blueprint of the actual values.

That being said, whenever you come across incorrect information, please feel free to edit the page, open a Pull Request and ask for your suggested changes to be applied.

**Comment by illfated** [comment]
Please also note:

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
