### ISSUE TITLE
When do you plan implement nested virtualization on AMD Ryzen?

### ISSUE THREAD

**Issue by KarenTazayan** [MicrosoftDocs/windowsserverdocs#4337]
When do you plan to implement nested virtualization on AMD Ryzen? I need it for my docker containers and emulators.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c77ecb-1822-a712-cad3-a4f9ba84f2a3
* Version Independent ID: 195f045d-cf48-fec1-93a8-48663d21ab04
* Content: [Understanding and using Hyper-V hypervisor scheduler types](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md)
* Product: **windows-server-hyper-v**
* Technology: **virtualization**
* GitHub Login: @allenma
* Microsoft Alias: **allenma**

**Comment by illfated** [comment]
I think you should try contacting the developers via the Feedback Hub instead of here. 
This repository is only intended for updating or correcting the documentation pages. 
The MS Docs Server team does not have capacity to answer questions, only to follow up any Pull Requests made to improve the existing documentation.

**Comment by KarenTazayan** [comment]
Ok, thank you!

**Comment by Heidilohr** [comment]
It looks like this customer's concern was addressed by the reply. #please-close
