### ISSUE TITLE
Comment in Table

### ISSUE THREAD

**Issue by v-radelg** [MicrosoftDocs/windowsserverdocs#4339]
created by @shawnbarton commented 10 hours ago — with docs.microsoft.com

The "Calculation summary example" table in the section "Virtualization considerations for RAM" (Link: https://docs.microsoft.com/de-de/windows-server/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services#calculation-summary-example) contains the text "sind sicher???"/"are you sure ??".

Such a comment leads the reader to doubt the accuracy of the information they are presented with in the KB article and should be improved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14876129-a683-ad93-6043-26fc6afdb456
* Version Independent ID: 041a6bb3-27cc-dd06-fc45-2f34bb466fc8
* Content: [Capacity planning for Active Directory Domain Services](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services#calculation-summary-example)
* Content Source: [WindowsServerDocs/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services.md)
* Product: **windows-server**
* Technology: **performance-tuning-guide**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea; kenbrunf**

**Comment by illfated** [comment]
Looks like that text was added when creating this document page and that table has not been updated since.

See commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/a9ac180a279b02e50b130e04c7cc453120c0fb48 (file link: https://github.com/MicrosoftDocs/windowsserverdocs/commit/a9ac180a279b02e50b130e04c7cc453120c0fb48#diff-ac3034e7827bd35cec78ba40e0efcdf9) for the creation of the file.

I don't have the required expertise to know if just the unwanted question should be removed, or if the RAM GB value needs correction as well.

**Comment by illfated** [comment]
@eross-msft : Do you have any recommendation for what action should be taken here, if any?

**Comment by eross-msft** [comment]
@illfated  Wow, that's quite something. This definitely needs to be fixed. Do you want to create the PR and remove the text? Then, I can assign the PR to the current writer to do a review of the text as a whole. 

Thanks to all that caught this!
