### ISSUE TITLE
Third Party Proxies

### ISSUE THREAD

**Issue by bkpearson** [MicrosoftDocs/windowsserverdocs#4386]
FYI, FortiADC 5.2.0+ appears to also support MS-ADFSPIP and can act as an ADFS proxy.
https://docs.fortinet.com/document/fortiadc/5.3.0/handbook/190300/chapter-1-whats-new

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7958465-7224-0c4b-8771-eba606511922
* Version Independent ID: ff44e422-e4b1-134a-47bd-88d9abc843e3
* Content: [AD FS FAQ](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-faq#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
