### ISSUE TITLE
Broken upgrade warning - lack of docs 

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/windowsserverdocs#4393]
# The problem
If you have an all patched up version of Windows Server 2012R2, and run "setup" from the Windows Server 2019, April update, DVD, hours after you start (sorry, didn't time it) you get a warning:

> "Active Directory on this domain controller does not contain Windows Server 2019 ADPREP /FORESTPREP updates. See https://go.microsoft.com/fwlink/?LinkId=113955

If you go to that web page, you get documentation on Win2K or Win2K8 upgrades, and a nanny warning that "We're no longer updating this content regularly."

Then the upgrade craps out and you have to restart.

## There are multiple issues with the docs and the redirect.

1) If I'm upgrading Server 2012R2 to Server 2019, I shouldn't get redirected to Windows 2000 upgrade errors. That's just 12 to 20 years out of date. 

2) It's extremely frustrating to lookup these docs on the server in question. I understand IE's Enhanced Security (where is Edge?) but when companies like Oracle tell you, as part of any install to start with "disable Enhanced Security" it's essentially useless. Even your own products won't work with it. 

3) The upgrade script really should check this FIRST, otherwise, you've got to back out, add schema admin, do the forestprep, and then repeat the whole pre-upgrade dialogs and stuff. It takes a while.

All in all, not a show stopper, but one of those little things that is just broken about Windows, that really frustrates people.

# Suggested fixes:

1) Fix the redirect so it goes to a more recent page, not the top level of the server docs.
2) Fix the page you do get redirected to, to go to a similar page in the current docs, not the top level of the server docs.
3) Fix the upgrade script to check at the very beginning, or even - offer to do the forestprep! I mean, the code is on the upgrade .ISO. Yes, not all forests will survive, so it should be optional, but 90% of the time it's fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505fe07b-6fdd-4887-3c8b-15405c5d8308
* Version Independent ID: 25645df2-0ffb-4cc3-a8d2-5466edd309fb
* Content: [Overview of Windows Server upgrades](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-overview)
* Content Source: [WindowsServerDocs/upgrade/upgrade-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/upgrade-overview.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by jgwinner** [comment]
Thanks for listening!

**Comment by illfated** [comment]
Thank you for the insight into your upgrade problems from Windows Server 2012R2 to Windows Server 2019.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual error reports, improvement suggestions and update requests for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big amount of workload.

Even though we as users could have collaborated to update existing documentation pages, the domains www.microsoft.com and go.microsoft.com are outside the responsibility area of the MS Docs teams, so it may very well take some time before any input in this repository reaches the main microsoft.com site maintainers for the fwlink redirects. (Even more so for the placement of that link, inside local software.)

In the meantime, I would like to suggest using the Feedback Hub to send feedback to the developers in addition to posting this ticket here. (I really do hope that some of your information will reach the central managers.)

**Comment by jgwinner** [comment]
Thank you Illfated!

I know it may take a while. Working through these issues and solving them is the difference between an IT professional and a dilletante. 

I figure though, if I don't report the issues, then who would ever fix them?

The Feedback hub is mostly useless. One shouldn't have to vote on fixing bugs. Quality has it's own purpose aside from being voted on. There was a book (which honstly I haven't read) called "Broken Windows, Broken Business" that illustrates this. But, that's a rant, I understand why you asked and it does make sense. I think there's a difference between reporting a bug and getting it fixed, and asking for new features/improvements, however.

**Comment by illfated** [comment]
Fair enough. Thanks again for the feedback.

**Comment by jgwinner** [comment]
I ran into another bug related to the above. After doing the FORESTPREP, then running setup again, it asks you if you'd like to continue with a Windows 10 upgrade.

I had images of the server being downgraded, so I canceled it. 

I think setup.exe meant an upgrade to Windows Server 2019.
Seems simple, but caused a significant delay.

Then it natters about DOMAINPREP ... again.

        == John ==

**Comment by IngridAtMicrosoft** [comment]
Hello jgwinner.  You probably have already solved the issues you were having and the document appears to have been edited since this issue was created.  For future reference, please see https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers

#please-close
