### ISSUE TITLE
Link throws 404

### ISSUE THREAD

**Issue by TheBeardedLlama** [MicrosoftDocs/windowsserverdocs#4405]
The link to get bcdboot examples does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a288353c-cce4-82dc-1285-6857758b0166
* Version Independent ID: dfb4d079-d860-d4fd-b93c-47bbcdc0fb85
* Content: [bcdboot](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bcdboot)
* Content Source: [WindowsServerDocs/administration/windows-commands/bcdboot.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/bcdboot.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Thank you for reporting the 404. I noticed that the link contains a typo and it works when corrected:
- https://docs.microsoft.com/en-gb/previous-versions/windows/it-pro/windows-8.1-and-8/hh824874(v=win.10)

Then again, the page says: "We’re no longer updating this content regularly. Check the Microsoft Product Lifecycle for information about how this product, service, technology or API is supported."

There is also this other link with the exact same page title, but in a different section of the docs.microsoft.com library:
- https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/bcdboot-command-line-options-techref-di

I am going to open a PR to have the typo resolved, where I will also ask if it will be more useful to point to the Windows / Manufacture / Desktop manufacturing section instead, since that page does not display the warning about the topic not being regularly updated.

May I trouble you with taking a moment to compare those 2 pages and see if any useful information will be lost by choosing the newer and more updated page, in favor of the old Windows 8 page?

**Comment by TheBeardedLlama** [comment]
thank you for the update @illfated 

makes sense to only have one copy or to redirect to a single source of truth

**Comment by illfated** [comment]
> makes sense to only have one copy or to redirect to a single source of truth

Thank you for the reply. I would like to point out that my suggestion was to choose between the 2 pages, but I have also mentioned that as an additional note in my PR, as a question to the MS Server Docs team.
