### ISSUE TITLE
Inconsistent strings

### ISSUE THREAD

**Issue by Robamalama** [MicrosoftDocs/windowsserverdocs#4409]
in "Configuring WIA for Chrome" under "In AD FS configuration, add a user agent string for Chrome on Windows-based platforms:" the sample tells us to use "Mozilla/5.0 (Windows NT)" as the agent for chrome. However, further down in the screenshot the value added is simply "Chrome". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf9cb6e-38be-d28e-6ad3-1151b7e1a379
* Version Independent ID: 3eed2746-fc1e-b7c3-ea04-203291aec098
* Content: [Configuring intranet forms-based authentication for devices that do not support WIA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-intranet-forms-based-authentication-for-devices-that-do-not-support-wia)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-intranet-forms-based-authentication-for-devices-that-do-not-support-WIA.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-intranet-forms-based-authentication-for-devices-that-do-not-support-WIA.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Good point. I am wondering whether the PowerShell command examples are from the Windows Server 2012 days when Chrome still used a Mozilla-compatible User Agent string. Also note the text directly above the image, stating the following:
> (You would need a new screen shot here)

**Comment by illfated** [comment]
Please note: The actual issue is that the image needs to be replaced with a similar image showing the use of "Mozilla/5.0 (Windows NT)" as the User Agent string.

See commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/1d33634de36c4966da5a1b2d69e32b0fe0708352 from 2019-07-26 and its Pull Request source **Recommendation for adding Chrome to WIASupportedUserAgents is too broad** **#2750** .

Note in particular the PR main comment, explaining the issue as follows:

> The current recommendation seems to suggest adding the “Chrome” string to WIASupportedUserAgents, but I think that is too broadly defined and could lead to a match when it probably should not because all Chrome user agent strings start with “Mozilla/5.0” followed by the platform. Adding "Chrome" by itself would lead to scenarios where WIA could incorrectly be attempted for devices such as Chrome for Android, which has a user agent string such as:
> 
> Mozilla/5.0 (Linux; ; ) AppleWebKit/ (KHTML, like Gecko) Chrome/ Mobile Safari/

So in fact, the text is correct, but the image is incorrect.
(I don't think I will be able to produce a working image on Windows 10 to replace the current one, but if you are able to create and use any ADFS Server VM, please post a replacement picture in a comment here with the same content as the existing image, except for the **Chrome** string being replaced by "Mozilla/5.0 (Windows NT)".)

**Comment by illfated** [comment]
You may also be interested in reading the final comment in the PR by the PR author, Brian Pendergrass (@bspender):

> For what it's worth, I just fixed an issue where my customer encountered this because they had used "chrome" instead of the more specific variants. Their 3rd party [phone] app (which I believe was built on the Electron app framework, which commonly has "chrome" in it's user agent strings) didn't support a mixed mode environment and required forms based auth on devices like Android ...but it kept trying WIA and failing. Once we replaced "chrome" with the specific variants - it all worked like a champ... Feel free to ping me internally if you need more specific details. *appreciated!

**Comment by illfated** [comment]
(ref. #4341 )

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
