### ISSUE TITLE
For Windows 10 1909 follow this guide instead

### ISSUE THREAD

**Issue by keeely** [MicrosoftDocs/windowsserverdocs#4412]
https://www.hanselman.com/blog/HowToSSHIntoAWindows10MachineFromLinuxORWindowsORAnywhere.aspx

1st caveat:  You need to reboot after installing sshd before you can try to start it and this is IMHO poorly signalled to the user.  It's there if you look, but it's not mentioned in the above guide.
2nd caveat:  If you're not connected to the network this is also rather poorly signalled (IMHO).

**Comment by illfated** [comment]
#please-close

#potential-spam

**Comment by keeely** [comment]
I was reading a Microsoft doc.  The article was here:
https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse
At the bottom of the article there is a link 'view all page feedback'.  When you click on it it takes you to this github project.  I surmised that feedback on the page should be directed here.

Unfortunately, my addition hasn't made it into the list that gets displayed when clicking on the link in the article, so maybe there's some special way of doing that. 

I certainly wasn't trying to spam anyone, just inform them of additional information relating to the article (which is the 2nd google hit when searching for 'ssh server windows'.

**Comment by illfated** [comment]
Fair enough. I recommend that you try again by using the Feedback button titled [This page]:

![image](https://user-images.githubusercontent.com/38162891/84348824-3fbd7580-abb6-11ea-8b46-4608b1c9f72c.png)

When you have successfully created a new issue ticket, I recommend closing this ticket.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, due to the small size of the team and the big workload.
Our best hope to make changes is to make sure the submitted material can be used to improve the existing documentation.

**Comment by illfated** [comment]
#please-close
