### ISSUE TITLE
parameter remoteapplicationexpandworkingdir seems wrong

### ISSUE THREAD

**Issue by MarcMQC** [MicrosoftDocs/windowsserverdocs#4417]
[Enter feedback here]
Hello,is there something wrong about the parameter RemoteApp->RDP setting->remoteapplicationexpandworkingdir.
According to others parameters in this doc, I think it should be "remoteapplicationexpandworkingdir:i:value" rather than "remoteapplicationexpandworkingdir".
I hope to receive your reply.Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 630c940d-79fe-3f4e-104c-8e8b19b480e4
* Version Independent ID: 2c4d6608-8fa2-ca33-3a3e-97acfc995f4f
* Content: [Supported Remote Desktop RDP file settings](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/rdp-files#remoteapp)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/rdp-files.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/rdp-files.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by illfated** [comment]
Yes, from what I can see in the table, the RDP setting `remoteapplicationexpandworkingdir` should follow the same pattern as the other settings and their values in the same table, especially because the values are named and described in the **Values** column.
*
I will open a Pull Request to have that **RDP setting** detail included. I believe it should be shown as follows:
- `remoteapplicationexpandworkingdir:i:value` (i = integer (as compared to s = string for other settings))

**Comment by illfated** [comment]
Thank you for being proactive in closing this ticket before the PR is merged.
Just thought you would like to know that I include auto close in my PRs.
