### ISSUE TITLE
Can a shadow be added around Remote Desktop App?

### ISSUE THREAD

**Issue by larrymac41** [MicrosoftDocs/windowsserverdocs#4433]
We are rolling out the remote desktop app and users click on the X to close the remote session in error when trying to close down Outlook, Word, etc.  It in an innocent error that could readily be addressed with a shadow or some hue around the border I believe.
See below graphic that looks like a normal exiting RDP screen.

Thanks.

![Close remote session](https://user-images.githubusercontent.com/48260068/83445047-4a3f7880-a41a-11ea-8d87-3b5e5ac20890.png)

**Comment by illfated** [comment]
Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to receive reports on the existing documentation (factual error reports, improvement suggestions and update requests for new versions).

Try one of the following resources to promote your improvement suggestion to the developers:
- Feedback Hub (Windows app or website)
- Technet forums: https://social.technet.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

By the way, is it possible that your dialog edge does not show because of too low resolution or viewing experience set to Low Speed (less resolution) instead of High speed / High Quality? I would have checked both the Windows 10 Performance settings (SystemPropertiesAdvanced.exe) as well as the MSTSC/RDP settings.

**Comment by larrymac41** [comment]
Thanks very much.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
