### ISSUE TITLE
Add Windows Server 2019 to steps

### ISSUE THREAD

**Issue by davemct** [MicrosoftDocs/windowsserverdocs#4438]
[Enter feedback here]
In Step 0, # 6, you say:  "On all source servers and on any destination servers running Windows Server 2012 R2 or Windows Server 2016, in Windows Admin Center,"  

If this applies to Windows Server 2019 also, can you please update it to say so.

I am a Microsoft Certified Trainer who often directs students to Doc pages and you'd be surprised how often folks can get it wrong unless you are very specific.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa81041-3a2a-961a-05d5-4a845cc74ae2
* Version Independent ID: fadf165a-5c81-0102-e096-7f527483313b
* Content: [Migrate a file server by using Storage Migration Service](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/migrate-data)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/migrate-data.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/migrate-data.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 4426 -b #assign:IngridAtMicrosoft

**Comment by v-thepet** [comment]
Hello @davemct , 

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused. 

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. This article is up to date for Windows Server 2019 and 2022, so versions referred to in specific steps should be accurate.

However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support. 

 

#please-close
