### ISSUE TITLE
Undocumented feature for ECHO (colon)

### ISSUE THREAD

**Issue by dseynhae** [MicrosoftDocs/windowsserverdocs#4443]
I have been using a colon with echo in batch files, so that empty variables don't result in giving me the echo status (ON or OFF):
Consider:
```bat
@echo off
set A=TEST
set B=
echo %A%
echo ====
echo:%A%
echo ====
echo %B%
echo ====
echo:%B%
echo ====
```

Running this from a `test.bat` file will give the following results:
```
D:\tmp>test
TEST
====
TEST
====
ECHO is off.
====

====
```

- The empty variable `%B%` without the colon gives me the status (off).
- The empty variable `%B%` with the colon gives me a blank line (which is what I want).
- The defined variable `%A%` gives me the desired result either way.

You can use the dot '.' as well.
It is documented that
```bat
echo.
``` 
gives a blank line, which explains the empty variable scenario, but doesn't explain that the dot "disappears" with the defined variable.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73a4605-c4b3-46a8-ec4e-493751fff82b
* Version Independent ID: 2bcfea05-35c7-49cb-0570-a0d5a4957ca1
* Content: [echo](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/echo#additional-references)
* Content Source: [WindowsServerDocs/administration/windows-commands/echo.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/echo.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Thank you for this interesting detail. I have been using the echo command in batch files a lot, ever since 1990, but I was not aware of the special case of empty variables displaying the echo status instead of a blank line. One of my most interesting feedback experiences comes from sharing my knowledge of the usage of the echo command is the use of the dot, backslash or colon as the special case when requiring a blank line to be displayed along with the other text output from the batch file.

I agree that it could be nice to have that special case documented for future use, so if you have suggestions for where to put that extra information and how to phrase it, I would happily start a Pull Request to have that information added. I presume that the current codestyle of the page needs to be followed, but some suggestions for the phrasing would be most useful.

**Comment by Xelu86** [comment]
Hey dseynhae,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the colon (`:`) and its function for batch files into the remarks section and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
