### ISSUE TITLE
HELP...

### ISSUE THREAD

**Issue by VGSandz** [MicrosoftDocs/windowsserverdocs#4478]
[Enter feedback here]
Open the Registry Editor, go to the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsNT\CurrentVersion hive, and then copy and paste the Windows Server BuildLabEx (version) and EditionID (edition) into the same location as above.

Could you explain this step in a simplified manner or a picture.
We are trying to do an in-place upgrade from server 2012 Std to Server 2016 std and unable to keep the "personal files and apps". May be because of this step i hope we can solve the issue.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465ee446-5e41-bd72-1305-976db9c3a4ec
* Version Independent ID: f7091237-826d-1e6e-d8f3-b688205f25fd
* Content: [Upgrade Windows Server 2012 to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2012-to-2016)
* Content Source: [WindowsServerDocs/upgrade/upgrade-2012-to-2016.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/upgrade-2012-to-2016.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
No reply or follow-up for more than 9 months. This should be handled elsewhere anyway, by Microsoft Support or other support instances.

#please-close
