### ISSUE TITLE
These 2020 "Windows Desktop" Documentation Pages are Extremely Confusing

### ISSUE THREAD

**Issue by arekfurt** [MicrosoftDocs/windowsserverdocs#4486]
Setting aside the baffling terribleness of having two separate RDP clients called Windows Remote Desktop Connections client and Windows Remote Desktop client, respectively, the way the documentation for this section is now structured and worded is bizarre and nearly unusable.

 Why aren't there separate sub-headings in the left-hand bar for the two different Win10"Desktop" clients, not just the one that only connects to Azure VD? How can you not have a sub-heading for the most frequently used Windows RDP client?

 Why aren't there links on this particular page to wherever the info for the traditional in-box client got relocated to? 

Why do some of the other pages in the documentation that apparently refer to the traditional, in-box client use the nomenclature "Windows Desktop" client?

Why are there sections of text that are apparently supposed to talk about the Azure VD client as if it can connect to on-prem machines when it can't do that right now? 

Why are the important distinctions between the now-three different official MS RDP clients on Windows PCs noted in the last page of this section of documentation while the first page (that supposedly says it explains what clients exist) makes no mention of the traditional RDP client (the one most people are probably looking for documentation on!) whatsoever? 

I'm honestly perplexed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey arekfurt,

Thanks again for contacting Microsoft. We value your feedback. 

Based on the length of time when this issue was generated, the page in question no longer exists, so edits to it cannot be made. Those who maintain the RDS technology documentation have made several changes over time since the app's release and there is more updated platform-specific documentation available.

Latest information about the Windows Desktop Client can be found at: https://learn.microsoft.com/en-us/azure/virtual-desktop/users/connect-windows?tabs=subscribe

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
