### ISSUE TITLE
Difference not clear of LTSC & SAC in examples

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/windowsserverdocs#4489]
Section "How to tell whether a server is running an LTSC or SAC release"
I don't see clearly the difference between the two examples (one is Datacenter edition the other Standard).
Please clarify a bit more precise the different in output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd87c102-6f5d-376b-4665-98ff94b4ca41
* Version Independent ID: f6140fb6-30bc-e9e7-463a-bf5bfc926165
* Content: [Servicing Channels](https://docs.microsoft.com/en-us/windows-server/get-started-19/servicing-channels-19)
* Content Source: [WindowsServerDocs/get-started-19/servicing-channels-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/servicing-channels-19.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey trudolf-msft,

Thanks again for contacting us, we value your feedback. 

Based on the time this issue was generated, the page in question has gone through several updates and the [How to tell whether a server is running an LTSC or AC release](https://learn.microsoft.com/en-us/windows-server/get-started/servicing-channels-comparison#how-to-tell-whether-a-server-is-running-an-ltsc-or-ac-release) section has been clarified.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
