### ISSUE TITLE
 windowsserverdocs/WindowsServerDocs/identity/ad-fs/operations/Access-Control-Policies-in-AD-FS-2.md

### ISSUE THREAD

**Issue by montereyharris** [MicrosoftDocs/windowsserverdocs#455]
windowsserverdocs/WindowsServerDocs/identity/ad-fs/operations/Access-Control-Policies-in-AD-FS-2.md
 rules in this article do not work at all. I am using ADFS 2.0 update roll up 3 and it isnt working at all

**Comment by illfated** [comment]
Page reference information, as provided when a ticket has been created correctly (see below).


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b28154a-89f5-942d-ed5f-a6c0286687de
* Version Independent ID: 4fcdb03a-3f62-1eaf-40b0-388c061d3262
* Content: [Client Access Control policies in Active Directory Federation Services 2.0](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/Access-Control-Policies-in-AD-FS-2)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Access-Control-Policies-in-AD-FS-2.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Access-Control-Policies-in-AD-FS-2.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
@montereyharris : I know it has been a long time (2.5 years) since you posted this issue ticket. This repository ticket system is used for documentation improvement suggestions. I can only assume that your original issue has been solved on your side since then.

Are there any specific parts in this document that needs improvement, do you know which parts should be changed or if there are any missing steps or incorrect information we can work on to improve for future use?

**Comment by illfated** [comment]
@montereyharris : If you have not done so already, I hope you will consider opening a ticket with your local Microsoft Support tenant or use one of the related forums to discuss your issue. If you find any improvements that affects the referred MS Docs documentation page, please open a new ticket to have the page corrected.

For now, I will proceed to close this ticket and ask you to open a new ticket if you still find that the page is in need of improvement changes.

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
