### ISSUE TITLE
Windows Virtual Desktop column marked with "X" is unclear, subjective

### ISSUE THREAD

**Issue by CJMakris** [MicrosoftDocs/windowsserverdocs#4595]
The description states _"...table also highlights which settings are supported as custom properties with Windows Virtual Desktop"_, but in the table some settings are only flagged in the Windows Virtual Desktop column with "X" with no legend to help the reader interpret whether that means supported or not. One can interpret an "X" as "wrong" or "not supported", or is the presence of any mark (in this case "X") assumed to mean "supported" leaving the absence of a mark to mean "not supported". While this could be gleamed from the context by a reader that knows each setting, one is normally reading this to GAIN such knowledge not guess what it means. Use something clearer than "X", such as: "Yes/No", "True/False", "OK/Not", or "Supported/[blank]".

A quick fix: rephrase "...table also highlights **(with an "X")** which settings are supported ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 630c940d-79fe-3f4e-104c-8e8b19b480e4
* Version Independent ID: 2c4d6608-8fa2-ca33-3a3e-97acfc995f4f
* Content: [Supported Remote Desktop RDP file settings](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/rdp-files)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/rdp-files.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/rdp-files.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by illfated** [comment]
I know, "don't shoot the messenger" (as the phrase goes), especially when using an unfamiliar media platform.

Then again, it is a bit difficult to digest the content of the issue description when all of it is written in the page title instead of the comment box. (It is pretty much like getting an email message with all the text in the Subject line and no text at all in the actual message body (except for the automatic signature addition).)

May I be so bold as to ask you to edit the page title and the comment box, moving the issue description to the comment box, while leaving only a very short keyword comment in the title, indicating what the issue is about?

If that is too difficult for you, maybe we could ask one of the MS Docs team members to edit this ticket, so it becomes a bit more readable as well as quotable?

**Comment by CJMakris** [comment]
Comment corrected. I've used feedback recently, and then--like this time--I saw only one place to put comments. Now, I know. Thanks.

**Comment by illfated** [comment]
Very good, thank you. Nice to see the ticket more like what we are used to see.
This should make it a lot easier to reply to and find out what we can do to move forward with this issue.

My local time is past 23:00 here in Norway (Central European Time), so I will have to get back to this tomorrow or the day after.
Anyway, feel free to add more comments in the meanwhile, if you want to point out more details or specifics.

**Comment by illfated** [comment]
I would preferably like to see the table updated to use an image tick mark ✔️ to show what is supported, but I will have to check the codestyle for the whole page, its sibling pages, and its parent page first, to see if this is a usable solution.

**Comment by illfated** [comment]
Oh. I browsed the file changes in the commits (history) here on GitHub,
- https://github.com/MicrosoftDocs/windowsserverdocs/commits/master/WindowsServerDocs/remote/remote-desktop-services/clients/rdp-files.md

and found that this has already been rectified. Please see links below for the relevant change.

**Comment by illfated** [comment]
See commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/215506254db29593d955b7c9e30ef24bdfa7ad2e for the change of " **X** " to "Yes" and " " to "No". Note also that the column title "Windows Virtual Desktop" has been expanded to **Windows Virtual Desktop support**.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
@CJMakris : Thank you for your initial report. It seems to have worked well, because the change was made, only with no reference to this ticket. I can only surmise that there could have been more than this report about the table being confusing, so I hope you were pleased to see the update 4 months ago.
