### ISSUE TITLE
Detect and delete previous VPN profile

### ISSUE THREAD

**Issue by stuart7777** [MicrosoftDocs/windowsserverdocs#4605]
Hi,
In the article there is a an example of code to Detect and delete previous VPN profiles (https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections#detect-and-delete-previous-vpn-profile)
We have a handful of computers running various versions of Windows 10 from 1809 to 2004. When we run the script to replace the VPN profile it fails with an error stating "A general error occurred that is not covered by a more specific error". The only way to get rid of this error is to rebuild the computer. I have tried resetting WMI repository and deleting all profiles. Running script as system. This issue seems to be with the  MDM_VPNv2_01 class.
I've had this with a few customers now and there are lots of reported issues with this in the forums. Is this a bug?

**Comment by illfated** [comment]
(Just to add the missing info, which would have been added if you had used the button **[:octocat: This page]** at the bottom of the page.)


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e14da1-102d-3ddf-e2a1-a20ce533b95a
* Version Independent ID: 374edc4c-f527-b7b7-c291-353928b97d8d
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections#detect-and-delete-previous-vpn-profile)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

---
Please note: The listed author info could be outdated, I don't know which team members will be available to answer your question.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

**Comment by illfated** [comment]
The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

There is a chance that the MS Docs team members may need quite some time to answer your question, both due to the small size of the team and the big workload.

You may want to try the following resources to get in touch with users who may be able to help you figure out if the content you refer to contains errors, or is imprecise in its functionality:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by Xelu86** [comment]
Hey stuart7777,

Thanks again for contacting Microsoft, we value your feedback. 

You have described a potential issue with a product or service rather than our documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
