### ISSUE TITLE
Summary image incorrect

### ISSUE THREAD

**Issue by mattwoolnough** [MicrosoftDocs/windowsserverdocs#4607]
Summary Image shows CurrentSet001 being updated, but it should be CurrentControlSet 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by illfated** [comment]
I have not worked on these details before, but it makes me wonder if there is a reasonable explanation for the deviation.

Could it be that the registry key & value `HKLM\CurrentControlSet\Services\LanmanWorkstation\DependOnService` (`Bowser MRxSmb20 NSI`) is either volatile or causes enough influence on a running system, that it needs to be replicated on a test machine to avoid instability or unsafe running conditions for the OS or system?

**Comment by illfated** [comment]
@Deland-Han : Would you be able to confirm if the image in
- https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#summary-1

uses an incorrect line referring to `\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\LanmanWorkstation` whereas `\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanWorkstation` usually contains identical information?

Maybe this issue is cosmetic and superficial, but I thought I should ask someone who works with this material on a daily basis, just to get feedback on the ticket question above.

**Comment by IngridAtMicrosoft** [comment]
@Deland-Han Thank you!

**Comment by IngridAtMicrosoft** [comment]
Addressed. #please-close
