### ISSUE TITLE
Is there more detailed documentation anywhere

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/windowsserverdocs#4610]
This whole section of the windows server documentation feels very light weight. Where, for example, is the documentation about how to set up DHCP failover? If there is more in-depth documentation somewhere a link to it from here would be a big help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 954e0962-fc03-814d-8033-138701993466
* Version Independent ID: 6fb6878d-af07-918f-7fe0-c796e44fa8a4
* Content: [Dynamic Host Configuration Protocol (DHCP)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/dhcp/dhcp-top)
* Content Source: [WindowsServerDocs/networking/technologies/dhcp/dhcp-top.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/dhcp/dhcp-top.md)
* Product: **windows-server**
* Technology: **networking-dhcp**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
I agree that it seems difficult to search for and find specific DHCP Failover, because there are many more search hits for "failover clustering" among the Win32 apps entry for `DHCP_FAILOVER_SERVER` (`dhcpsapi.h`).

Then again, I wonder if it would be of any help to read the Windows Server 2012 R2 pages for DHCP Failover:
- **What is DHCP Failover?** (https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn338983(v=ws.11) )
- **Understand and Deploy DHCP Failover** (https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn338978(v=ws.11) )

What are your thoughts on the usefulness of those pages?

I also wonder how much it affects your scenario that Azure solutions are getting increasingly more focus these days, compared to most on-premises environments.

**Comment by martingbrown** [comment]
I did find those pages eventually and they did help, but there is a message saying they are obsolete. Is it still relevant? Is it about to be deleted?

Also this page didn't appear to display correctly.

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn338973(v=ws.11)

**Comment by illfated** [comment]
> I did find those pages eventually and they did help, but there is a message saying they are obsolete. Is it still relevant? Is it about to be deleted?
>
The main takeaway from the message is "We're no longer updating this content regularly.", because the content was written for Windows Server 2012 & 2012 R2. The rest of the message is only meant to indicate the supportability in terms of the functionality still being valid for existing supported OS versions. In my opinion, it is still relevant, at least to the extent of its usefulness in a current server OS.

> Also this page didn't appear to display correctly.
> 
> https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn338973(v=ws.11)
>
Yes, I noticed that the right side column is messed up, mainly because it has not been updated to follow the newer HTML page layouts. There may also be other issues I didn't notice at first glance.

> We can't use Azure as we need to remain disconnected from the internet.

Fair enough, that is a perfectly valid scenario. I don't know if Microsoft Docs has got any plans for writing more updated pages on this topic, because I am not affiliated with nor employed by Microsoft or the Microsoft Docs teams.

Maybe you could look in other places for answers too, by visiting the following resources to get in touch with people who might be able to help you further:

- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by IngridAtMicrosoft** [comment]
Addressed in comments.
