### ISSUE TITLE
How to get version of HyperVisor (Hyper-V). 

### ISSUE THREAD

**Issue by KrupalJoshi** [MicrosoftDocs/windowsserverdocs#4611]
[Enter feedback here]

Hi,

How to get version of Hyper Visor Hyepr-V. What is correct place to look for the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 947653d7-fe3d-5c67-ae39-e72a8c6fe6c7
* Version Independent ID: 9e3e02e3-64f9-cead-cbdf-82710dfc280e
* Content: [Hyper-V Technology Overview](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/hyper-v-technology-overview)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Hyper-V-Technology-Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Hyper-V-Technology-Overview.md)
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by illfated** [comment]
The easiest method should be to open the Hyper-V Manager console (on the host OS) and open "**About Hyper-V Manager**" on the Help menu.

![Hyper-V Manager](https://user-images.githubusercontent.com/38162891/86518369-da197d80-be31-11ea-8406-810bef39e7cf.png)

There is also the command line method: `wmic datafile where name=”c:\\windows\\system32\\vmms.exe” get version`

![CMD wmic vmms version](https://user-images.githubusercontent.com/38162891/86518813-9d02ba80-be34-11ea-8bb4-be3c9aba43c1.png)

By the way, this information on "How to get version of HyperVisor (Hyper-V)" is not a secret, it is easily searchable via web search (Bing or Google).
Search term: `get version of HyperVisor (Hyper-V)`

If this comment did not answer your questions, you may want to look elsewhere for answers, unless you have suggestions for the improvement of one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
Is this ticket ready to be closed now?

**Comment by KrupalJoshi** [comment]
Thank you for your input and pointing me to forums.
Yes, this ticket can be closed now.
