### ISSUE TITLE
Help for exception: ObjectNotFound: (MSFT_FSRMQuota:Root/Microsoft/.../MSFT_FSRMQuota) [New-FsrmQuota]

### ISSUE THREAD

**Issue by lucygoldbergmicrosoft** [MicrosoftDocs/windowsserverdocs#4614]
I was wondering if anyone could help me with the following exception? I've built a custom image (based on image windows-2019-Datacenter) with FSRM preinstalled. But I'm running into the following issues when I'm trying to run New-FsrmQuota on the VM with my Custom Image. It seems like a dll issue, but I don't see any dlls located in the FSRM module path in powershell. 

New-FsrmQuota : Not found
At line:1 char:1
+ New-FsrmQuota -Path "D:\Test" -Description "limit usage to 1.5 GB" -S ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MSFT_FSRMQuota:Root/Microsoft/.../MSFT_FSRMQuota) [New-FsrmQuota], CimE
   xception
    + FullyQualifiedErrorId : HRESULT 0x80041002,New-FsrmQuota

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9a74250-4247-076f-c1f6-6d00bfe3dc9a
* Version Independent ID: b3153206-6f1f-c66f-8d42-869419b8d8b4
* Content: [File Server Resource Manager (FSRM) overview](https://docs.microsoft.com/en-us/windows-server/storage/fsrm/fsrm-overview)
* Content Source: [WindowsServerDocs/storage/fsrm/fsrm-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/fsrm/fsrm-overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try some or all of the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Please also note: Waiting for replies from the MS Docs team members can take anything from weeks to months before you get a useful answer, particularly if your ticket is not about correcting the pages.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @lucygoldbergmicrosoft,

Thanks again for updating us on this issue. We will now be closing this thread. Have a most pleasant day. #please-close
