### ISSUE TITLE
Block DNS queries to multiple web sites/destination addresses

### ISSUE THREAD

**Issue by ezxcess2020** [MicrosoftDocs/windowsserverdocs#4615]
How can add multiple address/websites in the list to block DNS queries to?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 275f0be8-0a48-65cb-3990-82b9a67e732a
* Version Independent ID: 15bae0bd-01dc-32ac-2131-46c5a350f036
* Content: [Use DNS Policy for Applying Filters on DNS Queries](https://docs.microsoft.com/en-us/windows-server/networking/dns/deploy/apply-filters-on-dns-queries)
* Content Source: [WindowsServerDocs/networking/dns/deploy/apply-filters-on-dns-queries.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/dns/deploy/apply-filters-on-dns-queries.md)
* Product: **windows-server**
* Technology: **networking-dns**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Sorry for the delayed response. I was waiting to see if someone else would post a reply to your question.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
On the other hand, if someone posts the answer to your question, as well as arguing that the solution should be added to the linked page, feel free to create a Pull Request to have the solution added to the documentation. I will be available for advice on how to manage a Pull Request.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
Hello @ezxcess2020. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
