### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mcurko** [MicrosoftDocs/windowsserverdocs#4617]
Please clarify what is considered large/small file, 1 KB, MB, GB ...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd02ed03-8445-e3fe-f2ae-e48549ffdbcc
* Version Independent ID: 1149f098-d1c6-22b0-e7de-1d2cb18cac26
* Content: [Slow SMB files transfer speed](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/slow-file-transfer?source=docs)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/slow-file-transfer.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/slow-file-transfer.md)
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by illfated** [comment]
Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub. I am also not an expert on this topic, so my reply might not be precise enough or contain any authoritative answers.

I am fairly sure that depends on the hardware in use in each scenario. To calculate what counts as small or large files, you would need to have previous knowledge of the expected throughput on the local network connection, the capabilities of the network hardware and the speed and resources available on the target system (server or client). Sure, there are some defined values available in the performance counter system, as well as the SMB configuration, but you also need the aforementioned information about the hardware speed and a fairly recent test result of what kind of performance to expect from the hardware configuration in question. Usually, it should be obvious from the types of data you want to transfer what counts as small or large files. Windows systems usually round up the reported size of byte-size files to 1024 (a.k.a. 1K), which should count as small files. Big files are usually rich graphics (high quality photos), movie files or special data storage files, as well as compressed archives. This should normally be fairly easy to sort out during preparations where we evaluate the types and data contents we want to transfer. So in my opinion, it is always useful to evaluate the files before starting a transfer, to be prepared for how much time it should take to transfer those data.

Please note: The intention of this repository is to accommodate reporting on the existing documentation (factual error reports, improvement suggestions and update requests for new versions).

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload. Sure, if your question is useful to provide good reasons for updating the documentation, you may get answers, but maybe not as soon as you might be hoping for.

Try the following resources to get in touch with users who may be able to help you, at least somewhat sooner than the users and team members in the current repository.
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by mcurko** [comment]
I have about 1000 files totaling 200 MB, many in kB range, some in 10s of MB range. Ita takes several minutes to copy all the files, and I guess the hardware supports much higher speeds that I'm achieving here (under 1 MB/s).

**Comment by illfated** [comment]
Fair enough. I guess I don't know enough about those details to have any particular knowledge on how to divide those files into groups of small and large files. I thought it would be possible to base an educated guess on how Windows Explorer classifies small & large files, but I may very well be mistaken in this case. I need to think through this a bit more, maybe see if I can get some research done later. Thank you for providing more details.

**Comment by IngridAtMicrosoft** [comment]
#label:doc-enhancement

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
@Deland-Han Thank you!
