### ISSUE TITLE
dir behaves different in PS and Command Promtp

### ISSUE THREAD

**Issue by ameb1981** [MicrosoftDocs/windowsserverdocs#4631]
Running `dir` with wildcards behaves differently in PS and Command Prompt. For example, if I have Excel files with **xls** and **xlsx** extensions, running `dir *.xls` will list all the _xls_ and _xlsx_ files in **Command Prompt**, but just the _xls_ files in **PS**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8095c8a1-5049-2eb1-2041-6392f2025cfa
* Version Independent ID: 6e63df5e-a455-33c7-22db-36f44121a2c0
* Content: [dir](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/dir)
* Content Source: [WindowsServerDocs/administration/windows-commands/dir.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/dir.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Sure, that much is true. Then again, this page is a subpage to Windows Server / Administration / Windows commands / Commands by server role /.

I don't think PS (PowerShell) is the intended usage scenario here, seeing how old the pages (or their origins) are. Then again, it is easy for me to think like this, when my experience started back in the MS-DOS days, long before the existence of PowerShell.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @ameb1981,

Thanks again for contacting Microsoft. We value your feedback. 

As we understand it, you're comparing two different command line interfaces, windows command prompt and PowerShell. The output for both will be different due to their nature. This **dir** article is found within **windows commands**, and PowerShell is not referenced as it has its own section. 

If there is an issue within the documentation itself, please let us know. We will now be closing this. Thank you and have a most pleasant day. #please-close
