### ISSUE TITLE
sshd doesn't work

### ISSUE THREAD

**Issue by SarKaa** [MicrosoftDocs/windowsserverdocs#4636]
So I has everything set up, but just for testing, tried out mobassh. I deleted it, but when I tried to re-enable windows ssh server, it would just freeze when I typed sshd, and "start-service sshd" would return there is no service named sshd. I really need this computer to have an ssh server, as I need to access it from work, please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Installation of OpenSSH For Windows Server](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
