### ISSUE TITLE
Privilege requirements for Get-PartitionSupportedSize

### ISSUE THREAD

**Issue by AurimasNav** [MicrosoftDocs/windowsserverdocs#4647]
What are the required privileges to be able to use ```Get-PartitionSupportedSize```? I have a user rights assignment for "Perform volume maintenance tasks", but it does not seem to be sufficient:

```powershell
Get-PartitionSupportedSize : Access to a CIM resource was not available to the client.
At line:1 char:1
+ Get-PartitionSupportedSize -DriveLetter D
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (MSFT_Partition ...indows/Stor...):ROOT/Microsoft/.../MSFT_Partition) [Get-PartitionSupportedSize], CimException
    + FullyQualifiedErrorId : MI RESULT 2,Get-PartitionSupportedSize
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2beddb54-a9ed-b53e-c8e1-152069c2c5c4
* Version Independent ID: 8aa0fe83-1e7f-3636-2122-477afd35a657
* Content: [Extend a basic volume](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/extend-a-basic-volume)
* Content Source: [WindowsServerDocs/storage/disk-management/extend-a-basic-volume.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/extend-a-basic-volume.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users
a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Otherwise, if you prefer to wait for solutions here, I hope you have a lot of patience.

**Comment by AurimasNav** [comment]
One could say the documentation is incomplete as it does not specify what privileges are required to be able to perform described tasks.

**Comment by illfated** [comment]
Fair enough. Let us wait for feedback from someone who knows what needs to be added in the documentation.

**Comment by Xelu86** [comment]
@assign:xelu86
