### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by teamneroblanco** [MicrosoftDocs/windowsserverdocs#4651]
[Enter feedback here]
 The link under automatic mdm enrolment is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74d09c81-d205-dbd0-ea6a-aaf469eadf5c
* Version Independent ID: 458db848-1b30-1115-8814-3a639a57c70b
* Content: [Configure Device-based Conditional Access on-Premises](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-device-based-conditional-access-on-premises)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-Device-Based-Conditional-Access-on-Premises.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-Device-Based-Conditional-Access-on-Premises.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Specific details: Paragraph section **Automatic MDM enrollment**
- https://docs.microsoft.com/windows-server/identity/ad-fs/operations/configure-device-based-conditional-access-on-premises#automatic-mdm-enrollment

**Automatic MDM enrollment**
To enable automatic MDM enrollment of registered devices so that you can use the isCompliant claim in your access control policy, follow the steps [here](https://blogs.technet.microsoft.com/ad/2015/08/14/windows-10-azure-ad-and-microsoft-intune-automatic-mdm-enrollment-powered-by-the-cloud/).

Broken URL: https://blogs.technet.microsoft.com/ad/2015/08/14/windows-10-azure-ad-and-microsoft-intune-automatic-mdm-enrollment-powered-by-the-cloud/

***

From experience, most of the TechNet blog pages are now hosted on a slightly different domain structure:
- https://techcommunity.microsoft.com/t5/custom/page/page-id/Blogs

***

So after doing a quick search, based on this knowledge, the working, up-to-date blog link URL is this one:
- https://techcommunity.microsoft.com/t5/azure-active-directory-identity/windows-10-azure-ad-and-microsoft-intune-automatic-mdm/ba-p/244067

**Comment by illfated** [comment]
I will get back to this later today and open a Pull Request to have this link URL updated.

**Comment by illfated** [comment]
Link corrected from
https://blogs.technet.microsoft.com/ad/2015/08/14/windows-10-azure-ad-and-microsoft-intune-automatic-mdm-enrollment-powered-by-the-cloud/

to https://docs.microsoft.com/en-us/windows/client-management/join-windows-10-mobile-to-azure-active-directory

in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/60b7e505e0580ba8eeff6ee96c9172e8c42ed630 as of July 22, 2020 (direct file link https://github.com/MicrosoftDocs/windowsserverdocs/commit/60b7e505e0580ba8eeff6ee96c9172e8c42ed630#diff-6df6593c8c6582bf1db0a1347e16f2c57a2e89703ed6233d83d3de2512a7f5c2).

**Comment by illfated** [comment]
#please-close
