### ISSUE TITLE
2019?

### ISSUE THREAD

**Issue by lefty44** [MicrosoftDocs/windowsserverdocs#4657]
Hi,
is this info also applicable on Windows Server 2019?
THanks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 666fb8cb-b1e5-c7b6-6326-cd172a2bf4b2
* Version Independent ID: 3d899ddb-c33f-28e6-3154-af039e28521a
* Content: [Upgrade Domain Controllers to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

Unfortunately, I don't have personal experience with the 2019 Server interface, because I have not had time or the opportunity to play around with the Windows Server 2019 user interface, least of all to test the actual productive capabilities in a replicated production environment. Please also note that this GitHub repository is primarily for reporting issues with the MS Docs pages.

Depending on which specific information you are looking for, I would think these pages could be a better start:

- https://docs.microsoft.com/windows-server/get-started-19/install-upgrade-migrate-19
- https://docs.microsoft.com/windows-server/upgrade/upgrade-2016-to-2019
- https://docs.microsoft.com/windows-server/get-started-19/app-compat-19
- https://docs.microsoft.com/windows-server/identity/ad-ds/ad-ds-getting-started
- https://docs.microsoft.com/windows-server/get-started-19/removed-features
- https://docs.microsoft.com/windows-server/get-started-19/removed-features-19

Then again, if there are no changes in the AD DS interfaces from 2016 to 2019, the answer to your question may simply be "Yes".

The most productive way to find the answer to your question would be if you are in a position to download and run a trial version of Windows Server 2019 on either a dedicated physical computer or a VM, so you can inspect the GUI and test the description on the page you posted your question from. Based on this, it would be very helpful if you could comment on any differences or similarities you find.

I am aware that some of these pages may be quite outdated, especially when it comes to the nitty-gritty details regarding command-line utilities, topical structures (like how the Active Directory is built structurally and theoretically) so you may find some of the documentation in need of updating. Some of the pages even link back to very old versions of Windows Server, like 2008 (not R2) and 2003. Feel free to report what you find to be completely missing, while you are browsing for specific documentation.

**Comment by IngridAtMicrosoft** [comment]
Applies to section updated to include 2019. Closing.
