### ISSUE TITLE
DLL written to be called by rundll32 does not work for certain DeviceID (COM ports) DEV_0501

### ISSUE THREAD

**Issue by cinderbdt** [MicrosoftDocs/windowsserverdocs#4659]
Redirected from:
https://github.com/MicrosoftDocs/windows-driver-docs/issues/2104

This does not seem to work for COM ports in Windows 10?
rundll32.exe devmgr.dll,DeviceProperties_RunDLL /MachineID "" /DeviceID "ACPI\VEN_PNP&DEV_0501"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09a448aa-499f-1489-5cd5-b519cb4be8d2
* Version Independent ID: f8c0c0a4-2ca0-a7a4-d56a-3457ea6eec46
* Content: [rundll32](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/rundll32)
* Content Source: [WindowsServerDocs/administration/windows-commands/rundll32.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/rundll32.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
I tested the command on my computer, but it did not give me any feedback, no error and no message what so ever.
*
Knowing how much Windows 10 has evolved beyond Windows 7 and earlier versions, I presume you need to use a vendor-specific driver for Windows 10.
What kind of device is `ACPI\VEN_PNP&DEV_0501` ?
*
You may be interested in pages similar to this one:

- https://www.driveridentifier.com/scan/download.php/download/452146606/1F8E736559F740E3939F5B46EDCEF420/ACPI%5cPNP0501

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.
Please also note that this part of the repository (MicrosoftDocs/windowsserverdocs) is mostly about Windows Server OS versions and their administrative tools.

Windows 10 has its own documentation pages, but I presume you have not found much about `rundll32.exe` in those pages.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by cinderbdt** [comment]
I determined that this works when using /DeviceID "ACPI\PNP0501\0", which is second in the list of "Hardware Ids" in the Details tab of the dialog box. PnPUtil helped me to find that.

`rundll32.exe devmgr.dll,DeviceProperties_RunDLL /MachineID "" /DeviceID "ACPI\PNP0501\0"`

<img width="304" alt="Communications Port dialog box" src="https://user-images.githubusercontent.com/24484594/117296851-fe633380-ae21-11eb-9627-0b6e5c3c8608.png">
[PNPUTIL_ENUM-DEVICES_CLASS_PORTS_PROPERTIES.txt](https://github.com/MicrosoftDocs/windowsserverdocs/files/6434459/PNPUTIL_ENUM-DEVICES_CLASS_PORTS_PROPERTIES.txt)

**Comment by Xelu86** [comment]
@assign:xelu86

**Comment by Xelu86** [comment]
Hey @cinderbdt,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing a problem with the product itself and not with the product documentation. GitHub isn't quite the right location if searching for technical support or feature requests as it is completely outside our scope. It is mainly for documentation updates, improvement, and clarity. If there are any issues within the content itself, please let us know.

To get assistance or support for your product issue, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of our product experts in these communities can better assist. We will now be closing this thread. Thank you and we wish you a most pleasant day. 
#please-close
