### ISSUE TITLE
The repository 'https://packages.microsoft.com/ubuntu/19.04/prod bionic Release' does not have a Release file.

### ISSUE THREAD

**Issue by dgtlrift** [MicrosoftDocs/windowsserverdocs#4663]
Following the instructions, for ubuntu, I get the error:

`E: The repository 'https://packages.microsoft.com/ubuntu/19.04/prod bionic Release' does not have a Release file.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25943cc5-9927-5ca7-b9db-4c1d398726c5
* Version Independent ID: ae5bf48b-26cf-b5c8-22c8-68fa9a70258f
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Product: **windows-server**
* Technology: **compute**
* GitHub Login: @szarkos
* Microsoft Alias: **szark**

**Comment by illfated** [comment]
@konstruktoid : Sorry for troubling you, but are you able to offer some insight here, or do you know anything at all about this?

**Comment by konstruktoid** [comment]
Hi @dgtlrift, and thanks for creating this issue.
It seems there's a mismatch since `https://packages.microsoft.com/ubuntu/19.04/prod bionic Release` contains both `19.04` which is codenamed `Eoan Ermine` and `bionic` which is release `18.04`.

Did you perhaps run `sudo apt-add-repository https://packages.microsoft.com/ubuntu/19.04/prod` on a server running Ubuntu 18.04?

A working `apt` source line for 19.04:
`deb https://packages.microsoft.com/ubuntu/19.04/prod disco main`

NB that Ubuntu 19.04 was EOL 2020-01-01.

(@illfated, never any troubles.)

**Comment by illfated** [comment]
Thank you. Very good follow-up. Looks promising.

**Comment by illfated** [comment]
#please-close
