### ISSUE TITLE
PowerShell cmdlet links go to wrong page

### ISSUE THREAD

**Issue by silvermarkg** [MicrosoftDocs/windowsserverdocs#4674]
The links for the PowerShell cmdlets take you to a page about Certificate Templates for Server 2008. I would fix them but not sure how to link to another doc repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbeabe4-15fa-65dd-9fe2-126ceadc96a1
* Version Independent ID: 7a8534d6-56b3-ae36-463c-158ebb5e86bc
* Content: [Advanced Data Deduplication settings](https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/advanced-settings)
* Content Source: [WindowsServerDocs/storage/data-deduplication/advanced-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/data-deduplication/advanced-settings.md)
* Product: **windows-server**
* Technology: **storage-deduplication**
* GitHub Login: @wmgries
* Microsoft Alias: **wgries**

**Comment by illfated** [comment]
Fair question. Looking at the raw source text, it appears that the current links intentionally point to the older pages (`/previous-versions/`) :

- https://raw.githubusercontent.com/MicrosoftDocs/windowsserverdocs/master/WindowsServerDocs/storage/data-deduplication/advanced-settings.md

Do you have the links you recommend using instead, so I may have a look at how to update the URLs to point to those pages instead?

**Comment by silvermarkg** [comment]
Get-DedupSchedule - https://docs.microsoft.com/en-us/powershell/module/deduplication/get-dedupschedule?view=win10-ps
New-DedupSchedule - https://docs.microsoft.com/en-us/powershell/module/deduplication/new-dedupschedule?view=win10-ps
Set-DedupSchedule - https://docs.microsoft.com/en-us/powershell/module/deduplication/set-dedupschedule?view=win10-ps
Remove-DedupSchedule - https://docs.microsoft.com/en-us/powershell/module/deduplication/remove-dedupschedule?view=win10-ps

**Comment by illfated** [comment]
Sorry for having put off this issue for so long. I was weighing for and against looking up the GitHub version of the current pages to add as links instead of the outdated links, but that is clearly unhelpful, seeing now that the old links are clearly pointing to the old page hierarchy on docs.microsoft.com, before the separation of the new and current PowerShell Docs pages. I will use your suggested links, since they are clearly working well. The only modification I will apply is to remove the language-specific part (`/en-us/`) to make the pages language agnostic, in accordance with the current codestyle recommendations of the Microsoft Docs.

**Comment by illfated** [comment]
There you go. Thank you for reporting the issue and for providing the correct links for each cmdlet. Feel free to visit Pull Request #4875 and comment, if you want.
