### ISSUE TITLE
Which Android app to use?

### ISSUE THREAD

**Issue by cglong** [MicrosoftDocs/windowsserverdocs#4686]
There's two Android apps listed in Google Play ([#1](https://play.google.com/store/apps/details?id=com.microsoft.rdc.android), [#2](https://play.google.com/store/apps/details?id=com.microsoft.rdc.androidx)); I'm not sure which one I should use. Are both going to continue being supported for the long term, or should I use the newer one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f7187f-7e2e-da7f-6f46-46568be43db7
* Version Independent ID: 49714e7e-ecfb-dba3-f43a-17b6ca677fa6
* Content: [Remote Desktop clients](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by RAJU2529** [comment]
@cglong  #1 for windows 8. #2 for windows 10

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey cglong,

Thanks for contacting Microsoft. We value your feedback.

Since the time this issue was opened, there is only 1 Remote Desktop app available for [Android](https://play.google.com/store/apps/details?id=com.microsoft.rdc.androidx). As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
