### ISSUE TITLE
Security warnings should be added.

### ISSUE THREAD

**Issue by beaukinstler** [MicrosoftDocs/windowsserverdocs#4697]
This document needs more security warnings. The prevalence of Terminal Services bugs that have been exposed over the years make it a very bad idea to expose RDP to the web. The VPN section should be highlighted, and the first choice, with the port forwarding section flooded with warnings and discouraged. Also, a mention of multi-factor would be smart.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb3496f-9df6-8859-4569-ea033daed5ac
* Version Independent ID: 9f762b67-575d-ea11-08d5-edbab9a21f15
* Content: [Remote Desktop - Allow access to your PC from outside your network](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **elizapo**

**Comment by dksimpson** [comment]
Hello @beaukinstler,

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
