### ISSUE TITLE
URI Prefix Matching for OAuth2 Relying Party Identifiers

### ISSUE THREAD

**Issue by kabronkline** [MicrosoftDocs/windowsserverdocs#4698]
By default none of this appears to be true for an OAuth2 relying party identifier. In testing ADFS 2019 it looks like the URI must be an exact match. Am I missing something? Does this page need to be clarified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82992476-4dc0-f5d6-f032-628e81c9d453
* Version Independent ID: 88068096-3473-f8b0-e2d5-e1685164c098
* Content: [How URIs Are Used in AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/how-uris-are-used-in-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/technical-reference/How-URIs-Are-Used-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/technical-reference/How-URIs-Are-Used-in-AD-FS.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
