### ISSUE TITLE
Does not list possible ssh commands

### ISSUE THREAD

**Issue by morgzz** [MicrosoftDocs/windowsserverdocs#4726]
[Enter feedback here]
Searched everywhere on the internet, this page or Microsoft documentation does not list possible ssh powershell commands.

How do you list what ssh keys have been loaded ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
You could look inside the files you find in the directory or folder `~/.ssh/.` where ~ (tilde) means the authorized SSH installer user account in Windows.

There is also the command or program file `ssh-keyscan.exe` which aids in collecting the public SSH host keys from a number of hosts.

Unfortunately, I don't know enough about these details to prove support as such.

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by RAJU2529** [comment]
@morgzz .Below all  the possible commands

usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] 
           [-B bind_interface]
           [-b bind_address] 
           [-c cipher_spec] 
           [-D [bind_address:]port]
           [-E log_file] 
           [-e escape_char] 
           [-F configfile]
           [-I pkcs11]
           [-i identity_file]
           [-J [user@]host[:port]] 
           [-L address]
           [-l login_name]
           [-m mac_spec]
           [-O ctl_cmd]
           [-o option]  
           [-p port]
           [-Q query_option]
           [-R address]
           [-S ctl_path] 
           [-W host:port]
           [-w local_tun[:remote_tun]] 
           destination [command]

**Comment by dknappettmsft** [comment]
The answer has been provided in this thread.

#please-close
