### ISSUE TITLE
Please provide clarification on Windows version

### ISSUE THREAD

**Issue by KrupalJoshi** [MicrosoftDocs/windowsserverdocs#4748]
[Enter feedback here]
In the page https://docs.microsoft.com/en-us/windows-server/failover-clustering/failover-cluster-csvs?source=docs

The statement in 1st paragraph "`(In Windows Server 2012 R2, the disk can be provisioned as NTFS or Resilient File System (ReFS).)`". Does it mean ReFS for CSV is only supported for Windows server 2012 R2? Or here "Windows server 2012 R2" means "Windows Server 2012 R2 later"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b417d33d-000d-5ae8-2525-663849e5e62a
* Version Independent ID: 16ccda8e-9d73-053f-4b67-20eaeac524bf
* Content: [Use Cluster Shared Volumes in a failover cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/failover-cluster-csvs?source=docs)
* Content Source: [WindowsServerDocs/failover-clustering/failover-cluster-csvs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/failover-cluster-csvs.md)
* Product: **windows-server**
* Technology: **failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @KrupalJoshi,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made clarifying the wording since the opening of this GitHub issue. We hope that the new verbiage is clearer regarding that CVS ReFS is supported in Windows Server 2012 R2 and above. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
