### ISSUE TITLE
Trial license period

### ISSUE THREAD

**Issue by scsummers** [MicrosoftDocs/windowsserverdocs#4758]
The article states that the trial license is 180 days but it is actually 120.

![RDSTrial](https://user-images.githubusercontent.com/37189552/91565522-f43e7c00-e907-11ea-8b18-0f7ba14f4c2b.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd015c0b-3360-88fd-86b1-08e8c0e8ec5e
* Version Independent ID: 0c3ddb09-23f3-68a3-e7a4-877951feb55b
* Content: [License your RDS deployment with client access licenses (CALs)](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by v-thepet** [comment]
Hello @scsummers,

Thanks again for contacting Microsoft. We value your feedback.

At the time this GitHub issue was created, the grace period in the documentation was updated to 120 days and this issue was not closed. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
