### ISSUE TITLE
Mention that VM Montitor Mode Extensions are Associated with Intel VT-d or AMD-Vi

### ISSUE THREAD

**Issue by franklesniak** [MicrosoftDocs/windowsserverdocs#4811]
It'd be nice to clarify that "VM Monitor Mode Extensions" are associated with Intel VT-d or AMD-Vi.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb08c5b-865d-26b5-0867-de14e87a205c
* Version Independent ID: 5eacc1db-a948-722b-d3d5-ae0f281e9e30
* Content: [System requirements for Hyper-V on Windows Server](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/system-requirements-for-hyper-v-on-windows)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/System-requirements-for-Hyper-V-on-Windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/System-requirements-for-Hyper-V-on-Windows.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by dksimpson** [comment]
Hi @franklesniak,
This info is now in the article. We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close

**Comment by franklesniak** [comment]
Thanks!
