### ISSUE TITLE
6.3. Configuring probe - link no longer works

### ISSUE THREAD

**Issue by yeswps** [MicrosoftDocs/windowsserverdocs#4813]
[Enter feedback here]
This link no longer works: https://blogs.technet.microsoft.com/applicationproxyblog/2014/10/17/hardware-load-balancer-health-checks-and-web-application-proxy-ad-fs-2012-r2/

I was able to find the archive page here:
https://web.archive.org/web/20200309090136/https://blogs.technet.microsoft.com/applicationproxyblog/2014/10/17/hardware-load-balancer-health-checks-and-web-application-proxy-ad-fs-2012-r2/

Please update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ac8cd29-26cd-47da-5b3e-d58ba7c4a20c
* Version Independent ID: ae9587c8-0822-f5af-98ef-5386c4f17e58
* Content: [Active Directory Federation Services in Azure](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md)
* Sub-service: **hybrid**
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
No luck so far finding anything but Azure AD blogs on the current version of "TechNet blogs" (https://techcommunity.microsoft.com/t5/azure-active-directory-identity/bg-p/Identity - same page as the old link resolves to now). Looks like Microsoft is focusing on the use of Azure AD instead of on-premise solutions, at least when it comes to blogs as old as 2014 for Windows Server 2012 R2.

Some other search attempts:
- https://docs.microsoft.com/en-us/archive/blogs/ (no luck finding the original author Ian Parramore in that register)
- https://docs.microsoft.com/en-us/search/?dataSource=previousVersions&terms=Hardware%20Load%20Balancer%20Health%20Checks%20and%20Web%20Application%20Proxy%20%2F%20AD%20FS%202012%20R2
- https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn486820(v=ws.11) (Windows Server 2012 R2 AD FS Deployment Guide)
- https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn486832(v=ws.11) (Deploying Federation Server Proxies)

I don't know, but it might look like Microsoft has completely removed the original page you are looking for (maybe for security & support reasons?), so the only available versions now are the Web Archive pages.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 4793 -b #assign:IngridAtMicrosoft

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
