### ISSUE TITLE
Documentation Manuals 

### ISSUE THREAD

**Issue by zftsss** [MicrosoftDocs/windowsserverdocs#4827]
[How to find the relevant documentation, manuals in the current present command line interface one is interacting with inside of any one of the Microsoft Windows Operating Systems either or any Office or whatever Server whatever or what ever else word is associated with the device low level software accessible through the command line, terminal, UI, virtual or whatever word is associated with a non graphical user interface  .]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d382ca0-6538-5e1d-3e83-e31c9ab6a911
* Version Independent ID: 11eff296-6158-f89a-4941-8735529183e9
* Content: [Windows commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands)
* Content Source: [WindowsServerDocs/administration/windows-commands/windows-commands.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/windows-commands.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by zftsss** [comment]
I do apologize for what I did write. I should have known better from previous experience in open source that to find answers takes a lot of researching. I do not have the clock time to write scripts nor data storage to accommodate w-get to pull all of Microsofts HTMl or XML files and sort them by OS. And then index the sub-subjects in each OS. And create tables of reference for the command-lets that are available in same OS`s And Servers. Interesting enough , when the computers were made one of their purposes was storing data after accumulation. Yes we know that. Yet I take it for granted that a Corporation would assimilate their data into comprehensible indexing by OS and its sub subjects and so on. We could take a hint from biology in animal and plant families and as to how they are cataloged by family etc. Or a modern day Library. Thank you
