### ISSUE TITLE
FeedDiscovery URL Error

### ISSUE THREAD

**Issue by imrananwar** [MicrosoftDocs/windowsserverdocs#4843]
[Enter feedback here]
Checking for a feed at listed URL https://rdweb.wvd.microsoft.com/api/arm/feeddiscovery gives:

{
  "error": {
    "code": "INCOMPATIBLE_CLIENT_VERSION",
    "message": "Client did not send any User Agent approved header"
  }
}
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0517ea6a-9417-31a8-39a5-f6128387fee5
* Version Independent ID: 7636ec70-e1dd-8c6b-516c-8af324d9f645
* Content: [Get started with the macOS client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Well, that is also the response I get when clicking the link in a web browser.
Seems like that address expects a specific client software and version, not a web browser.

How did you test the link yourself?

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey imrananwar,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with a Windows product or service, rather than the documentation itself.

GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. We offer other channels for engaging with us, whether you have a support question, product feedback, or other feedback. 

We cannot assist with the following as it's outside our scope of work:

- Support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, please use one or more of the following:

 - On a Windows OS, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
