### ISSUE TITLE
Instructions incomplete

### ISSUE THREAD

**Issue by MichaelMc64** [MicrosoftDocs/windowsserverdocs#4847]
Instructions state to run systeminfo.exe and "Scroll to the Hyper-V Requirements section to review the report."
Running systeminfo.exe on a Windows 2019 server yields the following:
"Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed."

So, where do I actually go to discover the system requirements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb08c5b-865d-26b5-0867-de14e87a205c
* Version Independent ID: 5eacc1db-a948-722b-d3d5-ae0f281e9e30
* Content: [System requirements for Hyper-V on Windows Server](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/system-requirements-for-hyper-v-on-windows)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/System-requirements-for-Hyper-V-on-Windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/System-requirements-for-Hyper-V-on-Windows.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by dksimpson** [comment]
Hi @MichaelMc64,

The documentation is correct. For devices that provide a minimal UEFI, virtualization settings are enabled by default, but can't be accessed, which is indicated by the message "A hypervisor has been detected. Features required for Hyper-V will not be displayed." For more information, see [Windows 10 Hyper-V System Requirements](https://learn.microsoft.com/virtualization/hyper-v-on-windows/reference/hyper-v-requirements).

For additional support, see:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
