### ISSUE TITLE
Hi, Microsoft

### ISSUE THREAD

**Issue by Poinprick** [MicrosoftDocs/windowsserverdocs#4848]
Feedback on the examples error 101 >>[ I believe you guys should give people an example on how to use < [/deny <sid>:[...]] > as well because it's a bit hard to understand how to write it after reading the whole instruction.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5906879b-e678-e3da-c404-07a437b42cc2
* Version Independent ID: 0779c597-9e20-38e0-3ae7-40126f5c2bcb
* Content: [icacls](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/icacls#examples)
* Content Source: [WindowsServerDocs/administration/windows-commands/icacls.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/icacls.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Not only is it difficult to find out, it is tough to make sure any documentation you write for use of `/Deny` is correct. There are several rabbit holes in this area, so I would not go there unless paid to do so. For example, the Delete permission (D) must be specified as (DE) for it to work, because there is a bug in icacls for this parameter.

If I were you, I would consider looking for a 3rd party alternative, at least if there are alternatives with good documentation and a positive reputation among IT pros.

**Comment by dksimpson** [comment]
Hello @Poinprick,

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close

**Comment by Xelu86** [comment]
#assign:xelu86
