### ISSUE TITLE
Updating the registry settings for the default priority ordering is not supported and may be reset with servicing updates?

### ISSUE THREAD

**Issue by wuwang166666** [MicrosoftDocs/windowsserverdocs#4853]
I can't understand this sentence, what the registry settings  means? Please explain to me

**Comment by RAJU2529** [comment]
@wuwang166666 , which article are you referring?

**Comment by wuwang166666** [comment]
> @wuwang166666 , which article are you referring?

referring from microsoft Official document : https://docs.microsoft.com/en-us/windows-server/security/tls/manage-tls
quote as follow :
"Configuring TLS Cipher Suite Order
Different Windows versions support different TLS cipher suites and priority order. See Cipher Suites in TLS/SSL (Schannel SSP) for the default order supported by the Microsoft Schannel Provider in different Windows versions.
Note
You can also modify the list of cipher suites by using CNG functions, see Prioritizing Schannel Cipher Suites for details.
Changes to the TLS cipher suite order will take effect on the next boot. Until restart or shutdown, the existing order will be in effect.
Warning
Updating the registry settings for the default priority ordering is not supported and may be reset with servicing updates."
I can't understand what the warning means?

**Comment by wuwang166666** [comment]
> @wuwang166666 , which article are you referring?

specifically, where is the registry settings for the default priority ordering? how to update this registry settings and it would be reset by which service? Please give me a hint.

**Comment by wuwang166666** [comment]
> @wuwang166666 , which article are you referring?

**Comment by illfated** [comment]
@wuwang166666 : To answer your question about the warning text and what it means:

> [!WARNING] Updating the registry settings for the default priority ordering is not supported and may be reset with servicing updates.

This means that you should not base your work on making changes to the Registry.
Do not expect that changes you make in the Registry will stay exactly like that until you change it manually yourself.
Software packages within Windows Updates are likely to undo your changes by resetting some Registry settings back to default.

Please contact your local Windows Support service department if you have trouble understanding the documentation.

***

Also: Please consider posting in the user forums instead of asking for help in a repository focused on keeping the documentation content correct and up to date.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions. The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/
