### ISSUE TITLE
RemoteException: A parameter cannot be found that matches parameter name 'IncludeDFSN'

### ISSUE THREAD

**Issue by DirtyBryan007** [MicrosoftDocs/windowsserverdocs#4861]
When trying to add credentials to a job (step 1) I receive this error.

**Comment by illfated** [comment]
Which document page is this about? Do you have a suggestion for improving the page?

**Comment by illfated** [comment]
Never mind, I found at least 1 page that matches your page title:

- https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues#storage-migration-service-inventory-fails-with-a-parameter-cannot-be-found-that-matches-parameter-name-includedfsn

## Storage Migration Service inventory fails with "a parameter cannot be found that matches parameter name 'IncludeDFSN'" 

When using the 2009 version of Windows Admin Center to manage a Windows Server 2019 orchestrator, you receive the following error when you attempt to inventory a source computer:

```
Remote exception : a parameter cannot be found that matches parameter name 'IncludeDFSN'" 
```

To resolve, update the Storage Migration Service extension to at least version 1.113.0 in Windows Admin Center. The update should automatically appear in the feed and prompt for installation.


## See also

- [Storage Migration Service overview](overview.md)

**Comment by illfated** [comment]
Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
