### ISSUE TITLE
Customize Microsoft Remote Desktop App

### ISSUE THREAD

**Issue by pawarvikaskwd** [MicrosoftDocs/windowsserverdocs#4862]
I want to customize Microsoft [Remote Desktop](https://www.microsoft.com/en-us/p/microsoft-remote-desktop/9wzdncrfj3ps#activetab=pivot:overviewtab) app. I want to show the virtualize applications to users depends on custom roles and licensing. I want to change the look and feel of application for company branding. 
Can you please share the document to customize this app?

**Comment by illfated** [comment]
You may have to use the Feedback Hub to discuss this kind of topic, at least to get some help in finding out more about branding.

Try contacting the application support by using the e-mail address from the page you linked: rdwinfbk@microsoft.com

Besides this, you may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
You might be able to find some information ( I don't know whether it is useful or not) on this page:
- https://docs.microsoft.com/windows-server-essentials/install/add-branding-to-the-dashboard--remote-web-access--and-launchpad

**Comment by illfated** [comment]
The only thing I can be certain about, is that this site is not the correct forum for questions about material not covered by the Microsoft ServerDocs.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
