### ISSUE TITLE
Server SAC releases are badly out of date. Where's v2009?

### ISSUE THREAD

**Issue by evan-morris** [MicrosoftDocs/windowsserverdocs#4911]
Server SAC releases are badly out of date. Where's v2009?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf74885-9525-9828-95c9-0ab9167b1f35
* Version Independent ID: f0a39382-120b-0cfa-692f-621124a23f37
* Content: [Windows Server release information](https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info)
* Content Source: [WindowsServerDocs/get-started/windows-server-release-info.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/windows-server-release-info.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @evan-morris,

Thanks again for contacting Microsoft. We value your feedback. 

Had to go down the rabbit hole to gain more insight into this documentation. We discovered that this document belongs to another team that maintains "release info" documents. As this is a cross-repository reference, we forwarded your inquiry to the appropriate team to handle any changes necessary. We do not have a timeframe for when this will be updated as we aren't the owners.

Due to this, any future inquiries about Windows Server Release information will still fall under the Windows Server Docs team as it is a cross-repo. We are more than happy to engage with the owning team if more issues or documentation changes need to be made. 

We will now be closing this thread. Thank you and have a most pleasant day. #please-close
