### ISSUE TITLE
Corrections in BGP Peering and DNS IPs

### ISSUE THREAD

**Issue by TomicaKaniski** [MicrosoftDocs/windowsserverdocs#4918]
1. DC001 & DC002 are missing the default gateway (or specific routes pointing to the GW1)
2. DNS server IPs should be crossed on DC001 & DC002 or you won't be able to add DC002 to the (same) domain
3. Install-RemoteAccess doesn't work if role is not installed (missing step)
4. BGP peering setup is missing the other direction (BGP peer setup on GW1) or it remains "never connected" state
5. We can check BGP route information instead of BGP statistics (it's maybe easier to see that the route is no longer there than statistics)
6. Firewall rules should be added for this all to work (BGP is added automatically, but ping doesn't work OOB)

T.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6d044aa-feb5-8c47-0362-6ccd3e36f262
* Version Independent ID: e8994596-ef61-f6a3-16d3-e6a2bf8d17c9
* Content: [Anycast DNS overview](https://docs.microsoft.com/en-us/windows-server/networking/dns/deploy/anycast)
* Content Source: [WindowsServerDocs/networking/dns/deploy/anycast.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/dns/deploy/anycast.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Thanks for checking these steps. 

1. I had this configuration (including the default gateways) but apparently missed adding it to the article.
2. The problem is that you cannot have DC002 configured as DNS on DC001 until DC002 exists. So the first domain controller will need to specify itself as DNS (DC001).  You're right that DC002 needs to use DC001 to find the domain, but afterward you can switch it back to DC002. After both are added it doesn't matter which is used for DNS on either one - because they are authoritative and don't use their resolver settings to answer queries.  But I should add a note saying to use DC001 at first when setting up DC002.
3. Thanks, I see that the Remote Access Windows PowerShell module is one of the management tools that needs to be installed for the command to work.
4. Thanks again I did add this at one point and I apparently forgot I did it.

PS C:\> get-bgppeer

PeerName LocalIPAddress PeerIPAddress PeerASN OperationMode ConnectivityStatus
-------- -------------- ------------- ------- ------------- ------------------
DC001    10.10.10.254   10.10.10.1    65511   Mixed         Connected
DC002    10.10.10.254   10.10.10.2    65511   Mixed         Connected

5. I never had to adjust the firewall, but I'll add a note to check this.
