### ISSUE TITLE
please include all switches

### ISSUE THREAD

**Issue by schnitz76** [MicrosoftDocs/windowsserverdocs#4921]
The error message on my screen says to use the "/OFFLOGFILE flag".  Please include this switch/flag in your documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d979606-3b11-34e5-70db-88d90855cf5c
* Version Independent ID: d2358e0b-7688-ac7f-0f08-fc198b6a57a9
* Content: [sfc](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sfc)
* Content Source: [WindowsServerDocs/administration/windows-commands/sfc.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/sfc.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
From https://www.windowslatest.com/2019/07/16/microsoft-acknowledges-sfc-error-in-windows-10/ :

```
Windows Resource Protection found corrupt files but was unable to fix some of them.
For online repairs, details are included in the CBS log file located at 
%windir%\Logs\CBS\CBS.log. For example C:\Windows\Logs\CBS\CBS.log. For offline 
repairs, details are included in the log file provided by the /OFFLOGFILE flag.
```

By the way, do you have a server scenario from where this issue has occurred? From what I can tell, based on a couple of quick web searches, that issue seems specific to Windows 10 (desktops/laptops/phones) and not necessarily for Windows Server environments.

**Comment by illfated** [comment]
Please note that the MS Docs section **Windows Server/Windows Commands/Commands by Server Role/** is only a continuation of the old command reference from Windows 2000/2003 era. That section is overdue for an overhaul anyway, but as an external contributor to this repository, I have no insight into when that will happen.

Thank you for your request for the addition of extra documentation for that parameter. I can only hope for this document to be updated at a later time, only knowing that this has been indicated earlier by one of the team members.

Seeing that there has been no update in this ticket for 3 months, I recommend closing this ticket, based on the knowledge that there is an intention of updating all of the Windows Commands/Commands by Server Role/ at a later time, since most of those pages are incomplete, seen from a documentation reference point of view.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
Hey @schnitz76,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made including the mentioned parameter and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
