### ISSUE TITLE
The SQL Server on Linux Link on this page is broken.

### ISSUE THREAD

**Issue by cbonilla88** [MicrosoftDocs/windowsserverdocs#4929]
The SQL Server on Linux Link on this page is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25943cc5-9927-5ca7-b9db-4c1d398726c5
* Version Independent ID: ae5bf48b-26cf-b5c8-22c8-68fa9a70258f
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software?source=docs)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @victorcheng7
* Microsoft Alias: **vichen**

**Comment by illfated** [comment]
Broken link: https://www.microsoft.com/sql-server/sql-server-vnext-including-Linux 
- (We are sorry, the page you requested cannot be found.
 The URL may be misspelled or the page you're looking for is no longer available.)

Most likely replacement candidate:

- https://docs.microsoft.com/sql/linux/sql-server-linux-overview

Based on the fact that the page title (**SQL Server on Linux**) matches the link text and being the entry page for the Linux section, I will open a Pull Request to suggest the URL to be updated to point to that page instead of the missing page and its broken URL.

**Comment by illfated** [comment]
There you go, PR #4934 is now available for review. Feel free to have a look, comment or suggest changes.
