### ISSUE TITLE
Review of the syntax for the command options 

### ISSUE THREAD

**Issue by darugeri** [MicrosoftDocs/windowsserverdocs#4933]
Hello,

I just tried to use diskpart with the command "format /q" and got an error. Then, by using the help command I noticed that the correct option was "QUICK", as in "format QUICK" and that did worked.

Could you take a look at that? Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9fbdba6-cfee-e68d-e1a9-e97d09f0cfad
* Version Independent ID: 26f12948-5d6d-41c2-21ac-538da6e25f7a
* Content: [format](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/format)
* Content Source: [WindowsServerDocs/administration/windows-commands/format.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/format.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
For a moment, I thought you referred to the regular `format` command in the CMD console window. Now I see you are talking about using the format command _within_ the `diskpart` command, either from within its own command line environment or in a script file. Because the regular `format` command still uses only /q as its quick format parameter.

Hmm. The interesting part is this: Where and how do we add the correct information in a correct and useful place?

This implies that we should not link the regular `format` command from the standard CMD commands list.

Then again, have you found any other `diskpart` sub-commands to operate differently from their regular CMD command counterparts? If the answer is yes, that might indicate the need for a more thorough review than just the `diskpart format` parameter.

If there are no other obvious diskpart parameters deviating from their stand-alone counterpart, I will start looking for material to use in the `diskpart format` parameter link.

CMD command line `format` command syntax (non-admin):

```sql
Microsoft Windows [Version 10.0.19041.572]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\illfated>format /?
Formats a disk for use with Windows.

FORMAT volume [/FS:file-system] [/V:label] [/Q] [/L[:state]] [/A:size] [/C] [/I:state] [/X] [/P:passes] [/S:state]
FORMAT volume [/V:label] [/Q] [/F:size] [/P:passes]
FORMAT volume [/V:label] [/Q] [/T:tracks /N:sectors] [/P:passes]
FORMAT volume [/V:label] [/Q] [/P:passes]
FORMAT volume [/Q]
```

CMD in admin mode running `diskpart`:

```css
Microsoft Windows [Version 10.0.19041.572]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>diskpart

Microsoft DiskPart version 10.0.19041.1

Copyright (C) Microsoft Corporation.
On computer: VPCSE2N1E-S

DISKPART> help format

    Formats the specified volume for use with Windows.

Syntax:  FORMAT [[FS=<FS>] [REVISION=<X.XX>] | RECOMMENDED] [LABEL=<"label">]
                [UNIT=<N>] [QUICK] [COMPRESS] [OVERRIDE] [DUPLICATE] [NOWAIT]
                [NOERR]
...
```

**Comment by illfated** [comment]
Another detail worth noting: this ticket has been created from the [format] (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/format) page instead of the [diskpart] (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/diskpart) page, which would have given the following (mostly similar) Document Details section:

[Enter feedback here]


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bca0f8f7-da0d-6340-bf63-f269be5f64d1
* Version Independent ID: 39758423-e92d-d2db-88f3-260dc5a1a26a
* Content: [diskpart](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/diskpart)
* Content Source: [WindowsServerDocs/administration/windows-commands/diskpart.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/diskpart.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
The page **diskpart scripts and examples** (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/diskpart-scripts-and-examples) (not in the TOC list) looks like a small introduction to diskpart parameter usage in scripts, but it neither goes into details of the individual parameters, nor highlighting or listing them with additional explanations.

We need to keep looking for some MS Docs page explaining the `diskpart format` parameter in detail.

**Comment by illfated** [comment]
Hmm. Not a lot of pages or page sections dedicated to the **DISKPART> format quick** parameter information (or even `DISKPART> format` parameter, for that matter).

I wonder if it would be acceptable to change the `format` table row from a link to the Windows Commands list over to being a fully detailed multi-row description for the diskpart version of the command.

**Current content:**

Command | Description
-- | --
. . .
[extend](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/extend) | Extends the volume or partition with focus, along with its file system, into free (unallocated) space on a disk.
[filesystems](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/filesystems) | Displays information about the current file system of the volume with focus and lists the file systems that are supported for formatting the volume.
[format](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/format) | Formats a disk to accept Windows files.
[gpt](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/gpt) | Assigns the gpt attribute(s) to the partition with focus on basic GUID partition table (gpt) disks.
[help](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/help) | Displays a list of the available commands or detailed help information on a specified command.
. . .


**Preliminary draft example modification:**

| Command | Description |
| ------- | ----------- |
|  . . .  |             |
| [extend](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/extend) | Extends the volume or partition with focus, along with its file system, into free (unallocated) space on a disk. |
| [filesystems](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/filesystems) | Displays information about the current file system of the volume with focus and lists the file systems that are supported for formatting the volume. |
| format | Syntax: FORMAT [ [FS=\<FS>] [REVISION=<X.XX>] \| RECOMMENDED ] <br> [LABEL=<"label">] [UNIT=<N>] [QUICK] [COMPRESS] [OVERRIDE] [DUPLICATE] [NOWAIT] [NOERR] |
| [gpt](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/gpt) | Assigns the gpt attribute(s) to the partition with focus on basic GUID partition table (gpt) disks. |
| [help](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/help) | Displays a list of the available commands or detailed help information on a specified command. |
| . . . |  |


... or maybe not. Maybe it needs a separate section below the table. (This is the decision-making part of the process where it would be very useful to know if there are more commands in need of having their description corrected, because then it would be somewhat easier to decide if the table should be split into several tables with separate subsections for each parameter detail.)

**Example page in the PowerShell repository** (heavily featuring help text styled code blocks and detailed tables) :
- https://docs.microsoft.com/en-us/powershell/module/storage/format-volume?view=win10-ps

**Comment by illfated** [comment]
Hang on a doggone minute... I just found the Windows Vista version of the page, in the /previous-versions/ hierarchy:

- https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc766465(v=ws.10)

That page is extensive and highly detailed, so please check it out and provide some feedback on it.


| Command | Syntax | Description |
| ------- | ------ | ----------- |
|  . . .  | ░░░░░░░░░░░░░░░░░░░░░░░░░░ |  . . . . .  |
| **format** | **format**<br><br>  [{ [**FS=\<FS\>**]<br><br><br>  [**REVISION=<X.XX>**]<br><br><br> \| **RECOMMENDED**  }]<br><br><br><br>  **[LABEL=<"label">]<br><br><br>  [UNIT=<N>]<br><br><br><br><br><br>  [QUICK]<br><br><br>  [COMPRESS]<br><br><br>  [OVERRIDE]<br><br><br>  [NOWAIT]<br><br><br><br>  [NOERR]**<br><br><br><br><br><br><br> | Formats the volume or partition. A volume must be selected for this operation to succeed.<br><br> **FS=\<FS>**<br> Specifies the type of file system. If no file system is given, the default file system displayed by the FILESYSTEMS command is used.<br><br> **REVISION = <X.XX>**<br> Specifies the file system revision (if applicable).<br><br> **RECOMMENDED**<br> If specified, use the recommended file system and revision instead of the default if a recommendation exists. The recommended file system (if one exists) is displayed by the FILESYSTEMS command.<br><br> **LABEL=<"label">**<br> Specifies the volume label.<br><br> **UNIT=\<N>**<br> Overrides the default allocation unit size. Default settings are strongly recommended for general use. The default allocation unit size for a particular file system is displayed by the FILESYSTEMS command.<br><br> NTFS compression is not supported for allocation unit sizes above 4096.<br><br> **QUICK**<br> Performs a quick format.<br><br> **COMPRESS**<br> NTFS only: Files created on the new volume will be compressed by default.<br><br> **OVERRIDE**<br> Forces the volume to dismount first if necessary. All opened handles to the volume would no longer be valid.<br><br> **NOWAIT**<br> Forces the command to return immediately while the format process is still in progress. If NOWAIT is not specified, DiskPart will display format progress in percentage.<br><br> **NOERR**<br> For scripting only. When an error is encountered, DiskPart continues to process commands as if the error did not occur. Without the NOERR parameter, an error causes DiskPart to exit with an error code.<br><br> Examples:<br> `FORMAT FS=NTFS LABEL="New Volume" QUICK COMPRESS`<br> `FORMAT RECOMMENDED OVERRIDE`
|  . . .  |  . . . |  . . . . .  |

... and that is only the `format` command parameter. The page is long and crammed with information.

**Comment by darugeri** [comment]
> For a moment, I thought you referred to the regular `format` command in the CMD console window. Now I see you are talking about using the format command _within_ the `diskpart` command, either from within its own command line environment or in a script file. Because the regular `format` command still uses only /q as its quick format parameter.
> 
> Hmm. The interesting part is this: Where and how do we add the correct information in a correct and useful place?
> 
> This implies that we should not link the regular `format` command from the standard CMD commands list.
> 
> Then again, have you found any other `diskpart` sub-commands to operate differently from their regular CMD command counterparts? If the answer is yes, that might indicate the need for a more thorough review than just the `diskpart format` parameter.
> 
> If there are no other obvious diskpart parameters deviating from their stand-alone counterpart, I will start looking for material to use in the `diskpart format` parameter link.
> 
> CMD command line `format` command syntax (non-admin):
> 
> ```sql
> Microsoft Windows [Version 10.0.19041.572]
> (c) 2020 Microsoft Corporation. All rights reserved.
> 
> C:\Users\illfated>format /?
> Formats a disk for use with Windows.
> 
> FORMAT volume [/FS:file-system] [/V:label] [/Q] [/L[:state]] [/A:size] [/C] [/I:state] [/X] [/P:passes] [/S:state]
> FORMAT volume [/V:label] [/Q] [/F:size] [/P:passes]
> FORMAT volume [/V:label] [/Q] [/T:tracks /N:sectors] [/P:passes]
> FORMAT volume [/V:label] [/Q] [/P:passes]
> FORMAT volume [/Q]
> ```
> 
> CMD in admin mode running `diskpart`:
> 
> ```css
> Microsoft Windows [Version 10.0.19041.572]
> (c) 2020 Microsoft Corporation. All rights reserved.
> 
> C:\WINDOWS\system32>diskpart
> 
> Microsoft DiskPart version 10.0.19041.1
> 
> Copyright (C) Microsoft Corporation.
> On computer: VPCSE2N1E-S
> 
> DISKPART> help format
> 
>     Formats the specified volume for use with Windows.
> 
> Syntax:  FORMAT [[FS=<FS>] [REVISION=<X.XX>] | RECOMMENDED] [LABEL=<"label">]
>                 [UNIT=<N>] [QUICK] [COMPRESS] [OVERRIDE] [DUPLICATE] [NOWAIT]
>                 [NOERR]
> ...
> ```

Yes, I meant using the `format` command within the `diskpart` command. I am not quite familiar with that tool, so I would not know if any other commands deviate in their syntax.

**Comment by darugeri** [comment]
> Another detail worth noting: this ticket has been created from the [format] (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/format) page instead of the [diskpart] (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/diskpart) page, which would have given the following (mostly similar) Document Details section:
> 
> [Enter feedback here]
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: bca0f8f7-da0d-6340-bf63-f269be5f64d1
> * Version Independent ID: 39758423-e92d-d2db-88f3-260dc5a1a26a
> * Content: [diskpart](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/diskpart)
> * Content Source: [WindowsServerDocs/administration/windows-commands/diskpart.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/diskpart.md)
> * Product: **windows-server**
> * Technology: **windows-commands**
> * GitHub Login: @JasonGerend
> * Microsoft Alias: **jgerend**

Well, I did hit the feedback button at the `format` page, to which I got after being redirected from the `diskpart` page.

**Comment by illfated** [comment]
> Yes, I meant using the `format` command within the `diskpart` command. I am not quite familiar with that tool, so I would not know if any other commands deviate in their syntax.

Fair enough. Thank you for your feedback. I will read through the Windows Vista page again and see if I should link anything back to that page, or if it makes more sense to add information about the `diskpart format` command pair to the current **diskpart** page. I admit that I haven't had much need to use the `diskpart` command myself, so that is more or less the only piece of information I can start working on. I noticed that the `[DUPLICATE]` parameter is not documented on the Vista page, so I will need to dig up that information from somewhere else, preferably within the microsoft.com domain. Hoping to get to work on this during this weekend.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @darugeri,

Thanks again for contacting Microsoft. We value your feedback. 

As stated by illfated, the syntax between using the `format` command used in CMD and Diskpart are different and not interchangeable.

CMD allows for quick formatting by running: `format <volume> /q`
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/cc730730(v=ws.10)

Diskpart allows for quick formatting by running: `format fs=<filesystem> quick`
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc753770(v=ws.11)

Even PowerShell has its own syntax for the same result (it also does a quick format unless `-Full` is specified): `Format-Volume -DriveLetter <DriveLetter>`
https://learn.microsoft.com/en-us/powershell/module/storage/format-volume?view=windowsserver2022-ps

Hopefully this clarifies the syntax usage. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
