### ISSUE TITLE
Remote Desktop Keyboard Layout

### ISSUE THREAD

**Issue by tdesaules** [MicrosoftDocs/windowsserverdocs#4936]
Hi there,

I'm using the last (I supposed) version and for all my serveur when I use "remote desktop" plugin I have the wrong layout.

I'm using an azerty keyboard
The client is configure in English
I use Windows Server 2016 (french version) 

When I use remote desktop the keyboard layout mapped to the rdd session look like a strnage qwerty style

I don't know if there already exist an issue for that , I can't find it

![image](https://user-images.githubusercontent.com/1481384/97010836-3968de00-1546-11eb-87b6-0f27279a68dd.png)
![image](https://user-images.githubusercontent.com/1481384/97010864-438adc80-1546-11eb-91ff-ffb838e8fde9.png)

**Comment by lampolo82** [comment]
0983254595

**Comment by lampolo82** [comment]
+84983254595

**Comment by lampolo82** [comment]
> +84983254595

$200000000

**Comment by tdesaules** [comment]
Hi there,

Any news regarding the issue ?

**Comment by illfated** [comment]
Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

Please use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

If you by any chance get feedback from Microsoft Support or Microsoft Forum members indicating that the current documentation needs to be amended/improved/adjusted, you are more than welcome to reopen this ticket or open a new ticket regarding your findings.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by tdesaules** [comment]
Noted
