### ISSUE TITLE
404 error on NTP server information link

### ISSUE THREAD

**Issue by MichaelMc64** [MicrosoftDocs/windowsserverdocs#4978]
[Enter feedback here]
For more information on available NTP Servers, see KB 262680, A list of the Simple Network Time Protocol (SNTP) time servers that are available on the Internet

KB262680 and the link provided both lead to a 404 not found page. Usually this page is in Finnish (I'm starting from a US English page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d09b16e-4bbb-91fa-3d84-e7623ec4dc07
* Version Independent ID: b6eadad5-0167-34b6-ed3a-16fa7ee83c60
* Content: [Windows Time service tools and settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
https://www.bing.com/search?q=KB+262680&form=QBLH&sp=-1&pq=kb+262680
- https://mskb.pkisolutions.com/kb/262680
- https://web.archive.org/web/20190919034219/https://support.microsoft.com/en-us/help/262680/a-list-of-the-simple-network-time-protocol-sntp-time-servers-that-are
- https://support.microsoft.com/en-us/topic/how-to-configure-an-authoritative-time-server-in-windows-server-39bdd409-960f-7726-4458-c77bc3a0ef72

Microsoft has removed a lot of KB articles, sometimes because they are heavily outdated and only intended for Windows Server 2000 / 2003 / 2008 (no longer supported OS versions).

You may want to check out these pages too:
- https://en.wikipedia.org/wiki/Network_Time_Protocol
- https://timetoolsltd.com/information/public-ntp-server/
- https://www.ntppool.org/en/

To be honest, NTP is not supposed to be difficult these days, it is mostly point-and-click by typing in a new name, if time.windows.com is not enough for you.

**Comment by illfated** [comment]
Oh right. About the link: I am fairly sure we can just remove the sentence where the link is placed and referenced, so it does not continue to increase the number of disappointed users who would like to see what that KB article is about.

**Comment by Teresa-Motiv** [comment]
Investigated--this link actually appears twice in the file, and has probably never worked. The article exists, but it's internal-only content. I'll start a change order on the doc.

**Comment by illfated** [comment]
Thank you for keeping us informed. The disappearing content has kept me pondering a lot about what happens to outdated Microsoft documentation and the bottomless bit buckets of the internet.

**Comment by Teresa-Motiv** [comment]
I've created a PR on the internal repo to fix this issue. I'm not able to link the PR directly to this issue, but the PR number is 1471.

**Comment by illfated** [comment]
👍🏻 Thank you. I am aware of the internal repo for the MS Docs team members, and also why it is not useful to link anything from it for other users. 🙂

**Comment by Teresa-Motiv** [comment]
Fix has been published from the internal repo; public page has been updated.

**Comment by illfated** [comment]
Nice. Glad to hear that.

@MichaelMc64 : Feel free to check the public page and see if you are satisfied with the changes.

**Comment by illfated** [comment]
See the following link for the main change in the table:
- https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#parameters

The line removal was done near the top of the page, in the **Examples** section below the table of this section:
- https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#w32tmexe-windows-time

The following content was removed:
```diff
- <p>**Note**<br />For more information on available NTP Servers, see KB 262680, [A list of the Simple Network Time Protocol (SNTP) time servers that are available on the Internet](https://support.microsoft.com/help/262680/a-list-of-the-simple-network-time-protocol-sntp-time-servers-that-are)
```

**Comment by illfated** [comment]
@MichaelMc64 : Thank you again for reporting the issue. Feel free to open a new ticket if you find other documentation details in need of correction.

**Comment by illfated** [comment]
#please-close
