### ISSUE TITLE
Markdown issues with windows commands

### ISSUE THREAD

**Issue by b-r-o-c-k** [MicrosoftDocs/windowsserverdocs#50]
Many of the windows commands have problems with markdown formatting. There are angle brackets that should be escaped, and some sections and notes that do not display properly because there isn't enough spacing. The capitalization also seems to have disappeared in many places. I'm guessing these problems resulted from when the documents were converted into markdown.

**Comment by lizap** [comment]
@b-r-o-c-k - Hi! Can you share some specific URLs? I fixed the formatting for what I thought were the last of the broken cmds last week. For those commands, we were displaying the YAML header, instead of starting with the MD. I'll also check the individual commands, but a place to start would help.

Thanks! Liza

**Comment by b-r-o-c-k** [comment]
There is a note for the [cd command](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cd) that contains almost the entire document and the `<path>` inside of the table is interpreted as an html tag because it isn't escaped. Also most of the formatting for the [bcdedit command](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bcdedit) is broken.
