### ISSUE TITLE
Cannot connect to server in WAC through VPN connection

### ISSUE THREAD

**Issue by Kryptoniteee** [MicrosoftDocs/windowsserverdocs#5007]
When i was in the office, I could connect to the server through WAC perfectly. But when I am at home and vpn into the office, I cannot access server through WAC.  I get this error:
![image](https://user-images.githubusercontent.com/50315842/98772069-d8d01100-2420-11eb-8486-e9cfb68dca88.png)

I have already checked that the port was configured to allow WAC connection
![image](https://user-images.githubusercontent.com/50315842/98771861-59dad880-2420-11eb-9b56-ea5588521cc1.png)

**Comment by illfated** [comment]
Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
