### ISSUE TITLE
I wanna find out the Processor Sockets, Cores, Logical Processors calculation rules.

### ISSUE THREAD

**Issue by Eathonhsu** [MicrosoftDocs/windowsserverdocs#5022]
Hi, I wanna find out processor calculation rules.
Our team are developing the next generation of server product that config two physical sockets.
Please refer the figure, we are using in the _Windows Server 2019 Datacenter build 17763._
**Configuration:**
**Two** the next generation processors that included 38 cores. total are **76** cores.
The Performance of task manager will display **4** sockets in the System and platform only have two physical sockets.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/jby7sj7/Sockets4.png" alt="Sockets4" border="0" /></a>
If we try to decrease cores (first processor applied 18 cores and the second applied 19 cores, total 37 cores), The Performance of task manager will display 2 sockets, it is correct.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/qFbhY10/Sockets2.png" alt="Sockets2" border="0" /></a>
So we want to understand what is cores calculation rules for Windows Server 2019, could you help to share this?

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by Eathonhsu** [comment]
Hi,  thanks for you information. I will close it.
