### ISSUE TITLE
Content still relevant?

### ISSUE THREAD

**Issue by cthomasberg** [MicrosoftDocs/windowsserverdocs#5028]
[Enter feedback here]
Is this content still relevant in terms of the requirement of local registry keys etc?
Maybe a reference and scenario/feature compare with the new preview feature https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-authentication-use-email-signin 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f399130-b854-363a-a3b6-f6148a34160e
* Version Independent ID: 27e2aec7-e720-dfbc-20df-4adfe3f02771
* Content: [Configuring Alternate Login ID](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configuring-alternate-login-id)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
