### ISSUE TITLE
Documentation not helpful

### ISSUE THREAD

**Issue by fmokren** [MicrosoftDocs/windowsserverdocs#5029]
This documentation needs examples on using the tool. Makecab.exe is a very complex tool and nearly impossible to use with out examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7d4f538-6c3b-43ba-1563-185f691d2134
* Version Independent ID: c85349af-411c-4cd4-e4c0-5a4d9147a59f
* Content: [makecab](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/makecab)
* Content Source: [WindowsServerDocs/administration/windows-commands/makecab.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/makecab.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by RAJU2529** [comment]
@fmokren . As a normal user, writing negative feedback is easily , but writing article with all necessary details with example in GitHub documentation is not easy. 
Writing article needs complex skills with good formatting . . 
so please change the title to different one.

**Comment by illfated** [comment]
@fmokren : Please note that the **Windows commands/Commands by Server role** directory is not intended as a user manual for each command.

One of the challenges is that this document hierarchy is more or less a descendant of the command list from Windows NT 4.0 and Windows 2000. It was never intended to be a 100% documentation for each and every command, just a simple, straightforward lookup index to get the main idea of how they are used, then search elsewhere for the finer details and information useful for scripting or API use.

Please consider other sources for your personal use, because this part of the documentation is not going to change other than receive corrections and minor updates.

Please use the build-in help function in your OS or reliable internet sources for the complex use you are asking for.

**Comment by illfated** [comment]
However, if you find that there is legitimate, everyday usage where essential information is needed for all users of this command, do not hesitate to open a new ticket with that information available, ideally with links and references to what you know it should look like to be equally useful for all IT Pro users and IT administrators.

Thank you for contributing to make the MS Docs documentation better. See you again soon.

#please-close
