### ISSUE TITLE
`client_credentials` grant flow supports the `resource` parameter which is not documented.

### ISSUE THREAD

**Issue by maxime-jeanson** [MicrosoftDocs/windowsserverdocs#5060]
`client_credentials` grant flow supports the `resource` parameter which is not documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5399f381-2744-9012-2575-b2d1dd110040
* Version Independent ID: c816cb8d-b7b5-6fe7-bcca-b5d0da9efefc
* Content: [AD FS OpenID Connect/OAuth flows and Application Scenarios](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios#client-credentials-grant-flow)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
