### ISSUE TITLE
Azure Mulit-Factor Auth Client Application Enable Step Needs Added

### ISSUE THREAD

**Issue by foi-cpatterson** [MicrosoftDocs/windowsserverdocs#5069]
Please add a section to this document highlighting the need to login to the azure portal, navigate to enterprise applications, and enable the Azure Multi-Factor Auth Client application for the tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f333e8cb-c046-ee06-d33d-d7dc8e8af695
* Version Independent ID: 10838695-f60e-42a7-b0e8-eed7820fd333
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa#step-1-generate-a-certificate-for-azure-mfa-on-each-ad-fs-server-using-the-new-adfsazuremfatenantcertificate-cmdlet)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
