### ISSUE TITLE
Thanks for nice article on this AD FS development

### ISSUE THREAD

**Issue by nickgsoft** [MicrosoftDocs/windowsserverdocs#509]
While testing this Article, we are ok on first login and it goes to  https://localhost:44326/#/Home URL just fine.
 but while navigating to https://localhost:44326/#/TodoList page, it says "{"Message":"Authorization has been denied for this request."}". 
So Any assistance on resolving this issue?? Do we need to add any extra registration for this TOdoList URL on AD FS Server or any special requirement in terms of running the application or configuring AD FS 4.0 web server application screens??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 731a5db9-3e53-0379-edcb-4c338dad0240
* Version Independent ID: 683ef16d-2cbd-7d01-a7da-842f4afb1d8f
* Content: [Build a single page web application using OAuth and ADAL.JS with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/single-page-application-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
@billmath : Since this is not about documentation improvements, wouldn't it be better to close this ticket and refer to a Microsoft Support tenant for Windows Server instead?

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
