### ISSUE TITLE
Can you submit a partpicker list an check to see if compoents would work

### ISSUE THREAD

**Issue by JGFMK** [MicrosoftDocs/windowsserverdocs#5103]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95b94892-aa2a-a130-f89b-311b12ee64a1
* Version Independent ID: 7e29bbc3-d4ec-385e-6d2b-f2a224af9b4f
* Content: [System Requirements for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/get-started/system-requirements)
* Content Source: [WindowsServerDocs/get-started/System-Requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/System-Requirements.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
This is not my article. @eross-msft I would just assign this to you, but it won't let me.

**Comment by illfated** [comment]
@jaimeo : Would you like to see a PR to change the page author for this referenced page? 
Or maybe it is preferable to handle it internally, e.g. as part of a further clean-up for documents you are no longer considered to be the current author?

**Comment by jaimeo** [comment]
That would be great. I haven't been involved in any Windows Server documentation for some years now.

**Comment by illfated** [comment]
@JGFMK : Unfortunately (for you), this repository is not a support instance. It is for documentation purposes only. Let me elaborate:

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
@eross-msft : I am considering whether I should open a PR to update all Windows Server docs to replace "jaimeo" with a different author (24 pages found in a simple search), but I just realized that I may not know if it would be correct to insert your callsign as current author. Do you prefer to make that change internally?

**Comment by illfated** [comment]
@JGFMK : Additional idea from my side: When it comes to parts & partpicker lists, I see that as hardware vendor territory. Please reach out to any vendors in your contact list and ask for a quote on what they make of the documented requirements.

**Comment by eross-msft** [comment]
We need to make these changes internally. I'm going to be going into many of these files in the coming month to fix things like broken and out-of-date metadata, so I will take care of it at that time. In the meantime, it's fine if the author unassigns themselves, I still get alerted about the open issues.

**Comment by illfated** [comment]
Very well. Thank you very much for the update.

**Comment by illfated** [comment]
@JGFMK : We will consider your ticket to be not pertaining to the documentation, so we will go ahead and close it. Feel free to open a new ticket if you find documentation issues you would like to see corrected or updated.

**Comment by illfated** [comment]
#please-close
