### ISSUE TITLE
Incorrect hyperlink

### ISSUE THREAD

**Issue by snowygman** [MicrosoftDocs/windowsserverdocs#5115]
Hey. In the section that deals with RAS Gateway Management tools, there are two links to direct readers to a page about VMM and one for powershell commands.  Both links take us to the same location, i.e. the page about the VMM. 

Please correct the link to take readers to the powershell commands. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3261ecfe-4839-a936-6d3c-87e9e8357d91
* Version Independent ID: bc8931b8-d67c-b05a-5fab-159bf064172a
* Content: [RAS Gateway](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/ras-gateway/RAS-Gateway)
* Content Source: [WindowsServerDocs/remote/remote-access/ras-gateway/RAS-Gateway.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/ras-gateway/RAS-Gateway.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Thank you for noticing and reporting. Yeah, that looks like a copy-paste duplication, an oversight by the page author (or whoever wrote that section later).

Oddly enough, there is an actual intended duplication in this paragraph (**[Remote Access Cmdlets]**), but the links have to be placed correctly.

***

## <a name="bkmk_manage"></a>RAS Gateway Management Tools
Following are the management tools for RAS Gateway.

-   In  Windows Server 2016, to deploy an RAS Gateway router, you must use Windows PowerShell commands. For more information, see  [Remote Access Cmdlets](https://docs.microsoft.com/powershell/module/remoteaccess) for  Windows Server 2016 and Windows 10.

-   In System Center 2012 R2 Virtual Machine Manager (VMM), the RAS Gateway is named Windows Server Gateway. A limited set of Border Gateway Protocol (BGP) configuration options are available in the VMM software interface, including **Local BGP IP Address** and **Autonomous System Numbers (ASN)**, **List of BGP Peer IP Addresses**, and **ASN values**. You can, however, use Remote Access Windows PowerShell BGP commands to configure all other features of Windows Server Gateway. For more information, see  [Virtual Machine Manager (VMM)](https://docs.microsoft.com/system-center/vmm/overview) and [Remote Access Cmdlets](https://docs.microsoft.com/system-center/vmm/overview) for  Windows Server 2016 and Windows 10.

***

I also notice that the links don't work on GitHub, because PowerShell and some other stuff has been moved to their own repositories or a different GitHub directory structure within WindowsServerDocs, so I am going to edit the page and insert the docs.microsoft.com links for all the PowerShell links and some of the known changes, like MEM (SCCM). Anyway, the page is in need of whitespace cleanup, as well as MarkDown checkup, so I will make an overall page cleanup PR for this ticket.

**Comment by illfated** [comment]
There you go. PR #5116 is ready for reading, commenting, review and suggestions.
