### ISSUE TITLE
Can't connect to server with legal notice enabled using MRD app version 10.2.1646.0

### ISSUE THREAD

**Issue by mcoupe2001** [MicrosoftDocs/windowsserverdocs#5120]
On servers with "Message text for users attempting to log on" setting applied via GPO, I do not get the option to click OK.  I just see the message "Connecting to desktop Configuring remote PC...." and eventually it times out. I am using Microsoft Remote Desktop version 10.2.1646.0
![MRD](https://user-images.githubusercontent.com/21247636/102097182-95880a00-3df3-11eb-9edd-7be54ad84bc2.jpg)

**Comment by illfated** [comment]
Which page (URL) sent you here?

**Comment by mcoupe2001** [comment]
> Which page (URL) sent you here?

I clicked on Help tab under Remote Desktop App which took me to "Get started with the Microsoft Store Client" page.  I then scrolled to the very bottom where there's a link for "View all page feedback".

![image](https://user-images.githubusercontent.com/21247636/103178351-144b6100-4850-11eb-9e18-1ca95afa801e.png)

**Comment by illfated** [comment]
OK, thanks, I see. The actual link to use for reporting issues in the documentation, the button named [ **This page** ] should be used:

![image](https://user-images.githubusercontent.com/38162891/103183050-6fad3b80-48b0-11eb-9073-6bd6434e19ed.png)

And in this case, it would have produced something like the following:

***


[Enter feedback here]

On servers with "Message text for users attempting to log on" setting applied via GPO, I do not get the option to click OK. I just see the message "Connecting to desktop Configuring remote PC...." and eventually it times out. I am using Microsoft Remote Desktop version 10.2.1646.0

--(image omitted)--

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc42a8f-2623-4352-7cc4-70f0f61e9d89
* Version Independent ID: 97d8b54b-5e7d-098b-4fb7-e8f6e0b30389
* Content: [Get started with the Microsoft Store Client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Please also be aware that this repository and its issue ticket system is intended only for reporting issues in the documentation pages themselves (document pages on docs.microsoft.com).

Here is a comprehensive message I have composed over the last couple of years I have contributed to these pages in my spare time:

***

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
Unfortunately, it usually takes weeks, if not months, to follow up on questions in tickets where there is no helpful content suggesting improvements for the linked page(s).

I also recommend that you either seek assistance from either Microsoft Support on the phone, or use the forums I listed above (one where you think your issue will be most positively replied to, or all of them). I am only sorry I can't help you with that particular issue, because the scenario is not part of my normal, average work. Try looking around in the Microsoft Forum pages or maybe even alternate Windows forums where this type of issue is discussed ((reddit.com, stackoverflow.com or others).

Your issue could just as easily be on the remote side as it could be on the client side, I don't know. Please use any forum site to ask for help.

**Comment by illfated** [comment]
I am sorry to leave you like this, but if you ever find that there is something important missing or incorrect on the page(s), do not hesitate to post again regarding documentation correction or improvements. The MS Docs team and us contributors are more than happy to receive tickets with practical, useful information to improve the docs.

I wish you the best of luck in your endeavours.

#please-close
