### ISSUE TITLE
Switch from SAC to LTSC

### ISSUE THREAD

**Issue by javoger** [MicrosoftDocs/windowsserverdocs#5131]
Is it possible to switch a running server with SAC to the LTSC channel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd87c102-6f5d-376b-4665-98ff94b4ca41
* Version Independent ID: f6140fb6-30bc-e9e7-463a-bf5bfc926165
* Content: [Windows Server servicing channels](https://docs.microsoft.com/en-us/windows-server/get-started-19/servicing-channels-19)
* Content Source: [WindowsServerDocs/get-started-19/servicing-channels-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/servicing-channels-19.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Before I start looking for the answer, is this question based on an actual scenario at your end?

**Comment by javoger** [comment]
No, its a generel question.

**Comment by illfated** [comment]
Thanks. I will see what I can do to find a reasonably correct answer.

**Comment by illfated** [comment]
Sorry, I have been delayed and it seems too complicated for me in my spare time. Your question topic is too far from my daily work and spare time contribution to the MS Docs.

I would recommend that you try asking in the forums instead, because the users there are more prepared to answer technical questions:

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Please also note that this repository is only intended for documentation improvement, leaving the support questions unanswered for a very long time, if answered at all.

**Comment by Xelu86** [comment]
Hey javoger,

Thanks again for contacting Microsoft. We value your feedback. 

The page referenced is no longer available. To answer your question directly, SAC & LTSC are two different release models, so you cannot switch from one to another. A clean install is required.

SAC was retired on August 9, 2022 and starting from September 2023, Windows Server will only have the LTSC and AC available. To learn more, see https://learn.microsoft.com/en-us/windows-server/get-started/servicing-channels-comparison.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close

**Comment by indigoidk** [comment]
We need a way to covert from LTSC to AC
