### ISSUE TITLE
SetClusterResourceName throws an exception

### ISSUE THREAD

**Issue by vixenathena** [MicrosoftDocs/windowsserverdocs#5136]
During the final cutover for storage migration from Server 2012 to Server 2019, the process gets stuck at 38% and throws an exception.
Exception happened during MapSourceNetworkInterfaces: One or more errors occurred., error=-2146233088, stack=   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.FailoverClusters.Framework.ClusterUtils.TryWaitForResourceState(SafeClusterResourceHandle resourceHandle, String resourceName, ResourceState desiredResourceState, CancellationToken ct, ISmsEventProvider logger)
   at Microsoft.FailoverClusters.Framework.ClusterUtilsProxy.SetClusterIPResource(SafeClusterResourceHandle resourceHandle, String& newResourceName, Nullable`1 enableDHCP, String ipAddress, String clusterName, HashSet`1& resourcesForWhichOnlineFailed, CancellationToken ct)
   at Microsoft.FailoverClusters.Framework.ClusterUtilsProxy.SetClusterIPResourceEnableDhcp(SafeClusterResourceHandle resourceHandle, String& newResourceName, String clusterName, HashSet`1& resourcesForWhichEnableDhcpFailed, HashSet`1& resourcesForWhichOnlineFailed, CancellationToken ct)
   at Microsoft.StorageMigration.Proxy.Cutover.NetworkInterfaceMapper.SetStaticIPOnIpResourceAndEnableDhcpOnOthers(SafeClusterHandle clusterHandle, String clusterName, SafeClusterResourceHandle nnResourceHandle, Win32_NetworkAdapterConfiguration nac, String newIpAddress, Byte prefixLength, HashSet`1& resourcesForWhichAssignIpFailed, HashSet`1& resourcesForWhichEnableDhcpFailed, HashSet`1& resourcesForWhichOnlineFailed)
   at Microsoft.StorageMigration.Proxy.Cutover.NetworkInterfaceMapper.MapSourceInterfaces(List`1& cutoverDeviceEndpoints, NetworkCredential networkCredential, Boolean isLocal, ServerType srcServerType, List`1 networkIpConfigPairs, SSHCredentials sshCredentials, String srcClusterName, String srcClusterNNResourceId)    [d:\os\src\base\dms\proxy\cutover\cutoverproxy\NetworkInterfaceMapper.cs::MapSourceInterfaces::857]

I have already looked at the known issues section and attempted the solutions provided but I run into the same issue as above.

**Comment by illfated** [comment]
Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

I hope you have tried contacting Microsoft Support regarding your issue. This repository is intended for MS Docs documentation issues (errors, corrections, improvement suggestions).

BTW, if this were a support instance forum and not a documentation rework site, I would have asked for a better formatting of the error message to make it more readable. (Then again, if I were working in the correct support instance for something like this, I would probably have access to some kind of filter or template to shape the error data the way I would expect it to be presented as most readable for troubleshooting.) Just to give you an example of some format I could have expected in such a case:

```ruby
Exception happened during MapSourceNetworkInterfaces: One or more errors occurred.
  , error=-2146233088, stack=

    at System.Threading.Tasks.Task.ThrowIfExceptional
        (Boolean includeTaskCanceledExceptions)

    at System.Threading.Tasks.Task_1.GetResultCore
        (Boolean waitCompletionNotification)

    at Microsoft.FailoverClusters.Framework.ClusterUtils.TryWaitForResourceState
        (SafeClusterResourceHandle resourceHandle, 
         String resourceName, 
         ResourceState desiredResourceState, 
         CancellationToken ct, 
         ISmsEventProvider logger)

    at Microsoft.FailoverClusters.Framework.ClusterUtilsProxy.SetClusterIPResource
        (SafeClusterResourceHandle resourceHandle, 
         String& newResourceName, 
         Nullable_1 enableDHCP, 
         String ipAddress, 
         String clusterName, 
         HashSet_1& resourcesForWhichOnlineFailed, 
         CancellationToken ct)

    at Microsoft.FailoverClusters.Framework.ClusterUtilsProxy.SetClusterIPResourceEnableDhcp
        (SafeClusterResourceHandle resourceHandle, 
         String& newResourceName, 
         String clusterName, 
         HashSet_1& resourcesForWhichEnableDhcpFailed, 
         HashSet_1& resourcesForWhichOnlineFailed, 
         CancellationToken ct)

    at Microsoft.StorageMigration.Proxy.Cutover.NetworkInterfaceMapper.SetStaticIPOnIpResourceAndEnableDhcpOnOthers
        (SafeClusterHandle clusterHandle, 
         String clusterName, 
         SafeClusterResourceHandle nnResourceHandle,
         Win32_NetworkAdapterConfiguration nac, 
         String newIpAddress, 
         Byte prefixLength,
         HashSet_1& resourcesForWhichAssignIpFailed, 
         HashSet_1& resourcesForWhichEnableDhcpFailed, 
         HashSet_1& resourcesForWhichOnlineFailed)

    at Microsoft.StorageMigration.Proxy.Cutover.NetworkInterfaceMapper.MapSourceInterfaces
        (List_1& 
         cutoverDeviceEndpoints, 
         NetworkCredential networkCredential, 
         Boolean isLocal, 
         ServerType srcServerType,
         List_1 
         networkIpConfigPairs, 
         SSHCredentials sshCredentials, 
         String srcClusterName, 
         String srcClusterNNResourceId)

[d:\os\src\base\dms\proxy\cutover\cutoverproxy\NetworkInterfaceMapper.cs::MapSourceInterfaces::857]
```
Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub. I don't know your issue or scenario well enough to provide support.

If your issue is in a production scenario, I really hope you have contacted Microsoft Support to get help. Otherwise, if you can't use MS Support, I have some links:
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

**Comment by illfated** [comment]
Also: if you manage to get support or help to resolve your issue, and the results show that there is something wrong in the documentation, don't hesitate to post feedback regarding your findings in contrast to the existing documentation. Please also keep in mind that troubleshooting a complex scenario like yours may uncover issues and causes different from methods or usage recommended by Microsoft. We just don't know yet.

Hope to hear from you soon regarding your progress resolving this issue.

**Comment by vixenathena** [comment]
Trond,

I am so sorry, I wasn't aware that the issues were just for the
documentation. Thank you for making me aware. Also, for letting me know how
to format the error. Yeah, I will open up a case with Microsoft Support and
if there is something that needs to be updated in the documentation, I will
open up an issue on the same github page.

Best,
Nabeelah.

**Comment by illfated** [comment]
Thank you for understanding. Best of luck with your support call and troubleshooting. Also, happy new year. 🙂 🥳

**Comment by illfated** [comment]
Closing this ticket now. Feel free to open a new ticket when you have news about any discrepancies in the documentation, so we can work on corrections.

Thank you for joining in to make the documentation better! 👍🏻

**Comment by illfated** [comment]
#please-close
