### ISSUE TITLE
Azure MFA oath tokens support?

### ISSUE THREAD

**Issue by Treeced** [MicrosoftDocs/windowsserverdocs#5137]
Does this ADFS / Azure MFA integration support oath tokens (like YubiKeys) that are setup with Azure MFA?

Thanks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f333e8cb-c046-ee06-d33d-d7dc8e8af695
* Version Independent ID: 10838695-f60e-42a7-b0e8-eed7820fd333
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
(Sorry for commenting a week later than I intended originally.)

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

Please note that this repository and its team members is not equipped to handle support questions, support issues or other technical queries. This issue tracker is intended to handle reports on issues in the documentation, so your question would be much better handled via real support channels or forums. Let me list some of them for you:

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

***

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 5131 -b #assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Treeced,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing a specific about the product compared to an issue with the documentation. GitHub isn't quite the right location if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, please let us know.
 
We recommend using the support forums in Illfated's last response and hopefully one of the community experts may be able to better assist. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
