### ISSUE TITLE
Define and expand acronyms

### ISSUE THREAD

**Issue by jguerin** [MicrosoftDocs/windowsserverdocs#5140]
There are acronyms on this page that aren't expanded or defined. It's recommend that this is done for best reader comprehension. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6bdcea6-e429-95ce-0012-a30241941e36
* Version Independent ID: b37b7c92-12d0-9d03-c181-05b7cfcbe276
* Content: [Best Practices for securing AD FS and Web Application Proxy](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by jguerin** [comment]
Example here is 'NLB', which I'm assuming is 'Network Load Balancer'?

**Comment by illfated** [comment]
I tried to look for "NLB" — in which paragraph or section did you find it? I am having trouble finding it in the linked document page.

**Comment by illfated** [comment]
> Example here is 'NLB', which I'm assuming is 'Network Load Balancer'?

Yes, that seems to be correct. Looking at the preceding text, I find this sentence (my emphasis added):

> At each layer, AD FS and WAP, a **hardware or software load balancer** is placed in front of the server farm and handles traffic routing.

I agree with you on the point that NLB and its expanded name could have been mentioned in the preceding text. 
Could you make a list of the initialisms and acronyms you find needs expanding for clarification?

**Comment by jguerin** [comment]
> I agree with you on the point that NLB and its expanded name could have been mentioned in the preceding text.
> Could you make a list of the initialisms and acronyms you find needs expanding for clarification?

I will let you do that, I was merely pointing out an instance that I observed that I had to find the meaning for myself. Acronyms in our technical documentation shouldn't be left for the user to decipher unless it's one that's in very wide usage (such as TCP). :)

Thank you for following up!

**Comment by jguerin** [comment]
@illfated doh, I just realised that you're not a Microsoft employee! My bad!

**Comment by illfated** [comment]
No problem. I tend to come across as too much of a "know-it-all", so I don't blame you. 🙂

**Comment by illfated** [comment]
Also, just to leave you some extra info I have picked up during my time here on GitHub, moreover specifically here in the MicrosoftDocs repository, here it goes:

***

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

***

Having much information is a dual-edged sword, it can both be a boon and a drawback. Hope it helps, somehow.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @jguerin,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation update has been made and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
