### ISSUE TITLE
AD Forest Recovery, SYSVOL authoritative restore forest root only, does not make sense to me.

### ISSUE THREAD

**Issue by CXMelga** [MicrosoftDocs/windowsserverdocs#5142]
[Hello
 The document at the following [link ](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/ad-forest-recovery-perform-initial-recovery)

States in a multi-domain forest (parent-child forest) you only perform an authoritative restore  of SYSVOL for the forest root domain (and thereby a non-authoritative restore of SYSVOL for the other domains in the forest.)

This does not make any sense to me as SYSVOL (as far as I am aware has a scope of Domain and not Forest). 

So if you have a forest with three Domains (root.pri,  sub.root.pri  and sub2.sub.root.pri) and performed an authoritative restore of SYSVOL for root.pri but then a non-authoritative SYSVOL restore for the other two sub domains, what happens when you add new domain controllers (e.g. build from scratch and promote in the normal way) to these sub domains? 

I am thinking SYSVOL has a scope of Domain and the only DC in the sub domain (following the initial restore) has a non-authoritative restore of SYSVOL, will it still push out any changes to the new DC? 

Please explain why it says SYSVOL authoritative restore should only be done at the forest root level?

Thanks very much in advance

Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa1b96d-309f-ec35-6365-48baaf7fcb25
* Version Independent ID: d3fbd66c-0abf-a078-faf0-d725b2f2ba04
* Content: [AD Forest Recovery - Perform initial recovery](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/ad-forest-recovery-perform-initial-recovery)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Perform-initial-recovery.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Perform-initial-recovery.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by illfated** [comment]
Please be aware that this repository is intended for documentation improvement based on reliable feedback from the community. This basically means that support questions may not be answered as such, unless the questions provide references to reliable sources showing that the linked document page is in need of improvement or correction based on other known facts. Allow me to add some information I have collected during my own time doing contributions to this repository:

***

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

***

That being said, if you can refer to reliable documentation elsewhere (either from Microsoft or other authoritative sources) confirming that the current linked document [[AD Forest Recovery - Perform initial recovery]](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/ad-forest-recovery-perform-initial-recovery) is incorrect and that the other documentation is showing the correct information, do not hesitate to add that information to this ticket. I would like to create Pull Requests to improve the document, but that needs to be backed up by reliable information stating what the correct description should be.
