### ISSUE TITLE
Windows Server, version 1803 and later are governed by the Modern Lifecycle Policy.

### ISSUE THREAD

**Issue by Olinsa67** [MicrosoftDocs/windowsserverdocs#5156]
[Enter feedback here]

There is a mistake with the note at the bottom of the page, that says "Windows Server, version 1803 and later are governed by the Modern Lifecycle Policy."

But there is no version 1803 that appears in the list of Windows Server current versions by servicing option.

Is it an error with the 1903 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf74885-9525-9828-95c9-0ab9167b1f35
* Version Independent ID: f0a39382-120b-0cfa-692f-621124a23f37
* Content: [Windows Server release information](https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info)
* Content Source: [WindowsServerDocs/get-started/windows-server-release-info.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/windows-server-release-info.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Interesting point, seems possible. I was thinking more of 1809 as a possible alternative.
Then again, it could also be that the Modern Lifecycle Policy applied to 1803, even if it is out of support.
So the statement in itself could be valid, even if it mentions a no longer supported product.

Could be useful to compare with this page showing the support lifecycle and end of support:
- https://docs.microsoft.com/en-us/lifecycle/products/windows-server

**Comment by illfated** [comment]
By the way, it could be useful to get a verification on this answer, just in case it is a typo.

**Comment by illfated** [comment]
It is also useful to remember some (or all) of the terms in the [Modern Lifecycle Policy](https://docs.microsoft.com/en-us/lifecycle/policies/modern):

> The Modern Lifecycle Policy covers products and services that are serviced and supported continuously. Under this policy, the product or service remains in support if the following criteria are met:
>
> 1. **Customers must stay current as per the servicing and system requirements published for the product or service.**
> 2. Customers must be licensed to use the product or service.
> 3. Microsoft must currently offer support for the product or service.

**Comment by Olinsa67** [comment]
Hello,
But the phrase version 1803 and later are governed by the Modern Lifecycle Policy, makes me think all versions are governed, but it is not the case of the 1809... So it is very confusing for the reader.

**Comment by illfated** [comment]
Fair point. I did not know if 1809 was covered or not, so if it is easy to confirm that 1809 is **not** covered by the Modern Lifecycle Policy, I guess we should suggest the change for that sentence to read "Windows Server, version **1903** and later are governed by the Modern Lifecycle Policy."

(Based on my experience with issue tickets in this repository, it is often quicker to get response by creating a Pull Request to have content changed according to what we think is the correct content, instead of waiting for response in the issue tickets.)

**Comment by Olinsa67** [comment]
OK, thank you, so you do a pull request on this subject ?

**Comment by illfated** [comment]
Sure, it is fairly easy, especially with so little change to implement.

**Comment by illfated** [comment]
There you go. PR #5166 is ready for review, comments, and suggestions.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
Assign:xelu86

**Comment by Xelu86** [comment]
Hey @Olinsa67,

Thanks again for contacting Microsoft. We value your feedback. 

Had to go down the rabbit hole to gain more insight into this documentation. We discovered that this document belongs to another team that maintains "release info" documents. As this is a cross-repository reference, we forwarded your inquiry to the appropriate team to handle any changes necessary. We do not have a timeframe for when this will be updated as we aren't the owners.

Due to this, any future inquiries about Windows Server Release information will still fall under the Windows Server Docs team as it is a cross-repo. We are more than happy to engage with the owning team if more issue's or documentation changes need to be made. 

Doing some digging led me to the [Windows Server Modern Lifecycle Policy](https://docs.microsoft.com/en-us/lifecycle/policies/modern) page which is also owned by the same team. It appears as though the earliest build part of this policy is 1709. This page may also need to be updated as not every version is governed by said policy. I'd wait to see what changes the owning team provides.  

We will now be closing this thread. Thank you and have a most pleasant day. #please-close
