### ISSUE TITLE
Which event log are these events logged to?

### ISSUE THREAD

**Issue by rcmpgi** [MicrosoftDocs/windowsserverdocs#5175]
Thanks for the event IDs, but which of the hundreds of event logs should I be looking in to find them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac93bb4-09b7-c1ae-255d-744ea719a0a7
* Version Independent ID: ec6ff685-ea93-cb5f-af9b-45ffe0857db1
* Content: [Automatic virtual machine activation](https://docs.microsoft.com/en-us/windows-server/get-started-19/vm-activation-19)
* Content Source: [WindowsServerDocs/get-started-19/vm-activation-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/vm-activation-19.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
I don't have access to this service in my production environment, but my best guess would be the following:

![image](https://user-images.githubusercontent.com/38162891/103949639-dc8bc580-513b-11eb-971d-d3bff095b87f.png)

**Application and Services Log -> Microsoft -> AppV -> Client -> Virtual Applications**

`%SystemRoot%\System32\Winevt\Logs\Microsoft-AppV-Client%4Virtual Applications.evtx`

To be on the safe side, please use a real support instance like Microsoft Support or the Microsoft Forums. This repository is intended for documentation improvement only.

Wish I could help you more, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by lupisaaa** [comment]
Hola
