### ISSUE TITLE
I'm clueless about using Microsoft Remote Desktop and the instructions aren't much help

### ISSUE THREAD

**Issue by gitclem** [MicrosoftDocs/windowsserverdocs#5201]
This page is really confusing to me.  I'm a Mac guy and I don't know much about Azure or other MS products.

For example, you assume that I understand what you mean by "**Workspace**", which is a technical jargon word that is so widely (ab)used that it almost doesn't mean anything.  I also don't know who my admin is or how they set up the system.  I'm not sure who to ask...

I'm not sure if I used use PCs or Workspaces.  I don't know how to fill out the PCs dialog box, so I went with Workspaces.

I'm trying to add a Workspace per the instructions: https://rdweb.wvd.microsoft.com/api/arm/feeddiscovery

but I have a status box that says "Setting up workspace... Connecting to workspace..." and it's taking FOREVER.

I hit cancel and tried the other URL:  https://rdweb.wvd.microsoft.com/api/feeddiscovery/webfeeddiscovery.aspx

and after entering my email: cwang@medpricer.onmicrosoft.com and password, I get this unhelpful errmsg:

> Error: ADAL failed to acquire claims token
> AADSTS650052: The app needs access to a service (\"https://mrs-Prod.ame.gbl/mrs-RDInfra-prod\") that your organization \"medpricer.onmicrosoft.com\" has not subscribed to or enabled. Contact your IT Admin to review the configuration of your service subscriptions.
> Trace ID: 0fa93af5-8f42-4a8a-a2c6-614e92c90d00
> Correlation ID: 18bc0a31-4c02-4cbb-8888-68e1c1bc10bf
> Timestamp: 2021-01-14 02:36:23Z (211)

I have no idea what to do.  Microsoft needs to do better with vetting instructions with newbies who are really clueless (like me) to make sure they perform the task without any problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0517ea6a-9417-31a8-39a5-f6128387fee5
* Version Independent ID: 7636ec70-e1dd-8c6b-516c-8af324d9f645
* Content: [Get started with the macOS client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Well, I sort of see what you are saying. I agree to some extent as well. I would just like to ask you if this is related to using Microsoft Azure or any other online Microsoft services, because this repository does not function as a support instance. It is here to receive constructive feedback on errors, omissions, suggestions of new material, phrasing, re-phrasing, and so on, until the separate pages are improved enough to be considered useful enough.

The reason I asked you about using online services is that I recommend that you contact the relevant online service support instance to get help.

See also my next comment for some relevant information I have collected during my time as a contributor here in this repository.

**Comment by illfated** [comment]
Please use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
Even though this may seem as a total write-off for your ticket, I want to point out that both the MS Docs team and its users would benefit from feedback based on any support instance interaction leading to any findings that the related documentation needs to be updated in some specific way or other. So please do not hesitate to post any relevant information you come across during your research to find out how these things work.
