### ISSUE TITLE
Complete the page with 

### ISSUE THREAD

**Issue by VinchBE** [MicrosoftDocs/windowsserverdocs#5205]
The print screen on the page show that we should add + Chrome :
Set-AdfsProperties -WIASupportedUserAgents ((Get-ADFSProperties | Select -ExpandProperty WIASupportedUserAgents) + "Chrome")
The reference of +chrome is not take into accountin the command after this sentence : 
In AD FS configuration, add a user agent string for Chrome on Windows-based platforms:
.. command should be completed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf9cb6e-38be-d28e-6ad3-1151b7e1a379
* Version Independent ID: 3eed2746-fc1e-b7c3-ea04-203291aec098
* Content: [Configuring intranet forms-based authentication for devices that do not support WIA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-intranet-forms-based-authentication-for-devices-that-do-not-support-wia)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-intranet-forms-based-authentication-for-devices-that-do-not-support-WIA.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-intranet-forms-based-authentication-for-devices-that-do-not-support-WIA.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
I was looking around for some documentation to support your suggestion, mostly because I feel more confident about making the change if I can back it up with official documentation showing that the suggested change is correct. Then I noticed the following search result:

**Chrome Phasing out Support for User Agent** (March 24, 2020)
- https://www.infoq.com/news/2020/03/chrome-phasing-user-agent/

Does this information have any effect on the suggested change, or is it peripheral as in Not Yet implemented?

**Comment by illfated** [comment]
Don't get me wrong, I am very interested in making necessary changes, whenever needed. I simply prefer to know that the change can be referenced properly.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
