### ISSUE TITLE
Using this tool causes Microsoft Defender Security Center to fire event "ADFS private key extraction attempt"

### ISSUE THREAD

**Issue by mschrisran** [MicrosoftDocs/windowsserverdocs#5217]
The use of this tool causes Microsoft Defender Security Center (Defender ATP) to fire event "ADFS private key extraction attempt" and should be adjusted to no longer cause this.

The alert description says:
"A suspicious LDAP (Lightweight Directory Access Protocol) query was launched. Attackers might be attempting to steal Active Directory Federation Service (ADFS) private keys or move laterally on the network."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f625ecc8-248e-e357-425b-dbd8234eb43f
* Version Independent ID: 383a61c4-2e82-4958-98b4-a0e8c124badb
* Content: [AD FS Rapid Restore Tool](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-rapid-restore-tool)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Interesting report & Feedback. I guess this should be discussed further with the team working on Microsoft Defender for Endpoint (previously known as Microsoft Defender ATP).

@e0i : Would you mind sharing this information internally with the MS Docs team members working on Microsoft Defender for Endpoint, who might be interested in this feedback?

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by andrewwillett** [comment]
This is by design, no? There's no way to certify an attacker using the rapid restore tool for exfiltration of the key vs an authorised user performing a backup?

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @mschrisran, 

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing a potential issue with the product compared to an issue with the documentation. GitHub isn't quite the right location if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, please let us know.

If not already done so, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs) to report this. Since the opening of this GitHub issue, I cannot confirm nor deny if this has been resolved. Please check our other forums if a solution was met.

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
