### ISSUE TITLE
Missing information on "Windows NT 10.0; WOW64; Trident/7.0"

### ISSUE THREAD

**Issue by rmda** [MicrosoftDocs/windowsserverdocs#5235]
"Windows NT 10.0; WOW64; Trident/7.0" appears as a new value on the updated documentation without any mention on the below table explaining the corresponding browser/operating system. It appears this is for IE11 on Windows 10 (please confirm.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd7eb3f6-c00a-453f-a596-6f8bde452cb7
* Version Independent ID: 3250a24b-8e71-a36c-a9a0-7c46bc36acd4
* Content: [Configure browsers to use Windows Integrated Authentication (WIA) with AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-browser-wia)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
