### ISSUE TITLE
example 3 is not correct

### ISSUE THREAD

**Issue by heroes1412** [MicrosoftDocs/windowsserverdocs#5241]
https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/understand-quorum
Three nodes without a witness.

when i have a dag with 3 node + witness (already configured when creating new DAG), but when 1/3 node is failed:
Get-ClusterNode | ft name, dynamicweight, state,id
Name   DynamicWeight State  Id
----   ------------- -----  --
EX1-DC             0  Down  1
EX2-DC             0    Up  2
EX3-DR             1    Up  3

EX2-DC not vote. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a185fb09-b421-337a-c84f-e5eb1c29485d
* Version Independent ID: cf94f4b9-1d56-5d1b-7d66-baf8f5252301
* Content: [Understanding cluster and pool quorum](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/understand-quorum)
* Content Source: [WindowsServerDocs/storage/storage-spaces/understand-quorum.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/understand-quorum.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @adagashe
* Microsoft Alias: **adagashe**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hello @heroes1412,

Thanks again for contacting Microsoft. We value your feedback. The documentation in question appears to have been moved from Windows Server to Azure-Stack, found [here](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/quorum). If the issue or concern is still prevalent, please open this issue under Azure-Stack so that the appropriate teams can make changes.

We'll be closing this issue on the Windows Server end as we cannot action it due to documentation movement. Thank you and have a most pleasant day. #please-close
