### ISSUE TITLE
Read passwords from credential store

### ISSUE THREAD

**Issue by matkoch** [MicrosoftDocs/windowsserverdocs#5299]
How exactly can I access previously-stored passwords? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75cec41-8055-df54-6ce2-c4a32c7d49c4
* Version Independent ID: 11100084-d632-5ac7-0d3a-f13335d35ffe
* Content: [cmdkey](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmdkey)
* Content Source: [WindowsServerDocs/administration/windows-commands/cmdkey.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/cmdkey.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Mike-Crowley** [comment]
This is not possible with cmdkey.exe. For accessing the credential manager programmatically, see projects such as: 

- https://github.com/davotronic5000/PowerShell_Credential_Manager#readme

more info here: 

- https://stackoverflow.com/questions/7162604/get-cached-credentials-in-powershell-from-windows-7-credential-manager
- https://web.archive.org/web/20110823225914/http://msdn.microsoft.com/library/aa480470.aspx

**Comment by dksimpson** [comment]
Hello @matkoch,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
 - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
