### ISSUE TITLE
How do I find [the] used [port] for Windows Admin Center installation?

### ISSUE THREAD

**Issue by israelng** [MicrosoftDocs/windowsserverdocs#5318]
The question title needs an update?

How do I find used for Windows Admin Center installation?

There are two ways to find out the port:

    Navigate to the Windows Admin Center (Preview) extension in the Azure portal. Try to connect via an IP address that will result in a failed connection.
    To verify this value on your VM, open the Registry Editor on your VM and look for the “SmePort” registry key in “\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ServerManagementGateway”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af46722-5b7c-eb50-f6fe-ba7ce4552f85
* Version Independent ID: b2710445-053e-14fd-1cf9-813cdc628d06
* Content: [Use Windows Admin Center in the Azure portal to manage a Windows Server VM](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/manage-vm)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/azure/manage-vm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/azure/manage-vm.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by dksimpson** [comment]
Hello @israelng,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
 - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
