### ISSUE TITLE
What to do when the discovery endpoint provides incomplete data

### ISSUE THREAD

**Issue by paulhickman-a365** [MicrosoftDocs/windowsserverdocs#532]
On my test ADFS server, the last entry in the metadata doc is "userinfo_endpoint" - everything form "capabilities" downwards is missing. How do you configure ADFS to return the remaining fields?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b52b3f3-8e91-e05a-1229-994fb6101e25
* Version Independent ID: e671e43a-3209-22b5-f58c-4f9cc8f8c0a5
* Content: [Single log-out for OpenID Connect with AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-logout-openid-connect)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/ad-fs-logout-openid-connect.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/ad-fs-logout-openid-connect.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Sorry for not visiting your ticket earlier, but I hope you have found a solution elsewhere in the meanwhile.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
