### ISSUE TITLE
Very confusing networking instructions

### ISSUE THREAD

**Issue by aidanfinn** [MicrosoftDocs/windowsserverdocs#5333]
The instructions on configuring the networking for this are very confusing. Do we need to open up ports for every VM we want to manage (wow!) or to a VM that is running Windows Admin Center? Can you please add a step-by-step and a diagram of the network architecture?

I think take-up will be minimal in an enterprise workload. I can't see us recommending this to customers for WAC - we'll probably stick with a more secure method of accessing the WAC site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af46722-5b7c-eb50-f6fe-ba7ce4552f85
* Version Independent ID: b2710445-053e-14fd-1cf9-813cdc628d06
* Content: [Use Windows Admin Center in the Azure portal to manage a Windows Server VM](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/manage-vm)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/azure/manage-vm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/azure/manage-vm.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dksimpson** [comment]
Hello @aidanfinn,

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
