### ISSUE TITLE
Minor typo in article - "configuraion" (actual) vs. "configuration" (expected)

### ISSUE THREAD

**Issue by SphinxKnight** [MicrosoftDocs/windowsserverdocs#5345]
This is just a minor typo I stumbled upon while trying to understand DAX.
I'll submit a PR in a few moments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb4898b-ae8a-9831-b779-205deb32693e
* Version Independent ID: 0d831015-986a-ad21-84b1-793e94adf19f
* Content: [Understand and deploy persistent memory](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-pmem)
* Content Source: [WindowsServerDocs/storage/storage-spaces/deploy-pmem.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/deploy-pmem.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @adagashe
* Microsoft Alias: **adagashe**

**Comment by illfated** [comment]
(Ref. #5346 )

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hello @SphinxKnight,

Thanks again for contacting Microsoft. We value your feedback. Following this thread leading to [#5346](https://github.com/MicrosoftDocs/windowsserverdocs/pull/5346), the deploy-pmem.md has been deleted from main and corrections cannot be made since it no longer exists.

We will be closing this thread. Thank you and have a most pleasant day. #please-close
