### ISSUE TITLE
Link of Container Networking Documentation is broken

### ISSUE THREAD

**Issue by srazasyed** [MicrosoftDocs/windowsserverdocs#5374]
The first link titled `Container Networking documentation` on the first line of the section titled "[Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/networking/sdn/contact-sdn-team#microsoft-docs)" is broken.

The broken link URL: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking

**Comment by illfated** [comment]
(everything below this sentence would have been available if you had used the button [This page] on the Doc page)

[Enter feedback here]


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b581b541-9b0b-06e2-fb89-7af5f7a7d800
* Version Independent ID: 3ac4461b-b5f3-477a-f0d1-612bf142168a
* Content: [Contact the Datacenter and Cloud Networking Team](https://docs.microsoft.com/en-us/windows-server/networking/sdn/contact-sdn-team#microsoft-docs)
* Content Source: [WindowsServerDocs/networking/sdn/contact-sdn-team.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/sdn/contact-sdn-team.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @AnirbanPaul
* Microsoft Alias: **anpaul**

**Comment by illfated** [comment]
By the way, it looks as if both links should go to the same page, because there is no directory named `/manage-containers/` underneath https://docs.microsoft.com/virtualization/windowscontainers/ .

I will attempt a Pull Request to make both of those identical texts point to the same working URL, since there is no logic to say that they should be different.

**Comment by illfated** [comment]
OK, after some messed-up digging around, I found a likely candidate:
- https://docs.microsoft.com/virtualization/windowscontainers/container-networking/architecture

Looks like the directory hierarchy has been restructured a bit, without this link being updated at the same time.

I will suggest that page link instead of the broken 404 one by creating a Pull Request for it.

**Comment by illfated** [comment]
PR #5375 is ready for review, comments, and suggestions.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @srazasyed,

Thanks again for contacting Microsoft. We value your feedback. 

The documentation in question may have been moved, archived, or absorbed and we cannot correct this issue. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
