### ISSUE TITLE
IN Place upgrade and Media Support

### ISSUE THREAD

**Issue by NareshAvunoori** [MicrosoftDocs/windowsserverdocs#5391]
I am looking for the information about the Windows server in-place upgrade, but somehow I feel all the necessary information is not there. Please do the needful. 
FYI:  I have tried to reach MS licensing Team but I couldn't get connected. 

I am trying to upgrade windows server 2012 to 2019 standard in-place upgrade, while I am doing I am seeing keep all my file options grayed out. 
with the forums, I come to know that the issue related to the Media that I am using. 
![image](https://user-images.githubusercontent.com/65230132/111971991-ef028200-8b22-11eb-94b4-56222c12d43b.png)
Now I am looking to download an ISO media retail / Volume media. I did not found any to do the same.

FYI: I have brought the License from a Retail Market. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9b52be-37b3-6f1f-21f1-bdb9e9036eb0
* Version Independent ID: 89501699-9fd7-12a2-fa42-9564916aa78b
* Content: [Install, upgrade, or migrate to Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/get-started-19/install-upgrade-migrate-19)
* Content Source: [WindowsServerDocs/get-started-19/install-upgrade-migrate-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/install-upgrade-migrate-19.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by robinharwood** [comment]
Hi @NareshAvunoori ,

Thanks for the feedback and dedication to our documentation. With regard to your query regarding download media, the method may vary depending on the distribution channel used, for example, volume licensing or retail like you mention. For more information, you can [read about fulfilment](https://www.microsoft.com/en-us/Licensing/existing-customer/fulfillment?activetab=fulfillment-pivot:primaryr2) or by contacting your licensing reseller.

To get further assistance or support for your issue, we recommend that you engage with the product community or open a ticket with Microsoft Support. For more information, see [Contact Microsoft Support](https://support.microsoft.com/ContactUs).

If you're submitting feedback about the product documentation, please reply to this comment to clarify your issue further. Otherwise, we'll proceed with closing out this Git issue.

Thanks,

Robin

#please-close
