### ISSUE TITLE
GCC High ADFS MFA adapter configuration guidance improvement

### ISSUE THREAD

**Issue by chalewi** [MicrosoftDocs/windowsserverdocs#5397]
The documentation isnt accurate for GCC high tenants. We would like to see GCC high steps outlined in the docs as well.

The default options would configure Azure MFA adapter against commercial Azure tenant environment. The customer team came to realization only after receiving the following warning message: 'This is a violation of compliance to isolate different cloud offerings. USGov and public clouds must respect cloud boundaries by using the right AAD endpoints for each tenant. Also, your apps will stop working after Fairfax tenants are migrated to Arlington for such tenants.' Azure monitoring team provided the following solution address the issue: Instructions for AD FS Adapter: 1. Export-AdfsAuthenticationProviderConfigurationData – Name AzureMfaAuthentication -FilePath 2. Open resulting file 3. Set-AdfsAzureMfaTenant -TenantId -ClientId -Environment USGov 4. [For minimal impact from step 5] One at a time, take each ADFS server out of the NLB rotation and wait for all connections to drain 5. Restart AD FS service on each node in the cluster *This only needs to be done on the primary AD FS server for a cluster and will take effect on all AD FS nodes in the cluster   If and only if the Set-AdfsAzureMfaTenant cmdlet doesn’t support the -Environment parameter (Windows Server without latest service pack), follow these instructions instead: 1. Open Registry Editor 2. Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ADFS 3. Create SasUrl key and set it to https://adnotifications.windowsazure.us/StrongAuthenticationService.svc/Connector 4. Create StsUrl key and set it to https://login.microsoftonline.us 5. Create ResourceUri key and set it to https://adnotifications.windowsazure.us/StrongAuthenticationService.svc/Connector 6. [For minimal impact from step 7] One at a time, take each ADFS server out of the NLB rotation and wait for all connections to drain 7. Restart the AD FS service 8. Repeat for each AD FS node in the cluster The public and FTC documentation should provide implementation details and guidance specific to GCC High customers so that future implementation doesn't run into the same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f333e8cb-c046-ee06-d33d-d7dc8e8af695
* Version Independent ID: 10838695-f60e-42a7-b0e8-eed7820fd333
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Thank you for this apparently quite important report. I have taken the liberty to format your report, both for readability and as a preparation in case your report content can be used 'as is' in the referenced document page. See my formatting suggestion below, including some minor grammar adjustments and additional formatting steps.

***

### The default options configures the Azure MFA adapter against a commercial Azure tenant environment

The customer team came to this realization only after receiving the following warning message:

> **"This is a violation of compliance to isolate different cloud offerings. USGov and public clouds must respect cloud boundaries by using the right AAD endpoints for each tenant. Also, your apps will stop working after Fairfax tenants are migrated to Arlington for such tenants."**

The Azure monitoring team has provided the following solution to address the issue:

Instructions for the AD FS Adapter (*run the cmdlets in an elevated PowerShell console*):

1. `Export-AdfsAuthenticationProviderConfigurationData – Name AzureMfaAuthentication -FilePath`
2. Open the resulting file.
3. `Set-AdfsAzureMfaTenant -TenantId -ClientId -Environment USGov`
4. For minimal impact from step 5: Take each ADFS server, one at a time, out of the NLB rotation and wait for all connections to drain.
5. Restart the AD FS service on each node in the cluster.

> [!NOTE]
> **This only needs to be done on the primary AD FS server for a cluster, and will take effect on all AD FS nodes in the cluster.**
> **If and only if** the `Set-AdfsAzureMfaTenant` cmdlet doesn’t support the -Environment parameter (Windows Server without the latest service pack), **use the following instructions instead:**

1. Open the Registry Editor.
2. Navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ADFS`
3. Create a `SasUrl` key and set it to `adnotifications.windowsazure.us/StrongAuthenticationService.svc/Connector`
4. Create a `StsUrl` key and set it to `login.microsoftonline.us`
5. Create a `ResourceUri` key and set it to `adnotifications.windowsazure.us/StrongAuthenticationService.svc/Connector`
6. For minimal impact from step 7: Take the ADFS server out of the NLB rotation and wait for all connections to drain.
7. Restart the AD FS service.
8. Repeat this procedure for each AD FS node in the cluster.

The public and FTC documentation should provide implementation details and guidance specific to GCC High customers, so that future implementation doesn't run into the same issue.

***

* Please point out any incorrect phrasing or wording, just in case my reformatting and adjustments could have caused a change in the meaning/interpretation of the report content.

**Comment by IngridAtMicrosoft** [comment]
Hi @chalewi Please respond to the suggested changes.
