### ISSUE TITLE
Error: Key ID is required

### ISSUE THREAD

**Issue by LJYng** [MicrosoftDocs/windowsserverdocs#5413]
1. I feel it would be good to point out that the following command won't work since the **ID is required** (see error)
2. And there is no explanation on how to get the ID with Powershell for use with the key pw backup command

**Doesn't work**:
`Manage-BDE -Protectors -AADBackup E:`

**Error**:
ERROR: Specifying the **parameter '-ID' is required** to back up recovery
information.

**The below command DOES show the Key Protectors, but nothing explains how to select the ID for `Manage-BDE -Protectors -AADBackup -ID ???? E:` **
`Manage-BDE -Protectors -Get E:`
[output]
        Volume E: [E]
        All Key Protectors
        
            Numerical Password:
              ID: {5Fxxxx8-7xx0-4xx1-9xx0-76xxxxxxx30}
              Password:
                1xxx8-2xxx2-3xxx8-1xxx6-0xxxx0-3xxx2-0xxx1-6xxx5
            External Key:
              ID: {7CD4BD8B-56E0-4F1F-BA0E-3BCxxxxxx55}
              External Key File Name:
                7xxxxxB-5xx0-4xxF-BxxE-3Bxxxxx5.BEK
              Automatic unlock enabled.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ef6d71-4070-a941-ccc2-868e435e7c18
* Version Independent ID: 1a9eac49-6fd4-de12-9c8a-452ee31f6bc7
* Content: [manage-bde protectors](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde-protectors)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde-protectors.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/manage-bde-protectors.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @LJYng - 

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner, and offer our apologies for any inconvenience we’ve caused. 

Updates were made to this article in May 2021 and January 2022 that the Id parameter is required for the command, and how to get the Ids. 

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.  

#please-close
