### ISSUE TITLE
Log files?

### ISSUE THREAD

**Issue by 0marni** [MicrosoftDocs/windowsserverdocs#543]
We still can't connect, are there any log files to troubleshoot the problem? Certificates are correct and updates are installed.

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by reluctantflux** [comment]
Make sure that you're using the FQDN for the RD Gateway in the Deployment Properties. I was just testing internally before putting it into the DMZ, and changing my dns entry for that to point to my correct server resolved the issue.

**Comment by henrikmai** [comment]
We have the same Problem. Published RD Gateway through WAP and ADFS with Pathtrough Auth.
Internally works fine, but externally we got a error Message. RD Gateway is set up correctly with FQDN and Certificates

**Comment by ChrisM80** [comment]
Same problem here. GW (FQDN) published with WAP and pass-through. Any log files available to troubleshoot this?

**Comment by MumpekPumpa** [comment]
I contacted the RD Web Client team and was told: "WAP support is not available in the RD Web Client yet. This is something we are investigating for a future release".

A features suggestion exists for it: https://remotedesktop.uservoice.com/forums/266795-remote-desktop-services/suggestions/33788473-support-wap-adfs-for-rd-web-client, please vote!

Another important one is for SSO: https://remotedesktop.uservoice.com/forums/266795-remote-desktop-services/suggestions/33788413-enable-sso-in-rd-web-client.

With these two features I'd be able to put this in production, until then... .

**Comment by ChrisM80** [comment]
Such a shame. I've been waiting for 11 years to get rid of that ActiveX control but without SSO and reverse proxy support upon GA i cant recommend this to my clients. @Davidbel, can you reveal if this is on the roadmap for GA?

**Comment by davidbel** [comment]
Hi @ChrisM80, the plan for GA is the current set of feature as we plan on reaching GA soon. This set should be suitable for some customers. The goal was to get a client out so we can receive feedback and ensure we are focusing on features that really matter. Since this is a downloadable client and admins can update it on their own cadence, the plan is to continue releasing updates to the client as new features become available and these are definitely some of the first ones we are working on based on the feedback already received. Definitely keep providing feedback and keep an eye out for updates if the current feature set isn't yet suitable for your clients. Thank you.

**Comment by MumpekPumpa** [comment]
@davidbel thank you for you candor, but I have to say I'm having a hard time imagining a scenario where one would place this in production without SSO and WAP/ADFS support.

Can you perhaps share how frequently can updates be expected and where will we find out about them?

**Comment by davidbel** [comment]
@MumpekPumpa Definitely appreciate all the candid feedback from you all also. That's why we're doing a Preview so we can find out if we're ready for GA. If some features are blockers for a lot of folks, we'll definitely take that in consideration.

For the frequency, we are still deciding on that and I'd love your feedback as to what you'd like to see. From a technical standpoint, we can ship at any time when new features are ready or critical issues have been addressed. However, we can also set a more formal cadence. Our other clients ship when it makes sense.

For finding out about updates, here's the current thinking, feedback always welcome. We will soon spin up a release note page on docs.microsoft.com where we will list the changes whenever we have a new release. This would be the primary way to look for new releases. We may also release a blog post when there is a significant change. Lastly, you could also write a PowerShell script to query for new versions and take an action when a new one is detected.

**Comment by davidbel** [comment]
@MumpekPumpa @ChrisM80 If you have time, please send mail to the support email on the About page of the client. I'd love to discuss SSO further.

**Comment by CoryLock** [comment]
@davidbel What about printer redirection. Is there a plan for this or to just keep it as saving as a pdf locally?

**Comment by davidbel** [comment]
@CoryLock The current plan is to stay with PDF printing primary due to limitations of what we can do in a web browser.

**Comment by MumpekPumpa** [comment]
@davidbel I sent an e-mail regarding SSO, but haven't received any replies yet. Let me know if additional details are needed.

**Comment by preetamzare** [comment]
we are facing same problem. I have uploaded the screen capture. Didn't noticed there is already. It is sad there is not response.

**Comment by MumpekPumpa** [comment]
How come this was closed, are log files now visible somewhere?

**Comment by lizap** [comment]
Hi, @MumpekPumpa - I closed this comment because it seems to have gone beyond the subject of the original question (and this article) into questions about future features. Perhaps that's not the case. I'll reopen and flag to the RD team to consult. However, the best channel to get technical support for the web client is the email address on the About page. If you've tried that channel and not gotten a response, please let me know. Thanks.

**Comment by davidbel** [comment]
@MumpekPumpa You can see what is happening in the client today by opening the browser dev console (F12 in Edge) and trying the scenario again. This is how we investigate issues today. We are working on a feature to provide an easy way to export the logs, likely from the About page, to simplify retrieving this information.
