### ISSUE TITLE
oldeer version links

### ISSUE THREAD

**Issue by gminty** [MicrosoftDocs/windowsserverdocs#5468]
Step 1: Review and Select Activation Methods.

Points to "older version and not updated page"
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/jj134256(v=ws.11)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e604221-4d7e-7ddb-6d07-2d35eb8689e7
* Version Independent ID: c0b26de1-8374-6c8f-dfbe-4c2c9e2a47a2
* Content: [Windows Server 2019 Activation](https://docs.microsoft.com/en-us/windows-server/get-started-19/activation-19)
* Content Source: [WindowsServerDocs/get-started-19/activation-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/activation-19.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Looks like you skipped reading the text right before the link:

> For information about KMS activation involving **operating systems older than those listed here**, see [(link)]

I assume it could be made more clear by adding a blank paragraph between the first 2 sentences, making the link part of a second paragraph instead of the first one.

**Comment by gminty** [comment]
You are correct, I was skimming, and just headed directly to “step 1”

__
Glen D. Minty
ITS, Dalhousie University
902-233-1617

**Comment by illfated** [comment]
Thanks for the feedback. Knowing this repository and that the MS Docs server team is quite small and quite overworked as it is, I am slightly hesitant to start a PR to have the document changed. Also, looking at the page for feedback on this article document page alone, it seems this ticket is tone only one so far:
- https://github.com/MicrosoftDocs/windowsserverdocs/issues?utf8=%E2%9C%93&q=%22c0b26de1-8374-6c8f-dfbe-4c2c9e2a47a2%22&in=body

Anyway, it is quite easy to create a PR to ask for this page to be updated (as I indicated above), so I am not worried about the work involved. I just think it may take weeks, maybe months, to have the article updated for clarity in this case. What do you think?

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @gminty,

Thanks again for contacting Microsoft. We value your feedback. 

The documentation for this page has changed since the opening of this GitHub issue. The original page has either been moved or merged as new updates are rolled out. As the original source is no longer available, I'm unable to update this page with a note to notify users of the activation method for Windows Server version in question.  

Do please let us know if you come across documentation that could benefit from an update, improvement, or clarity. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
