### ISSUE TITLE
Start targets

### ISSUE THREAD

**Issue by chriskalish** [MicrosoftDocs/windowsserverdocs#5470]
So, it's not clear from this page how START identifies the target. For example,
    start "" Excel - will start excel
    start "" winword - will start word

However, start "" word will not start word ... where are these associations maintained?

Appreciate any insight (and should be added to this page). Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52b78b6-e846-0b32-25c0-f9aab145b112
* Version Independent ID: 0c56bb98-4f1f-dd55-63ae-8bb18535cee1
* Content: [start](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start)
* Content Source: [WindowsServerDocs/administration/windows-commands/start.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/start.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Please note that some of the documentation pages underneath **Windows commands / Commands by Server role**
- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands
- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/commands-by-server-role

have been kept since the early beginnings of Microsoft documentation on the web (Windows 2000), so some content might be unchanged since then, and maybe not completely correct in currently supported versions of Windows. You may want to open a Pull Request to have the content updated to a working standard, like having the page refer to the application Microsoft Word as **Winword.exe** instead of "word.exe".

On the other hand, I usually presume that experienced IT professionals will be aware that some of the documentation is not meant to be verbatim dictation and that many commands or scripts should be adapted to individual scenarios and cases. But sure, the page in question could use some correction, so feel free to suggest how it could be written.

**Comment by chriskalish** [comment]
Hi Trond. Not sure you understood the question I was asking. Maybe an example would be best. From a CMD prompt, type "WINWORD" (it does not work) ... however, typing "start "" WINWORD" will start microsoft word:

                  c:\Temp\x\x>winword
                  'winword' is not recognized as an internal or external command,
                  operable program or batch file.
                  
                  c:\Temp\x\x>
-------------------------                  
                  c:\Temp\x\x>start "" winword
                  <WORD STARTS IN NEW WINDOW>
                  c:\Temp\x\x>

WINWORD is not in the path (or it would have executed in the first example); however, it does respond to a START request. Where is the mapping between what is given to START and the executable that is run?

Thank you.

**Comment by illfated** [comment]
Oh. Right. I did not read your question correctly, maybe because I got too caught up in the details regarding the otherwise common complaint about the inaccuracy of the old pages.

Currently, I don't know exactly how or where, but I can make an educated guess:

Parts of Windows Registry, loaded in RAM by the OS, could just as easily be a source. I have seen this mentioned somewhere related to "modern" game software, installed locally on the computer, but mainly built for online internet activity, often has Registry components which will affect how the game and its underlying components is engaged by the OS.

**Comment by dknappettmsft** [comment]
Hi @chriskalish - there's no specific association list as such. Winword works because that is the name of the executable (winword.exe), the same way that Excel is excel.exe and PowerPoint is powerpnt.exe.  The executable is not named word.exe.

When you use 'start' before a .exe it means it will launch regardless of the directory you are in at the command prompt because it searches.  If you are in the correct directory where the .exe is at the command prompt, you can just use the name, so in your example above for winword, that doesn't work because you're in c:\Temp\x\x and not using start means it doesn't search other locations.  If you change to the directory where winword.exe is, you can just run winword and Word will launch. An example is below:
------------
c:\>winword
'winword' is not recognized as an internal or external command,
operable program or batch file.

c:\>cd C:\Program Files\Microsoft Office\root\Office16

C:\Program Files\Microsoft Office\root\Office16>winword

C:\Program Files\Microsoft Office\root\Office16>
------------

I hope that helps clarify things.

**Comment by dknappettmsft** [comment]
I've added a sentence to the final bullet in the Remarks section that hopefully helps.

#please-close

**Comment by chriskalish** [comment]
> Hi @chriskalish - there's no specific association list as such. Winword works because that is the name of the executable (winword.exe), the same way that Excel is excel.exe and PowerPoint is powerpnt.exe. The executable is not named word.exe.
> 
> When you use 'start' before a .exe it means it will launch regardless of the directory you are in at the command prompt because it searches. If you are in the correct directory where the .exe is at the command prompt, you can just use the name, so in your example above for winword, that doesn't work because you're in c:\Temp\x\x and not using start means it doesn't search other locations. If you change to the directory where winword.exe is, you can just run winword and Word will launch. An example is below:
> 
> c:>winword
> 'winword' is not recognized as an internal or external command,
> operable program or batch file.
> 
> c:>cd C:\Program Files\Microsoft Office\root\Office16
> 
> C:\Program Files\Microsoft Office\root\Office16>winword
> 
> C:\Program Files\Microsoft Office\root\Office16>
> 
> I hope that helps clarify things.

I don't believe that is correct. %PATH is searched whether you type the command directly at the prompt or with START. In my case, WINWORD is not in the path, yet START finds it. Can you please check this answer with colleagues?

**Comment by illfated** [comment]
I agree, there is something different about the Start command which goes beyond what you can do with a normal command line command to just start Winword.exe .

If I only type "Winword.exe" at the command prompt, it will never start from any other directory folder than the one where Winword.exe is located.

Now, if I type "start winword" — now this will run Winword from any directory folder, whether it is C:\> or C:\Windows\system32\> or other.

There has to be a different environment available to the `start` command, which is not available if you only try to run the command itself alone.
