### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zifjon** [MicrosoftDocs/windowsserverdocs#5492]
[Voer hier feedback in]cool but do it work whit the raspberry pi?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 86f7187f-7e2e-da7f-6f46-46568be43db7
* Version Independent ID: 49714e7e-ecfb-dba3-f43a-17b6ca677fa6
* Content: [Remote Desktop clients](https://docs.microsoft.com/nl-nl/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey zifjon,

Thanks for contacting Microsoft. We value your feedback.

Since the time this issue was opened, we do not have a Remote Desktop app that can natively run in any Linux-based client or server operating system. Please see our [Remote Desktop client table](https://learn.microsoft.com/nl-nl/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients) for supported operating systems.

We do have a Web version of Remote Desktop that does work on a Raspberry Pi OS or other "Pi Alternatives". Below is an example of the Web RDC version on Pop OS:

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/103963494/a4629143-7165-4dfd-a481-21ef6af1f64c)

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
