### ISSUE TITLE
The current Semi-Annual Channel release is _not_ Windows Server, version 2004.

### ISSUE THREAD

**Issue by S-T-S** [MicrosoftDocs/windowsserverdocs#5503]
Now that 21H1 is almost out, should we update this note to reflect that 20H2 is the current SAC or jump to 21H1?
[Windows 10, version 20H2 and Windows Server, version 20H2](https://docs.microsoft.com/en-us/windows/release-health/status-windows-10-20h2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd87c102-6f5d-376b-4665-98ff94b4ca41
* Version Independent ID: f6140fb6-30bc-e9e7-463a-bf5bfc926165
* Content: [Windows Server servicing channels](https://docs.microsoft.com/en-us/windows-server/get-started-19/servicing-channels-19)
* Content Source: [WindowsServerDocs/get-started-19/servicing-channels-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/servicing-channels-19.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @S-T-S,

Thanks again for contacting Microsoft. We value your feedback.

Since the opening of this GitHub issue, the original source page for this documentation has been moved or merged into a new updated page. A note was also added into the hyperlink you provided discussing the mentioned below along with looking at [this page](https://learn.microsoft.com/en-us/windows-server/get-started/servicing-channels-comparison#semi-annual-channel) with the following notes:

> There will be no future Semi-Annual Channel releases of Windows Server. Customers using the SAC should move to [Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/) where the same release cadence and rapid innovation continues with features such as [Azure Kubernetes Service on Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/aks-hci/). Alternatively, use the Long-Term Servicing Channel of Windows Server.

and

> The current Semi-Annual Channel release is Windows Server, version 20H2. If you want to put servers in this channel, you should install Windows Server, version 20H2, which can be installed in Server Core mode or as Nano Server run in a container. In-place upgrades from a Long-Term Servicing Channel release aren't supported because they are in different release channels. This applies vice versa. You cannot upgrade or change from Semi-Annual Channel to Long-Term Servicing Channel without a clean installation.

>
> A Semi-Annual Channel release isn't an update – it's the next Windows Server release in the Semi-Annual Channel. In-place upgrades from one Semi-Annual Channel release to a later Semi-Annual Channel release are possible. This makes it easier to keep up with the relatively short release cadence.

More information on this is that [Windows Server, version 20H2](https://learn.microsoft.com/en-us/lifecycle/products/windows-server) will reach the end of servicing on August 9, 2022. This will also be the retirement of Windows Server Semi-Annual Channel (SAC). [There will be no future SAC releases of Windows Server](https://learn.microsoft.com/en-us/windows-server/get-started/servicing-channels-comparison#semi-annual-channel), and this product will no longer receive security updates after August 9, 2022.

Windows Server is moving to the Long-Term Servicing Channel (LTSC) as the primary release channel.
Customers using Windows Server SAC should move to [Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/). Alternatively, customers may use the Long-Term Servicing Channel of Windows Server. More can be read at our [Windows Server Release](https://learn.microsoft.com/en-us/windows-server/get-started/windows-server-release-info) page if interested.

We hope that this clarifies the missing content. We will now be closing this thread.

We do wish that you have a most pleasant day!
#please-close
