### ISSUE TITLE
Issuer in access_token differs from id_token

### ISSUE THREAD

**Issue by Technicali** [MicrosoftDocs/windowsserverdocs#551]
In the response I get from the token endpoint there is a disparity in the issuer value in the access_token and the id_token.

access_token says "iss": "http://adfs.mydomain.local/adfs/services/trust"
id_token says "iss": "https://adfs.mydomain.local/adfs"

Any ideas why this might be the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3824263-5c49-03e9-9063-b44b1c636540
* Version Independent ID: 31684400-9100-b442-8957-c1300ad35cb8
* Content: [AD FS Scenarios for Developers](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-scenarios-for-developers#why-modern-authentication)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/AD-FS-Scenarios-for-Developers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/AD-FS-Scenarios-for-Developers.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
