### ISSUE TITLE
/soft switch isn't documented

### ISSUE THREAD

**Issue by TripleNico** [MicrosoftDocs/windowsserverdocs#5513]
Recently i noticed on windows build 19042 that there is a new `/soft` switch when running `shutdown /?` but there is no documentation explaining the function of this switch?

![image](https://user-images.githubusercontent.com/64465421/117137689-5bbb9e00-adaa-11eb-9536-2319701a8272.png)

**Comment by illfated** [comment]
It looks like you missed the reporting button of the page you wanted to report for the missing information. Any documentation page will be updated, usually much later than the software described on the documentation pages.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

You might want to use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by Xelu86** [comment]
Hey TripleNico,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made as to what the `/soft` parameter does and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
