### ISSUE TITLE
request for update

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windowsserverdocs#5516]
This has not been updated in several years and does not include Windows Server 2019.  Please review and update as appropriate. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3cfb096-8fc8-7f33-f42f-8082371940c2
* Version Independent ID: a41c5888-b33a-7090-64c2-ff209b41ee70
* Content: [Monitoring Active Directory for Signs of Compromise](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/monitoring-active-directory-for-signs-of-compromise)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Monitoring-Active-Directory-for-Signs-of-Compromise.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Monitoring-Active-Directory-for-Signs-of-Compromise.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by illfated** [comment]
I remember back in the 1990s when we used to read RFCs - Request For Comment - documents. 
Will we ever go as far as to create a meme-like acronym for this, RFU - Request For Update? 😉

**Comment by dksimpson** [comment]
Hello @DeanGross,

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
