### ISSUE TITLE
Cannot find any service with service name 'sshd'

### ISSUE THREAD

**Issue by staff0rd** [MicrosoftDocs/windowsserverdocs#5530]
Some step is missing from _Host key generation_ considering (on a new windows install) the last step fails:

```
# Now start the sshd service
Start-Service sshd
```

Fails with:

```
Start-Service : Cannot find any service with service name 'sshd'.
At line:1 char:1
+ Start-Service sshd
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (sshd:String) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.StartServiceCommand
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by dknappettmsft** [comment]
Hi @staff0rd, you're seeing this error because the OpenSSH Server has not been installed yet. If you follow the steps on [this page](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse), the sshd service will be present and you should be able to start it.

I've updated the page you linked with a note to say that OpenSSH Server has to be installed first.  The changes should be visible in a few hours.  As a reference I've included the output of before and after OpenSSH Server installation this below:

PS C:\> Get-Service ssh*

Status   Name               DisplayName
------   ----               -----------
Stopped  ssh-agent          OpenSSH Authentication Agent


PS C:\> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'


Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

Name  : OpenSSH.Server~~~~0.0.1.0
State : NotPresent



PS C:\> Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0


Path          :
Online        : True
RestartNeeded : False



PS C:\> Get-Service ssh*

Status   Name               DisplayName
------   ----               -----------
Stopped  ssh-agent          OpenSSH Authentication Agent
Stopped  sshd               OpenSSH SSH Server


PS C:\>

#please-close
