### ISSUE TITLE
Robocopy

### ISSUE THREAD

**Issue by xerZV** [MicrosoftDocs/windowsserverdocs#5540]
[Enter feedback here]
Where can I find a list with statuses details? E.g. 

* tweaked - it means ...
* new - it means...
* old - it means...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Depends on which statuses you are thinking of. Most of them should be described either in this page, or in other operating system command line manual pages.

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy#file-selection-options

#### File selection options

| Option | Description |
|--|--|
| /a | Copies only files for which the **Archive** attribute is set. |
| /m | Copies only files for which the **Archive** attribute is set, and resets the **Archive** attribute. |
| /xf `<filename>[ ...]` | Excludes files that match the specified names or paths. Wildcard characters (**&#42;** and **?**) are supported. |
| /xd `<directory>[ ...]` | Excludes directories that match the specified names and paths. |
| /xc | Excludes existing files with the same timestamp, but different file sizes. |
| /xn | Excludes existing files newer than the copy in the source directory. |
| /xo | Excludes existing files older than the copy in the source directory. |
| /xx | Excludes extra files and directories present in the destination but not the source. Excluding extra files will not delete files from the destination.  |
| /xl | Excludes "lonely" files and directories present in the source but not the destination. Excluding lonely files prevents any new files from being added to the destination. |
| /is | Includes the same files. Same files are identical in name, size, times, and all attributes. |
| /it | Includes "tweaked" files. Tweaked files have the same name, size, and times, but different attributes. |
| /max:`<n>` | Specifies the maximum file size (to exclude files bigger than *n* bytes). |
| /min:`<n>` | Specifies the minimum file size (to exclude files smaller than *n* bytes). |
| /maxage:`<n>` | Specifies the maximum file age (to exclude files older than *n* days or date). |
| /minage:`<n>` | Specifies the minimum file age (exclude files newer than *n* days or date). |
| /maxlad:`<n>` | Specifies the maximum last access date (excludes files unused since *n*). |
| /minlad:`<n>` | Specifies the minimum last access date (excludes files used since *n*) If *n* is less than 1900, *n* specifies the number of days. Otherwise, *n* specifies a date in the format YYYYMMDD. |
| /xj | Excludes junction points, which are normally included by default. |
| /fft | Assumes FAT file times (two-second precision). |
| /dst | Compensates for one-hour DST time differences. |
| /xjd | Excludes junction points for directories. |
| /xjf | Excludes junction points for files. |

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @xerZV,

Thanks again for contacting Microsoft. We value your feedback. A documentation change was made, and changes are live. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
