### ISSUE TITLE
Remote Desktop new version not removing old version

### ISSUE THREAD

**Issue by Maelito77** [MicrosoftDocs/windowsserverdocs#5559]
[Enter feedback here]
Deploying via SCCM we noticed that the new msi will not remove the old Remote Desktop client. 
is there a switch option on the msi for this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b56197c8-e490-f6fe-a494-a8aa584a8faa
* Version Independent ID: 46d1a544-517b-a4eb-68a2-cd7194aca44b
* Content: [Windows Desktop client for admins](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-admin.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by illfated** [comment]
I believe that would have to be the msiexec.exe command line options, because launching the downloaded file and running it from the command line produced the following options in a dialog box to me:
```
Windows ® Installer. V 5.0.19041.1 

msiexec /Option <Required Parameter> [Optional Parameter]

Install Options
	</package | /i> <Product.msi>
		Installs or configures a product
	/a <Product.msi>
		Administrative install - Installs a product on the network
	/j<u|m> <Product.msi> [/t <Transform List>] [/g <Language ID>]
		Advertises a product - m to all users, u to current user
	</uninstall | /x> <Product.msi | ProductCode>
		Uninstalls the product
Display Options
	/quiet
		Quiet mode, no user interaction
	/passive
		Unattended mode - progress bar only
	/q[n|b|r|f]
		Sets user interface level
		n - No UI
		b - Basic UI
		r - Reduced UI
		f - Full UI (default)
	/help
		Help information
Restart Options
	/norestart
		Do not restart after the installation is complete
	/promptrestart
		Prompts the user for restart if necessary
	/forcerestart
		Always restart the computer after installation
Logging Options
	/l[i|w|e|a|r|u|c|m|o|p|v|x|+|!|*] <LogFile>
		i - Status messages
		w - Nonfatal warnings
		e - All error messages
		a - Start up of actions
		r - Action-specific records
		u - User requests
		c - Initial UI parameters
		m - Out-of-memory or fatal exit information
		o - Out-of-disk-space messages
		p - Terminal properties
		v - Verbose output
		x - Extra debugging information
		+ - Append to existing log file
		! - Flush each line to the log
		* - Log all information, except for v and x options
	/log <LogFile>
		Equivalent of /l* <LogFile>
Update Options
	/update <Update1.msp>[;Update2.msp]
		Applies update(s)
	/uninstall <PatchCodeGuid>[;Update2.msp] /package <Product.msi | ProductCode>
		Remove update(s) for a product
Repair Options
	/f[p|e|c|m|s|o|d|a|u|v] <Product.msi | ProductCode>
		Repairs a product
		p - only if file is missing
		o - if file is missing or an older version is installed (default)
		e - if file is missing or an equal or older version is installed
		d - if file is missing or a different version is installed
		c - if file is missing or checksum does not match the calculated value
		a - forces all files to be reinstalled
		u - all required user-specific registry entries (default)
		m - all required computer-specific registry entries (default)
		s - all existing shortcuts (default)
		v - runs from source and recaches local package
Setting Public Properties
	[PROPERTY=PropertyValue]

Consult the Windows ® Installer SDK for additional documentation on the
command line syntax.

Copyright © Microsoft Corporation. All rights reserved.
Portions of this software are based in part on the work of the Independent JPEG Group.
```
Judging by the following section, you might be able to treat the previous version as an older update package to be removed:
```
Update Options
	/update <Update1.msp>[;Update2.msp]
		Applies update(s)
	/uninstall <PatchCodeGuid>[;Update2.msp] /package <Product.msi | ProductCode>
		Remove update(s) for a product
```
From my point of view, you may want to experiment with the following line of options:
`/uninstall <PatchCodeGuid>[;Update2.msp] /package <Product.msi | ProductCode>`

**Comment by ii-batman** [comment]
A bit disappointed that an MS msi for an MS app is not removing the old version during installation.
I have tried many way with msiexec command and cannot find a way to remove the old version.
This is supposed to be an enterprise application so expect it to be deployed by a central system to many machines.
Please can you look into this and reply back with a solution?
Many thanks, 
M

**Comment by illfated** [comment]
Please use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
You may also want to consider reporting this via the Feedback Hub, which is a reporting tool directed towards the developers.

If the developers can be alerted of this issue by enough users, it should catch their attention and make them work on software improvements.

Also, if you contact Microsoft Support about this, they may also direct the question to the developers, but I don't know which path they recommend.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey Maelito77,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product or service rather than our documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
