### ISSUE TITLE
RDP not working after upgrade v1.3.2105.24004

### ISSUE THREAD

**Issue by kovacspro** [MicrosoftDocs/windowsserverdocs#5577]
RDP connection is not working from Windows Admin Center. Start loading the session but after that it displays a pop-up says connection lost. 
This issue appered after upgrade to 1.3.2105.24004 version.
I tried to another browsers and clear the browser's cache etc.

**Comment by illfated** [comment]
Your RDP problem seems to be a support issue. Maybe you would like to contact Microsoft Support instead, to get help?

Did you intend to ask for help with the issue, or have you got any suggestions for documentation improvement?

By the way, if you did want to report any issues in one of the document pages, what is the URL to that page?

**Comment by Xelu86** [comment]
Hey kovacspro,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product or service rather than our documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
