### ISSUE TITLE
Remote Desktop client - version 10.2.2015.0 availability

### ISSUE THREAD

**Issue by PetrMa** [MicrosoftDocs/windowsserverdocs#5589]
Hello,

could I asked when will be available in Windows store the version 10.2.2015.0 of Remote Desktop app (https://www.microsoft.com/cs-cz/p/microsoft-remote-desktop/9wzdncrfj3ps) please?
The current available version has some issues which prevent connection to our RDS farm.
The version 10.2.2015.0 working fine but we´re not able to ensure that all clients can download this version.

Thanks, Petr

**Comment by illfated** [comment]
Please use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- Contact Microsoft Support: https://support.microsoft.com/en-gb/contactus/?%3Fws=support#tab0
- Support Options: https://www.microsoft.com/accessories/en-gb/support/contact-us%EF%BB%BF
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by Xelu86** [comment]
Hey PetrMa,

Thanks again for contacting Microsoft. We value your feedback.

The response by the ghost account is correct. The authors of these technologies do not provide tech support on GitHub as we have different resources available for those needs.

As we understand it, you're describing an issue with the product compared to an issue with the documentation. Searching for technical support, deeper specifics of the product or feature requests here is completely outside our scope. If there are any issues within the content itself, such as incorrect code, verbiage, etc., please let us know.

Please utilize the mentioned forums in the previous post. Hopefully one of the community experts may be able to better assist. 

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
