### ISSUE TITLE
there is issue with change the drive letter,

### ISSUE THREAD

**Issue by belpin** [MicrosoftDocs/windowsserverdocs#5599]
[Enter feedback here]
virtual disk manager gives error after attempt to change drive letter,
this is not describe in this article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f8441a-d145-c5ce-36ee-49058d0c09b4
* Version Independent ID: 49a7f4be-4d96-8b7b-537d-3a758d0a4beb
* Content: [Change a drive letter](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-a-drive-letter)
* Content Source: [WindowsServerDocs/storage/disk-management/change-a-drive-letter.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/change-a-drive-letter.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @belpin, 

Thanks again for contacting Microsoft. We value your feedback. 

As per our [changing a drive letter](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-a-drive-letter) article, I followed the given example with the results below in my VM.

I already had attached another virtual drive to my VM, "Backup Drive", and opened Disk Management:
![image](https://user-images.githubusercontent.com/103963494/186041652-6db78364-a9d3-4dcb-823a-310a5bbe6ea1.png)

I right-clicked in the box that says, "Backup Drive" (alternatively, you can right-click on the Disk number to get the option to change drive letter, or right-clicking on the drive label (drive name) for the same option under the "Volume" tab):
![image](https://user-images.githubusercontent.com/103963494/186041735-199def86-285f-410c-9c7e-e984f643f97c.png)

In the primary popup window, I clicked on the "Change" button:
![image](https://user-images.githubusercontent.com/103963494/186041778-2e0bb1ee-7db0-4582-92ae-0c2b0d60a4dc.png)

In the secondary popup window, I chose to assign "X" from the dropdown and clicked OK:
![image](https://user-images.githubusercontent.com/103963494/186041827-0c72a76a-e3e6-4fa6-89b8-e65c9dcc4412.png)

I proceeded after the warning window:
![image](https://user-images.githubusercontent.com/103963494/186041944-d37b4631-2dd1-4bb3-9fb6-f3b3ccc7ff01.png)

You will notice that in the top window under "Volume" that the drive letter did change, but in the window below it displays the old drive letter:
![image](https://user-images.githubusercontent.com/103963494/186042720-0b4c02e0-0cdb-424d-a5f2-e513916fe4a8.png)
 
If you go to tabs above, select Action > Refresh, to see this change if desired:
![image](https://user-images.githubusercontent.com/103963494/186042774-1a936bb5-4f8a-4523-a3a5-3450e21db7bb.png)

Can you please kindly provide a screenshot of the error so that we may determine if redirection would be necessary?

Thank you.

**Comment by Xelu86** [comment]
Hey @belpin,

If you're still experiencing an issue changing the drive letter, we recommend that you engage with the product community or open a ticket with Microsoft Support. For more information, see [Contact Microsoft Support](https://support.microsoft.com/ContactUs).

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
