### ISSUE TITLE
Information not clear

### ISSUE THREAD

**Issue by EarthToAccess** [MicrosoftDocs/windowsserverdocs#561]
For Windows Server 2012, the information as to the command's syntax and functionality isn't clear. For an example; I attempted to view my RSoP information, and using every combination of command syntax I can imagine, it simply returned with the command in the output file I requested; going all from .TXT, .HTML, .XML, and many more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ba12e0-1402-a199-3bf4-0798e6b00f41
* Version Independent ID: 436399b3-51b3-c9ad-c31d-c59b1c9b9110
* Content: [gpresult](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/gpresult)
* Content Source: [WindowsServerDocs/administration/windows-commands/gpresult.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/gpresult.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by RAJU2529** [comment]
I  am using standalone computer with windows 10 1809 64bit .  RAJU is my username 
you can use the following command , all commands are worked perfectly

Gpresult /F /H C:\Gpreport03-05-2019.html

GPRESULT /USER RAJU /SCOPE COMPUTER /Z >C:\Gpreportscopecomputer03-05-2019.txt
GPRESULT /USER RAJU /SCOPE COMPUTER /Z >C:\Gpreportscopecomputer03-05-2019.html
GPRESULT /USER RAJU /SCOPE COMPUTER /Z >C:\Gpreportscopecomputer03-05-2019.xml

for getting rsop information try below commands , I am not sure will work in your server .I entered those commands , partial reports were  found in C:\

GPRESULT /R /Z >C:\Gpreportrsop03-05-2019.html
GPRESULT /R /Z >C:\Gpreportrsop03-05-2019.xml
GPRESULT /R /Z >C:\Gpreportrsop03-05-2019.txt

**Comment by illfated** [comment]
Please use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
Additionally: Without contribution content in form of constructive suggestions, references or links to what the documentation should include or how it should look, it is less likely that the commands documents in the **Windows commands/Commands by server role** will change other than from error corrections or minor updates.

**Comment by illfated** [comment]
#please-close
