### ISSUE TITLE
Windows 2012 server were .net 4.8 won't repair. How do i fix that

### ISSUE THREAD

**Issue by shannon32** [MicrosoftDocs/windowsserverdocs#5619]
I have a patched Windows 2012 machine. I'm getting a communications error - System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. This is happening when a web application I wrote tries to access a SQL Server at the hosting provider Arvixe. I don't get the error on windows 10 machines. Anyway.. doing a little digging most suggest that i need to run .net 4.8 on the 2012 machine. The issue i'm having is that .net 4.8 says it's installed. The .net repair tool says it's installed but not correctly. So i can't install it again and it's not working correctly. .net 4.8 is not one of the unisntall programs under the add remove programes like some of the other .net versions are. I've included what powershells Get-WindowsFeature net shows in case that is helpful.

Can anyone give some advice on hot to get 4.8 working on this machine. Thanks
![DotNet](https://user-images.githubusercontent.com/54543143/122049418-0363bd00-cda8-11eb-9949-c6c0c4690830.png)

**Comment by Xelu86** [comment]
Hey shannon32,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product or service rather than our documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
