### ISSUE TITLE
to enroll the VPN server certificate, can you please confirm 

### ISSUE THREAD

**Issue by lukenie** [MicrosoftDocs/windowsserverdocs#562]
to enroll the VPN server certificate, can you please confirm in both "Subject Name" and "Alternative Name", you need to provide type the name of external client will be used to connect?  why would you need to provide public name in "Alternative Name"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e886cf2-b2cc-1942-2e93-b83ba3f5c81a
* Version Independent ID: 14185f76-c920-66a5-9d3b-51ddc4845ee8
* Content: [Configure the Always On VPN Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Service: **unspecified**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by nickthecheese** [comment]
For those who are using non-domain joined VPN server I have used the following to export the key to DMZ VPN Server:
* Set the VPN Server Certificate template to mark private key as exportable
* Add the NPS server to the VPN Server group
* Request the key manually from the NPS Server as the server (Computer personal store > right click > all tasks > request new certificate)
* Export the key to PFX and transfer to DMZ VPN Server

The instructions assume that the VPN Server is domain joined but then recommend that it is not.

**Comment by shortpatti** [comment]
@lukenie, I apologize for the delay, I have the engineering team working on providing more details.

**Comment by shortpatti** [comment]
@lukenie, sorry for the delay in response.  The Always On VPN documentation has been updated and you can find your answer [here](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure#enroll-and-validate-the-vpn-server-certificate).

Closing since the content was updated on May 23rd.

**Comment by drewPrince** [comment]
Can the steps please be updated, on step 4 of "Enroll and validate the VPN server certificate" the next button is grayed out because I assume the computer is not domain joined.  I have to click "Add New" and figure out how to populate this screen to be able to connect to the CA server in the domain (I think thats what I'm doing??).
