### ISSUE TITLE
Standard Windows Controls only appear sometimes

### ISSUE THREAD

**Issue by tbc** [MicrosoftDocs/windowsserverdocs#5621]
I hide my taskbar to maximize usable pixels. I prefer to connect in full-screen mode. Sometimes I can bounce my mouse against the top of my display, and a standard set of Windows controls appears in the upper right: minimize (`_`) restore (`[ ]`), and close (`X`). Other times, like now, I see the connection bar as described on this page, and there's also a small bar at middle-top and at middle-bottom of display. The top bar doesn't seem to do anything. The bottom bar is useful because when I click on it the Start menu from my local PC unhides.

**How do I get the standard Windows controls every time?** (Those are the controls I like best.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc42a8f-2623-4352-7cc4-70f0f61e9d89
* Version Independent ID: 97d8b54b-5e7d-098b-4fb7-e8f6e0b30389
* Content: [Get started with the Microsoft Store Client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows#give-us-feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
** Microsoft Alias: **elizapo**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @tbc,

Thanks again for contacting Microsoft. We value your feedback. 

As we understand it, you're using the Microsoft Remote Desktop Client app. Per your description, you have hidden the taskbar to maximize pixel usage but the connection bar at the top of your remote session also disappears until you hover to the very top.

Once you hover to the top and the standard windows controls appears, click on the pin/tack to the left in order to pin the standard controls so it won't disappear:

![image](https://user-images.githubusercontent.com/103963494/188964175-ff2f4a7a-cbde-4d03-a47f-907fb31a3f70.png)

You can even move the connection bar by a left click and hold it to move it left or right at the top of your screen. The connection bar can also be resized to fit snuggly into a corner or stretched out to cover the top of your remote session. 

We hope that this addressed your concern. We will now be closing this thread. Thank you and have a most pleasant day. #please-close
