### ISSUE TITLE
I don't want to use subscribe the url on windows, i want to show the workspace directly to add IP 

### ISSUE THREAD

**Issue by chaooe** [MicrosoftDocs/windowsserverdocs#5635]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
@assign:xelu86

**Comment by Xelu86** [comment]
Hey @chaooe,

Thanks again for contacting Microsoft. We value your feedback. 

At the current moment, the Windows Remote Desktop Client app does not possess the ability to add an IP address over subscribing via a URL. IP addresses aren't used due to the fact that this app uses certificate verification for workspaces. As this is a globally distributed service, the IP address continually changes. If making a remote connection to <SomeWebsite.com> and using nslookup, you will notice that the endpoint IP does change during connectivity for workspaces. 

To accomplish what you want in the Windows OS itself, the native Remote Desktop Connection does have the ability to add either the computer name or IP address into the "Computer:" field for remote connections.

An IP address can be added to the Remote Desktop Client app for PC connections and not workspaces in the mobile version. Please see these articles for a reference:

- [Android](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-android)
- [iOS](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-ios)

Hopefully this sheds more insight into the Windows OS client version. We will now be closing this thread. Thank you and have a most pleasant day. #please-closeThank you and have a most pleasant day. #please-close
