### ISSUE TITLE
Do you have any guidelines, high level plan, suggestion, how to decomission WINS?

### ISSUE THREAD

**Issue by msft-jaiverma** [MicrosoftDocs/windowsserverdocs#5636]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4209745-b88d-8051-0b87-b460c424360c
* Version Independent ID: e4976fc2-b7bf-1a1c-aece-712b7bda5cc9
* Content: [Windows Internet Name Service (WINS)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/wins/wins-top)
* Content Source: [WindowsServerDocs/networking/technologies/wins/wins-top.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/wins/wins-top.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by craigcaseyMSFT** [comment]
Hello @msft-jaiverma,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
