### ISSUE TITLE
More info on wait times pls

### ISSUE THREAD

**Issue by shivladsky** [MicrosoftDocs/windowsserverdocs#5681]
Would be nice to have some suggested times based on what I'm trying to do - or rough examples, or even the "could take anywhere from" is still an indication

I am at work, I need to shrink a basic volume down to 500gb from 952.28gb - how long will this take? Can I do it during work hours or better do it at end of work day? I don't know what to expect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91258c0-7929-4d60-3f88-e67c957584c6
* Version Independent ID: d952a74b-1f86-de68-df1e-1956ac045fc7
* Content: [Shrink a basic volume](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/shrink-a-basic-volume)
* Content Source: [WindowsServerDocs/storage/disk-management/shrink-a-basic-volume.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/shrink-a-basic-volume.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by nccerhostmaster** [comment]
How long this takes will depend mostly on your environment. It could be almost instant for an empty volume on fast hardware, or could take hours if you must first defragment a highly fragmented volume with slow hardware.

**Comment by Joachim-Otahal** [comment]
It depends on how many NTFS-Cluster must be moved. That is something hard to guess in advance, let alone hard to guess when doing it from within the disk management MMC. External tools, which can boot from CD/USB, have it easier to guess when shrinking since they don't have to care about the OS running while shirinking.
In your case: Do it outside of work time. If you have to use diskmanager you may not even be able to shrink that far from within Windows, depending on: How the data is spread on that volume, where the $MFT is. And if the $MFT had to grow you may not even be able to get below 700 GB since the grown $MFT part will not be moved by Disk Management MMC.
(I am not from Microsoft support)

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @shivladsky,
 
Thanks again for contacting Microsoft. We value your feedback. 

Wait times are not documented due to varying hardware that individuals are using: 

- RAM type and speed
- CPU type, amount, and cores
- Storage media type and size
- Amount of files to shrink

Also, the amount of running apps consuming resources in the background may affect this. Unfortunately, the number of factors in each environment involved make it difficult to provide a more precise answer on wait times for disk management.  

**_Can I do it during work hours or better do it at end of work day?_**
I don't know what job type you have or hours you work. You can set up to shrink a drive and go to work as it may be complete upon your return or do it after work. Whatever situation fits you best.

We will be closing this thread. Thank you and have a most pleasant day. #please-close
