### ISSUE TITLE
please update with "additional authentication rules"

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windowsserverdocs#5698]
Where do they fit in in the order?  There are general additional authentication rules [optional], and additional authentication rules specific to each relying party [optional].

But, I don't know where in the flow these occur.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29b34e4-9db4-991d-4549-d7abd055b0d4
* Version Independent ID: ec24f28d-d8ce-52ef-6308-aab873e22ee0
* Content: [The Role of the Claims Pipeline](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/the-role-of-the-claims-pipeline)
* Content Source: [WindowsServerDocs/identity/ad-fs/technical-reference/The-Role-of-the-Claims-Pipeline.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/technical-reference/The-Role-of-the-Claims-Pipeline.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @anwarmahmood1, 

Thanks again for contacting Microsoft. We value your feedback.

I did find these 3 articles that hopefully provides more information:

- [Additional Authentication Methods in AD FS 2019](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/operations/additional-authentication-methods-ad-fs).
- [Configure Additional Authentication Methods for AD FS](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-additional-authentication-methods-for-ad-fs).
- [Build a Custom Authentication Method for AD FS in Windows Server](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-build-custom-auth-method).

If the above is not of help, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 

We also have additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close

**Comment by anwarmahmood1** [comment]
highly disappointing that it's taken 18 months to be given references to irrelevant content.

I still don't know where in the claims pipeline additional authentication rules apply, and those links don't tell me.

This fails to meet the quality standards I expect from Microsoft.  To be told to raise a support incident is deeply unhelpful. Why is there a documentation feedback channel, when you expect me to pay for a support incident because of inadequate documentation?

**Comment by Xelu86** [comment]
Hey @anwarmahmood1,

We apologize for the dissatisfactory response to your question. GitHub is the wrong channel if looking for a very specific response to a product. It is solely for documentation clarity and updates. We are to redirect all users to our tech forums for deeper information that is outside of our documentation.  

The long wait is due to the Windows Content Server team being very small and we're utilizing all the resources we have available to us to produce said content. We're back tracking cases from 2020 until now with a queue a little over 1100 potential issues concerning documentation.

I understand this won't satisfy your concern but not all writers of this content may not be the experts with the given product and thus we provided the support forums in the original response, which are free to use.

Thank you once again and we hope you have an amazing day.
#please-close
