### ISSUE TITLE
No planning or deployment instructions for a five year old doc

### ISSUE THREAD

**Issue by Knurmia** [MicrosoftDocs/windowsserverdocs#5782]
I'm looking to implement Group Managed Service Accounts in our environment and was pretty disappointed to see that Microsoft's page for gMSA's from five years ago doesn't have implementation instructions. Don't you think it's high time for somebody to add those?

Thanks,
Kris Nurmia

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31492eef-b917-e663-8648-e08ab1410b24
* Version Independent ID: a20b80c8-995a-4963-91e3-643daf6ffff4
* Content: [Group Managed Service Accounts Overview](https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/group-managed-service-accounts-overview)
* Content Source: [WindowsServerDocs/security/group-managed-service-accounts/group-managed-service-accounts-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/group-managed-service-accounts/group-managed-service-accounts-overview.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dksimpson** [comment]
Hello @Knurmia,

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
