### ISSUE TITLE
Connect to a Windows 2016 or Windows 10 remote host outside your domain, or with no domain

### ISSUE THREAD

**Issue by tinojr** [MicrosoftDocs/windowsserverdocs#583]
I was trying to connect from a domain-joined windows 10 client to a workgroup windows 2016 hyper-v server and followed the directions in the section "Connect to a Windows 2016 or Windows 10 remote host outside your domain, or with no domain", but it did not work. I had to do the following to get it to work.
Step 1: add fqdn to workgroup server (https://blogs.msdn.microsoft.com/virtual_pc_guy/2017/03/10/giving-a-workgroup-server-an-fqdn/)
Step 2: add registry keys for AllowFreshCredentials and AllowFreshCredentialsWhenNTLMOnly (https://powertoe.wordpress.com/2011/04/29/enable-credssp-from-a-windows-7-home-client/)

Afterwards, I was finally able to use hyper-v manager on my domain-joined client to manage my dev workgroup hyper-v server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bb2d4-9b81-b153-6936-3ca0f95bf631
* Version Independent ID: 968f574d-3be8-2af6-7470-d4e1f65b4a48
* Content: [Remotely manage Hyper-V hosts](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/remotely-manage-hyper-v-hosts#connect-to-a-windows-2016-or-windows-10-remote-host-outside-your-domain-or-with-no-domain)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Remotely-manage-Hyper-V-hosts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Remotely-manage-Hyper-V-hosts.md)
* Service: **na**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by Reittier** [comment]
I was trying to use HyperV Manager on a Client in Domain1 and connect to a hyperV Server to Domain2. This Documentation helped me alot and I can sucessfully connect my HyperV-Manager Console. BUT I cannot use the "Connect" function to view the "VM Console". The VM-Console tries to connect a few times and ultimately fails with an Error Message: "Cannot connect to the virtual machine."

**Comment by illfated** [comment]
Please use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
