### ISSUE TITLE
Unable to Update WVD Remote Desktop

### ISSUE THREAD

**Issue by dapadill** [MicrosoftDocs/windowsserverdocs#5830]
My WVD app shows an update is available, but when I attempt to update via the "Update Available" in the "..." or going into "..." > "About" > "Update" the installer runs and then closes after 1-2 seconds and does not update.

**Comment by Xelu86** [comment]
Hey dapadill,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product or service rather than our documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
