### ISSUE TITLE
Missing a Successful authentication response for the Client credentials grant flow

### ISSUE THREAD

**Issue by amirabr** [MicrosoftDocs/windowsserverdocs#5835]
Missing a Successful authentication response for the Client credentials grant flow:
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios#client-credentials-grant-flow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5399f381-2744-9012-2575-b2d1dd110040
* Version Independent ID: c816cb8d-b7b5-6fe7-bcca-b5d0da9efefc
* Content: [AD FS OpenID Connect/OAuth flows and Application Scenarios](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios#example-1)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @amirabr,

Thanks again for contacting Microsoft. We value your feedback. 

Are you referring to: 
- The image in the documentation that may need an update?
- Wording that may be missing? 
- Or are you experiencing a technical issue with unsuccessful authentication?

**Comment by Xelu86** [comment]
Hey @amirabr,

We will now be closing this thread due to no response. If there are any issues within the content itself, such as incorrect code, verbiage, etc., please let us know.

If you are experiencing an issue with the product itself, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We do wish that you have a most pleasant day. 
#please-close
