### ISSUE TITLE
Server versions

### ISSUE THREAD

**Issue by terafirmanz** [MicrosoftDocs/windowsserverdocs#5858]
Should this page note more recent versions of Windows server as it currently only lists 2016 but does not say if newer are also supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eaa668f-880c-8415-17bb-8169fe23fd26
* Version Independent ID: fe5d3e99-46fc-6daf-a8af-5b0653d500f7
* Content: [AD FS prompt=login](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-prompt-login)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Prompt-Login.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Prompt-Login.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
