### ISSUE TITLE
Additional References link throws 404

### ISSUE THREAD

**Issue by erikj180** [MicrosoftDocs/windowsserverdocs#5862]
Clicking on the link in the Additional References throws a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c26eae-f46d-707a-f092-0c3d66b22912
* Version Independent ID: c4f0453e-2904-864f-fcfe-d7a2555f5732
* Content: [Install the Hyper-V role on Windows Server](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/get-started/install-the-hyper-v-role-on-windows-server)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/get-started/Install-the-Hyper-V-role-on-Windows-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/get-started/Install-the-Hyper-V-role-on-Windows-Server.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Desires4** [comment]
viewing my ownership be extending looking for Honest branches

**Comment by dksimpson** [comment]
Hi @erikj180,

The link has been fixed. We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
