### ISSUE TITLE
Where can Microsoft Customers report Bugs and small but important feature requests? (Serious bug in VMConnect)

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/windowsserverdocs#5863]
Hello

Because _'Submit and view feedback for this product'_ no longer works on the 'Docs' site and because the Virtual Machine Connection (VMConnect) has a serious bug, 
#### we have this question: 
Where can Microsoft Customers report Bugs and small but important feature requests for Windows Server and its Components?

For your information, 
#### this is the bug mentioned above in Virtual Machine Connection (VMConnect):

- We can configure the VMConnectReleaseKey / the VM Mouse Release key (see screenshot)
- No matter what you have configured: `Ctrl+Alt+Up` and `Ctrl+Alt+Down` are always bound to the VMConnectRelease Event 😞 therefore they can never used in virtual machines.
- Therefore we have two small but important requirements:
  1. Please allow us to completely disable the VM Mouse Release key function
  2. Please allow us to freely configure any Key-Combination to initiate the VM Mouse Release function

![image](https://user-images.githubusercontent.com/8282673/132669973-53e254a7-6bd0-466c-ba50-fb85d67300ed.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dc50ab2-5b70-2b78-5345-cb261071fcc0
* Version Independent ID: c081e16d-cf9d-f9a7-e86c-80a38e33d211
* Content: [Hyper-V Virtual Machine Connection](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey schittli,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with a Windows product or service, rather than the documentation itself.

GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. We offer other channels for engaging with us, whether you have a support question, product feedback, or other feedback. 

We cannot assist with the following as it's outside our scope of work:

- Support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, please use one or more of the following:

 - On a Windows OS, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
