### ISSUE TITLE
Invalid URL Link

### ISSUE THREAD

**Issue by munhoumok** [MicrosoftDocs/windowsserverdocs#5913]
[Enter feedback here]
Invalid URL with " in the link. Please update the link from _https://internal.support.services.microsoft.com/en-US/help/4569891"_ to _https://internal.support.services.microsoft.com/en-US/help/4569891_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d947ba9b-b87a-867f-1f86-bba7fcfcc734
* Version Independent ID: 251fb0e6-79a8-a135-3ff3-f82a02cff4ab
* Content: [Create a failover cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/create-failover-cluster)
* Content Source: [WindowsServerDocs/failover-clustering/create-failover-cluster.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/create-failover-cluster.md)
* Product: **windows-server**
* Technology: **failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dksimpson** [comment]
Hi @munhoumok,
The link has been fixed. We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
