### ISSUE TITLE
Windows Server 2016 is broken

### ISSUE THREAD

**Issue by ColborneGreg** [MicrosoftDocs/windowsserverdocs#592]
Setup of a remote 3d FX video card into hyper-v failed in Windows Server 2016, but worked in Windows 10.
There is suppose to be more support in Windows server then Windows 10, this is a monumental failure, and unless you need active directory, you're better off installing Windows 10 on your server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0230423b-be6b-c5b3-7c69-d99b0a0f79aa
* Version Independent ID: 825d1114-1fa8-5e9b-a0d1-478ac15d7626
* Content: [Windows Server](https://docs.microsoft.com/en-us/windows-server/windows-server#feedback)
* Content Source: [WindowsServerDocs/Windows-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/Windows-Server.md)
* Service: **unspecified**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by lizap** [comment]
Hi, Greg - Since your comment is related to a specific issue with the product, I think it might be better suited as product feedback, which you can provide here: https://windowsserver.uservoice.com/forums/295047-general-feedback

I don't know the specifics of your config, but have you seen the information about Hyper-V with DDA for graphics? (https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/deploying-graphics-devices-using-dda)

Thanks!
