### ISSUE TITLE
Keybindings for keyboards without "Break" or "Pause" keys

### ISSUE THREAD

**Issue by kingma-sbw** [MicrosoftDocs/windowsserverdocs#5947]
As Laptops get more powerful it becomes common to create VM on mobile devices without a full keyboard. Generally these laptops come with a keyboard without a "break" or "pause" key. They keybindings with these keys can therefor not be entered. 

Document a solution with custom keybindings to use these on mobile devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dc50ab2-5b70-2b78-5345-cb261071fcc0
* Version Independent ID: c081e16d-cf9d-f9a7-e86c-80a38e33d211
* Content: [Hyper-V Virtual Machine Connection](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by cmcclister** [comment]
#label:"request"

**Comment by cmcclister** [comment]
#label:"product-feedback"

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey kingma-sbw,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with a Windows product or service, rather than the documentation itself.

GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. We offer other channels for engaging with us, whether you have a support question, product feedback, or other feedback. 

We cannot assist with the following as it's outside our scope of work:

- Support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, please use one or more of the following:

 - On a Windows OS, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
