### ISSUE TITLE
InterfaceMetric and VPN Connections

### ISSUE THREAD

**Issue by MWPollard** [MicrosoftDocs/windowsserverdocs#5949]
Unfortunately, VPN connections seem to reset the interface metric each time they connect if it's set by PowerShell.

I connect the VPN, then I set it to 10:
Set-NetIPInterface -InterfaceAlias "My-VPN" -InterfaceMetric "10"

I verify with Get-NetIPInterface:
ifIndex InterfaceAlias AddressFamily NlMtu(Bytes) InterfaceMetric Dhcp ConnectionState PolicyStore
35 My-VPN IPv4 1400 10 Disabled Connected ActiveStore

I disconnect and reconnect the VPN, and check again with Get-NetIPInterface:
ifIndex InterfaceAlias AddressFamily NlMtu(Bytes) InterfaceMetric Dhcp ConnectionState PolicyStore
35 My-VPN IPv4 1400 25 Disabled Connected ActiveStore

Setting the metric via the GUI seems to keep working, but I need to handle this programmatically. My users aren't going to want to run a script after they connect each time. Any suggestions? Is there a registry key I can set for the same setting to be persistent?

BTW, using InterfaceAlias works just as well as the ifIndex, and it doesn't require that you know the index that can vary between computers. With a VPN, I set exactly what it will be called, so that's easier for me to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2198b2a6-6d6f-c4ee-4904-f63701b02a58
* Version Independent ID: 740087d9-5ee2-a930-61ef-2510376f5cbb
* Content: [Configure the Order of Network Interfaces](https://docs.microsoft.com/en-us/windows-server/networking/technologies/network-subsystem/net-sub-interface-metric)
* Content Source: [WindowsServerDocs/networking/technologies/network-subsystem/net-sub-interface-metric.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/network-subsystem/net-sub-interface-metric.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by cmcclister** [comment]
#label:"doc-bug"

**Comment by cmcclister** [comment]
#label:"request"

**Comment by craigcaseyMSFT** [comment]
Hello @MWPollard,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
