### ISSUE TITLE
Uservoice link to submit feedback is invalid

### ISSUE THREAD

**Issue by Locknes** [MicrosoftDocs/windowsserverdocs#5957]
On page "https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/support/troubleshooting"
The listed uservoice page 404's

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f168bf93-cc54-2a7e-2c1c-7c649a8458d2
* Version Independent ID: 0edf20e5-268c-b5df-93a6-85186eb4ba86
* Content: [Windows Admin Center Common Troubleshooting Steps](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/support/troubleshooting)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/support/troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/support/troubleshooting.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by IngridAtMicrosoft** [comment]
#label:"doc-bug"

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey Locknes,

Thanks again for contacting Microsoft. We value your feedback. 

The link in question was corrected a few weeks after creating this issue where users were being redirected to https://aka.ms/wacfeedback and this issue was left open. We're now closing this thread.

Thank you and have a most pleasant day. 
#please-close
