### ISSUE TITLE
Date format for relog.exe isn't accurate

### ISSUE THREAD

**Issue by sicklittlemonkey** [MicrosoftDocs/windowsserverdocs#596]
For starters, it says "date and time must be in this exact format M/D/YYYYHH:MM:SS" when that is clearly only for US-style date locales.

Further, relog wasn't working for me because in its command line help it was quoting what I'd set in Windows 10 as the Short Date Format (because you have to do that to change the date format you see for the clock in the taskbar - a bug for someone else!?).

So relog printed this in its help: -b <ddd, d/MM/yyyy h:mm:ss[AM|PM]>

But gave "Invalid syntax: -b <ddd, d/MM/yyyy h:mm:ss[AM|PM]>" errors until I went and removed the ddd from the short date format. What's the point of quoting the exact short date format if you can't parse it!?

Anyway, notes to this effect and some examples wouldn't go amiss. Most of the world doesn't live in the USA.

Cheers,
Nick.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88c7179b-7544-073e-c4d9-0f88db2a4ef3
* Version Independent ID: 7c71336f-7074-dceb-448d-f3d4d7aa377d
* Content: [relog](https://docs.microsoft.com/en-nz/windows-server/administration/windows-commands/relog)
* Content Source: [WindowsServerDocs/administration/windows-commands/relog.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/relog.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
@sicklittlemonkey : Sorry for picking up on this ticket so long after you first posted this. Looks like this could be a software related bug issue, at least that is the most likely scenario.

From what I have seen in most other tickets about software issues, not directly aiming at improving the document page, it is suggested to use the Feedback app to contact the Microsoft Developer team. If you still find that your issue needs to be called out in the documentation, please state which parts of the documentation needs to be changed by suggesting improvement details.

Just to add some more information based on my experience from interacting with tickets like this one:

***

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
Seems to be resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/ce6a687b3a8a71a87c9bb6257b3d575664c92747

#please-close
