### ISSUE TITLE
Instructions for "Mounting a drive in an empty folder" are wrong

### ISSUE THREAD

**Issue by swwright** [MicrosoftDocs/windowsserverdocs#5970]
Your instructions for "Mounting a drive in an empty folder" are incorrect. If the instructions are followed as written, you will have a circular reference to the drive containing the mount folder.  So, for example, after following your instructions, `C:\USB\WD1TB` will NOT refer to the external USB drive, it will refer to the `C:` drive itself.

If I follow your instructions as written, I can then type
`cd \USB\WD1TB\USB\WD1TB\USB\WD1TB\USB\WD1TB\USB\WD1TB\USB\WD1TB`
and I will wind up at C:\.  No matter how many times I repeat `\USB\WD1TB`.

Step 1 should read as follows:  "In Disk Manager, right-click the partition or volume that you want to mount."

All subsequent steps can be followed as written.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6ac6c7b-22cb-1094-ceca-8be11bfc9558
* Version Independent ID: 6f7aa81a-8cc7-2a5b-0e89-059c8fbb14a5
* Content: [Assign a mount point folder path to a drive.](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/assign-a-mount-point-folder-path-to-a-drive)
* Content Source: [WindowsServerDocs/storage/disk-management/assign-a-mount-point-folder-path-to-a-drive.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/assign-a-mount-point-folder-path-to-a-drive.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dksimpson** [comment]
Hi @swwright

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
