### ISSUE TITLE
Error when trying to open apps from 2012 session host

### ISSUE THREAD

**Issue by KennethVerbeure** [MicrosoftDocs/windowsserverdocs#598]
When using the rd web client to start an application from my 2012 session host (which is linked to my rds setup on a 2016 server) i keep getting the same error andi cannot find anything in event viewer or rds logs

i do get the second log in screen... the error is after that:

Your session ended because of a protocol error. If this keeps happening, ask your admin or tech support for help.

(unknown) 2018-04-11T14:51:45.432Z Connection(ERR): The connection generated an internal exception with disconnect code=GenericProtocolError(18), extended code=<null>, reason=Unsupported Security Header PDU received! Type: 6
 Thrown in thread 0 at:
    iochannel.cpp(347)
Call Stack:
        at Xcb
        at Ucb
        at vkb
        at g3c

    connection.cpp(1307): OnException()

in the logs i can see that the broker successfulyy connect user to the second appserver and immediatly after the client disconnected

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
