### ISSUE TITLE
Only implementable in Internet Explorer!

### ISSUE THREAD

**Issue by ferradiego** [MicrosoftDocs/windowsserverdocs#5980]
**This solution only works for Internet Explorer!!**. It looks like Chrome, Edge and Firefox do not support this type of authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74d09c81-d205-dbd0-ea6a-aaf469eadf5c
* Version Independent ID: 458db848-1b30-1115-8814-3a639a57c70b
* Content: [Configure Device-based Conditional Access on-Premises](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-device-based-conditional-access-on-premises)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-Device-Based-Conditional-Access-on-Premises.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-Device-Based-Conditional-Access-on-Premises.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
