### ISSUE TITLE
Exchange Hybrid - WAP with PTA and EWS

### ISSUE THREAD

**Issue by Balamurugan-dot** [MicrosoftDocs/windowsserverdocs#5987]
[Enter feedback here]
Internal collaboration says EWS can be published in WAP server with PTA and it is supported, but its not clear in the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dbee2ba-d766-93b9-77fa-c727528e35d9
* Version Independent ID: 78b6df02-dc9d-f5b0-15ce-01f3175e3d3c
* Content: [Publishing Applications with SharePoint, Exchange and RDG](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/publishing-applications-with-sharepoint,-exchange-and-rdg#BKMK_6.2)
* Content Source: [WindowsServerDocs/remote/remote-access/web-application-proxy/Publishing-Applications-with-SharePoint,-Exchange-and-RDG.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/web-application-proxy/Publishing-Applications-with-SharePoint,-Exchange-and-RDG.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
