### ISSUE TITLE
update article for Service Account requirements

### ISSUE THREAD

**Issue by MichaelHall001** [MicrosoftDocs/windowsserverdocs#6002]
In this article for Service Account requirements we should put the ADFS Service Account needs read permission to the private key of the Service Communication cert and that ADFS will configure this when creating a new ADFS farm. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fc58b9-7063-5107-5f65-c77694b33c7e
* Version Independent ID: a541e745-1505-696d-2adf-c578e1f54b4c
* Content: [AD FS 2016 Requirements](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements#BKMK_7)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
