### ISSUE TITLE
Update backwards compatibility for Windows 2022 Remote Desktop User/Device CALs

### ISSUE THREAD

**Issue by dumblerod** [MicrosoftDocs/windowsserverdocs#6027]
[Enter feedback here]
Can you update or provide information on backwards compatibility for the latest 2022 Remote Desktop User/Device CALs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd015c0b-3360-88fd-86b1-08e8c0e8ec5e
* Version Independent ID: 0c3ddb09-23f3-68a3-e7a4-877951feb55b
* Content: [License your RDS deployment with client access licenses (CALs)](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by v-thepet** [comment]
Hi @dumblerod,

Thank you for contacting Microsoft. We value your feedback.

Sorry for the tardy response to this issue. The documentation was updated in Feb. 2022 to add 2022 information. Because this issue is now outdated, we’re closing the issue. If you still have a documentation concern, you're encouraged to open a new GitHub issue. 

Thanks again and have a very pleasant day.
#please-close
