### ISSUE TITLE
HyperV and RemoteFX`

### ISSUE THREAD

**Issue by djones1963** [MicrosoftDocs/windowsserverdocs#6120]
This article says that RemoteFX can be re-enabled on server 2016, 2019 and 2022.   But when it is attempted, it does not allow us to add RemoteFX to our VMs in the HyperV console.   Does anyone know if RemoteFX is actually enabled or can be enabled again?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77efb54a-9900-ec91-1d56-1ce4cb49ebcf
* Version Independent ID: 904abb0d-2544-2cae-d5a6-f2cb0128188d
* Content: [Deploy graphics devices using RemoteFX vGPU](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/deploy-graphics-devices-using-remotefx-vgpu#enable-remotefx-vgpu)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/deploy-graphics-devices-using-remotefx-vgpu.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/deploy/deploy-graphics-devices-using-remotefx-vgpu.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @rick-man
* Microsoft Alias: **rickman**

**Comment by craigcaseyMSFT** [comment]
Hello @djones1963,

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
