### ISSUE TITLE
ECHO Command

### ISSUE THREAD

**Issue by chips2014** [MicrosoftDocs/windowsserverdocs#6150]
I typed (**echo lambda.py**) and it was supposed to give me lambda.py file. I asked my team and everyone else but they didn't have the answer. Please help me. Email: cpolury.ttt25@gmail.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73a4605-c4b3-46a8-ec4e-493751fff82b
* Version Independent ID: 2bcfea05-35c7-49cb-0570-a0d5a4957ca1
* Content: [echo](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/echo)
* Content Source: [WindowsServerDocs/administration/windows-commands/echo.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/echo.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend/for user the username is @chips2014 (EDITTED BY USER)
* Microsoft Alias: **jgerend**

**Comment by dksimpson** [comment]
Hello @chips2014,

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
