### ISSUE TITLE
No info on Windows 2022 

### ISSUE THREAD

**Issue by sklein972** [MicrosoftDocs/windowsserverdocs#6159]
The applies to indicated windows 2022 server but the content doesn't mention 2022 even once...

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12b03f10-0639-a434-6737-b7f69f9d0473
* Version Independent ID: d2acf26c-c9aa-04a7-92e8-bd28e46f85f6
* Content: [Supported configurations for Remote Desktop Services](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-supported-config)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-supported-config.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-supported-config.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by dksimpson** [comment]
Hello @sklein972,

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
