### ISSUE TITLE
Can't access local resources on 32-bit Win10Pro Hyper-V virtual machine

### ISSUE THREAD

**Issue by suspenser-github** [MicrosoftDocs/windowsserverdocs#6166]
Dear Sir or Madam,

you article https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/use-local-resources-on-hyper-v-virtual-machine-with-vmconnect#requirements-for-using-local-resources is **outdated**. 
The VM Connection and Hyper-V settings have a new outlook on recent Windows 10 Pro. 
I can only log into the 32-bit Win 10 Pro guest OS in a **Basic session** mode of the VM. But there is NO any resource sharing with the 64-bit Win10 Pro host OS. 
In an **Enhanced session** mode only the Windows splash screen appears on OS start but NOT a login field to enter a login PIN.

Could you please advise.

Thank you for considering my request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55dae836-2730-7a91-b162-cd154557d0fd
* Version Independent ID: 69c4c00c-f3e6-9710-28fe-6ecdc7731c65
* Content: [Use local resources on Hyper-V virtual machine with VMConnect](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/use-local-resources-on-hyper-v-virtual-machine-with-vmconnect)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/Use-local-resources-on-Hyper-V-virtual-machine-with-VMConnect.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/Use-local-resources-on-Hyper-V-virtual-machine-with-VMConnect.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Xelu86** [comment]
Hey suspenser-github,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with a Windows product or service, rather than the documentation itself.

GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. We offer other channels for engaging with us, whether you have a support question, product feedback, or other feedback. 

We cannot assist with the following as it's outside our scope of work:

- Support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, please use one or more of the following:

 - On a Windows OS, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
