### ISSUE TITLE
What protocol does robocopy use when transferring files?

### ISSUE THREAD

**Issue by trevors20** [MicrosoftDocs/windowsserverdocs#6242]
It would be nice to have a section detailing what protocols robocopy uses to transfer files across machines.  I've been looking into whether robocopy is "secure" enough to encrypt files while transferring across machines.  There doesn't seem to be any official looking documentation from Microsoft with this detail.  It seems like robocopy uses SMB.  Could someone confirm this and document this, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by PRMerger5** [comment]
Users xelu86 are already assigned.

**Comment by Xelu86** [comment]
Hey @trevors20,

Thanks again for contacting Microsoft. We value your feedback. 

Robocopy supports the file systems and protocols supported by the core Windows OS. For example, local file systems and SMB rather than any protocols specifically support by Robocopy.  

You can configure encryption for data in transit using SMB encryption. For further information please see [SMB Security Enhancements](https://docs.microsoft.com/en-us/windows-server/storage/file-server/smb-security) uses.

As this does not require an update to the documentation, we are closing this issue. Thank you and have a most pleasant day. #please-close
