### ISSUE TITLE
Video link is not present

### ISSUE THREAD

**Issue by Trentent** [MicrosoftDocs/windowsserverdocs#6246]
"The following video goes into details on how caching works for Storage Spaces Direct, as well as other design considerations."

There is no link to a video that I can find.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 507612bf-2f19-4b78-da6a-e058385b7c51
* Version Independent ID: 748e68d9-4bf7-99d4-6e4d-817e48912327
* Content: [Understanding the cache in Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/understand-the-cache)
* Content Source: [WindowsServerDocs/storage/storage-spaces/understand-the-cache.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/storage-spaces/understand-the-cache.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Trentent,

Thanks again for contacting Microsoft. We value your feedback. 

It appears that this documentation has either been archived, redirected, absorbed or retired. Due to this, I am unable to make any changes as it is unavailable. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
