### ISSUE TITLE
Remote Desktop Client download is incomplete

### ISSUE THREAD

**Issue by DreamU1952** [MicrosoftDocs/windowsserverdocs#6272]
The documentation page gives a download link. When I download mstsc.exe and run I get an error that it is not compatible with mstscax.dll. This page needs to tell us where to get that file or why the error occurs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43e914-5ede-6f18-2fbc-165f3386f7cb
* Version Independent ID: a9489295-572d-ff60-6bff-a44390ac4031
* Content: [What's new in the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Hey DreamU1952,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product or service rather than the documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
