### ISSUE TITLE
first use problems

### ISSUE THREAD

**Issue by marcelotpcosta** [MicrosoftDocs/windowsserverdocs#628]
After install I could see my own computer, I click on it and I was asked to permit modifications on it, and the connection was lost. This is very bad because I experienced the same problem on all earlier versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5d4a9c-11eb-3b85-91dd-cdbb0625db5a
* Version Independent ID: 01dad638-f8fb-61ff-4952-e3b25007a234
* Content: [Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/windows-admin-center#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/understand/windows-admin-center.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/understand/windows-admin-center.md)
* Service: **unspecified**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by jwwool** [comment]
Can you elaborate on "the connection was lost"?

The expected behavior is that you will get a UAC popup to elevate the Windows Admin Center process. After accepting the UAC popup, a new tab should spawn with the now-elevated Windows Admin Center process, where you can reselect the local machine and successfully connect. 

Note: if you are using a MSA to log on to the machine, there is a separate [known issue](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/known-issues#computer-management-solution)
