### ISSUE TITLE
DISM /online /Set-Edition:ProfessionalWorkstation  /GetEula:C:\eula.rtf

### ISSUE THREAD

**Issue by 5U8cVs** [MicrosoftDocs/windowsserverdocs#6337]
Setting an edition is not supported with online images.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b19ef8-a273-c1c8-18ff-7d29664bb9d2
* Version Independent ID: 8cf37a43-cff4-78de-0d66-2f482c022dc7
* Content: [Upgrade and conversion options for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/upgrade-conversion-options)
* Content Source: [WindowsServerDocs/get-started/upgrade-conversion-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/upgrade-conversion-options.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by robinharwood** [comment]
Hi @5U8cVs - I notice in your command you have the switch `/Set-Edition:ProfessionalWorkstation`. This is used the Windows client rather than Windows Server. Setting the edition using DISM has also been documented in the [Windows client docs](https://docs.microsoft.com/windows-hardware/manufacture/desktop/dism-windows-edition-servicing-command-line-options), as well as the [Windows Server docs](https://docs.microsoft.com/windows-server/get-started/upgrade-conversion-options#windows-server-standard-or-datacenter). Are you able to clarify your comment?

Thanks,

Robin

**Comment by robinharwood** [comment]
#assign:robinharwood

**Comment by Xelu86** [comment]
Closing issue due to no response.
#please-close
