### ISSUE TITLE
About LTSC 2021 KMS activation

### ISSUE THREAD

**Issue by yujiish** [MicrosoftDocs/windowsserverdocs#6353]
I have a customer who uses Windows 10 LTSB 2016 as a KMS host.
They are planning to deploy LTSC 2021 PCs and are worried that their existing KMS hosts will continue to work.
The reason is that the following URL does not include LTSB 2016 / LTSC 2019/2021 as the OS that can be activated by Windows 10 KMS host.

[https://docs.microsoft.com/en-us/windows-server/get-started/kms-activation-planning#activation-versions]
 
Is it possible to activate LTSC 2021 and existing LTSB 2016 machines with a same Windows 10 KMS host?
If so, should they get the LTSC 2021 KMS key from VLSC and add it to the existing KMS host?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b24b69-ab33-c1b1-b8e2-51c23bbba31d
* Version Independent ID: ebc3123c-57f7-0d2c-f875-9b6ac6c7a319
* Content: [Key Management Services (KMS) activation planning for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/kms-activation-planning#activation-versions)
* Content Source: [WindowsServerDocs/get-started/kms-activation-planning.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/kms-activation-planning.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by craigcaseyMSFT** [comment]
Hello @yujiish 

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
