### ISSUE TITLE
activate.microsoft.com offers incompatible CALs to be installed

### ISSUE THREAD

**Issue by ewashX** [MicrosoftDocs/windowsserverdocs#6354]
[RDS CAL compatibility with RDS licensing is cool, but when it comes to installation using activate.microsoft.com it offers 2022 CALs to be installed to 2019, this is very confusing and it was not like that in previous versions, that page always detected your OS version and offered only compatible CALs to be installed.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd015c0b-3360-88fd-86b1-08e8c0e8ec5e
* Version Independent ID: 0c3ddb09-23f3-68a3-e7a4-877951feb55b
* Content: [License your RDS deployment with client access licenses (CALs)](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by v-thepet** [comment]
Hello @ewashX, 

Thanks for contacting Microsoft. We value your feedback. 

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself. GitHub Issues in the Windows Server Docs repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.  

As you're probably aware, we offer many channels for engaging with us. Please use one of the following links for support questions, product feedback, or other feedback.  

Also, see this page for more information and possible resolution for this issue: [Windows Server 2022 Licensing Server with 2019 Downgrade CAL from 2022 CAL](https://learn.microsoft.com/en-us/answers/questions/605789/windows-server-2022-licensing-server-with-2019-dow).

- From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback). 
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home). 
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home). 
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/). 
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)

Because this issue is a non-documentation issue, we’re closing this thread. 

 

Thank you. 

 

#please-close
