### ISSUE TITLE
microsoft cant access browser 

### ISSUE THREAD

**Issue by Sibusiso793** [MicrosoftDocs/windowsserverdocs#6362]
i cannot log and browse using my default manager, cannot access my student portal by outlook

**Comment by Xelu86** [comment]
Hey Sibusiso,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product or service rather than a document page for the Windows Server repo. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
