### ISSUE TITLE
MFA Adapter requirements - Federated Domain

### ISSUE THREAD

**Issue by aferrillo** [MicrosoftDocs/windowsserverdocs#6366]
Hi
Regarding the statement "Your on-premises environment is federated with Azure AD.", is it still necessary to be in a Federated Azure AD Domain to use the MFA Adapter?
The adapter authenticates using a certificate and once the relationship between useridentifier, upn in AD and accountname in AAD is done, you're good to go.
Thanks
Alessandro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f333e8cb-c046-ee06-d33d-d7dc8e8af695
* Version Independent ID: 10838695-f60e-42a7-b0e8-eed7820fd333
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa?msclkid=78a684a9ab8311ec9d5ada713e28064c&source=docs#pre-requisites)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by craigcaseyMSFT** [comment]
Hello @aferrillo,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
