### ISSUE TITLE
Applies to OS section incorrect

### ISSUE THREAD

**Issue by nlinley** [MicrosoftDocs/windowsserverdocs#6376]
I was told in a microsoft support case on lsass hardening enablement that the setting applies to 2012R2 and above. This article's top portion only shows 2016 and higher.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b04bc4d-9435-cdbc-429f-2433ada7bd37
* Version Independent ID: 5c902397-b2e7-4435-2b37-a57919434c9e
* Content: [Configuring Additional LSA Protection](https://docs.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection)
* Content Source: [WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
@JasonGerend, in windows 10 and windows 11, using group policy editor. lSA policy can be applied.

**Comment by v-thepet** [comment]
Hello @RAJU2529,

Thank you for contacting Microsoft. We value your feedback.

You're correct that the LSA protection feature was introduced for Windows Server 2012 R2 and can be configured in that version as well as in WS 2016, 2019, and 2022. Because support for WS 2012 R2 has ended, we're no longer updating documentation to add that version. The Applies to line was also misleading because it didn't list any Windows Client versions, although most of the article discussed Windows Client. We've updated the documentation to remove the misleading Applies to line. The changes will be live after the next business day.

We'll now be closing this thread. Thank you again for your feedback, and have a very pleasant day.

#please-close
