### ISSUE TITLE
Remote desktop 1 display on the client wants to see both displays on the host

### ISSUE THREAD

**Issue by GitJJHub** [MicrosoftDocs/windowsserverdocs#6382]
It seems like 100% of the articles on this topic discuss how the client, with 2 displays can access the host computer. I have only 1 display at home and need to see both monitors on my office computer. I can do that easily with RAdmin or other 3rd party applications but how is this done with Remote Desktop? Windows 10 Pro client, to Windows 10 Pro host.
The two displays at the office are of equal size and resolution (1920 X 1080) and the left display is the primary.
Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e3bc1ca-2fde-4a75-3583-fdb8ff2bf962
* Version Independent ID: 5cef2f0a-bed1-f05f-0f74-ba6f2808a714
* Content: [Remote Desktop clients FAQ](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.yml](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.yml)
* Product: **windows-server**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by dksimpson** [comment]
Hello @GitJJHub,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
