### ISSUE TITLE
Typo in version of Remote Desktop client

### ISSUE THREAD

**Issue by ldoron** [MicrosoftDocs/windowsserverdocs#6388]
The Microsoft Store client's "latest version" is listed as 1.2.1810. It should be 10.2.1817.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f7187f-7e2e-da7f-6f46-46568be43db7
* Version Independent ID: 49714e7e-ecfb-dba3-f43a-17b6ca677fa6
* Content: [Remote Desktop clients](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Hey ldoron,

Thanks again for contacting Microsoft. We value your feedback. 

Updates have occurred during the time this issue was opened and new information about the Windows Store client for RDS can be found here: https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows-whatsnew 

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
