### ISSUE TITLE
The mouse wheel does not click while using Samsung Dex.

### ISSUE THREAD

**Issue by Ashua** [MicrosoftDocs/windowsserverdocs#6397]
I use the mouse wheel click frequently.
I don't know about other Androids, but when using Samsung Dex, the mouse wheel does not click.

Is it not supported because there is no need for this feature?
Or is the feature not supported intentionally?

I hope this feature is supported.

**Comment by Xelu86** [comment]
Hey Ashua,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product, service, or feature request rather than our documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
