### ISSUE TITLE
Update Rollback

### ISSUE THREAD

**Issue by Ngenus1** [MicrosoftDocs/windowsserverdocs#6485]
Is it too much to ask for the ability to rollback the automated updates forced upon a system?  I have an issue with the Arowhead cursor taking on some weird shape after the update.  I also have a problem begging you guys for this, but that's another story.  I have attached a screenshot of the issue, I'm sure you can see my concern.
![IMG_1981](https://user-images.githubusercontent.com/106316268/170484414-b6c2e0a6-ec69-4ca5-a2f3-5133f7d2a98c.jpg)
![IMG_1982](https://user-images.githubusercontent.com/106316268/170484487-d5ae0708-f413-411a-b681-79f957ca1c01.jpg)

**Comment by Xelu86** [comment]
Hey Ngenus1,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product, service, or feature request rather than our documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
