### ISSUE TITLE
changing AdditionalCriticalWorkerThreads to 64 causes windows 25133.rs_onecore_base2.220601-1453 to blue screen

### ISSUE THREAD

**Issue by Gt3pccb** [MicrosoftDocs/windowsserverdocs#6522]
changing AdditionalCriticalWorkerThreads to 64 causes windows 25133.rs_onecore_base2.220601-1453 to blue screen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eff7ae9-34b9-5047-b707-50bbd05dbe5a
* Version Independent ID: 8e6ae745-afb9-89d0-77ad-3a9059aac122
* Content: [Performance Tuning for SMB File Servers](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/file-server/smb-file-server)
* Content Source: [WindowsServerDocs/administration/performance-tuning/role/file-server/smb-file-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/performance-tuning/role/file-server/smb-file-server.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @phstee
* Microsoft Alias: **nedpyle**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Gt3pccb,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing an issue with the product compared to an issue with the documentation. GitHub isn't quite the right location or channel if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, such as incorrect code, verbiage, etc., please let us know.

As the error you're receiving is quite specific, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Depending on what our support team is able to determine the issue, if this is a bug for this specific build/release, please do let us know so that we can update this document accordingly to bring awareness. 

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
