### ISSUE TITLE
Mistake in PowerShell example (Hyper-V, step 13)

### ISSUE THREAD

**Issue by i3laze** [MicrosoftDocs/windowsserverdocs#6527]
At Hyper-V guide:  GUI method, step 13 in a PowerShell code example an unknown **"Seattle**" site is used instead of **"Redmond"**.

Same for PowerShell method, step 8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5b8571f-1576-5c86-e257-1dad6c525ffc
* Version Independent ID: e2b0badd-9319-d81d-9cc9-e6a7010af3d7
* Content: [Stretch Cluster Replication Using Shared Storage](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/stretch-cluster-replication-using-shared-storage)
* Content Source: [WindowsServerDocs/storage/storage-replica/Stretch-Cluster-Replication-Using-Shared-Storage.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/storage-replica/Stretch-Cluster-Replication-Using-Shared-Storage.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @i3laze,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting this issue, where applicable, so that the examples being used match the wording. Changes are live. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
