### ISSUE TITLE
Call syntax incorrect

### ISSUE THREAD

**Issue by Mysteron347** [MicrosoftDocs/windowsserverdocs#6560]
Syntax definition is incorrect.

[drive:][path]<filename> [<batchparameters>] and  [:<label> [<arguments>]] are mutually-exclusive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13182672-dd73-9962-4a96-dcf7e73880b5
* Version Independent ID: 889fa95c-7987-bfe0-f7d4-3a2570250638
* Content: [call](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/call)
* Content Source: [WindowsServerDocs/administration/windows-commands/call.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/call.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by A-Mofi** [comment]
That is absolutely right. The **Syntax** box should have the two lines:

    call [drive:][path]<filename> [<batchparameters>]
    call :<label> [<arguments>]

That makes it clearer for every reader that the command `call` can be used either to call another batch file from within a batch file or call command lines below a label in the currently processed batch file in a new batch file context. The usage help output on running `call /?` in a command prompt window describes the two possible usages of command `call` better because of explaining both variants with separate syntax lines and not both in one syntax line.

The current syntax lets readers think that it is possible to use something like `call other_batch.cmd :Label` to call command lines below a label in a different batch file than the currently processed batch file which is not possible at all. The **Syntax** block with the two lines would avoid such a misunderstanding in usage of command `call`.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Mysteron347 & @A-Mofi,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made updating the syntax box for more clarity and will be live after the next business day. We will now be closing this thread. 

Thank you and we wish that both of you have a most pleasant day. #please-close
