### ISSUE TITLE
Description of "/e" says "use /e with /s and /t" but examples ignore this

### ISSUE THREAD

**Issue by b2ag** [MicrosoftDocs/windowsserverdocs#6573]
Description of "/e" says "use /e with /s and /t" but the examples are ignoring this. So which is it? Is "xcopy a: b: /s /e" a valid usage and the descripton is wrong or is the example wrong? I'm no english native so maybe I'm lacking reading skills to understand it properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a1e859-b436-290e-69c0-810dd3a5ce90
* Version Independent ID: 10c81289-2bf7-40d9-39ea-e624cf92aa3e
* Content: [xcopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/xcopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/xcopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @b2ag, 

Thanks again for contacting Microsoft. We value your feedback.

The question is in reference to:

|Parameter|Description|
|---------|-----------|
|/s|Copies directories and subdirectories, unless they are empty. If you omit **/s**, **xcopy** works within a single directory.|
|/e|Copies all subdirectories, even if they are empty. Use **/e** with the **/s** and **/t** command-line options.|
|/t|Copies the subdirectory structure (that is, the tree) only, not files. To copy empty directories, you must include the **/e** command-line option.|

And the example below:
_To copy all the files and subdirectories (including any empty subdirectories) from drive A to drive B, type:_
```
xcopy a: b: /s /e
```

The reason why the `/t` parameter is not used in this example is because if it were to be used, then it would not copy the _files_ and the example used wants the files to also be copied.

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close

**Comment by b2ag** [comment]
So it is "Use `/e` with the `/s` ~and~ or `/t` command-line options." Still unsure if my english is too bad or I am just to picky about logic. Still this documentation is not that great. If I omit `/s` and use `/e` and `/t` will it still only "work within a single directory" ? I actually don't care because I used another one of the gazillion copy commands and also tend to avoid Microsoft products in general. Thanks for posting the documentation again I guess?!
