### ISSUE TITLE
Storage Spaces overview  & Storage Spaces in Windows

### ISSUE THREAD

**Issue by mfstanton** [MicrosoftDocs/windowsserverdocs#6580]
When taking on the task of actually implementing something in your documentation I like to print a copy of the instructions, mark it up and carry the copy to the platform I plan to use for the test before putting it up on a live system.  The problem is when i print the document, the top of the page is overlaid with your marketing nonsense that makes it really ugly to work from. The seems to be a persistent problem with your web pages for at least the last 10 years.  When are the web page editors going to learn how to make that possible. No, if i download the PDF it is not always the same content so I can't print from that text.  Obviously there is a QC issue here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5889391f-be98-72d7-45cc-7843687125f0
* Version Independent ID: e7210874-fedb-39f8-9e5b-01d12fc27ccf
* Content: [Storage Spaces overview](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/overview)
* Content Source: [WindowsServerDocs/storage/storage-spaces/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/storage-spaces/overview.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dksimpson** [comment]
Hi @mfstanton,

Have you tried printing to PDF from your browser with headings and footers deselected?

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
