### ISSUE TITLE
Some published apps in the Remote Desktop Client have a bug where popup windows are extremely delayed or are not displayed at all.

### ISSUE THREAD

**Issue by colin-small** [MicrosoftDocs/windowsserverdocs#6608]
Some published apps in the Remote Desktop Client have a bug where popup windows are extremely delayed or are not displayed at all.

- Launch the published app
- Inside the app perform a task that causes a new popup window/dialog box to be opened and displayed in the foreground and take focus.
- The new popup window doesn't show up, but it seems to have focus, you cannot interact with the background app window as if the popup window is there and has focus, but it isn't visible.
- Eventually... over the course of minutes... the popup window might randomly display... other times it doesn't. If you click around and attempt to interact with the app and the remote desktop client it might eventually display the window as well. But there appears to be no reason for it.

This only is an issue in the Desktop version of the Remote Desktop Client. The same published app does not have this problem when accessed through the HTML5 browser based Remote Desktop client. So the issue is related to the Desktop version of the Remote Desktop client when using a published app.

The issue also doesn't affect the app when accessed in a full desktop session using the Desktop version of the Remote Desktop client. It only seems to be an issue when using it as a published app via the Desktop version of the Remote Desktop client.

It is a big problem for us, I'm not sure if Microsoft is aware of it or if it is slated to be fixed already etc..

**Comment by Xelu86** [comment]
Hey colin-small,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product or service rather than our documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
