### ISSUE TITLE
Cant add A child Domain to an existing Forest, W srv 2019 essentials.

### ISSUE THREAD

**Issue by mkmma** [MicrosoftDocs/windowsserverdocs#6627]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6116630e-8753-9f35-cd7c-1bac97ace1cd
* Version Independent ID: 03d21e87-8b89-ff82-3977-bfbb8b7b4bb9
* Content: [AD DS Installation and Removal Wizard Page Descriptions](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/ad-ds-installation-and-removal-wizard-page-descriptions#BKMK_Results)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/AD-DS-Installation-and-Removal-Wizard-Page-Descriptions.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/deploy/AD-DS-Installation-and-Removal-Wizard-Page-Descriptions.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by IngridAtMicrosoft** [comment]
@mkmma Would you please add more details to the issues with the documentation? The title is worded in such a way that we cannot tell if you are having problems adding a child domain to an existing forest or that the document states something that is not possible. Thanks!

**Comment by v-thepet** [comment]
Hello @mkmma, 

Thanks for contacting Microsoft. We value your feedback. 

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.  Note that per https://learn.microsoft.com/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers, "Active Directory Domain Services isn't supported on the following Windows operating systems: Windows MultiPoint Server, Windows Server Essentials." Therefore the AD DS configuration procedure described in this article can't be done with Windows Server Essentials. 

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples. 

For support cases or support tickets, extended troubleshooting, technical support, or product support, use one or more of the following methods: 

  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback). 

 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 

 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home). 

 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home). 

 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/). 

 - [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide) 

Because this issue is a non-documentation issue, we’re closing this thread. 

Thank you. 

#please-close
