### ISSUE TITLE
Windows Admin Center "connection refused"

### ISSUE THREAD

**Issue by Deeptnt** [MicrosoftDocs/windowsserverdocs#6680]
- Installed as gateway on Windows server 2019 std (UI)
- Was functionnal to August 22 - temp certificate expired - Renewed by app/modify reissue certificate
- When connecting via Chrome or Edge: connection timeout / connection refused
- ServermanagementGateway service running
- No response on port 443 (gateway was configured on port 443) 
- In "Microsoft-ServerManagementExperience" logs when restarting service: 
- Source: SMEGateway - event: 0 - Level: error
- > The signing certificate (thumbprint: 5EAD300DC7E4D637948ECB0ED829A072BD152E17) for file 'C:\Program Files\Windows Admin Center\System.ValueTuple.dll' is revoked.
-
> The signing certificate (thumbprint: 67B1757863E3EFF760EA9EBB02849AF07D3A8080) for file 'C:\Program Files\Windows Admin Center\System.Web.Http.dll' is revoked.
- This is repeated for 18 of the dlls in this directory. 
- These errors did not appear before renewing the certificate.
- A full uninstall - verified that all files were deleted - reboot - download and reinstall was done.
- Same result.

- 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f168bf93-cc54-2a7e-2c1c-7c649a8458d2
* Version Independent ID: 0edf20e5-268c-b5df-93a6-85186eb4ba86
* Content: [Windows Admin Center Common Troubleshooting Steps](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/support/troubleshooting)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/support/troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/manage/windows-admin-center/support/troubleshooting.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by Deeptnt** [comment]
added note:
The "Connection refused" message appears when I try to connect locally on the Admin Center Gateway.
The "Connection timeout" message appears when I try to connect from a client machine.

**Comment by dksimpson** [comment]
Hello @Deeptnt,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
