### ISSUE TITLE
Upgrade directly from 2012R2 to 2022

### ISSUE THREAD

**Issue by 02dag** [MicrosoftDocs/windowsserverdocs#6709]
We have now upgraded 10 servers directly from 2012R2 to 2022 and this works fine. Found this article on friday, and it is monday now.

My question is should we go forward with upgrading our 200 remaining 2012R2 servers to 2022 or or should we stop and go for 2019 instead? Going directly to 2022 will save us from a lot of work in the long run.

We cannot imagine that the server developers at Microsoft planned any differently when they added support for this. If it is not possible to do this direct upgrade, the installation readiness checks should have stopped it. It does not.

If it is possible to do it this way, your article could have mentioned a little bit more around this topic. Like for example "It is possible to do this, and, hey it is not a problem, however proceed with caution.....or do this first....."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505fe07b-6fdd-4887-3c8b-15405c5d8308
* Version Independent ID: 25645df2-0ffb-4cc3-a8d2-5466edd309fb
* Content: [Overview of Windows Server upgrades](https://docs.microsoft.com/en-us/windows-server/get-started/upgrade-overview)
* Content Source: [WindowsServerDocs/get-started/upgrade-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/upgrade-overview.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by dksimpson** [comment]
Hello @02dag,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
