### ISSUE TITLE
Migrating the ‘NPS' Network Policy Server from a 2012 R2 Standard to a new 2019 Server

### ISSUE THREAD

**Issue by SAIMMINHAS** [MicrosoftDocs/windowsserverdocs#6714]
Hi,

I first migrated it by Exporting and then Importing the NPS Configuration from the old to the new server.

I then manually tried by creating a new NPS Role on the new 2019 Server and then configured it. I just wanted to check if it has been correctly setup or not. The reason for that is because when i compare it with the old server, there is a slight difference. If you notice in the below snapshots, the ‘**NAP-Capable**’ column is missing from the new NPS Server Settings on the 2019 Server. Please note that i did gave the new RADIUS on the new server, the same IP Address as the old one.

**1) NPS on the old server (**2012 R2 Standard**)**
![image](https://user-images.githubusercontent.com/30388154/188648797-30ac5ef5-2cc9-453b-9f90-a7e9072cf4c9.png)

**2) NPS on the new server (**2019 R2 Standard**)**
![image](https://user-images.githubusercontent.com/30388154/188648935-2c849320-4e18-4d62-a512-e999655d8f6c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da547401-f0e8-a8ae-f350-a309109895d4
* Version Independent ID: c8521262-0bac-e256-1cd5-1b65e4902967
* Content: [Configure RADIUS Clients](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-radius-clients-configure)
* Content Source: [WindowsServerDocs/networking/technologies/nps/nps-radius-clients-configure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/technologies/nps/nps-radius-clients-configure.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by craigcaseyMSFT** [comment]
Hello @SAIMMINHAS,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
