### ISSUE TITLE
[feature request] How to Disable Drive Mapping in Remote Desktop (MSRDC) client?

### ISSUE THREAD

**Issue by voyager2u** [MicrosoftDocs/windowsserverdocs#6747]
[Enter feedback here]

The Drive Mapping was Enabled by default in the Windows Desktop client, and there is no option to turn off drive mapping.
 
<img width="580" alt="mapped-drives" src="https://user-images.githubusercontent.com/73457869/191473559-e9674c4a-7134-4864-b85e-9107b1b15cf5.png">
<img width="313" alt="settings" src="https://user-images.githubusercontent.com/73457869/191474200-c27613b5-1a8c-438c-a869-264c0a7a9770.png">

I would like to have the option to turn off drive mapping in client Settings, just like in the MSTSC.
<img width="637" alt="mstsc" src="https://user-images.githubusercontent.com/73457869/191475004-b4a0f70c-3672-4d5c-9d58-bcd49b0df21a.png">

Please add this feature in the future release, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Hey voyager2u,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product, service, or feature request rather than our documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
