### ISSUE TITLE
Administrative template admx/adml source?

### ISSUE THREAD

**Issue by martinbherbener** [MicrosoftDocs/windowsserverdocs#6773]
In this section https://learn.microsoft.com/en-us/windows-server/security/tls/manage-tls#configuring-tls-cipher-suite-order-by-using-group-policy I see the statement 

"From the Group Policy Management Console, go to Computer Configuration > Administrative Templates > Network > ..." 

I don't think the Network administrative template is installed by default (I'm running GPME on Windows 10, the AD DC is Windows Server 2019); where is it supposed to be found?  I've done a fair amount of searching and the only administrative templates I have found that address schannel config are unofficial.

thanks!

Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e40eec07-5000-8af5-37f9-c2908bea3c67
* Version Independent ID: 4540c962-9294-e70d-de5b-8094e608768c
* Content: [Manage Transport Layer Security (TLS)](https://learn.microsoft.com/en-us/windows-server/security/tls/manage-tls#configuring-tls-cipher-suite-order)
* Content Source: [WindowsServerDocs/security/tls/manage-tls.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/tls/manage-tls.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by dksimpson** [comment]
Hello @martinbherbener,

We'd like to express our gratitude for your commitment to our documentation. Unfortunately, we’ve recently fallen short of our usual standards in addressing documentation concerns in a timely manner and offer our apologies for any inconvenience we’ve caused.

Because this issue is now outdated, we’re closing this request. If we've addressed the documentation issue, this thread will also be closed. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
