### ISSUE TITLE
Change Domains

### ISSUE THREAD

**Issue by eostermueller** [MicrosoftDocs/windowsserverdocs#6786]
[Enter feedback here]

Need documentation on how to get "whoami /GROUPS" output for my user from a different domain other than my desktop domain.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15c3e19b-dd81-20a2-f797-9590d37cb84e
* Version Independent ID: f3d14a6d-f4fb-971f-c648-d69439e1b81e
* Content: [whoami](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/whoami)
* Content Source: [WindowsServerDocs/administration/windows-commands/whoami.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/whoami.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hi @eostermueller,

Thanks for contacting Microsoft. We value your feedback.

The Windows whois command doesn't have a built-in option to query group membership in other domains directly. It provides information about the current user and their group membership within the current domain context. If you need to query group membership in other domains, you would typically use PowerShell:

[Get-ADGroupMember (ActiveDirectory) | Microsoft Learn](https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adgroupmember?view=windowsserver2022-ps)

[Get-ADGroup (ActiveDirectory) | Microsoft Learn](https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2022-ps)

Since this isn't a Windows documentation issue, we'll now be closing this thread. Thanks again for your feedback.

#please-close
