### ISSUE TITLE
Port Range for v4tov4 is not working

### ISSUE THREAD

**Issue by dkalog** [MicrosoftDocs/windowsserverdocs#6790]
[Enter feedback here]
Port Range for v4tov4 is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3b40a3-1d83-9dab-d06b-784944580ddb
* Version Independent ID: 0be7bac0-6fc9-ce45-92dc-81d612ae8204
* Content: [Netsh commands for interface portproxy](https://learn.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy)
* Content Source: [WindowsServerDocs/networking/technologies/netsh/netsh-interface-portproxy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/technologies/netsh/netsh-interface-portproxy.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by craigcaseyMSFT** [comment]
Hello @dkalog,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
