### ISSUE TITLE
Plenty of White Space for Brief Summary

### ISSUE THREAD

**Issue by PaltryProgrammer** [MicrosoftDocs/windowsserverdocs#6934]
There is plenty of white space on the page next to each command for a brief summary of each thus obviating the need to click upon each in order to know its' purpose/effect/meaning\use which is of course a needless waste of time -Cheerios

**Comment by Xelu86** [comment]
Hey PaltryProgrammer,

Thanks again for contacting Microsoft, we value your feedback. 

There is no document in reference in this post. Based on the time this issue was created, corrections may or have not been made but as we don't know which documentation page is in question, we cannot verify. If you do find it, please let us know so proper updates can be made. We'll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
