### ISSUE TITLE
Windows 11 Command Update

### ISSUE THREAD

**Issue by EC-429** [MicrosoftDocs/windowsserverdocs#6955]
The provided PowerShell commands did not work, had to subsistute with:

1. Enable OpenSSH Authentication Agent in Services
2. Start-Service ssh-agent
4. Set-Service -Name ssh-agent -StartupType 'Automatic'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH for Windows](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=gui)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @robinharwood
* Microsoft Alias: **roharwoo**

**Comment by Xelu86** [comment]
Hey EC-429,

Thanks again for contacting Microsoft. We value your feedback. 

Reading through the PowerShell section of this article, it is describing how to start the `sshd.exe` process:

> _"To start and configure OpenSSH Server for initial use, open an elevated PowerShell prompt (right click, Run as an administrator), then run the following commands to start the sshd service"_

The PS command `Set-Service -Name sshd -StartupType 'Automatic'` is used to start the `sshd.exe` found in _C:\WINDOWS\System32\OpenSSH\sshd.exe_.

The command you're referencing, `Set-Service -Name ssh-agent -StartupType 'Automatic'`, is associated with the OpenSSH Authentication Agent found in _C:\WINDOWS\System32\OpenSSH\ssh-agent.exe_.

The `sshd.exe` process is responsible for running the SSH server and handling incoming SSH connections. It does not require the `ssh-agent.exe` process to be running in order to function properly. If you are not using SSH keys for authentication, then you do not need to worry about the `ssh-agent.exe` process. However, if you want to use SSH keys for authentication, then you will need to use the `ssh-agent.exe` process to manage those keys.

**Comment by Xelu86** [comment]
We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
