### ISSUE TITLE
Failover Clustering 

### ISSUE THREAD

**Issue by MisterSunshine44** [MicrosoftDocs/windowsserverdocs#7012]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab323676-c43c-f1cb-75f3-911fb54ac78b
* Version Independent ID: 19e5c814-4984-f1a9-1759-ac8c5bd14c87
* Content: [Failover Clustering](https://learn.microsoft.com/en-us/windows-server/failover-clustering/failover-clustering-overview)
* Content Source: [WindowsServerDocs/failover-clustering/failover-clustering-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/failover-clustering/failover-clustering-overview.md)
* Product: **windows-server**
* Technology: **failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dksimpson** [comment]
Hi @MisterSunshine44,

Because this issue is now outdated, we’re closing this request. If you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
