### ISSUE TITLE
Converting an evaluation version to a retail version (Server Core)

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windowsserverdocs#7017]
[Enter feedback here]
This was also still broken for Server 2019 and even now is still broken for Server 2022
 
WARNING: To launch Server Configuration tool again, run "SConfig"
PS C:\Users\Administrator> $PSVersionTable.BuildVersion.ToString()
10.0.20348.320
PS C:\Users\Administrator> get-hotfix

Source        Description      HotFixID      InstalledBy          InstalledOn
------        -----------      --------      -----------          -----------
WIN2022CORE   Update           KB5010475     NT AUTHORITY\SYSTEM  3/7/2022 12:00:00 AM
WIN2022CORE   Security Update  KB5010354     NT AUTHORITY\SYSTEM  3/7/2022 12:00:00 AM
WIN2022CORE   Update           KB5009639     NT AUTHORITY\SYSTEM  3/7/2022 12:00:00 AM

PS C:\Users\Administrator> Dism /Online /Get-CurrentEdition

Deployment Image Servicing and Management tool
Version: 10.0.20348.1

Image Version: 10.0.20348.524

Current edition is:

Current Edition : ServerStandardEvalCor

The operation completed successfully.
PS C:\Users\Administrator> Dism /Online /Get-TargetEditions

Deployment Image Servicing and Management tool
Version: 10.0.20348.1

Image Version: 10.0.20348.524

Editions that can be upgraded to:

Target Edition : ServerDatacenterCor

The operation completed successfully.
PS C:\Users\Administrator> DISM /online /Set-Edition:ServerStandardCor /ProductKey:VDYBN-27WPP-V4HQT-9VMD4-VMK7H /AcceptEula

Deployment Image Servicing and Management tool
Version: 10.0.20348.1

Image Version: 10.0.20348.524

Starting to update components...
Starting to install product key...
Finished installing product key.

Finished updating components.

Starting to apply edition-specific settings...

Error: 1168

An error occurred while applying target edition component settings. The upgrade cannot proceed.
For more information, review the log file.

The DISM log file can be found at C:\Windows\Logs\DISM\dism.log
PS C:\Users\Administrator>

2022-03-07 15:26:04, Error                 DISM   DISM Transmog Provider: PID=2956 TID=3184 Failed to copy edition license file. - ThreadSkuInstallEula(hr:0x80070490)
2022-03-07 15:26:04, Error                 DISM   DISM Transmog Provider: PID=2956 TID=972 Thread for Installing EULA Failed. - CTransmogManager::ProjectEditionLicenseFile(hr:0x80070490)
2022-03-07 15:26:04, Error                 DISM   DISM Transmog Provider: PID=2956 TID=972 Failed to apply edition settings - CTransmogManager::ApplyEditionSettings(hr:0x80070490)
2022-03-07 15:26:04, Error                 DISM   DISM Transmog Provider: PID=2956 TID=972 Failed to apply edition settings for [ServerStandardCor] - CTransmogManager::TransmogrifyWorker
2022-03-07 15:26:04, Error                 DISM   DISM Transmog Provider: PID=2956 TID=972 [Upgrading system]: An error occurred while applying target edition component settings. The upgrade cannot proceed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1b19ef8-a273-c1c8-18ff-7d29664bb9d2
* Version Independent ID: 8cf37a43-cff4-78de-0d66-2f482c022dc7
* Content: [Upgrade and conversion options for Windows Server](https://learn.microsoft.com/en-us/windows-server/get-started/upgrade-conversion-options)
* Content Source: [WindowsServerDocs/get-started/upgrade-conversion-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/upgrade-conversion-options.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by v-thepet** [comment]
Hello @DSPatrick,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. If a desired upgrade path doesn't show as available, you'll need to install the retail version as a fresh install. The doc changes will be live after the next business day.

To follow up on the product issue, you can use one of the following methods:

- From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback). 
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home). 
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home). 
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/). 
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide) 

Because this issue is a non-documentation issue, we’re now closing this thread. 

Thank you again and have a most pleasant day.
#please-close

**Comment by DSPatrick** [comment]
This is ridiculous. A document change does not fix the underlying problem!

**Comment by v-thepet** [comment]
Hi @DSPatrick, 

Thanks for contacting Microsoft. As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself. 

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples. 

Don’t use GitHub Issues if you’re searching for: 

- Support cases or support tickets 
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide) 
- Extended troubleshooting, technical support, or product support 

Instead, you can use the resources we listed in the previous comment. 

Because this wasn't a documentation issue, we have closed the thread. Thanks again.

**Comment by DSPatrick** [comment]
> 
> Documentation changes have been made to clarify and acknowledge this issue.  If a desired upgrade path doesn't show as available, you'll need to install the retail version as a fresh install. 

This is ridiculous. A document change does not fix the underlying problem!

**Comment by v-thepet** [comment]
@DSPatrick,

Thanks again for contacting Microsoft. As you point out, a documentation change does not fix the underlying problem. Therefore, we have closed this documentation issue.

**Comment by DSPatrick** [comment]
All the windows server feedback channels are now defunct so I guess we just have to put up and shut up.
