### ISSUE TITLE
Doesn't help if mstsc works but the app doesn't

### ISSUE THREAD

**Issue by lukos** [MicrosoftDocs/windowsserverdocs#7025]
All of this page is about making sure RDP is on and enabled. If, as in my case, the remote desktop client works (although the scaling doesn't) but the store app doesn't then there is nothing.

Also, we are now in 2023 and it is really time that apps stop reporting e.g. "Error 0x4" which is completely useless for anyone and imposes on customers the need to do Google searches for stuff that they won't be able to identify. If that code means "can't connect to machine" or "firewall blocked" then for goodness sake, please just print that, it would be much easier to find help!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 420f2431-a31d-c952-eec9-47399399e151
* Version Independent ID: c00b4f63-1ddf-27b5-835b-35f7d6d80484
* Content: [General Remote Desktop connection troubleshooting](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/troubleshoot/rdp-error-general-troubleshooting)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/troubleshoot/rdp-error-general-troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/troubleshoot/rdp-error-general-troubleshooting.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **delhan**

**Comment by Xelu86** [comment]
Hey lukos,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing an issue with the product or service rather than the documentation itself.

GitHub Issues for the Windows Server repo are monitored for content issues we can address, such as: broken links, grammar or wording, typos, updates, or incorrect code examples.

GitHub is not the right location or channel if searching for:

- Answers for support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:


- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

For additional feedback:

- From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**.
  - You can also provide feedback through the [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
 
As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day.
#please-close
