### ISSUE TITLE
clarification on flexibility of this tool

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windowsserverdocs#7033]
In the "scenarios" section, the second item says that this tool can be used to deploy identical test and production environments. What are the constraints for this statement? Can the test environment be joined to a different Active Directory domain in the same forest? Different forest? Does the restoration attempt to connect to the "old" location for backupDKM,? Is network connectivity therefore required, or on the other hand must be blocked?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f625ecc8-248e-e357-425b-dbd8234eb43f
* Version Independent ID: 383a61c4-2e82-4958-98b4-a0e8c124badb
* Content: [AD FS Rapid Restore Tool](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-rapid-restore-tool)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
Hey Mike-Crowley,

Thanks again for contacting Microsoft. We value your feedback. 

So for this section:

> ## Use case scenarios
> - **Deploy identical test and production environments**. Quickly create an accurate copy of the production AD FS in a test environment. You can also use the Rapid Restore tool to quickly deploy a validated test configuration to production.

All the constraints of the AD FS Rapid Restore tool is not mentioned as it is too much to detail every use case scenario. Searching for deeper specifics, technical support, scenarios, product/feature requests is completely outside our scope in GitHub. 

Based on the asks:

> #### Note that I am _NOT_ a community expert on this technology and responses are based on our documents surrounding this tool. 

- **Can be joined to a different Active Directory domain in the same forest?** 
  - From reading this doc, the AD FS Rapid Restore Tool can be used to restore an AD FS farm to a new environment within the same forest, as long as the new environment is in the same Active Directory domain as the original environment.
- **A different forest?** 
  - AFAIK, it's specifically designed to work within the same Active Directory forest.
    - The AD FS Deployment Tool or AD FS Federation Server Configuration Wizard may be more suitable in this instance. (I am not 100% confident that I'm correct).
- **Does the restoration attempt to connect to the "old" location for BackupDKM?** 
  - This really depends on how the AD FS server was or is being configured so there isn't a clear answer. It attempts to connect to the location of the BackupDKM but you can specify a different location, if not using the defaults, with the `-BackupDkmFile` parameter along with `Restore-AdfsRapidRestoreConfiguration` (which it may prompt for if it has been saved to a different location).
- **Is network connectivity therefore required, or on the other hand must be blocked?**
  - Yes, network connectivity is required between the computer on which the tool is running and the AD FS server that you are restoring using the AD FS Rapid Restore Tool.

We highly recommend the use of our support forums so that one of the community experts may be able to better assist:

- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/
- Microsoft Support: https://support.microsoft.com/ContactUs

**Comment by Mike-Crowley** [comment]
Thanks. Are you aware of a tool or documentation to support the migration of an ADFS farm from one domain to another domain?

**Comment by Xelu86** [comment]
@Mike-Crowley,

Did some more digging and looked into our forums:

https://learn.microsoft.com/en-us/answers/questions/432465/ad-users-migration-cross-forest

A user described the ADMT tool, [Active Directory Migration Tool version 3.2](https://www.microsoft.com/en-us/download/details.aspx?id=56570)

"The Active Directory Migration Tool version 3.2 (ADMT v3.2) simplifies the process of migrating objects and restructuring tasks in an Active Directory® Domain Service (AD DS) environment. You can use ADMT v3.2 to migrate users, groups, and computers between AD DS domains in different forests (inter-forest migration) or between AD DS domains in the same forest (intra-forest migration). ADMT can also perform security translation (to migrate local user profiles) when performing inter-forest migrations. NOTE: this tool has known problems and is in limited support – please carefully review the ADMT Known Problems and Support Statement link in Related Resources below before using." 

Is this more in line with what you're looking to achieve?
