### ISSUE TITLE
How do I set up an account that is a member of the built-in Administrators group?

### ISSUE THREAD

**Issue by tile2** [MicrosoftDocs/windowsserverdocs#7064]
Hi.  I ran the "(New-Object Security.Principal.WindowsPrincipal...GetCurrent...IsInRole...Admininistrator)" command and the result was False.  How can I make it true?  How do I set up an account that is a member of the built-in Administrators group?

Thanks in advance for your help,
Tien

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH for Windows](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=gui)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @robinharwood
* Microsoft Alias: **roharwoo**

**Comment by Xelu86** [comment]
Hey tile2,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with a Windows product or service, rather than the documentation itself.

GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. We offer other channels for engaging with us, whether you have a support question, product feedback, or other feedback. 

We cannot assist with the following as it's outside our scope of work:

- Support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, please use one or more of the following:

 - On a Windows OS, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
