### ISSUE TITLE
I like the little icons better than having to use a sign-in name better Oh you

### ISSUE THREAD

**Issue by aac4041** [MicrosoftDocs/windowsserverdocs#7086]
I like the old login better where they show the little icons shown in these photographs this new way I do not like it at all Will you have to enter a username in the password How do I change it back to the old way like shown in these photos

I'm trying to figure out how to get it back to this way where it shows individual icons with the names on them

![Screenshot_20230302-095214](https://user-images.githubusercontent.com/17684051/222745173-ba7d15bd-431b-4afe-b719-e1f268cb13d1.png)

![Screenshot_20230302-095115](https://user-images.githubusercontent.com/17684051/222745260-faf100ee-a51b-4699-8f33-520483d33656.png)

This is the new way and I hate it I like the old way better

![Screenshot_20230303-092557](https://user-images.githubusercontent.com/17684051/222745486-6dd4c180-8b6d-48e6-bce0-8935d7bd01f3.png)

**Comment by Xelu86** [comment]
Hey aac4041,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described a potential issue with a Windows product or service, rather than one of our documents.

GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. We offer other channels for engaging with us, whether you have a support question, product feedback, or other feedback. 

We cannot assist with the following as it's outside our scope of work:

- Support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, please use one or more of the following:

 - On a Windows OS, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
