### ISSUE TITLE
Please explain in a user friendly way the actions to be done, fixing the security warnings.

### ISSUE THREAD

**Issue by FlightControl-User** [MicrosoftDocs/windowsserverdocs#7113]
[Enter feedback here]

Windows defender gives me this warning.

![image](https://user-images.githubusercontent.com/13690775/226166807-adeb7b6c-1490-4569-87e0-21ca752e6cd3.png)

And when i try to click for help, it gives me this page.

I am an END USER, not a security specialist. Please explain in a user friendly way how to resolve the issue.

Sven

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b04bc4d-9435-cdbc-429f-2433ada7bd37
* Version Independent ID: 5c902397-b2e7-4435-2b37-a57919434c9e
* Content: [Configuring Additional LSA Protection](https://learn.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection)
* Content Source: [WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @FlightControl-User,

Thank you for contacting Microsoft. We value your feedback and apologize for the delay in responding to your issue.

This issue was caused by a Windows Update in March 2023, but an update in July 2023 fixed the problem. For more information, see ["Local Security Authority protection is off" with persistent restart](https://learn.microsoft.com/en-us/windows/release-health/resolved-issues-windows-11-22h2#3048msgdesc). This problem should be resolved, but if you're still experiencing issues, you can refer to the following support links:

[Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press Windows + F. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).
Since this issue has been resolved, we're closing this thread. Thanks again for your input, and have a very pleasant day.

#please-close
