### ISSUE TITLE
Error: insufficient memory

### ISSUE THREAD

**Issue by SoftwareTailor** [MicrosoftDocs/windowsserverdocs#7115]
I got an _insufficient memory_ error using xcopy, but it seems to be a minor glitch in some cases.
You can get the error even if you just want to use the list switch, xcopy /y/d/l

You should be able to use xcopy . d: to copy files from a folder on one drive to a folder on another drive.
Or use xcopy folder1 d:folder1, but it's only a minor glitch.
Instead, use xcopy *.* d: to copy files.
Or use xcopy folder1\*.* d:folder1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69a1e859-b436-290e-69c0-810dd3a5ce90
* Version Independent ID: 10c81289-2bf7-40d9-39ea-e624cf92aa3e
* Content: [xcopy](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/xcopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/xcopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey SoftwareTailor,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made in the Remarks section about insufficient memory and will be live after the next business day. 

Other reasons why this can _potentially_ occur is due to:

- Trying to copy too large a number of files or folders
- Unnecessary programs or several browser tabs consuming RAM
- RAM health degradation
- Too little RAM set in VM environment

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
