### ISSUE TITLE
After Enableing Local Security Authority Protection still show warning

### ISSUE THREAD

**Issue by gajjardarshithasmukhbhai** [MicrosoftDocs/windowsserverdocs#7118]
Hi, I am creating this issue. Today I get a warning about the LSA is off. After LSA is on and restart my machine as per mentioned guidelines. still showing the same warning. Please fix this If need any help from my side, let me know. for Ref attach SC.
![Screenshot 2023-03-22 001238](https://user-images.githubusercontent.com/34138770/226710095-a9b57091-59c7-4bfb-8b29-e7b62e782dba.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b04bc4d-9435-cdbc-429f-2433ada7bd37
* Version Independent ID: 5c902397-b2e7-4435-2b37-a57919434c9e
* Content: [Configuring Additional LSA Protection](https://learn.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection)
* Content Source: [WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @gajjardarshithasmukhbhai,

Thank you for contacting Microsoft. We value your feedback and apologize for the delay in responding to your issue.

This issue was caused by a Windows Update in March 2023, but an update in July 2023 fixed the problem. For more information, see ["Local Security Authority protection is off" with persistent restart](https://learn.microsoft.com/en-us/windows/release-health/resolved-issues-windows-11-22h2#3048msgdesc). This problem should be resolved, but if you're still experiencing issues, you can refer to the following support links:

- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide) 
 - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback). 
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home). 
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home). 
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Since this issue has been resolved, we're closing this thread. Thanks again for your input, and have a very pleasant day.

#please-close
