### ISSUE TITLE
Disk copy discourages dd but provides no alternative

### ISSUE THREAD

**Issue by SmallJoker** [MicrosoftDocs/windowsserverdocs#7199]
> Don't use a block-level copy to transfer the data. This method also copies the bad sector table, and the new disk treats these sectors as bad even though they're healthy.

This mentions that `dd` is not an option, however providing no viable alternatives. Please refer to applications that do it properly.
EDIT: For the context: I would like to move my Windows installation to an SSD, hence file permissions and any Windows-specific information within NTFS must be preserved. If not `dd`, what else?
EDIT2: Or would it be possible to clear this "bad sector table" afterwards? If so, please mention that somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f91258c0-7929-4d60-3f88-e67c957584c6
* Version Independent ID: d952a74b-1f86-de68-df1e-1956ac045fc7
* Content: [Shrink a basic volume](https://learn.microsoft.com/en-us/windows-server/storage/disk-management/shrink-a-basic-volume)
* Content Source: [WindowsServerDocs/storage/disk-management/shrink-a-basic-volume.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/disk-management/shrink-a-basic-volume.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hi @SmallJoker,

Thanks for contacting Microsoft. The intent of this article is to discuss the use of native Windows-based software to perform disk-related functions, You can also use non-Windows software to perform disk functions. 

Since dd isn't a native Windows app, this isn't a Windows documentation issue, so we're closing this issue. 

Thank you.

#please-close

**Comment by SmallJoker** [comment]
@v-thepet I see. Thank you for your answer. The issue is however not about `dd` in particular but rather that there is no alternatives provided for the "do not block-level copy" advice. Whereas it is good to know that block-level copy should not be performed, it does not provide an answer to the follow-up question of *how it should be done properly* (including Windows-based software).

**Comment by v-thepet** [comment]
@SmallJoker - Thanks for your response. I think I see the problem now. The formatting of the bullets and line breaks in that section seems to imply that block-level copy should never be done. Actually that was meant to apply only to the situation where the shrink operation failed due to bad sectors. The arrangement of bullets and paragraphs in that section should be more like this:

>## Other considerations

>- When you shrink a partition, certain files like the paging file or the shadow copy storage area can't be automatically relocated. Also, you can't decrease the allocated space beyond the point where the unmovable files are located.
>
>- If the shrink operation fails, check the Application Log for Event 259, which identifies the unmovable file. If you know the cluster(s) associated with the file that's preventing the shrink operation, you can also use the **fsutil** command at a command prompt (enter **fsutil volume querycluster /?** for usage). When you provide the **querycluster** parameter, the command output identifies the unmovable file that's preventing the shrink operation from succeeding. 
> 
>   In some cases, you can relocate the file temporarily. For example, if you need to shrink the partition further, you can use Control Panel to move the paging file or stored shadow copies to another disk, delete the stored shadow copies, shrink the volume, and then move the paging file back to the disk.
> 
>-  If the number of bad clusters detected by dynamic bad-cluster remapping is too high, you can't shrink the partition. If this situation occurs, consider moving the data and replacing the disk. Don't use a block-level copy to transfer the data. This method also copies the bad sector table, and the new disk treats these sectors as bad even though they're healthy.

I've proposed this update in a PR, and I hope that clarifies the issue. (BTW while investigating I noticed the following article about moving a Windows partition, not directly relevant to shrink: https://forums.opensuse.org/t/using-dd-to-clone-windows/87151.)

Thanks again for your feedback!

**Comment by SmallJoker** [comment]
@v-thepet Yes, your theory matches with what I understood from the article. Finally I copied the partitions with Clonezilla which worked out well but I was not sure whether it was done properly. The bad sector count was negligible, thus I conclude that such tool is indeed suited to copy partitions of healthy drives. Thank you.
