### ISSUE TITLE
Please add comments/disclaimers that the date format must match the culture.

### ISSUE THREAD

**Issue by jamesaepp** [MicrosoftDocs/windowsserverdocs#7205]
I was just wondering why I couldn't use a certutil -deleterow command. The command kept failing with an unhelpful error message. The reason was because the documentation uses a d/m/yyyy format but my server's shortdate format was yyyy-mm-dd. That was enough to break the command. PLEASE update the documentation with very specific call-outs to this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d238db2c-10e1-d418-e780-54b421779754
* Version Independent ID: d1313e31-d990-2f0b-3f70-ae0fcdb4ba5c
* Content: [certutil](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/certutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/certutil.md)
* Service: ****
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @jamesaepp,

Thanks for contacting Microsoft. We value your feedback.

A documentation change has been made to address this issue and will go live the next business day. See the new Note at the beginning of the article.

Thank you again and have a most pleasant day.
#please-close

**Comment by jamesaepp** [comment]
@v-thepet the new note is simply not technically correct.

It currently states:

> Certutil Date arguments expect the format mm/dd/yyyy, for example 5/6/2022 for May 6, 2022. If your server isn't configured with US regional settings, using certutil with Date arguments might produce unexpected results.

A more accurate note would be something _like_ the following (would require some wordsmithing by MS to make it clearer):

> Certutil Date arguments expect the format of the date to follow the conventions defined by the user profile's region "short date" format. For example 5/6/2022 for May 6, 2022 if using the default US regional settings, but 2022-05-06 for the same date if using the yyyy-MM-dd short date format.

**Comment by v-thepet** [comment]
@jamesaepp - Thanks for your response. After reviewing it and the original issue (also raised by others), the pain point for Date in the -deleterow param seems to be that it uses US m-d-y format rather than Euro/global d-m-y. But after experimenting with Windows Time & Language short date settings I don't think it's directly affected by that. And some other certutil options that use Date, like -view -restrict, expect other formats like y-m-d. So I clarified the Note. 

Hope this helps, but if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

**Comment by jamesaepp** [comment]
@v-thepet just out of curiosity, when you experimented with the short date intl/region settings, were you restarting your shell? The shell you open for cmd/powershell only "adopts" the region settings at launch time. If you open as shell while the shortdate is mm/dd/yyyy, then set the region to a format such as dd/mm/yyyy, the shell doesn't know about this until you restart it.

**Comment by v-thepet** [comment]
@jamesaepp Yes I did reboot. The short date format for example in the output of certutil -store did change. But not for these certain other params. If you see different please feel free to open an issue with repro steps if possible! Thanks :-)
