### ISSUE TITLE
Verifying LSA protection - missing info on how to display Windows Logs

### ISSUE THREAD

**Issue by pakanek** [MicrosoftDocs/windowsserverdocs#7210]
Section 'Verifying LSA protection' lacks information on how to show Windows Logs - that is by running 'Event Viewer'.
I am regular Windows user. Windows 11 keeps complaining about LSA being off despite turning it On and restarting. So I have no clue how to display Windows Logs to ensure that LSA is actually on. Knowing that I will find Windows logs in application 'Event Viewer' would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b04bc4d-9435-cdbc-429f-2433ada7bd37
* Version Independent ID: 5c902397-b2e7-4435-2b37-a57919434c9e
* Content: [Configuring Additional LSA Protection](https://learn.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection#verifying-lsa-protection)
* Content Source: [WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by spiralofhope** [comment]
The sub-link would be
https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md#verifying-lsa-protection

I also echo the complaint that this makes little sense:

> To discover if LSA was started in protected mode when Windows started, search for the following WinInit event in the System log under Windows Logs:
> 
> 12: LSASS.exe was started as a protected process with level: 4

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/492880/899bb5ce-5b93-4ff6-b262-d920b883c97a)

Does the above mean it is not started?

Additionally, it might be useful to provide a link to documentation on using the event viewer.

**Comment by SnookerPhil** [comment]
Are you looking in Windows Logs/System Log section? Shouldn't be in any log labeled as LSA which is why I'm asking. I think that's the problem you're having.

**Comment by v-thepet** [comment]
Hello @pakanek, 

Thank you for contacting Microsoft. We value your feedback.

We've made a documentation update that clarifies how to search Event Viewer for the event that indicates LSASS.exe was started as a protected process. The update will be live after the next business day.

Also, the issue of Windows 11 incorrectly reporting LSA protection status was caused by a Windows Update in March 2023, but an July 2023 update fixed the problem. For more information, see ["Local Security Authority protection is off" with persistent restart](https://learn.microsoft.com/en-us/windows/release-health/resolved-issues-windows-11-22h2#3048msgdesc). 

We'll now be closing this thread. Thanks again for your feedback, and have a most pleasant day.

#please-close
