### ISSUE TITLE
Skip verify certificate warning on iOS app

### ISSUE THREAD

**Issue by rwehe** [MicrosoftDocs/windowsserverdocs#7319]
I'm able to RDP to my Windows machine from macOS using the Microsoft Remote Desktop application, however I can't do it from an iOS device using the RD Client App (version 10.4.7). I believe the issue is that on macOS I'm prompted to be able to continue past a certificate that couldn't be verified but I'm not able to continue past that from the iOS application. Using the same config on both setups (clients in same subnet) the iOS app spins with the text "Securing connection to remote PC..." instead of allowing me to accept the untrusted (self-signed) certificate.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d21e96b-c8a6-7f9f-76e1-62ee4fbde62b
* Version Independent ID: 5530201e-2ff5-19de-5990-1a996cf5ef2e
* Content: [Get started with the iOS client](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-ios)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Hey rwehe,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with a Windows product or service, rather than the documentation itself.

Per this article https://techcommunity.microsoft.com/t5/windows-server-for-it-pro/security-risk-ios-remote-desktop-client-accepting-invalid-rd/m-p/3093083, it appears this was a security risk for iOS devices to behave this way and may have been rectified.

GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. We offer other channels for engaging with us, whether you have a support question, product feedback, or other feedback. 

We cannot assist with the following as it's outside our scope of work:

- Support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, please use one or more of the following:

 - On a Windows OS, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
