### ISSUE TITLE
Is PKTMON ready for SQL Server 2022, TDS 8.0 and TLS 1.3?

### ISSUE THREAD

**Issue by DavidWing** [MicrosoftDocs/windowsserverdocs#7350]
[Enter feedback here]
Can PKTMON capture, dissect and present network packets from a connection to SQL Server 2022 configured to require TDS 8.0 protocol (at the application level) resulting in a TLS 1.3 protocol handshake (at the transport level)?

PS: WireShark does not yet support TDS 8.0 protocol (https://ask.wireshark.org/question/31853/when-will-tds-80-be-added-to-protocol-types/)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53ec0bc8-a577-0626-23b5-5973f741fc7b
* Version Independent ID: ed759e11-bb84-d2fb-ec60-b1ca08d9500a
* Content: [Packet Monitor (Pktmon)](https://learn.microsoft.com/en-us/windows-server/networking/technologies/pktmon/pktmon)
* Content Source: [WindowsServerDocs/networking/technologies/pktmon/pktmon.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/technologies/pktmon/pktmon.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @khdownie
* Microsoft Alias: **wscontent**

**Comment by DavidWing** [comment]
Can someone confirm that this is the appropriate place to provide my feedback (questions) about PKTMON?

**Comment by DavidWing** [comment]
@khdownie - are you able to respond?

**Comment by dksimpson** [comment]
Hello @DavidWing,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
 - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close
