### ISSUE TITLE
In-place upgrade of KMS server? 

### ISSUE THREAD

**Issue by mikemagarelli** [MicrosoftDocs/windowsserverdocs#7459]
Is an in-place upgrade supported for a server running KMS? I can find no clear documentation that confirms or denies that it is supported. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26a28fb3-5359-dcd1-7361-64deec4f1fd5
* Version Independent ID: fd95c553-bd8d-f060-5bfe-ad5b69ab1216
* Content: [Perform an in-place upgrade of Windows Server](https://learn.microsoft.com/en-us/windows-server/get-started/perform-in-place-upgrade)
* Content Source: [WindowsServerDocs/get-started/perform-in-place-upgrade.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/perform-in-place-upgrade.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @robinharwood
* Microsoft Alias: **roharwoo**

**Comment by mikemagarelli** [comment]
Hi. Is there any update on this?

**Comment by v-thepet** [comment]
Hello @mikemagarelli,

Thanks for contacting Microsoft.

There's no reason this wouldn't be supported, but just like upgrading with a new server, the steps and issues would vary depending on the OS version being upgraded to and from, as well as the clients the KMS host needs to support. For example when upgrading from WS 2016 to 2019, the Volume Activation Services role will migrate straight across or possibly need to be reinstalled after a restart, but upgrading from 2012 R2 to 2019, you would need to install the KMS Host for 2019. 

For more information about your particular scenario, see the KMS documentation linked in the article, particularly the section on [KMS host required updates](https://learn.microsoft.com/windows-server/get-started/kms-activation-planning#kms-host-required-updates). I also found these resources that mentioned doing an in-place upgrade with KMS, although not always as the main point or question:

- [How to upgrade KMS server to new OS](https://techcommunity.microsoft.com/t5/windows-server-for-it-pro/how-to-upgrade-kms-server-to-new-os/m-p/3030521) - The OP wants to install KMS on a new server but there is a subquestion about in-place upgrade that indicates it should work
- [Upgrading Server 2012 with KMS host installed to 2019](https://community.spiceworks.com/topic/2268673-upgrading-server-2012-with-kms-host-installed-to-2019) - Indicates that in-place will work but might lead to (unspecified) problems later, and it's easy to upgrade to a new server
- [Resolved | KMS Server stopped working right after updating Server to 2019](https://www.linkedin.com/pulse/resolved-kms-server-stopped-working-right-after-updating-haider) - Had to uninstall the Volume Activation Services role and restart

For support cases or tickets, extended troubleshooting, technical support, or product support, you can use one or more of the following methods: 

 - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback). 
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home). 
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home). 
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/). 
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide) 

Because this is a non-documentation issue for this article, we’re closing this thread. 

Thank you. 

#please-close
