### ISSUE TITLE
Changing CA might cause interesting problems

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/windowsserverdocs#7489]
I suppose that I'm on the bleeding edge with regards to VPN certificate problems. My problem might help other people who change the CA.

We have changed the internal CA and are issuing new certificate templates and certificate. The VPN server recently got new certificates, but we didn't delete the old ones in case there was problems. There was problems, but they were resolved. I thought.

The error messages indicated certificate problems, but all the certificates were correct. I discovered that just changing the certificates was not enough, the server did not present the VPN clients with the correct server certificate. We had to do `Set-VpnAuthProtocol -RootCertificateNameToAccept $RootCACert -PassThru` to get the clients and servers to agree about the certificates. 

That was good, but suddenly there were new problems. Seemingly random PCs no longer connects to the VPN even if they have valid certificates in both ends. Reinstalling the client operating system and using the new certificate didn't work. But older reinstallations and new certificates worked fine. In WireShark, it looked the same as the previous problem. The server certificate was rejected by the client.

Eventually checking the `Application and Services Logs -> Microsoft -> Windows -> CAPI2 -> Operational` event log on the server showed what was going on. The server was remembering that the PCs had previously used certificates with the old CA and the server presented the old server certificate to clients with the new VPN certificated. The old certificate was rejected by the VPN client.

I'm now waiting for time to restart the VPN server to see if that clears the memory problem. I will probably also have to remove the old certificates. There might be new problems because SCCM seems to have a talent for locking itself out of folders. And that causes the client to not update the client VPN sertificate because it is distributed as a package.

To me, the event logs are clumsy on the server. There really should have been events which speeded up investigation the problem. E.g. connecting the clients with the certificates.  That would make searching easier.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bcd6e591-3a1f-84a8-5406-4b2877e6f6bf
* Version Independent ID: bcd6e591-3a1f-84a8-5406-4b2877e6f6bf
* Content: [Troubleshoot Always On VPN](https://learn.microsoft.com/en-us/Windows-server/remote/remote-access/troubleshoot-always-on-vpn)
* Content Source: [WindowsServerDocs/remote/remote-access/troubleshoot-always-on-vpn.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-access/troubleshoot-always-on-vpn.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **inhenkel**

**Comment by craigcaseyMSFT** [comment]
Hello @Tarjei-stavanger,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with the Window Server product or service, rather than the documentation itself.

As you're probably aware, we offer many channels for engaging with us, whether you have a support question, product feedback, or other feedback.  GitHub Issues in the Windows Server repo are monitored for content issues we can address, such as broken links, grammar or wording, typos, updates, or incorrect code examples.

Don’t use GitHub Issues if you’re searching for:
- Support cases or support tickets
- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, use one or more of the following methods:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Because this issue is a non-documentation issue, we’re closing this thread.

Thank you.

#please-close

**Comment by Tarjei-stavanger** [comment]
Actually, it is a documentation issue.

This will only be a problem if the Certificate Authority is changed. Or other changes need to be made to the VPN profile. It is not likely to happen often.

We are still waiting for Microsoft Support to conclude what our problem is :-)

We resolved the problem by swapping the VPNphonebook with a known good one. Depending on the VPN profile PowerShell script might not work. I think I'm going to complain about that when Microsoft Support responds.

That is something that might be useful to document. It might be useful to know in case the VPN profile needs to be changed. And it will be very useful if the person doing the fixing didn't configure the VPN in the first place and don't know what the profile contains.
