### ISSUE TITLE
Failed to add filter: The system cannot find the file specified.

### ISSUE THREAD

**Issue by angelperezleon** [MicrosoftDocs/windowsserverdocs#7542]
I am getting this:
C:\Users>pktmon filter add MySubnet -i 10.10.10.0/24
Failed to add filter: The system cannot find the file specified.

Suspect I need to install some packages?
Don't see anything on web searches to help with this error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62b31b8b-483b-0b22-7b97-b91697c78d26
* Version Independent ID: c27d6b3d-db6d-07f0-1fe1-a389f7731e46
* Content: [pktmon filter add](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/pktmon-filter-add)
* Content Source: [WindowsServerDocs/administration/windows-commands/pktmon-filter-add.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/pktmon-filter-add.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @robinharwood
* Microsoft Alias: **wscontent**

**Comment by Xelu86** [comment]
Hey angelperezleon,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product or service rather than our documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close

**Comment by tmolenh** [comment]
It likely means pktmon needs to be run as admin.
