### ISSUE TITLE
What's 0×300005f error code

### ISSUE THREAD

**Issue by Realtorgrant** [MicrosoftDocs/windowsserverdocs#7567]
![Screenshot_2023-10-29-22-23-28-486_com.microsoft.rdc.androidx.jpg](https://github.com/MicrosoftDocs/windowsserverdocs/assets/149342991/e7932a35-4054-4989-a06c-600acfd44e5a)

![Screenshot_2023-10-29-22-22-46-565_com.microsoft.rdc.androidx.jpg](https://github.com/MicrosoftDocs/windowsserverdocs/assets/149342991/5e2aa861-bdc8-4f4d-bbbe-602d9d529778)

**Comment by christking246** [comment]
Hey @Realtorgrant,
 
Thanks again for contacting Microsoft, we value your feedback.
 
You have described an issue with a product or service rather than our documentation. Please see our [GitHub content feedback guidelines](https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread.
 
Thank you and have a most pleasant day.
#assign:christking246
#please-close

**Comment by christking246** [comment]
#assign:christking246
