### ISSUE TITLE
Instructions after Step 4 are missleading

### ISSUE THREAD

**Issue by floremsft** [MicrosoftDocs/windowsserverdocs#769]
At the end of Step 4, you are asked to either go to Step 8, or 7, which make you skip steps 5 and 6 in any case.
A customer and myself interpreted the instructions the same way. But we soon realized that step 6 was mandatory.
Could it be rephrased?

Also, my customer and I faced the same issue described below, to bring the WSUS server online again:
-WID had to be removed
-WSUSutil.exe command required

https://social.technet.microsoft.com/Forums/ie/en-US/fd38f661-0352-4cee-b6df-4bf4763b3aa4/updateservicesdbxml-missing?forum=winserverwsus

_**Step 4:
Verify permissions on the database:
Right-click the SUSDB, select Properties, and then click Permissions. The NT AUTHORITY\NETWORK SERVICE account should be listed. If it is not, you need to add it.
If both WSUS and SQL Instance are on the same machine skip to step 8. Otherwise proceed to step 7.**_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e2a5a31-29b9-5599-2f14-bc244c5da034
* Version Independent ID: 393db29c-0866-46f4-9ee6-7ae82e8cb29f
* Content: [Migrating the WSUS Database from (Windows Internal Database) WID to SQL](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wid-to-sql-migration)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md)
* Service: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
Thanks, Florent! We'll take a look and update.

**Comment by slylabs13** [comment]
Yes the additional step 6 is *essential* and I (like probable *everyone* who follows these instructions) skipped step 6 because it looked like I was told to. Afterwards the trick is to run the postinstall, otherwise the database cannot grow beyond the roughly 8 gig limit of the local database. The command in an elevated DOS prompt is first navigate to C:\Program Files\Update Services\Tools then run WsusUtil.exe postinstall SQL_INSTANCE_NAME=<SERVER-NAME>\<SQL-INSTANCE>. (The instructions in the link above fail to mention that the instance name is not enough. I found out by trial and error). I now am able to connect in the WSUS console, and then run the cleanup wizard. I may actually be on my way back to WSUS functionality after weeks of being down! Just a note to anyone at Microsoft who could be listening: Don't put out software that will eat it's own liver if the default settings are used.

**Comment by slylabs13** [comment]
something got undone. it's WsusUtil.exe postinstall SQL_INSTANCE_NAME=<server-name>\<SQL-INSTANCE>

**Comment by slylabs13** [comment]
OK the web page is deleting what I type after the equal sign! Who wrote this HTML??? Its = left angle bracket server name right angle bracket backslash left angle bracket sql instance right angle bracket!!!!!

**Comment by aydeisen** [comment]
@floremsft @lizap 
The document is an obvious copy-and-paste from the Windows Server 2008 R2 documentation, with little rework done.  I took a stab at reformatting the document for clarity (#1223), doing my best to leave the content intact.  Seeing that this issue has been open for almost 3 months, I can take a stab at adding the instructions for wsusutil based on the [10/18/2016 blog in TechNet](https://blogs.technet.microsoft.com/sus/2016/10/18/recreating-the-susdb-and-wsus-content-folder-for-a-windows-server-2012-based-wsus-computer/), but I'd prefer leave content to the MS professionals.

NOTE: I've performed these steps multiple times previously, so I wouldn't be augmenting the document in a vacuum, if I were to do it.

**Comment by lizap** [comment]
The wonderful @aydeisen cleaned up the formatting for this article and updated per the comments above. You can see it here: https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wid-to-sql-migration

I'm going to close this issue, in light of those changes. Thanks, all!
