### ISSUE TITLE
Can't find any info on TSCLIENT connections

### ISSUE THREAD

**Issue by ComputerHabit2** [MicrosoftDocs/windowsserverdocs#7761]
The RDP app seems useless.  Menus are weird.  Can barely know if I've even 'saved' something.

There is no area about TSCLIENT connections.  Especially for workspaces.

**Comment by Xelu86** [comment]
Hey @ComputerHabit2,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product, service, or feature request rather than our documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
