### ISSUE TITLE
icacls crashes

### ISSUE THREAD

**Issue by sjakob52** [MicrosoftDocs/windowsserverdocs#796]
icacls is not functioning -- exists in the system directory but crashes at execution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a990d09-b5b1-3aba-de57-0aec79c12784
* Version Independent ID: 36d90c17-ba95-4ed6-de9d-f379dcad6c4d
* Content: [icacls](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/icacls)
* Content Source: [WindowsServerDocs/administration/windows-commands/icacls.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/icacls.md)
* Service: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
@sjakob52 : Sorry that it has taken so long to post a reply to your issue ticket. Please note that this repository is intended for improvement of the Microsoft Docs documentation pages, not so much for troubleshooting software or the OS itself. I can only assume that your issue has already been resolved via other resources, so just to let you know what I would have suggested if I had been around to notice this ticket earlier:

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

I will proceed to close this issue ticket now, but if you find that there are any errors, discrepancies or details in need of correction, please open a new ticket to report the faulty parts of the document page itself. Thank you for using the Microsoft Docs documentation pages (even though it did not resolve your issue back in 2018).

**Comment by illfated** [comment]
#please-close
