### ISSUE TITLE
Why its not working Mr. @ Deadmann 

### ISSUE THREAD

**Issue by actionaer** [MicrosoftDocs/windowsserverdocs#802]
Why its not working Mr. @Deadmann  let me help you. Its made easy then before. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5581a04a-e204-4a19-3eba-0852d2eb5d8e
* Version Independent ID: 820c77b6-2182-7e92-bbe6-0819f727d207
* Content: [Remote Desktop clients FAQ](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md)
* Service: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by deadmann** [comment]
are you sure that you are asking a right person? or is there any background behind this question which i do not remember?

BTW if you refer my old issue in windows 10, i'm using local user because i hate passwords, and also my family use my PC and i don't want to consume space for separate users, or give my password away to anyone.
Then i use Mikrotik router board and provide a nat between my network and outside world, and i use port forwarding for remote desktop port, to access my PC through outside world...

The issue is, i never sign out my pc, family user may wish to use, or when i get back it take long time for user to sign in, yet when i'm in need and i'm not home when i try to connect, i receive the error which indicates: that the local user denied my presence... even one i tried with my mobile from home, and no dialog msg appeared to ask me the local user if i want to deny my own access from other device (my phone).
Even if any dialog happen to appear it should get lost once it take long time...
I even gave Administrative permission to the user i use for my phone, thinking maybe it's because the local user has higher authority, but no luck.
this is so frustrating. That's all the info i can give you, even i tried searching, but search engines are flooded with garbages of same/repeated question from below average users, and with high filtering of sentences no result will get returned.

Thank you for your concerns,
Hassan F.
