### ISSUE TITLE
Your session ended because of an error

### ISSUE THREAD

**Issue by preetamzare** [MicrosoftDocs/windowsserverdocs#827]
![image](https://user-images.githubusercontent.com/29382020/40124575-e7a62480-5939-11e8-8ce9-0db8f86f06b1.png)
Attached is the image. No errors in event viewer, IIS logs. Neither at server side nor at client side. So no clue why it is failing.

**Comment by uc-prk** [comment]
I am facing the same issue can anyone please help

**Comment by illfated** [comment]
Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
