### ISSUE TITLE
Hybrid Cloud Print limitations

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windowsserverdocs#890]
Hi, Setup worked fine, but, please update your article with limitation of this solution -> when you print, user cannot access printer preferences to change tray to print, change paper size A3, to change black/white etc. so all printing preferences not showing, only limited as page layout. So if you are using Azure and you need set this up, you buy a server from Azure, you buy consultant maybe or spent your time in order to set this up and at the end solution is limited.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21d1d072-911f-92c0-248a-9e44efbff42d
* Version Independent ID: 0fdb921d-d97d-5b12-ae28-286216e130df
* Content: [Deploy Windows Server Hybrid Cloud Print](https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-deploy)
* Content Source: [WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @msjimwu
* Microsoft Alias: **coreyp**

**Comment by msjimwu** [comment]
We are aware of the issue regarding printing preferences when running on Windows Server 2016.  This has been addressed in Windows Server 2019, which is available for preview.

**Comment by lightupdifire** [comment]
Hello Jimmy,

Thanks for info! I will wait for 2019 release in our Azure tenant.

2018-05-30 0:26 GMT+02:00 Jimmy Wu <notifications@github.com>:

**Comment by lightupdifire** [comment]
Hello,
We have deployed Windows Server 2019. We deployed hybrid cloud print configuration. Still the printing preferences not available when using Windows Server 2019... 
Can you please check? Else we simply go another solution.

**Comment by GillesPE** [comment]
Hello,
I have the same issue with Windows 2019 like 2016, We deployed hybrid cloud printing but still the printing préférences not available..
Please help.

**Comment by msjimwu** [comment]
Thank-you reporting the issue you are hitting with Windows Server 2019.  To help us investigate, please let us know what is the Make and Model of the printer.

**Comment by GillesPE** [comment]
For the moment, we use a Lexmark X792 with Lexmark universal V2 drivers on Print Server.
Same issue with the EcpPrintTest, i think it's not a Make and Model printer issue, just a limitation of Microsoft Enterprise Cloud Print Class Drivers.
I thought I wouldn't have any more problems in Windows Server 2019.

**Comment by Jo0Lz** [comment]
I am currently in the process of deploying a Server 2019 machine in Azure, because the limitations regarding printers are supposed to be resolved. 
These comments make me fear that is going to be a disappointment. 

Currently having issues with my 2016 Server throwing away print jobs in color, black and white are working fine, but we can't use the finisher of the printers or select the tray to be used. I will continue to deploy the 2019 server and report back here if it is an improvement.

Like GillesPE mentioned, I suspect these issues are related to the cloud print class drivers. Is there any way we can test a new driver or something?

**Comment by lightupdifire** [comment]
Hello,
We have many models in company available (Canon, Xerox, HP etc.), I used for test only one printer, and it is "HP Color Laser Jet Pro M252dw" if you install this printer locally you have Color/Black/Tray/Double-print options etc. while via Hybrid Cloud Print via Windows Server 2019 non of those available.

**Comment by msjimwu** [comment]
Thank-you for letting us know which printers you are encountering issues with.  We are investigating.

**Comment by lightupdifire** [comment]
Hello,
Any update please. Would be nice to know possible ETA.. if possible :)

**Comment by GillesPE** [comment]
Hello,
Any update please ? i tried with my new HP Printer but the same error ..
For me, it's a limitation of Microsoft Enterprise Cloud Print Class Drivers.

**Comment by Jo0Lz** [comment]
> Hello,
> Any update please ? i tried with my new HP Printer but the same error ..
> For me, it's a limitation of Microsoft Enterprise Cloud Print Class Drivers.

It's been awfully quiet. Like mentioned months ago, I also suspect the driver is the issue. 
How can we go about escalating this, I haven't heard any success stories regarding Hybrid Cloud Printing, from anyone. Is it time to move on and find a different implementation? I haven't seen ANY news ANYWHERE, and it's quite frustrating to see announcements that this is a feature, only to find the implementation is horrible and functionality is sub-par.

I've set up a Windows Server 2016 machine, successfully published printers to the cloud, only to find issues with print jobs,  finisher options that are missing, etc. It's then mentioned that Server 2019 would resolve these issues. So I setup a 2019 server and configured cloud printing, only to find that installation has changed, sql versions mismatch, and after a lot of effort only find that it doesn't resolve any of the issues. Meanwhile we are several months down the road and there hasn't been any response to the issue here. Is there another place/forum/ticket system I should be using to report issues and get some help to finally get this working?

**Comment by bruun963** [comment]
Microsoft stated that alot of problems would be solved in Windows Server 2019, however haven't seen any updated documentation. Simple question: does it work as promised?

**Comment by Jo0Lz** [comment]
> Microsoft stated that alot of problems would be solved in Windows Server 2019, however haven't seen any updated documentation. Simple question: does it work as promised?

Simple answer: No. It does not. 

I've gone through the trouble of setting up a new 2019 Server, but I'm facing the exact same issues. It literally makes no difference if you're running an updated 2019 server or a 2016 server.
Finisher options are not available, print drawer selection does not work, heck if I print in color, the print jobs get removed. Only black and white printing works. The issue you are replying on is closed even though it's not solved and Microsoft doesn't respond or seems to be even working on this. It's disappointing to say the least.
