### ISSUE TITLE
Unable to analyse which folders have failed

### ISSUE THREAD

**Issue by The-Experimentalist** [MicrosoftDocs/windowsserverdocs#893]
I am using a Robocopy command in a batch file. The output at the end of my Robocopy operation shows 18 "FAILED" "Dirs" but I am unable to find which folders failed. The command I am using uses the following command line switches:

 /MIR /FFT /XD "U:\System Volume Information" /LOG:"%logpath%%filename%" /V /TEE

I can find no information on the folders that failed in the log file.

**Comment by illfated** [comment]
Please use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
