### ISSUE TITLE
WSUS Console no longer connects to WSUS

### ISSUE THREAD

**Issue by slylabs13** [MicrosoftDocs/windowsserverdocs#898]
I followed the instructions to the letter here, and now the console cannot connect to the WSUS server. I tried using localhost\sqlexpress and <myservername>\sqlexpress. I'm not using SSL. Everything else is stock defaults. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e2a5a31-29b9-5599-2f14-bc244c5da034
* Version Independent ID: 393db29c-0866-46f4-9ee6-7ae82e8cb29f
* Content: [Migrating the WSUS Database from (Windows Internal Database) WID to SQL](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wid-to-sql-migration)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
