### ISSUE TITLE
Is OneDrive Sync App or One-Drive Files On Demand supported on Windows 2016 remote desktop?

### ISSUE THREAD

**Issue by missilelaunchr** [MicrosoftDocs/windowsserverdocs#951]
The article mentions Windows 2008 and 2012 R2 but does not address Windows 2016 Remote Desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0118050-ce3d-9526-6611-dbd2debb8fdf
* Version Independent ID: 4bfea77f-5eca-cba9-7037-a799daec7b1b
* Content: [OneDrive for Business and VDI environments](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-onedrive-for-business)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-onedrive-for-business.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-onedrive-for-business.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap

**Comment by illfated** [comment]
There has been some major changes to the document since this ticket was created.

***

Old page URL: https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-onedrive-for-business (redirects to the new page)
New page URL: https://docs.microsoft.com/en-us/onedrive/sync-vdi-support

GitHub old URL: https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-onedrive-for-business.md (removed)
GitHub new URL: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-vdi-support.md

***



# Use the sync app on virtual desktops

For all [supported operating systems](https://support.office.com/article/cc0cb2b8-f446-445c-9b52-d3c2627d681e), the OneDrive sync app supports:

- Virtual desktops that persist between sessions. 
- Non-persistent virtual desktops that use [Windows Virtual Desktop](https://azure.microsoft.com/services/virtual-desktop/).
- Non-persistent virtual desktops that have [FSLogix Apps 2.8 or later](/fslogix/configure-profile-container-tutorial), [FSLogix Office Container](/fslogix/configure-office-container-tutorial), and a Microsoft 365 subscription for all of the following operating systems:
  - Windows 10, 32 or 64-bit (supports VHDX files) 
  - Windows 7, 32 or 64-bit (supports VHD files) 
  - Windows Server 2019 (supports VHDX)
  - Windows Server 2016 (supports VHDX)
  - Windows Server 2012 R2 (supports VHDX)
  - Windows Server 2008 R2 (supports VHD)

 Using the OneDrive sync app with non-persistent environments requires that you [install the sync app per machine](https://docs.microsoft.com/onedrive/per-machine-installation).
 
> [!NOTE]
> The OneDrive sync app is not supported in remote app scenarios. </br> If you're running FSLogix with Files On-Demand on Windows 10 or Windows Sever 2019, the minimum supported versions are: OneDrive 19.174.0902.0013, FSLogix Apps 1909 HF_01 (2.9.7237.48865).</br> For Windows Server, the [SMB network file sharing protocol](/windows-server/storage/file-server/file-server-smb-overview) is also required. </br> The OneDrive sync app with FSLogix does not support running multiple instances of the same container simultaneously.

## See also

Learn more about [VHDX](/openspecs/windows_protocols/ms-vhdx/83f6b700-6216-40f0-aa99-9fcb421206e2) and [VHD](/windows/desktop/vstor/about-vhd).

For info about creating virtual hard disks, see [Manage virtual hard disks](/windows-server/storage/disk-management/manage-virtual-hard-disks).

**Comment by illfated** [comment]
Ticket resolved by the new changes.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
