### ISSUE TITLE
Unhelpful detail

### ISSUE THREAD

**Issue by pbyhistorian** [MicrosoftDocs/windowsserverdocs#996]
The Description for Subkey "DisabledByDefault" is "Flag to disable &lt;protocol&gt; by default."  We can pretty much work that out ourselves.  What you should describe is how this setting differs from Enabled=0.

Describing a term with the term itself is shoddy work.  Maybe "Client" could refer to controlling outbound requests and "Server" could refer to controlling inbound requests?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38fcd9dd-91c8-e79b-5f4d-28a435a8ada8
* Version Independent ID: 0d79a0c8-0b73-c783-4d5c-b107d24acf55
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server-threshold**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Szeraax** [comment]
I would add further, there is no description that discusses the implications of setting this DisabledByDefault property. We get that changes the default, but the doc should detail if that's ALL that this property does.

**Comment by Justinha** [comment]
@pbyhistorian @Szeraax for each setting, I added that DisabledByDefault means that if an app requests to use that protocol, it will be negotiated.

**Comment by Justinha** [comment]
@Szeraax Thanks for the suggestion. It does mean disabled by default. I revised it again to clarify this and the difference between DisabledByDefault = 1 and Enabled = 0.

**Comment by Szeraax** [comment]
Well, you do whatever you want, but here's the use scenario that a lot of us fit into:

a vulnerability scanner will explicitly try to use each vulnerable cipher on a host port. If that scanner can connect with 3des or sha1 or whatever, it counts as enabled and we fail the scan. This "DisabledByDefault" does not disable the cipher. Just doesn't list it initially. I know I'm going in circles here, so I'll just know to never use that key because it serves no functional purpose.
